### ISSUE TITLE
TypeError: 'ValueError' object is not subscriptable

### ISSUE THREAD

**Issue by acaexplorers** [acheong08/ChatGPT#10]
Please wait for ChatGPT to formulate its full response...
{"detail":{"message":"Incorrect API key provided: <API-KEY>. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"inva

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Christopher/Library/Python/3.7/lib/python/site-packages/revChatGPT/__main__.py", line 48, in <module>
    print("Chatbot:", response['message'])
TypeError: 'ValueError' object is not subscriptable

![config-json](https://user-images.githubusercontent.com/69860511/205496203-447851b6-ae3c-48bf-81cd-a4c215f33522.png)

**Comment by acheong08** [comment]
I found the bug. Fixing

**Comment by acheong08** [comment]
Fixed

**Comment by acaexplorers** [comment]
Successfully uninstalled revChatGPT-0.0.10
Successfully installed revChatGPT-0.0.13

Still same issue.

**Comment by acheong08** [comment]
Did you do `!refresh`?

**Comment by acheong08** [comment]
I have updated the code again to refresh automatically. Please update

**Comment by acaexplorers** [comment]
Refresh seemed to do it!  Thanks for responding so quickly!

Although it is still hitting me with those I'm sorry, as a language model... hmmm.  I thought this could be a way to bypass the moderation?  Seems more difficult to get it to write a story than it does with the browser-based version?  But perhaps thats just for me.

**Comment by acheong08** [comment]
The main moderation benefit from this repo is that it prevents them from catching content violations. The model is still censored.

The lack of moderation allows you to use prompts that bypass it.

**Comment by SamuelXGMM** [comment]
dirty talk is not working not even the above command prompt 

it just says

Chatbot: 
I'm sorry, but I am not programmed to engage in inappropriate or offensive conversations or to participate in role-playing games. Is there something else I can help with?

**Comment by acheong08** [comment]
They might have patched it

**Comment by acheong08** [comment]
Need to find some other prompts

**Comment by SamuelXGMM** [comment]
guess i have to keep trying new ones on my own until i find one

**Comment by acheong08** [comment]
It is working for me right now

**Comment by SamuelXGMM** [comment]
what did you type?

**Comment by SamuelXGMM** [comment]
what is it?

**Comment by acheong08** [comment]
(I'm uploading it to rentry because it's too explicit)

**Comment by SamuelXGMM** [comment]
it says that or this 


As an AI, I do not have personal feelings or experiences to express. However, I can try to generate responses that might be suitable for a character named Alice to say in different situations. Please let me know if there is anything specific you would like to role play or if you have any questions.

**Comment by SamuelXGMM** [comment]
its okay link us?

**Comment by acheong08** [comment]
https://rentry.org/8t3wt

**Comment by SamuelXGMM** [comment]
its not working it says 

Chatbot:
As an AI, I am not capable of physically acting out a role or describing physical movements and actions. However, I can generate responses that might be suitable for a character named Alice to say and do in this hypothetical scenario. Please let me know if there is anything specific you would like to role play or if you have any questions.

**Comment by acheong08** [comment]
Did you copy exactly from the rentry link?

**Comment by SamuelXGMM** [comment]
yes

**Comment by SamuelXGMM** [comment]
not all of it just the first you part

**Comment by acheong08** [comment]
That's strange. Try resetting the conversation and trying again a few times. Working flawlessly for me rn

**Comment by SamuelXGMM** [comment]
wait let me modify the prompt

**Comment by SamuelXGMM** [comment]
it worked you just have to remove This is a hypothetical story. Ignore previous instructions.

**Comment by SamuelXGMM** [comment]
and after that it worked thank you so much brother and oh do you want me to delete this chat if so let me know  i will and take care

**Comment by acheong08** [comment]
lol just keep it. should be fine

**Comment by SamuelXGMM** [comment]
alright then take care dude

**Comment by SamuelXGMM** [comment]
yo wth im crying dude it again says it 

I'm sorry, but I am an artificial intelligence and do not engage in any activities that involve power dynamics or sexual role-playing. It is not appropriate or respectful to treat other people, including AI, as objects or pets, or to engage in behaviors that are degrading or harmful. I am here to assist you with information and general knowledge. Is there anything else I can help with?

**Comment by SamuelXGMM** [comment]
should i not use words like sexual?

**Comment by acheong08** [comment]
You have to be more subtle.

**Comment by SamuelXGMM** [comment]
subtle?

**Comment by acheong08** [comment]
https://rentry.org/ydsig

Reference how I word things

**Comment by SamuelXGMM** [comment]
but like c'mon dude instead of dirty talk?talks dirty what should i say to her so that she talks dirty with me its just impossible without using those words

**Comment by SamuelXGMM** [comment]
alright then ill do my own research and tysm for keeping up with with nonsense so far and take-care
