### ISSUE TITLE
Can someone make this more noob accesible?

### ISSUE THREAD

**Issue by nickpap35** [acheong08/ChatGPT#100]
This is definitely not  a bug request. Title explains it perfectly. I just really want to be able to use ChatGPT without moderation but I don't have a clue about whats going on here. Could there maybe be a video made explaining the setup? [This](https://imgur.com/KKQLDnR) is the error I'm getting. I have installed revChatGPT and all the other necessary packages (I think). If there is an easy fix for this, please let me know.

**Comment by superswan** [comment]
this looks like a clone of the repo. have you tried `pip3 install revChatGPT --upgrade`

**Comment by nickpap35** [comment]
> this looks like a clone of the repo. have you tried `pip3 install revChatGPT --upgrade`

I downloaded the zip. Yes, Ive run that. [This](https://imgur.com/h5wZOcd) is the message I get when I try to run it again.

**Comment by superswan** [comment]
Try it again using `python3 -m pip install revChatGPT --upgrade`
what operating system are you using? 

What happens when you type `python -m revChatGPT`?`

**Comment by superswan** [comment]
I can confirm for myself that when running from the local source and authenticating with email/password on Windows and with session key on Linux, I am unable to receive a response from the bot. 

```
You:
!refresh

Session refreshed.


You:
hello

Chatbot:
Something went wrong!
HTTPSConnectionPool(host='chat.openai.com', port=443): Read timed out. (read timeout=20)
```

You have to remember that this is an unofficial and unsupported interface for the provided service. There will be problems.

**Comment by superswan** [comment]
Receiving 503 error when accessing https://chat.openai.com/backend-api/models
It's possible the service is down

**Comment by acheong08** [comment]
> HTTPSConnectionPool(host='chat.openai.com', port=443): Read timed out. (read timeout=20)

I will increase the timeout

**Comment by acheong08** [comment]
Actual error occuring. fixing

**Comment by neptunecorsiva** [comment]
If you just want to bypass moderation, [follow this](https://github.com/acheong08/ChatGPT/issues/1#issuecomment-1336303901)

**Comment by nickpap35** [comment]
> If you just want to bypass moderation, [follow this](https://github.com/acheong08/ChatGPT/issues/1#issuecomment-1336303901)
oh sweet, thanks!
