### ISSUE TITLE
Error while starting multiple instances. 

### ISSUE THREAD

**Issue by CopyPasteJedi** [acheong08/ChatGPT#1012]
It is possible to run multiple instances on different accounts at ones? When I'm trying to connect second client I got an error(on Chatbot and AsyncChatbot):

` raise Error( OpenAIAuth.Error 2023-03-02 18:51:45,957 - asyncio - ERROR - default_exception_handler - Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x000002C14C3E1B40> 2023-03-02 18:51:45,957 - asyncio - ERROR - default_exception_handler - Unclosed connector connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002C14C3C2A40>, 487861.171)]'] connector: <aiohttp.connector.TCPConnector object at 0x000002C14C3E16C0> 2023-03-02 18:51:45,957 - asyncio - ERROR - default_exception_handler - Fatal error on SSL transport protocol: <asyncio.sslproto.SSLProtocol object at 0x000002C14C3E23E0> transport: <_ProactorSocketTransport fd=1724 read=<_OverlappedFuture cancelled>> Traceback (most recent call last): File "C:\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog self._transport.write(chunk) File "C:\Python310\lib\asyncio\proactor_events.py", line 361, in write self._loop_writing(data=bytes(data)) File "C:\Python310\lib\asyncio\proactor_events.py", line 397, in _loop_writing self._write_fut = self._loop._proactor.send(self._sock, data) AttributeError: 'NoneType' object has no attribute 'send' Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000002C149ABFEB0>`

or

`    raise Error( OpenAIAuth.Error 2023-03-02 18:56:28,196 - asyncio - ERROR - default_exception_handler - Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x0000029FA9431BA0> 2023-03-02 18:56:28,197 - asyncio - ERROR - default_exception_handler - Unclosed connector connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000029FA9421D80>, 488140.281)]'] connector: <aiohttp.connector.TCPConnector object at 0x0000029FA9431720> 2023-03-02 18:56:28,197 - asyncio - ERROR - default_exception_handler - Fatal error on SSL transport protocol: <asyncio.sslproto.SSLProtocol object at 0x0000029FA9432440> transport: <_ProactorSocketTransport fd=1732 read=<_OverlappedFuture cancelled>>`

System:  Win 10
Python:  3.10.7

**Comment by acheong08** [comment]
Async issues are out of scope. Not officially supported
