### ISSUE TITLE
[Bug]:  Check the type of  "detail" when openai return errors that are not handled specially in code.

### ISSUE THREAD

**Issue by Peiiii** [acheong08/ChatGPT#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When an unhandled error occured, for example when openai return error: `{'detail': 'Something went wrong, please try reloading the conversation.'}`, and the code will run with fault like this: 
```
Traceback (most recent call last):
  File "D:\Projects\PythonProjects\cloudos-apps\app-chatgpt-backend\chatbot\chat_service.py", line 72, in task
    for line in self.chatbot.ask(
  File "D:\Programs\miniconda\lib\site-packages\revChatGPT\V1.py", line 516, in ask
    if line.get("detail", {}).get("code") == "invalid_api_key":
AttributeError: 'str' object has no attribute 'get'
```

### Steps to reproduce the problem

.

### What should have happened?

This is caused by `if line.get("detail", {}).get("code") == "invalid_api_key":`, at V1.ChatBot.ask function.
The type of "detail" should be checked first. For example,
```python
if isinstance(line.get("detail",{}),str):
    log.error("Unknown error :",line.get("detail"))
    raise Error(source="ask", message=line.get("detail"), code=-1)
```

### Version where the problem happens

3.0.5

### Command Line Arguments

```Shell
None
```

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\Projects\PythonProjects\cloudos-apps\app-chatgpt-backend\chatbot\chat_service.py", line 72, in task
    for line in self.chatbot.ask(
  File "D:\Programs\miniconda\lib\site-packages\revChatGPT\V1.py", line 516, in ask
    if line.get("detail", {}).get("code") == "invalid_api_key":
AttributeError: 'str' object has no attribute 'get'
```

**Comment by acheong08** [comment]
Should be fixed in version 3.0.8
