### ISSUE TITLE
[BUG] As a noob, I don't get the error message and still can't make a request. Any help please ?

### ISSUE THREAD

**Issue by Matthieu92-arch** [acheong08/ChatGPT#102]
Hello dears,

I saw I need to call get_chat_text() for example to make a request with data as a dict but I can't find the proper structure of the dict I should give to the function. I get the error message from the API after calling the function with this parameter {"msg": "What's 4 + 4 ?"} ->  `ValueError: ('Response is not in the correct format', [{'loc': ['body', 'action'], 'msg': 'field required', 'type': 'value_error.missing'}`

I tried to give {"msg": "What's 4 + 4 ?"} yet but
But it doesn't help me much. I don't find it particularly well explained. Any help please ?

**Comment by acheong08** [comment]
Call the function with just the prompt. The output format is optional.

`message = chatbot.get_chat_response("Hello world")['message']`

This gets the message from the API
