### ISSUE TITLE
[Feature Request]: Compliant with other APIs of OpenAI, such as whisper.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

It should be better if this package can also be used to log in and use other APIs of OpenAI, such as [whisper](https://openai.com/research/whisper).

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
Whisper is open source and can be used without an API. It doesn't take much compute. Works fast on my RPI

https://github.com/openai/whisper

**Comment by hongyi-zhao** [comment]
Do you mean it even can work fast on [Raspberry Pi](https://de.wikipedia.org/wiki/Raspberry_Pi)?

**Comment by acheong08** [comment]
A bit slower but yes

**Comment by hongyi-zhao** [comment]
My interest is in integrating web crawlers, OCR, whisper, and ChatGPT so that they work together to automate complex data analysis.

**Comment by acheong08** [comment]
Someone already did that though I'm not sure if it's open source

**Comment by acheong08** [comment]
>  In this case, RPI is unlikely to be competent.

Yes. CLIP interrogation is pretty intensive for image to text

**Comment by hongyi-zhao** [comment]
> Someone already did that though I'm not sure if it's open source

I didn't know what project you were referring to, but I noticed the following one:

https://github.com/pharmapsychotic/clip-interrogator

**Comment by acheong08** [comment]
> [pharmapsychotic/clip-interrogator](https://github.com/pharmapsychotic/clip-interrogator)

Yes, a variant of that is the one used in Stable Diffusion

> I didn't know what project you were referring to

@waylaidwanderer made a Telegram bot that could process images and audio but I can't find it on their GitHub. I'm assuming it to be closed source.

**Comment by hongyi-zhao** [comment]
Where is the bot? I tried to find it, but found nothing:

![image](https://user-images.githubusercontent.com/11155854/222876385-59a1a293-86ac-4c27-9282-3c848f04894b.png)

**Comment by waylaidwanderer** [comment]
It's not available for public use yet :)

**Comment by hongyi-zhao** [comment]
Thank you for telling me this information.
