### ISSUE TITLE
[Bug]:  Multiple people talking at the same time will result in confusion and crossover

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Multiple people talking at the same time will result in confusion and crossover

<img width="994" alt="image" src="https://user-images.githubusercontent.com/19570026/222906575-1d376342-00c6-4e0d-a47d-7515d2c27b77.png">

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

Multiple people talking at the same time will result in confusion and crossover

<img width="994" alt="image" src="https://user-images.githubusercontent.com/19570026/222906577-b1748e95-84e5-4007-a76d-eb0c17c331ed.png">

### What should have happened?

<img width="994" alt="image" src="https://user-images.githubusercontent.com/19570026/222906575-1d376342-00c6-4e0d-a47d-7515d2c27b77.png">

### Version where the problem happens

3.0.9

### What Python version are you running this with?

3.10.4

### Command Line Arguments

```Shell
ython3 -m revChatGPT.V3 --api_key afaffafaafaffsf
```

### Console logs

```Shell
<img width="994" alt="image" src="https://user-images.githubusercontent.com/19570026/222906575-1d376342-00c6-4e0d-a47d-7515d2c27b77.png">
```

**Comment by acheong08** [comment]
Duplicate
