### ISSUE TITLE
[Bug]:  多用户同时聊天会出现Bug

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

code：
<img width="820" alt="image" src="https://user-images.githubusercontent.com/19570026/222914256-5cfeac2e-4e44-4155-b890-cb4a39fc7020.png">

question：
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/222914332-af3bf42d-e357-4471-b440-6139046f70b6.png">

When two user roles appear at the same time, the assistant role does not respond. It should be one user and one assistant and that's fine

### Steps to reproduce the problem

code：
<img width="820" alt="image" src="https://user-images.githubusercontent.com/19570026/222914256-5cfeac2e-4e44-4155-b890-cb4a39fc7020.png">

question：
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/222914332-af3bf42d-e357-4471-b440-6139046f70b6.png">

When two user roles appear at the same time, the assistant role does not respond. It should be one user and one assistant and that's fine

### What should have happened?

code：
<img width="820" alt="image" src="https://user-images.githubusercontent.com/19570026/222914256-5cfeac2e-4e44-4155-b890-cb4a39fc7020.png">

question：
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/222914332-af3bf42d-e357-4471-b440-6139046f70b6.png">

When two user roles appear at the same time, the assistant role does not respond. It should be one user and one assistant and that's fine

### Version where the problem happens

3.10

### What Python version are you running this with?

3.10.4

### Command Line Arguments

```Shell
python3 -m revChatGPT.V3 --api_key wertyuiowrqrqrqrqr
```

### Console logs

```Shell
question：
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/19570026/222914332-af3bf42d-e357-4471-b440-6139046f70b6.png">


When two user roles appear at the same time, the assistant role does not respond. It should be one user and one assistant and that's fine
```

**Comment by acheong08** [comment]
Create different conversations for different users. This is expected and from OpenAI
