### ISSUE TITLE
[Feature Request]: remove support for python 3.3 (asyncio)

### ISSUE THREAD

**Issue by realsnick** [acheong08/ChatGPT#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

asyncio is depcrecated , pythong 3.3 is EOF

### Proposed workflow

not sure what the update is. I'm not a python expert

### Additional information

i'm building a nixos package for revchatGPT and as python 3.3 is deprecated there are no nixos packages for it at this point.

**Comment by acheong08** [comment]
Removed asyncio as dependency since V2 is already broken
