### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by noseon** [acheong08/ChatGPT#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

a way to edit a question that has already been asked in the chat. 

### Proposed workflow

I searched and didn't find a function that does this, if you have one, post an example here or on the wiki.

**Comment by acheong08** [comment]
`!rollback 1` and then press the up key to bring up the previous message. 

As for using it as a library, it's out of scope and should be done by the implementation
