### ISSUE TITLE
[Bug]: Wiki for WebGPT does not show up

### ISSUE THREAD

**Issue by NymdaFromSalad** [acheong08/ChatGPT#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I don't know, how the github wiki works, but it seems, a new page must be added manually somewhere
Page WebGPT.md is in wiki folder, but does not show up in wiki section

### Steps to reproduce the problem

1. Go to https://github.com/acheong08/ChatGPT/wiki
2. See no WebGPT page

### What should have happened?

There is WebGPT page

### Version where the problem happens

---

### What is your operating system ?

Other/Cloud

### Command Line Arguments

```Shell
---
```

### Console logs

```Shell
---
```

**Comment by acheong08** [comment]
Because it hasn't been published yet. I'm still reviewing and testing the code

**Comment by acheong08** [comment]
The code doesn't work. Discuss in the WebGPT feature request. I will add it to wiki when it works
