### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by mccoydj1** [acheong08/ChatGPT#1047]
Occasionally I'm getting a very long bad gateway message as my response instead of ChatGPT response. Not sure what is causing this...?

                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>

**Comment by acheong08** [comment]
Server overload possibly. I'll check

**Comment by acheong08** [comment]
It seems there was a DDOS attack while I was sleeping. Even the rate limit didn't stop it since it was from multiple IPs

**Comment by acheong08** [comment]
Should be fixed for now. Blocked their ASN

**Comment by mccoydj1** [comment]
Still getting gateway timeouts :(

**Comment by ghaddarAbs** [comment]
Same issue here

**Comment by mccoydj1** [comment]
getting 504 errors now unfortunately :(

**Comment by acheong08** [comment]
I don't understand why people would DDOS this public service. Over 300 IP addresses blocked at this point

**Comment by acheong08** [comment]
Should be fixed

**Comment by FAIpang** [comment]
Same issue here

**Comment by FAIpang** [comment]
I tried to respond successfully without setting the conversation_id, and if I set it, it would report 502 or 504

**Comment by jooray** [comment]
Still same :(

**Comment by Malomalsky** [comment]
Yeah, same here

**Comment by Darkluna999** [comment]
now， Code：504

**Comment by Darkluna999** [comment]
> I don't understand why people would DDOS this public service. Over 300 IP addresses blocked at this point

about this question could we deploy it by ourselves?

**Comment by acheong08** [comment]
Since the official API is out, I'll just implement it locally in this python lib and remove the proxy server.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/3.1.4

**Comment by acheong08** [comment]
I don't understand why people keep trying to DDOS my service.

**Comment by ghaddarAbs** [comment]
now it fix, but the issue is that it became super slow
