### ISSUE TITLE
[Bug]: My Server IP is blocked by mistake?

### ISSUE THREAD

**Issue by wenyinos** [acheong08/ChatGPT#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

> w3m https://chatgpt.duti.tech/                                                            23-03-06 8:57
> Access denied
> 
> Error code 1020
> 
> You do not have access to chatgpt.duti.tech.
> 
> The site owner may have set restrictions that prevent you from accessing the site.
> 
> Error details
> 
> Caret icon [ ]
> 
> Provide the site owner this information.
> 
> I got an error when visiting chatgpt.duti.tech/.
> 
> Error code: 1020
> 
> Ray ID: 7a36a52dcf1920ef
> 
> Country: HK
> 
> Data center: hkg10
> 
> IP: ******
> 
> Timestamp: 2023-03-06 00:57:33 UTC
> 
> Click to copy
> 
> Was this page helpful? Yes No
> Thank you for your feedback!
> 
> Performance & security by Cloudflare External link
> ≪ ↑ ↓ Viewing[SSL] <Access denied>

### Steps to reproduce the problem

use Tencent Cloud Lightsail（腾讯云轻量服务器）in HongKong.

w3m https://chatgpt.duti.tech/

### What should have happened?

"404 not found" is normal behavior.
I tested is my other servers.

### Version where the problem happens

Version: 3.0.9 and 3.1.1

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
none
```

**Comment by acheong08** [comment]
TENCENT is blocked due to DDOS attempt

**Comment by acheong08** [comment]
I cannot unblock as it risks the whole server being taken down. (A few thousand requests per second from a range of tencent IPs)

**Comment by wenyinos** [comment]
> I cannot unblock as it risks the whole server being taken down. (A few thousand requests per second from a range of tencent IPs)

Can you add my IP in whitelist? 

43.154.58.54

I can't change my IP any more.

**Comment by acheong08** [comment]
I'll add it to my whitelist

**Comment by vincehxb** [comment]
> https://chatgpt.duti.tech/

ops, did you block all tencent cloud ip and will block them like forever? any workaroud?my svr is on tencent cloud

**Comment by vincehxb** [comment]
> I'll add it to my whitelist

ops, did you block all tencent cloud ip and will block them like forever? any workaroud?my svr is on tencent cloud

**Comment by acheong08** [comment]
@vincehxb Send Ray ID and I'll whitelist. I'll add some measures to automatically whitelist later

**Comment by acheong08** [comment]
I had to block it due to distributed abuse I cannot block

**Comment by vincehxb** [comment]
> @vincehxb Send Ray ID and I'll whitelist. I'll add some measures to automatically whitelist later
many thanks!!!
7a370c6b7fa01d9f

**Comment by vincehxb** [comment]
> @vincehxb Send Ray ID and I'll whitelist. I'll add some measures to automatically whitelist later

many thanks!!!
7a370c6b7fa01d9f

**Comment by XMDS** [comment]
@acheong08 Hello, I have the same problem. I use Tencent Cloud Server. I request a white list, but how should I send the IP to you。Send here? Or email or other

**Comment by yanpengfei-git** [comment]
如何把ip发给你

**Comment by acheong08** [comment]
Upgrade to https://github.com/acheong08/ChatGPT/releases/tag/3.1.4 will fix it

**Comment by knight-666** [comment]
Error code: 1020

Ray ID: 7a404208fa1c2f41

Country: US

Data center: lax09

IP: 47.87.**.**

Timestamp: 2023-03-07 04:57:29 UTC

**Comment by acheong08** [comment]
Upgrade to latest version of revChatGPT

**Comment by Harry-zklcdc** [comment]
> Upgrade to latest version of revChatGPT

I have upgraded to 3.1.6, but I also received the following information

> You do not have access to chatgpt.duti.tech.The site owner may have set restrictions that prevent you from accessing the site.

My cloudflare id is

~~~

Ray ID: 7a4837930be32acf
Country: US
Data center: lax08
Timestamp: 2023-03-08 04:08:27 UTC
~~~

**Comment by zhangxianwei2015** [comment]
7a4883e91d6af9ed, please help, thanks! @acheong08
