### ISSUE TITLE
[Bug]: v1 Error code 1020

### ISSUE THREAD

**Issue by knight-666** [acheong08/ChatGPT#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Use v1 version of sending message to prompt error code 1020

### Steps to reproduce the problem

not have

### What should have happened?

get the answer

### Version where the problem happens

3.5.1

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
error code: 1020
```

**Comment by acheong08** [comment]
Duplicate

**Comment by imconical** [comment]
I have the same problem.

**Comment by JerryGaoYJ** [comment]
问题解决了吗？我也遇到了这个问题

**Comment by acheong08** [comment]
Upgrade to latest version

**Comment by JerryGaoYJ** [comment]
it is solved，thanks you

**Comment by sanmmm** [comment]
@acheong08 
Sorry to bother you。
it still return 1020 error when i upgrade to lastest version....
"revChatGPT.V1.Error: OpenAI: error code: 1020 (code: 403)"
my server is located at singapore.
what should i do

**Comment by acheong08** [comment]
Send Ray ID

**Comment by johnshuxian** [comment]
> Send Ray ID

I got the same problem.
Ray ID: 7a47edf29d1228f2

**Comment by sanmmm** [comment]
> Send Ray ID
7a47fe5ee902482e-SIN

**Comment by sanmmm** [comment]
> Send Ray ID

7a47fe5ee902482e-SIN

**Comment by xiao-er-shang-jiu** [comment]
I got the same problem.
Ray ID: 7a483c8e4f5604c3

**Comment by tinbolw** [comment]
I'm having the same issue. 
Ray ID: 7a486e3aad52cf09-SJC

**Comment by zhangxianwei2015** [comment]
7a4883e91d6af9ed, please help, thanks!

**Comment by acheong08** [comment]
@sanmmm @johnshuxian @xiao-er-shang-jiu fixed

**Comment by acheong08** [comment]
> I'm having the same issue. Ray ID: 7a486e3aad52cf09-SJC

@tinbolw your user agent was invalid

**Comment by sanmmm** [comment]
> @sanmmm @johnshuxian @xiao-er-shang-jiu fixed

it's ok. thanks!

**Comment by tinbolw** [comment]
> @tinbolw your user agent was invalid

My mistake, thank you.

**Comment by caojimin** [comment]
same issue
Ray ID: 7a4b87431ae54d5d
thanks!

**Comment by MieMieMieeeee** [comment]
> Send Ray ID
I got the same problem.
My Ray ID: 7a4fce7dda23aff1-NRT
