### ISSUE TITLE
[Feature Request]: Disposal ask function based on offical API

### ISSUE THREAD

**Issue by yangheng95** [acheong08/ChatGPT#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Can you add option for Disposal ask() function? because sometimes tedious word that we need chatgpt to do do not need context in a conversation, which maysave the token usages. I am not really familiar with this repo, so it my question is wrong I am sorry for that.

### Proposed workflow

1. Revise the ask function to support dispoasl

**Comment by acheong08** [comment]
`chatbot.conversations[convo_id].pop(1)`
