### ISSUE TITLE
[Error]:  Connection broken: InvalidChunkLength(got length b'', 0 bytes read)...

### ISSUE THREAD

**Issue by darthbit** [acheong08/ChatGPT#1076]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hey sometimes Im getting this; 

`("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))`

Is it some kind of overload on openAi end? Or im doing something wrong? My prompt is not that long at all and I have default settings for the chat

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

no error

### Version where the problem happens

present

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by Darkluna999** [comment]
Same Question

**Comment by HITxuefeng** [comment]
i also make a same mistake

**Comment by peanut996** [comment]
try a better network environment or retry more times.

**Comment by acheong08** [comment]
Your network issue cannot be fixed by me
