### ISSUE TITLE
[Bug]: 404 when calling `clear_conversations()`

### ISSUE THREAD

**Issue by monosans** [acheong08/ChatGPT#1082]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

It seems that the new V1 API does not support conversation management or some other endpoint must be used.

### Steps to reproduce the problem

Call `clear_conversations()`.

### What should have happened?

The conversations should have cleared up.

### Version where the problem happens

3.1.8.1

### Console logs

```Shell
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://gpt.pawan.krd/backend-api/conversations'
```

**Comment by GenifeG** [comment]
Same with 
```
chatbot = AsyncChatbot(conversation_id=conv_id, config=acc1)
    async for response in chatbot.ask(prompt=message, conversation_id=conv_id, timeout=4800):
        responseMessage = response["message"]
```
It does not work with conv_id

**Comment by acheong08** [comment]
It seems that proxy doesn't support a few features. I'll swap back to the previous proxy. Do note that it will be sunset soon though. Please migrate to V1

**Comment by acheong08** [comment]
Or downgrade to https://github.com/acheong08/ChatGPT/releases/tag/3.1.6

`pip3 install revChatGPT==3.1.6`

**Comment by liyucheng09** [comment]
So, I think the proxy is offically sunset. Thanks a lot for hosting the proxy server for such a period!

Now third party API doesn't support features to check conversation histories. I want to continue use this method so maybe I need to start my own proxy server?

I found you mention this repo: https://github.com/fuergaosi233/chatgpt-proxy-server.
and also this: https://github.com/RunawayVPN/PROX/tree/temp2
and also this repo: https://github.com/acheong08/ChatGPT-API-server

I wonder which is the best way to go. Could you please give some suggestions on that? I need not only the feature of "ask" but also "conversation"

Many thanks

**Comment by acheong08** [comment]
The issue is that the bypass method got shut down

**Comment by acheong08** [comment]
Will work on finding other ways

**Comment by liyucheng09** [comment]
@acheong08 does that mean starting our own proxy will still got the 404 error?

**Comment by acheong08** [comment]
Yes.

**Comment by liyucheng09** [comment]
@acheong08 So there is no hope at all for v1? If so I would be really really sad...

**Comment by acheong08** [comment]
I would guess not. We're trying to find something else but it could take a long while
