### ISSUE TITLE
Getting 500 Internal Server Error

### ISSUE THREAD

**Issue by frorayz** [acheong08/ChatGPT#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Getting this suddenly:
 
```
File "/home/rayz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 816, in ask
    self.__check_response(response)
  File "/home/rayz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 930, in __check_response
    response.raise_for_status()
  File "/home/rayz/.local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://chat.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/500
```

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

It should run

### Version where the problem happens

3.1.8.2

### What Python version are you running this with?

3.10.6

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
N/A
```

**Comment by Pengchengistaken** [comment]
This is happened when using ```
chatbot = AsyncChatbot(config={
        "email": "********@gmail.com",
        "password": "********"
    })
    ```

**Comment by acheong08** [comment]
Server overload

**Comment by acheong08** [comment]
It would help if people would stop DDOSing the server

**Comment by acheong08** [comment]
Current alternative: https://github.com/acheong08/ChatGPT/discussions/1081

**Comment by acheong08** [comment]
I just blocked a ton more IPs. Hopefully that resolves it

**Comment by frorayz** [comment]
> I just blocked a ton more IPs. Hopefully that resolves it

I am guessing this is just dud since V1 is dead?

**Comment by acheong08** [comment]
yes
