### ISSUE TITLE
[Bug]: Error code: 1020

### ISSUE THREAD

**Issue by hongshunanhai** [acheong08/ChatGPT#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I deploy the app in a Washington server, the server return "Access Denied", I'v update the revChatGPT to the latest version, 
error message:
<p>Error code: 1020</p>
<p>Ray ID: 7a4c42104def397f</p>
<p>Country: US</p>
<p>Data center: iad12</p>

### Steps to reproduce the problem

request the interface normally

### What should have happened?

In my local environment, open the clashx app, I can get the reponse from the server, in a Washington server, the server return "Access Denied"

### Version where the problem happens

(chat) ubuntu@10-27-36-80:~/chat$ python3 -m pip show revChatGPT
Name: revChatGPT
Version: 3.1.5

### What Python version are you running this with?

3.10.10

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
<body>
   <div class="cf-main-wrapper" role="main">
      <div class="cf-header cf-section">
         <div class="cf-error-title">
            <h1>Access denied</h1>
            <span class="cf-code-label">Error code <span>1020</span></span>
         </div>
         <div class="cf-error-description">
            <p>You do not have access to chatgpt.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>
      </div>
   </div>

   <div class="cf-details-wrapper">
      <div class="cf-section" role="region">
         <div class="cf-expandable" id="cf-details-wrapper-expandable">
            <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
               <p class="cf-dropdown-title">Error details</p>
               <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
               class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
            </label>

            <input id="error-details-checkbox" class="hidden" type="checkbox">

            <div class="cf-expandable-error-info hidden">
               <p class="cf-error-copy-description">Provide the site owner this information.</p>
               <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
<div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chatgpt.duti.tech/api/conversation.</p>

<p>Error code: 1020</p>
<p>Ray ID: 7a4c42104def397f</p>
<p>Country: US</p>
<p>Data center: iad12</p>
```

**Comment by sebastien247** [comment]
Some problem with version 2.3.4 and 3.1.8.2

**Comment by cheadrian** [comment]
It looks like they patched this method by implementing some new checkups. It also doesn't work if I copy 1:1 the request from browser to Postman.

**Comment by acheong08** [comment]
@hongshunanhai whitelisted

**Comment by acheong08** [comment]
The reason was due to abuse from UCLOUD

**Comment by chroniclex** [comment]
I also started receiving the error this morning

**Comment by acheong08** [comment]
Send RayID and I'll review it. It's an automatic blocking by Cloudflare based on abuse from IP range

**Comment by acheong08** [comment]
@chroniclex Whitelisted

**Comment by chroniclex** [comment]
thanks! i'll test now

**Comment by chroniclex** [comment]
still access denied, I'm using revChatGPT through https://github.com/Zero6992/chatGPT-discord-bot. the ray ID i got was from a POST I sent when I was troubleshooting. Will the Ray ID be different between the two?

**Comment by hongshunanhai** [comment]
> 

thank you very much

**Comment by hongshunanhai** [comment]
what does this mean?

Traceback (most recent call last):
  File "/home/ubuntu/chat/lib/python3.10/site-packages/werkzeug/serving.py", line 333, in run_wsgi
    execute(self.server.app)
  File "/home/ubuntu/chat/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    for data in application_iter:
  File "/home/ubuntu/chat/lib/python3.10/site-packages/werkzeug/wsgi.py", line 500, in __next__
    return self._next()
  File "/home/ubuntu/chat/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/home/ubuntu/chat/lib/python3.10/site-packages/flask/helpers.py", line 149, in generator
    yield from gen
  File "/home/ubuntu/chat/app.py", line 30, in _new_generate
    for response_data in chatbot.ask(
  File "/home/ubuntu/chat/lib/python3.10/site-packages/revChatGPT/V1.py", line 509, in ask
    self.__check_response(response)
  File "/home/ubuntu/chat/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/chat/lib/python3.10/site-packages/revChatGPT/V1.py", line 630, in __check_response
    raise Error(
revChatGPT.V1.Error: OpenAI: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a4f65646fac3b4d","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>
 (code: 404)

**Comment by Liukang1002** [comment]
> 发送 RayID，我会进行审核。这是 Cloudflare 根据 IP 范围内的滥用自动阻止

Hello, Ray ID: 7a4fb537be4d1964
Thank you so much

**Comment by caojimin** [comment]
> 

Ray ID: 7a50141abc8e3e30
please help, thanks!

**Comment by sigaer** [comment]
Error code: 1020

Ray ID: 7a5025470a79d2f5

Country: DE

**Comment by acheong08** [comment]
The bypass has been blocked by OpenAI. V1 will not be functional until further notice. Use V3 for now
