### ISSUE TITLE
[Feature Request]: Langchain integration

### ISSUE THREAD

**Issue by sushmitxo** [acheong08/ChatGPT#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Please create a Langchain wrapper that would use revchatGPT. it would be really helpful.

Relevant information about this can be found here: https://github.com/hwchase17/langchain/issues/258  and here https://twitter.com/hwchase17/status/1599559478042857472?s=20&t=Hb8D3oXynVVvVHjwd4Dp4w 

Thank you.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
Out of scope
