### ISSUE TITLE
[Bug]: 403 Forbidden When using Async Ask

### ISSUE THREAD

**Issue by 7trail** [acheong08/ChatGPT#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hello,

I have been receiving a "403 Forbidden" error since about an hour ago when attempting an API call. I don't have much information to give, but it is **https://chatgpt.duti.tech/api/conversation** giving the 403, and I am using AsyncChatbot.ask().

### Steps to reproduce the problem

Attempt to make an API call.

### What should have happened?

The API call should have gone through.

### Version where the problem happens

3.1.8.2

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Client error '403 Forbidden' for url 'https://chatgpt.duti.tech/api/conversation'
For more information check: https://httpstatuses.com/403
```

**Comment by 7trail** [comment]
Edit, the recent push just came through. I see the issues with high costs, and understand shutting it down. Is there another proxy you can recommend/a way to just use the default gateway?

**Comment by hafidzaini** [comment]
waiting for this too

**Comment by acheong08** [comment]
It's no longer an issue with cost. The method got shut down

**Comment by acheong08** [comment]
Can't bypass cloudflare that way anymore
