### ISSUE TITLE
[Bug]: Requests getting a cloudflare error

### ISSUE THREAD

**Issue by SlickTorpedo** [acheong08/ChatGPT#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I ran V1 as normal with this result:

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a4f91d178dd2d26","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

### Steps to reproduce the problem

Run V1 as normal.

### What should have happened?

Ran as normal

### Version where the problem happens

Name: revChatGPT
Version: 3.1.8.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/SlickTorpedo/.local/lib/python3.10/site-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by: 

### What Python version are you running this with?

python 3.9

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Answering Question: Who is this
Formulating Response
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a4f91d178dd2d26","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

No questions. Delaying
```

**Comment by SnapdragonLee** [comment]
same

**Comment by acheong08** [comment]
V1 officially gone

**Comment by acheong08** [comment]
The endpoint has been blocked

**Comment by 7trail** [comment]
Alright. It was fun while it lasted.

Do you have an alternative link/API we can use?

**Comment by acheong08** [comment]
Use V3.

**Comment by acheong08** [comment]
Duplicates:
- #1092
- #1093

**Comment by hrizal** [comment]
V1 RIP 
(◞‸◟ㆀ)
