### ISSUE TITLE
[Bug]:  revChatGPT.V2 No response is received after successful login

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

revChatGPT.V2 No response is received after successful login

example：
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/19570026/223978013-4ea16489-d148-45db-b08c-d50e1ebc7df4.png">

### Steps to reproduce the problem

revChatGPT.V2 No response is received after successful login

example：
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/19570026/223978013-4ea16489-d148-45db-b08c-d50e1ebc7df4.png">

### What should have happened?

revChatGPT.V2 No response is received after successful login，no output

example：
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/19570026/223978013-4ea16489-d148-45db-b08c-d50e1ebc7df4.png">

### Version where the problem happens

Name: revChatGPT
Version: 3.1.8.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/python3/lib/python3.10/site-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by: 

### What Python version are you running this with?

Python 3.10.5

### Command Line Arguments

```Shell
python3 -m revChatGPT.V2 --api_key=pk-TNkDYMHpJKKuSfiAWJlUCKQSnKluoZxvLGKRPnPzxCDPdVxs
```

### Console logs

```Shell
No output：


python3 -m revChatGPT.V2 --api_key=pk-TNkDYMHpJKKuSfiAWJlUCKQSnKluoZxvLGKRPnPzxCDPdVxs

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
11是素数嘛 
 
                                                                                                                                                                            
Exiting...
```

**Comment by acheong08** [comment]
And don't need to define API key

**Comment by geagerg** [comment]
> And don't need to define API key

May I ask what is the reason for this?
{"status":false,"error":"Your API key is not allowed to be used from this IP address, if you want to reset your authorized IP address please use /resetip on our discord server","contact":"https://discord.pawan.krd"}

**Comment by acheong08** [comment]
Oh it seems he limited usage.

**Comment by geagerg** [comment]
Looking forward to it very much.

**Comment by acheong08** [comment]
@geagerg https://github.com/acheong08/ChatGPT/releases/tag/3.1.9.1

Figured it out

**Comment by acheong08** [comment]
Hopefully this doesn't get patched
