### ISSUE TITLE
How long is the copied token from the request valid?

### ISSUE THREAD

**Issue by ezzcodeezzlife** [acheong08/ChatGPT#11]
Title sais it all. Anyone knows? 🙏🏼

**Comment by acheong08** [comment]
The session token should be valid for a month. The bearer token is valid for an hour. Refresh the bearer token with `!refresh`

**Comment by luckcul** [comment]
> 

Hi, what is the bearer token ?

**Comment by acheong08** [comment]
Session token: https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

Access/Bearer token (same thing): https://github.com/acheong08/ChatGPT/wiki/Setup#access-token-authentication

**Comment by luckcul** [comment]
> Session token: https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication
> 
> Access/Bearer token (same thing): https://github.com/acheong08/ChatGPT/wiki/Setup#access-token-authentication

Thanks!  
If I use `Email and password authentication`, how long is it valid?  Or how often to call `refresh_session()` in a long-running process?

**Comment by acheong08** [comment]
I just updated the code to refresh session every time you request a message which should only take ~50ms (depending on your internet speed). It automatically detects if a session expires and logs in again. You don't need to call `refresh_session()` anymore.
