### ISSUE TITLE
[Bug]: Too many requests in 1 hour. Try again later.

### ISSUE THREAD

**Issue by hafidzaini** [acheong08/ChatGPT#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```
{"detail":"Too many requests in 1 hour. Try again later."}
OpenAI: {"detail":"Too many requests in 1 hour. Try again later."} (code: 400)
```

### Steps to reproduce the problem

no request in last 1 hour
no history chat on browser

### What should have happened?

pawan proxy limit the request?

### Version where the problem happens

3.2.0 Fix V1 (Partially Working)
latest from github

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
{"detail":"Too many requests in 1 hour. Try again later."}
OpenAI: {"detail":"Too many requests in 1 hour. Try again later."} (code: 400)
```

**Comment by frorayz** [comment]
Since you are using the free model, usage is limited. As the error says—try again later.

**Comment by youmebangbang** [comment]
same

**Comment by jianhai0527** [comment]
what's the proxy server?

**Comment by chelishchev** [comment]
The same problem
Nothing works :(

**Comment by annncc** [comment]
you can try again.Maybe server too busy.

**Comment by sromexs** [comment]
same, it works sometimes but most of the time error is the same

**Comment by singlag** [comment]
same, 1 out of 4 success, other 3 is OpenAI: {"detail":"Too many requests in 1 hour. Try again later."} (code: 400)

**Comment by hafidzaini** [comment]
> you can try again.Maybe server too busy.

server busy should give another type of error

**Comment by hafidzaini** [comment]
been switch and rotating account, end up the same.
never use it in last couple of hours

**Comment by sromexs** [comment]
> been switch and rotating account, end up the same. never use it in last couple of hours

I think they made something to ban the bots, i hope this is not true :(

**Comment by hafidzaini** [comment]
> > been switch and rotating account, end up the same. never use it in last couple of hours
> 
> I think they made something to ban the bots, i hope this is not true :(

yeah. maybe account and IP (proxy server)

**Comment by hafidzaini** [comment]
working now
dont know why
