### ISSUE TITLE
lookup chat.openai.com: too many open files

### ISSUE THREAD

**Issue by jianhai0527** [acheong08/ChatGPT#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

{"error":"Post \"https://chat.openai.com/backend-api/conversation\": dial tcp: lookup chat.openai.com: too many open files"} 

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

{"error":"Post \"https://chat.openai.com/backend-api/conversation\": dial tcp: lookup chat.openai.com: too many open files"} 

### Version where the problem happens

Name: revChatGPT
Version: 3.3.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /Users/tanfan/opt/miniconda3/envs/chatgpt_scrawler/lib/python3.10/site-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by: 

### Command Line Arguments

```Shell
V1 dev
```

### Console logs

```Shell
{"error":"Post \"https://chat.openai.com/backend-api/conversation\": dial tcp: lookup chat.openai.com: too many open files"}
```

**Comment by F33RNI** [comment]
same

**Comment by Grong** [comment]
same

**Comment by MuhsinunC** [comment]
I was also facing this issue earlier.

**Comment by acheong08** [comment]
fixed
