### ISSUE TITLE
[Bug]:  TCP: Too Many Open Files

### ISSUE THREAD

**Issue by AmarnathCJD** [acheong08/ChatGPT#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

May be increase the system ulimit

Error in ask: {"error":"Post \"https://chat.openai.com/backend-api/conversation\": dial tcp: lookup chat.openai.com: too many open files"}

### Steps to reproduce the problem

send post request to https://bypass.duti.tech/api/conversation with valid access_token
Happens sometimes only 
Probably I'm using 5 clients at same time 

### What should have happened?

No error,
Response returned

### Version where the problem happens

3.1.3

### What Python version are you running this with?

golang-1.20

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Nil
```

### Console logs

```Shell
Error in ask: {"error":"Post \"https://chat.openai.com/backend-api/conversation\": dial tcp: lookup chat.openai.com: too many open files"}
```

**Comment by F33RNI** [comment]
https://github.com/acheong08/ChatGPT/issues/1116

**Comment by acheong08** [comment]
fixed
