### ISSUE TITLE
[Bug]: Error code: 1020

### ISSUE THREAD

**Issue by Grong** [acheong08/ChatGPT#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

V1

my proxy 47.89.208.207

<p>Error code: 1020</p>
<p>Ray ID: 7a597c10a9229645</p>
<p>Country: CN</p>
<p>Data center: sjc06</p>
<p>IP: 183.17.231.221</p>
<p>Timestamp: 2023-03-10 06:26:10 UTC</p>

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

。。

### Version where the problem happens

python3 -m pip show revChatGPT

### Command Line Arguments

```Shell
NO
```

### Console logs

```Shell
NO
```

**Comment by caojimin** [comment]
same problem
Ray ID: 7a59947dfa964096

**Comment by acheong08** [comment]
Should be fixed. Check again

**Comment by vaibhavard** [comment]
Error On python Version : 3.10
Python Version 3.8 Works Perfectly!

**Comment by acheong08** [comment]
If you're banned, it means your IP address or range is being used for abuse. I can't unblock for some people in case. There was someone who asked for whitelist and then started spamming the server after approval.
