### ISSUE TITLE
[Bug]: from revChatGPT.V1 import Chatbot

### ISSUE THREAD

**Issue by Harry-zklcdc** [acheong08/ChatGPT#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "chatGPT.py", line 3, in <module>
    from revChatGPT.V1 import Chatbot
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 25, in <module>
    from .utils import create_completer
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/utils.py", line 72, in <module>
    def get_filtered_keys_from_object(obj: object, *keys: str) -> set[str]:
TypeError: 'type' object is not subscriptable

### Steps to reproduce the problem

1. pip install revChatGPT -- upgrade # Version is v3.3.2
2. and import V1 Chatbot

### What should have happened?

import sussess

### Version where the problem happens

Name: revChatGPT
Version: 3.3.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by

### What Python version are you running this with?

3.8.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
root@****:/workplace# python3 chatGPT.py
Traceback (most recent call last):
  File "chatGPT.py", line 3, in <module>
    from revChatGPT.V1 import Chatbot
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/V1.py", line 25, in <module>
    from .utils import create_completer
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/utils.py", line 72, in <module>
    def get_filtered_keys_from_object(obj: object, *keys: str) -> set[str]:
TypeError: 'type' object is not subscriptable
```

### Additional information

When I use `pip install revChatGPT==3.3.1` to install revChatGPT v3.3.1, it is working

**Comment by justin-jiajia** [comment]
same issue

**Comment by acheong08** [comment]
Upgrade to Python 3.10

**Comment by acheong08** [comment]
Python 3.8 will be supported on next release

**Comment by Harry-zklcdc** [comment]
> Python 3.8 will be supported on next release

OKay, Thanks!

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/3.3.3

**Comment by acheong08** [comment]
This should work. Let me know if it doesn't

**Comment by Harry-zklcdc** [comment]
> This should work. Let me know if it doesn't

It's Working! Thanks so much!

**Comment by Shakestaff** [comment]
I am having this issue also. V0.py works, but the rest give:

from .utils import create_completer
ImportError: attempted relative import with no known parent package

I have python3.11, revChatGPT3_3.3.4, I am using termux on Android.
