### ISSUE TITLE
[BUG] Error when trying to get a response

### ISSUE THREAD

**Issue by LuckyHead11** [acheong08/ChatGPT#114]
Hello! I am running this for the first time, and I am getting this error when I try to submit a question:

**UnboundLocalError: local variable 'error_desp' referenced before assignment**

Does anyone know how to fix this issue?
![Screenshot 2022-12-06 184504](https://user-images.githubusercontent.com/93405290/206059785-f46c4086-d5e3-4e22-ac1e-417e18eaaa34.png)

**Comment by LuckyHead11** [comment]
Alright thank you very much for responding so quickly!

**Comment by turtlebasket** [comment]
Bump, having this issue as well. Thanks for resolving

**Comment by LuckyHead11** [comment]
I did not mean to do that

**Comment by acheong08** [comment]
Internal server error. The API must have been overhauled

**Comment by LuckyHead11** [comment]
So is there a fix?

**Comment by acheong08** [comment]
I've found the change. Damn openAI. We're playing cat and mouse with the API

**Comment by turtlebasket** [comment]
> I've found the change. Damn openAI. We're playing cat and mouse with the API

Seeing as to how this is a reverse engineered API and they charge users for their mainline API, don't you think they'll try to close whatever allows this lib to exist eventually? Yesterday it had 1.1k stars and now 2.5k— probably can't stay under their radar forever :(

**Comment by acheong08** [comment]
yes

**Comment by acheong08** [comment]
will take time to replicate the new API

>  probably can't stay under their radar forever 

I'm waiting for a DCMA strike

**Comment by turtlebasket** [comment]
> I'm waiting for a DCMA strike

based

**Comment by LuckyHead11** [comment]
Yeah, this is going crazy. OpenAI better release a API quick. But for now we will stick with this one!

**Comment by LuckyHead11** [comment]
Thank you! Let me try it out real quick!

**Comment by LuckyHead11** [comment]
Alright, it works! Thank you so much for helping me out! Don't forget to change readme.md because it talked about the older version.
