### ISSUE TITLE
[Bug]: Having Error using V1, seems like issue with the base_url

### ISSUE THREAD

**Issue by tracy15932** [acheong08/ChatGPT#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Getting the following while using V1:
<img width="707" alt="Screen Shot 2023-03-12 at 4 50 46 PM" src="https://user-images.githubusercontent.com/40265519/224582792-d3109f49-11ba-45c8-b298-7c63596aabed.png">

### Steps to reproduce the problem

NA

### What should have happened?

NA

### Version where the problem happens

The newest version

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
python3 test.py
```

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`
