### ISSUE TITLE
[v3 Feature Request]: Allow base prompt to be modified on runtime

### ISSUE THREAD

**Issue by Jecket22** [acheong08/ChatGPT#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The chatbot adds in a base prompt automatically at the start of the conversation and from what I can tell it can only be modified in the CLI environment through `--base_prompt`. For most I think this is completely fine by them, however I would like to have the option to have a function or something else that lets me modify the base prompt before/upon creating a new conversation.

### Proposed workflow

Let the user configure the base prompt before running `chatbot.ask()`.
As example: 
```py
chatbot.set_base_prompt(
    role="system",
    prompt="You are Yoogle, a large language-based ai search engine model trained by OpenAI. Respond conversationally, and provide preferably generic sources if possible",
    #convo_id: "default"
)
```
The function is expected to run before creating a conversation, and should not be used for existing conversation (maybe throw an error/warning or do nothing in that case).

**Comment by acheong08** [comment]
`chatbot.reset(convo_id="default", system_prompt="You are Yoogle, a large language-based ai search engine model trained by OpenAI. Respond conversationally, and provide preferably generic sources if possible")`

**Comment by Jecket22** [comment]
Ah, I completely overlooked that function as I (admittedly) assumed that it only serves for erasing conversations in there. Find it a bit hacky but that works well enough for me, thank you!
