### ISSUE TITLE
[Feature Request]: 我是否可以搭建一个"https://gpt.pawan.krd/backend-api/"这样的代理

### ISSUE THREAD

**Issue by blankxyz** [acheong08/ChatGPT#1148]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

我是否可以搭建一个"https://gpt.pawan.krd/backend-api/"这样的代理

### Proposed workflow

我是否可以搭建一个"https://gpt.pawan.krd/backend-api/"这样的代理，如果可以，您可以提供些相关的信息吗

### Additional information

我是否可以搭建一个"https://gpt.pawan.krd/backend-api/"这样的代理

**Comment by acheong08** [comment]
我不是Pawan而且也没有用他的proxy
