### ISSUE TITLE
[Bug]: V1 OpenAI: error code: 1020 (code: 403)

### ISSUE THREAD

**Issue by fkxxyz** [acheong08/ChatGPT#1153]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

bypass.duti.tech is down?

### Steps to reproduce the problem

execute `python3 -m revChatGPT.V1` and send `hello`
I got `__main__.Error: OpenAI: error code: 1020 (code: 403)`

### What should have happened?

get Chatbot reply

### Version where the problem happens

Name: revChatGPT
Version: 3.3.5
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by: 

### What Python version are you running this with?

Python 3.10.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.
Allow analytics? (y/n) 

You: 
hello

Chatbot: 
error code: 1020
Traceback (most recent call last):
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 1064, in <module>
    main(configure())
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 1043, in main
    for data in chatbot.ask(prompt):
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 522, in ask
    self.__check_response(response)
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/fkxxyz/.pyenv/versions/3.10.9/lib/python3.10/site-packages/revChatGPT/V1.py", line 632, in __check_response
    raise Error(
__main__.Error: OpenAI: error code: 1020 (code: 403)
```

**Comment by ading2210** [comment]
I'm having the exact same issue with Python 3.9.2 on Debian 11.

**Comment by F33RNI** [comment]
same

**Comment by KaiserWhoLearns** [comment]
Exact same issue +1

**Comment by soltanoff** [comment]
Yep, the same problem

**Comment by MeltingObsidian** [comment]
Exact same error code when running on Windows as well (Python 3.9)

**Comment by Doeca** [comment]
same too

**Comment by MeltingObsidian** [comment]
Has anyone found the reason for this happening? I checked the current version of ChatGPT, it was still the Feb 15th version, and the API was also working till yesterday...

**Comment by AgustinPinedaGarcia** [comment]
Maybe has to do with GPT-4 release? By the way, are you planning to support it here? :)

**Comment by sromexs** [comment]
Same

**Comment by FastSchnell** [comment]
the same problem

**Comment by singlag** [comment]
same here

**Comment by andybenichou** [comment]
Same for me

**Comment by FastSchnell** [comment]
My v1 version has been restored, has yours been restored too?
this is my gpt proxy, https://www.postbook.xyz/read/chatGPT

**Comment by andybenichou** [comment]
> My v1 version has been restored, has yours been restored too? this is my gpt proxy, https://www.postbook.xyz/read/chatGPT

I still get the error 1020

**Comment by FastSchnell** [comment]
> et the

i used assess_token instead password login

**Comment by FastSchnell** [comment]
Although I can currently use GPT-4, I don't know how to input images, so I can't feel the shock that GPT-4 brings for now. If someone knows how to do it, please let me know.

**Comment by andybenichou** [comment]
> > et the
> 
> 
> 
> i used assess_token instead password login

Me too the login is not the problem, I login then used the API using the ChatBot with access_token.

**Comment by andybenichou** [comment]
> My v1 version has been restored, has yours been restored too? this is my gpt proxy, https://www.postbook.xyz/read/chatGPT

What version are you using, how did you restore it?

**Comment by ouwx** [comment]
Exact same issue +1

**Comment by iamaliveai1** [comment]
Same here

**Comment by acheong08** [comment]
Money ran out on the VPS

**Comment by acheong08** [comment]
Temporarily solved with a scaled down server. It could be easily overloaded though. Will look for more resources/funding

**Comment by seii-saintway** [comment]
I know it's my fault. My OpenAI account is deactivated.

**Comment by sromexs** [comment]
> I know it's my fault. My OpenAI account is deactivated.

All my accounts that used in api is deactivated too

**Comment by seii-saintway** [comment]
> > I know it's my fault. My OpenAI account is deactivated.
> 
> 
> 
> All my accounts that used in api is deactivated too

Dear user,

According to the privacy protection laws in the United States, such as the California Consumer Privacy Act (CCPA) and the General Data Protection Regulation (GDPR), users have the right to access, correct, and delete their personal information, as well as request service providers to export their personal information. However, whether information service providers need to provide user information export services is not a legal requirement, but depends on the policies of the service provider. Some service providers may offer this feature, while others may not.

ChatGPT

**Comment by F33RNI** [comment]
I want open-source ChatGPT very badly..... Without all this bureaucracy, accounts, phone numbers....
*and why are OpenAI called "Open" if it's all proprietary?* 🙃
