### ISSUE TITLE
[Feature Request]: GPT-4 Compatibility

### ISSUE THREAD

**Issue by xslingcn** [acheong08/ChatGPT#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

OpenAI has just launched their latest generation of the model, [GPT-4](https://openai.com/research/gpt-4)! It's now accessible to all ChatGPT Plus users. Any plans to add support for it? (Currently only proxy since the paid API is invite only at the time).

### Proposed workflow

The logics should be relatively similar to previous ones. (cf bypass, web calls, etc.. Needs more investigation...)

Edit: update unclear wording.

**Comment by frorayz** [comment]
API is still invite only AFAIK, maybe the proxy can be updated with the plus website model which has GPT 4?

**Comment by xslingcn** [comment]
> API is still invite only AFAIK, maybe the proxy can be updated with the plus website model which has GPT 4?

Ah sorry I meant the web APIs, i.e. yes the proxy.

**Comment by EpicLiem** [comment]
I don't have plus so I can't really help, but users could input images with something like !image [path]. Also, do we if there is an updated tos is for the new model?

**Comment by frorayz** [comment]
> > API is still invite only AFAIK, maybe the proxy can be updated with the plus website model which has GPT 4?
> 
> Ah sorry I meant the web APIs, i.e. yes the proxy.

Do note its still limited to 100 conversations in 4 hours. Unless you have dev access to the wait-listed API  I don't think its possible yet.

**Comment by acheong08** [comment]
Will add once I get the bypass servers sorted out. I ran out of VPS credit

**Comment by xslingcn** [comment]
> Will add once I get the bypass servers sorted out. I ran out of VPS credit

Nice! Thank you for your work!

**Comment by frorayz** [comment]
> Will add once I get the bypass servers sorted out. I ran out of VPS credit

Is that why its giving 404 💀

**Comment by acheong08** [comment]
Yes. Just verified that bypass still working. The reason is due to servers being down and stopping internet access.

**Comment by acheong08** [comment]
It should be working again now but it's running on a single small server. Crashes expected if overload. Please use with care

**Comment by xslingcn** [comment]
> > > API is still invite only AFAIK, maybe the proxy can be updated with the plus website model which has GPT 4?
> > 
> > 
> > Ah sorry I meant the web APIs, i.e. yes the proxy.
> 
> Do note its still limited to 100 conversations in 4 hours. Unless you have dev access to the wait-listed API I don't think its possible yet.

Doesn't the proxy work by requesting using the user  provided account info? I think the 100 limit applies to each individual account so the proxy should be working the same like previous versions.

**Comment by frorayz** [comment]
> It should be working again now but it's running on a single small server. Crashes expected if overload. Please use with care

How does one create proxy like yours? I have a dedicated server I can provide help.

**Comment by frorayz** [comment]
> > > > API is still invite only AFAIK, maybe the proxy can be updated with the plus website model which has GPT 4?
> > > 
> > > 
> > > Ah sorry I meant the web APIs, i.e. yes the proxy.
> > 
> > 
> > Do note its still limited to 100 conversations in 4 hours. Unless you have dev access to the wait-listed API I don't think its possible yet.
> 
> Doesn't the proxy work by requesting using the user provided account info? I think the 100 limit applies to each individual account so the proxy should be working the same like previous versions.

Yes think so. Not too sure but I was talking about individual limits

**Comment by acheong08** [comment]
Supported

**Comment by acheong08** [comment]
I have a lot of crypto. I'll be scaling it on a different provider that accepts that once I get the time. I'm at school atm

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/4.0.0

**Comment by Barbery** [comment]
> https://github.com/acheong08/ChatGPT/releases/tag/4.0.0

how to install 4.0.0? I try `pip install --upgrade revChatGPT` still version 3.3.4  @acheong08

**Comment by frorayz** [comment]
> > https://github.com/acheong08/ChatGPT/releases/tag/4.0.0
> 
> how to install 4.0.0? I try `pip install --upgrade revChatGPT` still version 3.3.4 @acheong08

pip install revChatGPT==4.0.0

**Comment by acheong08** [comment]
https://pypi.org/manage/project/revChatGPT/release/4.0.0/

It has been properly released
