### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WoxC** [acheong08/ChatGPT#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

My account got banned so I made a new account but no matter what I do it still says I'm using a banned account but I can confirm my new account works. I've updated the session token and it still doesn't work. 

### Steps to reproduce the problem

Update session token
Run main program

### What should have happened?

Help me write an outline for my blog

### Version where the problem happens

4

### What Python version are you running this with?

3.11.2

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
python ./main.py
```

### Console logs

```Shell
{"detail":{"message":"This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.","type":"invalid_request_error","param":null,"code":"account_deactivated"}}
OpenAI: {"detail":{"message":"This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.","type":"invalid_request_error","param":null,"code":"account_deactivated"}} (code: 401)
```

**Comment by acheong08** [comment]
`rm ~/.config/revChatGPT/cache.json`
