### ISSUE TITLE
[Bug]: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

### ISSUE THREAD

**Issue by Worrah** [acheong08/ChatGPT#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Good day to you. Something changed? I've got a new error instead of response

HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversations?offset=0&limit=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x63c07bf8>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
 My account still active though

### Steps to reproduce the problem

Ask for a response
Got a null result

### What should have happened?

Have a normal response

### Version where the problem happens

4.0.1

### What Python version are you running this with?

3.9.2

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
HTTPSConnectionPool(host='chat.duti.tech', port=443): Max retries exceeded with url: /api/conversations?offset=0&limit=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x63c07bf8>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
```

**Comment by acheong08** [comment]
If you're really using `4.0.1`, any mention of chat.duti.tech has already been removed. Check your environment or venv
