### ISSUE TITLE
Login error on windows

### ISSUE THREAD

**Issue by 7Cecil** [acheong08/ChatGPT#117]
![Captura de tela 2022-12-06 224405](https://user-images.githubusercontent.com/64791735/206067208-7d8fe341-3f0a-4613-92e5-a3a2c8a988dd.png)

I'm getting this prompt. I'm on windows 10 64bit, already installed python and pip. Config.json has my email and password but still seems to have something to do with the issue.

**Comment by acheong08** [comment]
is config.json in the right place?

**Comment by acheong08** [comment]
Please follow the bug template please

**Comment by 7Cecil** [comment]
![image](https://user-images.githubusercontent.com/64791735/206067637-4c5cd2f2-a498-4a1c-9cd0-87953c9479e2.png)

config is in chatGPT-main.

Steps to reproduce the behavior:
1. Go to CMD
2. Type in "py -m revChatGPT"
3. Get this command prompt error. 

Config.json is in the files i downloaded from the repository.

**Comment by acheong08** [comment]
The config.json should be at your current working directory. Open CMD and change directory to chatGPT-main

**Comment by 7Cecil** [comment]
![image](https://user-images.githubusercontent.com/64791735/206070173-60ebf4e4-57bf-46cb-b3ee-25b7bc33aeaf.png)

Thank you so much! Unfortunately, I'm still getting this error even tho I got both my user and my password right. Any ideas, chief?

**Comment by acheong08** [comment]
What version are you on? `pip3 show revChatGPT`. The older versions have been broken by OpenAI due to bot blocking. the latest version circumvents that

**Comment by acheong08** [comment]
It's at 0.0.31

**Comment by acheong08** [comment]
Might be rate limiting. Need windows people to replicate. I can't replicate

**Comment by 7Cecil** [comment]
Ok friend. Thank you so much. BTW, more people are having the same issue on your reddit post about it.

**Comment by bird** [comment]
I've had this a few times, usually if you wait a few seconds and retry it will work.

**Comment by acheong08** [comment]
@LuckyHead11 Just try to log in and see if it works. I am literally having an exam in 20 minutes lol

**Comment by LuckyHead11** [comment]
Bruh, I have been using it fine for the past couple of minutes. So I don't know really. Wrong email or password? Same error happened when I did that

**Comment by LuckyHead11** [comment]
@acheong08 Good luck btw. Go study I think i got this

**Comment by acheong08** [comment]
> @acheong08 Good luck btw. Go study I think i got this

thanks!

**Comment by 7Cecil** [comment]
Actually, my email and password are both correct. I double-checked it.

**Comment by LuckyHead11** [comment]
Is it a google account, a microsoft account, or just regular old open ai account

**Comment by 7Cecil** [comment]
It's an open ai account.

**Comment by LuckyHead11** [comment]
Hmm. That's very odd. Try this ok... make a new file named main.py
Then put this code in there:

```
from revChatGPT.revChatGPT import Chatbot

config = {
    "email": "<YOUR_EMAIL>",
    "password": "<YOUR_PASSWORD>"#,
}

chatbot = Chatbot(config, conversation_id=None)


message = chatbot.get_chat_response(input("Enter a question: "))['message']
print(message)
```

Make sure to change <YOUR_EMAIL> with your email and <YOUR_PASSWORD> with your password

then run main.py through command prompt.

**Comment by LuckyHead11** [comment]
That's all I can do. I have to go. Good luck though hope that works out @7Cecil

**Comment by 7Cecil** [comment]
Ok, thank you so much, friend. @LuckyHead11

**Comment by LuckyHead11** [comment]
Does it work?

**Comment by 7Cecil** [comment]
@acheong08 diid !config and just confirmed it, my email and pass are indeed correct.

**Comment by acheong08** [comment]
Your request is getting blocked and I have no idea why. If you are in the ChatGPT git directory, do `git pull` to get the latest commit and try. If there are still errors, I apologize, I have no idea what is going on.

**Comment by Ziba-li** [comment]
![image](https://user-images.githubusercontent.com/90883114/206085059-d5518f14-e152-4509-92df-c5546dcca0e5.png)
I had the same problem as my friend above, and I found out in debug that it was because access_tojen was empty,I am not familiar with the Python network, please help me see how to solve this, thank you.

**Comment by acheong08** [comment]
Logging in with credentials seem to be a common issue. I will add support for accessToken-only for the next release

**Comment by Ziba-li** [comment]
Thank you very much. I'll be waiting for your update. Does“This will only allow 1hour sessions” mean long connections of up to 1 hour?

**Comment by acheong08** [comment]
Yes. You have to refresh the token manually after 1 hour

**Comment by acheong08** [comment]
I am done with the code but haven't updated docs for it yet

**Comment by Ziba-li** [comment]
Should I just input”! Refresh” when I refresh?I may need to write a timed task.Thank you.

**Comment by acheong08** [comment]
@Ziba-li Do session tokens work? https://github.com/acheong08/ChatGPT/wiki/Setup#token-authentication

Delete email and password from config and do that instead

**Comment by acheong08** [comment]
If you do that, you can just !refresh

**Comment by Ziba-li** [comment]
OK, I'll try it first

**Comment by acheong08** [comment]
I have added more verbose error handing with --debug. After updating to the latest version (0.0.31.3 atm) run python3 -m revChatGPT --debug and it should show better errors.

**Comment by acheong08** [comment]
Track in new issue https://github.com/acheong08/ChatGPT/issues/134
