### ISSUE TITLE
Nat.dev compatibility

### ISSUE THREAD

**Issue by SlickTorpedo** [acheong08/ChatGPT#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Reverse engineer https://nat.dev/ as it has a lot of AI models that are public right now for completely free. 

### Proposed workflow

1) import the package
2) select your model
3) talk to the chatbot

**Comment by acheong08** [comment]
Do they have the scale to handle traffic from this library? I can reverse it easily

**Comment by SlickTorpedo** [comment]
I'm not sure. It's owned by the former CEO of github so I would presume so? But I'm not sure.

**Comment by SlickTorpedo** [comment]
None of the code is obfuscated though so that's really good. I'm working with one of my software engineering friends and we are trying to reverse engineer it as well and if we get it I'll tell you how here to save you a little time.

**Comment by SlickTorpedo** [comment]
![image](https://user-images.githubusercontent.com/55722867/225751940-6464ad72-0831-44cc-a33d-5a57404d62a1.png)

**Comment by ading2210** [comment]
I might give a shot at writing an API wrapper for this tonight.

**Comment by ading2210** [comment]
I've just posted my API wrapper on Github: https://github.com/ading2210/openplayground-api

Currently it's very basic, as I wrote it in around an hour, but currently it has the ability to download the available models and generate text from a prompt.

**Comment by acheong08** [comment]
Closing since it was done by @ading2210
