### ISSUE TITLE
[Bug]: Deployment failure

### ISSUE THREAD

**Issue by ZhuningS** [acheong08/ChatGPT#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

  Could not find a version that satisfies the requirement tiktoken>=0.3.0 (from revChatGPT) (from versions: )
No matching distribution found for tiktoken>=0.3.0 (from revChatGPT)
![image](https://user-images.githubusercontent.com/38108376/225851472-f1b0c03a-f921-4a73-9414-3f7e687f12d7.png)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

deployment success 

### Version where the problem happens

pip3 install --upgrade revChatGPT

### What Python version are you running this with?

Python 3.6.8

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
python3 -m pip show revChatGPT
```

### Console logs

```Shell
no info
```

**Comment by acheong08** [comment]
Upgrade to Python 3.10
