### ISSUE TITLE
[Bug]: V3.py: error: unrecognized arguments: --model gpt-3.5-turbo

### ISSUE THREAD

**Issue by callzhang** [acheong08/ChatGPT#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```python
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet --model gpt-3.5-turbo
```
error: unrecognized arguments: --model gpt-3.5-turbo

### Steps to reproduce the problem

```python
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet --model gpt-3.5-turbo
```

### What should have happened?

no error

### Version where the problem happens

Name: revChatGPT
Version: 4.0.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /Users/derek/miniforge3/lib/python3.9/site-packages
Requires: httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by: 

### What Python version are you running this with?

3.9

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet --model gpt-3.5-turbo
```

### Console logs

```Shell
python3 -m revChatGPT.V3 --api_key sk-xxx --enable_internet --model gpt-3.5-turbo

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

usage: V3.py [-h] --api_key API_KEY [--temperature TEMPERATURE] [--no_stream] [--base_prompt BASE_PROMPT] [--proxy PROXY] [--top_p TOP_P]
             [--reply_count REPLY_COUNT] [--enable_internet] [--config CONFIG] [--submit_key SUBMIT_KEY]
V3.py: error: unrecognized arguments: --model gpt-3.5-turbo
```

**Comment by acheong08** [comment]
The latest version is https://github.com/acheong08/ChatGPT/releases/tag/4.0.4
