### ISSUE TITLE
[Bug]: Internal Server Error

### ISSUE THREAD

**Issue by RoseLoverX** [acheong08/ChatGPT#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Error in ask: Internal Server Error

### Steps to reproduce the problem

send a request to api endpoint with valid access_Token
v1 btw

### What should have happened?

response

### Version where the problem happens

endpoint

### What Python version are you running this with?

golang1.20

### What is your operating system ?

Windows, Linux

### Command Line Arguments

```Shell
nil
```

### Console logs

```Shell
Error in ask: Internal Server Error
```

**Comment by hrizal** [comment]
using google chrome open official url `https://chat.openai.com/chat` also blank response

**Comment by acheong08** [comment]
Fixed
