### ISSUE TITLE
[Feature Request]: V3 high request time，Some requests are longer than 60 seconds

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/19570026/226367147-d45b1176-821a-4dcc-91d0-b4afd75b082a.png">

### Proposed workflow

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/19570026/226367168-f122d78d-c550-4778-8491-29228ba7e246.png">

### Additional information

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/19570026/226367177-9ef38472-6dc9-4278-9ebd-b8e3f0a8f5fc.png">

**Comment by Martinzz** [comment]
+1

**Comment by acheong08** [comment]
OpenAI issue. I cannot fix
