### ISSUE TITLE
[Bug]: 404 Not found

### ISSUE THREAD

**Issue by AmarnathCJD** [acheong08/ChatGPT#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

https://bypass.duti.tech/api/conversation ----> 404
Not found Error

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

.

### Version where the problem happens

.

### What Python version are you running this with?

.

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

### Additional information

.

**Comment by chelishchev** [comment]
Maybe depends on https://status.openai.com/incidents/jq9232rcmktd

**Comment by acheong08** [comment]
Working now
