### ISSUE TITLE
[BUG]I am just stupid, sorry

### ISSUE THREAD

**Issue by circe11** [acheong08/ChatGPT#120]
I'm a moron and can't figure out where the config file goes, sorry.
please help me, i have put a config file everywhere i can think the working directory is but it still won't work.
surely it is somewhere in the revchat folders in the screenshot but where?
![Capture](https://user-images.githubusercontent.com/120000166/206099516-ee17821c-323b-407e-a4b1-58f9d50435e0.PNG)

**Comment by acheong08** [comment]
You current working directory is at `echo %CD%`

**Comment by acheong08** [comment]
You can change your working directory with `DIR`

**Comment by circe11** [comment]
sorry im not sure what the echo %cd% thing is or where it is. i tried seaching but only got some echos in test_asyncio folder 
i tried to change directory but still same no config and then i tried to open the new dir but no __main__ file
![image](https://user-images.githubusercontent.com/120000166/206102472-7cfe6dbb-2846-4f88-bd07-499b8ec3348b.png)

**Comment by acheong08** [comment]
Your current working directory is at `C:\Users\0`. Put the config there
