### ISSUE TITLE
[Feature Request]: Add my project to Awesome List

### ISSUE THREAD

**Issue by RockChinQ** [acheong08/ChatGPT#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I've made a project [QChatGPT](https://github.com/RockChinQ/QChatGPT) which can let people interact with ChatGPT/NewBing or other language models via Tencent QQ, and [one of its plugins](https://github.com/RockChinQ/revLibs) uses revChatGPT.  

I would like to request you to add my project to the awesome list. Thank you very much!

### Proposed workflow

(This is a request and has no other info)

**Comment by 511602** [comment]
I wonder how to use please

**Comment by acheong08** [comment]
Added.

@511602 It's in the readme

**Comment by RockChinQ** [comment]
> I wonder how to use please

Do you need a English README? File a issue there if you want.
