### ISSUE TITLE
[Feature Request]: Send json files from indexgpt

### ISSUE THREAD

**Issue by leonvit** [acheong08/ChatGPT#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like for chatgpt to reply based on my database contents that i have parsed to a json using indexgpt. I can use this functionality on the openai api this way (https://beebom.com/how-train-ai-chatbot-custom-knowledge-base-chatgpt-api/)

### Proposed workflow

1. Is it possible?

**Comment by acheong08** [comment]
Yes it is possible. Use this repo as a library and build it yourself.

**Comment by leonvit** [comment]
I have tried pretty much anything and I am still not able to implement this functionality. Any help from @acheong08 or anyone will be very much appreciated.
