### ISSUE TITLE
Message in error handler

### ISSUE THREAD

**Issue by snowmeow2** [acheong08/ChatGPT#124]
So some of the error messages are now handled by `self.debugger.log(...)` instead of `raise Exception(...)`, and we have to use `debug = True` for showing them.

I am a little confused here because we should be able to deal with such messages through `raise` rather than just print them out. And I will not know what exactly the error I am getting unless I turn on this `debug` switch since the text in `raise` still looks incomplete.

In addition, some messages seem to be printed twice when we run `__main__.py` with `--debug`, for example, on line 200
```
self.debugger.log("Error refreshing session")
self.debugger.log(response.text)
raise Exception("Error refreshing session") from exc
``` 

Do you have any plans/logic flow for this (how to handle messages properly), or did I miss something?

**Comment by acheong08** [comment]
Sorry. I broke something. Will fix in next release

**Comment by acheong08** [comment]
Already did but an unresolved merge request is in the way. Should be done in a few minutes

**Comment by acheong08** [comment]
Fixed

**Comment by acheong08** [comment]
Debugging is more difficult than I thought

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`. Also `pip3 install --upgrade OpenAIAuth` if you installed an older version
