### ISSUE TITLE
[Feature Request]: Add Chat with Embedding feature

### ISSUE THREAD

**Issue by sungkim11** [acheong08/ChatGPT#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When LLM responds based on Embedding results, clicking on the response will open up the right nav with Embedding results with associated metadata. Embedding results can be 1 or multiple, so pagination is needed.

### Proposed workflow

1. Go to Chat
2. Click on Response
3. Open associated Embedding results on the right nav.

### Additional information

No additional information Embedding results can be pandas data frame.

**Comment by acheong08** [comment]
out of scope
