### ISSUE TITLE
[Feature Request]:  reverse ChatGPT server working with latest version with rate limit and domain limitation features

### ISSUE THREAD

**Issue by Abolfazl74** [acheong08/ChatGPT#1268]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello, I've made a project to make server for your amazing project which works with latest version and has user limitation feature. The other server version in your list that I checked is outdated, and it's not working with current version.

Here it's the link of the project:
https://github.com/Abolfazl74/revChatGPTApiServer

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by sean284150** [comment]
raise error from None revChatGPT.typings.Error: __get_cached_access_token: Invalid access token (code: 5)

**Comment by Abolfazl74** [comment]
Obviously, your access token has problems. Please edit config.json file and check if your access token is valid

**Comment by acheong08** [comment]
improper issue. missing details
