### ISSUE TITLE
[Feature Request]: Add rAIversing to Awesome List

### ISSUE THREAD

**Issue by MrMatch246** [acheong08/ChatGPT#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Please add [rAIversing](https://github.com/MrMatch246/rAIversing) to your [Awesome List](https://github.com/stars/acheong08/lists/awesome-chatgpt)
rAIversing is a small but powerfull tool written in python that uses ghidra and chatGPT API (kinda needed) to reverse engineer binaries. It can be used on already existing ghidra projects as well as plain binaries. setup.py has code to get some test binaries that cost arount 10-30 cents to reverse. 

### Proposed workflow

Add it please.

### Additional information

WIP please feel free to open issues if you encounter problems

**Comment by acheong08** [comment]
added. looks cool
