### ISSUE TITLE
[Bug]: V1 response error code: 1020

### ISSUE THREAD

**Issue by fkxxyz** [acheong08/ChatGPT#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Can't talk to chatbot

### Steps to reproduce the problem

pip install --upgrade revChatGPT
python3 -m revChatGPT.V1

type "hello" and press ALT+Enter

### What should have happened?

get a reply from Chatbot

### Version where the problem happens

Name: revChatGPT
Version: 4.0.11
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/fkxxyz/.local/lib/python3.10/site-packages
Requires: OpenAIAuth, requests, httpx, prompt-toolkit, tiktoken, openai
Required-by: 

### What Python version are you running this with?

Python 3.10.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
python3 -m pip show revChatGPT
```

### Console logs

```Shell
# fkxxyz @ office-99-fkxxyz in ~ [19:20:31] 
$ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You: 
hello

Chatbot: 
error code: 1020
Traceback (most recent call last):
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 962, in main
    for data in chatbot.ask(prompt):
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 449, in ask
    self.__check_response(response)
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 557, in __check_response
    raise error
revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 986, in <module>
    main(configure())
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/fkxxyz/.local/lib/python3.10/site-packages/revChatGPT/V1.py", line 972, in main
    raise error from e
revChatGPT.typings.CLIError: command line program unknown error
```

### Additional information

bypass.churchless.tech is down?

**Comment by Jxells** [comment]
error code: 1020

**Comment by Germey** [comment]
Same error

**Comment by sunjiadai** [comment]
revChatGPT.typings.Error: OpenAI: error code: 1020 (code: 403)

**Comment by acheong08** [comment]
fixed

**Comment by acheong08** [comment]
OpenAI blocked my IP. It seems they really dislike the proxy server

**Comment by peanut996** [comment]
> OpenAI blocked my IP. It seems they really dislike the proxy server. Just swapped over to another server I set up beforehand in case this happens

my ip is also blocked.  i do not know whether use your go proxy will be block?.

**Comment by acheong08** [comment]
PUID gets around it most times unless OpenAI explicitly blocks your IP rather than just IP range

**Comment by peanut996** [comment]
> PUID gets around it most times unless OpenAI explicitly blocks your IP rather than just IP range

i think open ai just block my ip by range.  :(

**Comment by acheong08** [comment]
> i think open ai just block my ip by range. :(

Then having a puid will get around it

**Comment by peanut996** [comment]
> > i think open ai just block my ip by range. :(
> 
> Then having a puid will get around it

maybe my puid expires?

**Comment by acheong08** [comment]
fixed

**Comment by acheong08** [comment]
> Do you have multiple proxies IP and random change for every call? Or just one fixed proxy IP?

Load balanced between 2 servers atm. The reason for that isn't because of load but rather because of how I have to rotate the IP every few days (a small script does that automatically). This is because it was figured out that the previous ban wave was due to the server IP being flagged while self hosted instances were not affected. There is a bit of downtime when IP changes which is when the other server takes the load.

> Do you have multiple PUIDs behind it? Or you just have one and just renew it before expired.

It uses both a cf_clearance and a single PUID. It refreshes the cf_clearance via another service proxied to the public server (because those are linked to IP. the cf_clearance is fetched with an automated browser). This allows for some fallback in case either one of them fails. I manually refresh the access token every 2 weeks (which is used in turn to fetch the PUID). It seems that just now, the cf_clearance fetch hit a captcha while the access token used prematurely expired due to myself logging in to the account used for the proxy (which sometimes revokes old access tokens).

**Comment by Germey** [comment]
Same issue occurrs

**Comment by chelishchev** [comment]
@acheong08 hi!
The error reappears right now

**Comment by saccohuo** [comment]
Same error occurs.

**Comment by hrizal** [comment]
i got this too 1020

**Comment by FriendlyUser** [comment]
same error

**Comment by Germey** [comment]
@acheong08 any news?

**Comment by stoickk** [comment]
same error
