### ISSUE TITLE
[Feature Request]: Deploying to a server

### ISSUE THREAD

**Issue by leonvit** [acheong08/ChatGPT#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have created a simple flask api for this package. When I run the api locally it works but when I deploy it to a render.com server I receive the below error. 

Can someone help?

The error:
`
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f726ab2cad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

The api code:
```

from flask import Flask, request, jsonify
from revChatGPT.V1 import Chatbot

app = Flask(__name__)

chatbot = Chatbot(config={
  "access_token": "<ACCESS TOKEN>"
})

@app.route('/ask', methods=['POST'])
def ask():
    prompt = request.json['prompt']

    response = ''
    for data in chatbot.ask(prompt):
        response = data["message"]

    return jsonify({'response': response})

if __name__ == '__main__':
    app.run()

```

### Proposed workflow

1. Deploy to render.com

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`
