### ISSUE TITLE
[Bug]: v3 接口返回很慢是怎么回事

### ISSUE THREAD

**Issue by QiuZiXian** [acheong08/ChatGPT#1282]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

v3 接口返回很慢是怎么回事？
是openai对api限速了吗，还是对免费用户限速。
用plus测了，感觉也很慢

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

v3响应太慢，是否可以提速到10s内，5秒内更好

### Version where the problem happens

v3提问

### Command Line Arguments

```Shell
response too slowly
```

### Console logs

```Shell
response too slowly
```

**Comment by QiuZiXian** [comment]
是否是官方针对性限速？https://community.openai.com/t/your-service-is-useless-for-developers-just-tell-us-the-truth/145376

**Comment by jk256** [comment]
api平均每个回复 现在30S+ ，东部沿海+美国直连节点。还以为是我网络问题。
