### ISSUE TITLE
[Bug]: Fucked up cloudflare compression

### ISSUE THREAD

**Issue by noname01t1** [acheong08/ChatGPT#1283]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

第二次对话尽管`conversation_id=None`，但仍然没有`New Chat`

### Steps to reproduce the problem

在同一程序，先`for data in chatbot.ask(prompt=prompt, conversation_id=None):`  
然后再`for data in chatbot.ask(prompt=prompt, conversation_id=None):` 

会发现两次对话在同一个对话中，而不是分开的。即第二次并未新建对话

### What should have happened?

理论而言，只有设置了conversation_id才应该继续对话。设置为无应该新建对话

### Version where the problem happens

```
Name: revChatGPT
Version: 4.1.4
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.9/dist-packages
Requires: tiktoken, OpenAIAuth, prompt-toolkit, openai, requests, httpx
Required-by:
```

### What Python version are you running this with?

Python 3.9.5

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
好像没找到设置debug的方式，因此没有log。如果有设置为debug方式，请麻烦告知
```

### Additional information

快速复现方法：
```py
from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "access_token": "<your access_token>"
})

print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()

prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
```

**Comment by noname01t1** [comment]
Docs问题，要reset_chat。但是wiki里没说明白会自动储存

**Comment by jahentao** [comment]
> 好像是docs问题，要reset_chat。但是wiki里没说明白会自动储存

怎么reset_chat？conversation_id是在哪获取的，我没找到啊

**Comment by d1h1r1** [comment]
我填了conversation_id但是每次还是打开新对话，不能联系上下文
![image](https://github.com/acheong08/ChatGPT/assets/103206466/9c98c427-274a-4776-a992-845df47b221d)

**Comment by acheong08** [comment]
API changed. I will fix

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/ChatGPT/assets/36258159/e5528283-d80f-4d85-97a2-4b74562f6317)

![image](https://github.com/acheong08/ChatGPT/assets/36258159/dee6dafe-901e-46f9-a796-3a5d2d09e1e1)
