### ISSUE TITLE
[Bug]: ValueError: PUID is required

### ISSUE THREAD

**Issue by t7rr7xb** [acheong08/ChatGPT#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When use email-passwork or session_token login method, raise Exception:
ValueError: PUID is required

### Steps to reproduce the problem

1. chatbot = Chatbot(config={
    "session_token": session_token,
})

### What should have happened?

ValueError: PUID is required

### Version where the problem happens

env:
Python 3.11
revChatGPT              4.1.4

### What Python version are you running this with?

Python 3.11.2

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
File "/Users/env_python311/lib/python3.11/site-packages/OpenAIAuth.py", line 38, in __init__
raise ValueError("PUID is required")
```

**Comment by LongforRealthing** [comment]
Maybe you can use access_token to login, I met the same problem and changed to access_token then it's fine

**Comment by ggg5438** [comment]
Me either have the same issue. I input email and password. It worked but does not work now after update of revChatGPT.

**Comment by acheong08** [comment]
Please use access tokens. OpenAI shut down the authentication for non-plus users

**Comment by uniqueni** [comment]
> 

@acheong08 我是plus会员 为什么还是无法验证啊

**Comment by Cherish90722** [comment]
Why do I still prompt the frequency display 3 times per minute when I am a plus member
