### ISSUE TITLE
Increase the truncate limit when using V3.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#1287]
在使用V3的时候，有时候会得不到完整的回复。结果总是缺少后面的一部分。有没有办法提高  truncate limit？

**Comment by wangjiyang** [comment]
Same issue here.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/4.1.6

**Comment by acheong08** [comment]
CLI: `--truncate_limit 3500`
Dev: `truncate_limit=3500`

**Comment by hongyi-zhao** [comment]
V1 是否也可以添加类似实现？

**Comment by acheong08** [comment]
V1 handled server side by OpenAI

**Comment by hongyi-zhao** [comment]
For different models called by V3, what are the corresponding truncate limit upper bounds?

**Comment by acheong08** [comment]
> For different models called by V3, what are the corresponding truncate limit upper bounds?

4k - gpt-3.5
8k - gpt-4
32k - gpt-32k

**Comment by hongyi-zhao** [comment]
Here, k means 1000 or 1024?

**Comment by acheong08** [comment]
1024
