### ISSUE TITLE
new aws project

### ISSUE THREAD

**Issue by PlexPt** [acheong08/ChatGPT#129]
https://github.com/PlexPt/chatgpt-java

**Comment by acheong08** [comment]
Nice to see implementations in other languages. Added to list. OpenAI's email/password auth is difficult to translate at the moment though due to custom TLS requirements. Good luck

**Comment by acheong08** [comment]
@rawandahmad698 is the one that implemented the OpenAI Authentication. I have no idea how he did it, I only took the code and modified it to fit this repository. You might also need the help of @FlorianREGAZ who wrote the TLS client
