### ISSUE TITLE
[Bug]: v1/chat/completions endpoint Not Found

### ISSUE THREAD

**Issue by JustinLiang522** [acheong08/ChatGPT#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

v1/chat/completions endpoint Not Found

### Steps to reproduce the problem

execute `python -m revChatGPT.V3 --api_key <api_key>`

### What should have happened?

response correctly

### Version where the problem happens

master

### What Python version are you running this with?

3.11.3

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
revChatGPT.typings.APIConnectionError: 404 Not Found {
  "error": {
    "message": "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}
```

**Comment by acheong08** [comment]
This is very strange.

**Comment by JustinLiang522** [comment]
> Can you offer more info on the model used? Looks like you tried to use text-davinci-003

I think there was something wrong with my API KEY. It works after I updated it.
