### ISSUE TITLE
[Feature Request]: Auto GPT Integration

### ISSUE THREAD

**Issue by murfASM** [acheong08/ChatGPT#1302]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Auto GPT integration

### Proposed workflow

Just compatibility with auto would be nice

**Comment by maminiainalaic** [comment]
excellent idea

**Comment by acheong08** [comment]
I haven't looked into the internals of AutoGPT yet. If you have any ideas on how this could be implemented, let me know

**Comment by peteh** [comment]
You would need to modify: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/autogpt/llm_utils.py

The function create_chat_completion() should be extended to handle other chatbots.

**Comment by PsychoSmiley** [comment]
One possible solution would be to act as openai api by redirect requests.

**Comment by acheong08** [comment]
You can tweak AutoGPT to use chat.openai.com by changing the endpoint to self hosted https://github.com/acheong08/ChatGPT-to-API

**Comment by acheong08** [comment]
> [Look this](https://github.com/IntelligenzaArtificiale/Free-AUTO-GPT-with-NO-API)

Bump. Closing this as completed. Thank you for your work @IntelligenzaArtificiale
