### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by baifagg** [acheong08/ChatGPT#132]
![image](https://user-images.githubusercontent.com/51266591/206180660-76504807-8a73-4d19-a52d-5bd9d7792c07.png)
Failed to install BS4. I wonder if other people have this problem. I checked that BS4 is a python2 package

**Comment by acheong08** [comment]
Outdated version of `revChatGPT` 

`pip3 install --upgrade revChatGPT`

**Comment by baifagg** [comment]
> 

It seems that the pip image website I use is too old. Which pip image do you recommend

**Comment by acheong08** [comment]
> It seems that the pip image website I use is too old. Which pip image do you recommend

The latest version is `0.0.31.5`. You can upgrade by doing `pip3 install --upgrade revChatGPT`

**Comment by David-19940718** [comment]
> > It seems that the pip image website I use is too old. Which pip image do you recommend
> 
> The latest version is `0.0.31.5`. You can upgrade by doing `pip3 install --upgrade revChatGPT`

Why the version is always 0.0.23.6 even the commond line `pip3 install --upgrade revChatGPT` is run over and over again?

**Comment by acheong08** [comment]
Do `pip3 install revChatGPT==0.0.31.5`
