### ISSUE TITLE
[Bug]: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by wenyinos** [acheong08/ChatGPT#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bypass.churchless.tech/api/conversation

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

reply messages

### Version where the problem happens

4.2.2

### What Python version are you running this with?

3.10.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/site-packages/revChatGPT/V1.py", line 689, in __check_response
    response.raise_for_status()
  File "/home/wenyinos/qcg-bot/python/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bypass.churchless.tech/api/conversation
```

**Comment by peanut996** [comment]
@acheong08 it seems your proxy server has been blocked by using puid and access token？ or expires

**Comment by liustar1989** [comment]
The v4 proxy I built myself is also invalid, and even if I update the puid and access token, it won't work

**Comment by peanut996** [comment]
seems that puid can not bypass cf anymore. sad :(

**Comment by acheong08** [comment]
Track: https://github.com/acheong08/ChatGPT/issues/1336
