### ISSUE TITLE
[Feature Request]: Is not very clear how to execute the api locally

### ISSUE THREAD

**Issue by OscarJVD** [acheong08/ChatGPT#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Is not very clear how to execute the api locally

### Proposed workflow

Is not very clear how to execute the api locally

### Additional information

Is not very clear how to execute the api locally

**Comment by acheong08** [comment]
Try https://github.com/linweiyuan/go-chatgpt-api. It is documented there.
