### ISSUE TITLE
[Feature Request] : Support azure openAi service 

### ISSUE THREAD

**Issue by myh-st** [acheong08/ChatGPT#1342]
Here's sample from Microsoft

 - gpt-35-turbo 
 - gpt-4
 - gpt-4-32k

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=programming-language-python

**Comment by acheong08** [comment]
`export API_URL="https://yourazuredomain.com/v1/chat/completions"` or something like that

**Comment by acheong08** [comment]
and then run V3
