### ISSUE TITLE
[Feature Request]: ChatGPT-Plus  application for add my project to Awesome List.

### ISSUE THREAD

**Issue by zhpd** [acheong08/ChatGPT#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have developed a [ChatGPT-Plus](https://github.com/zhpd/chatgpt-plus) application that can be deployed for free with one click.
Online  ：[https://chatgpt-plus.app](https://chatgpt-plus.app)
Github ：[https://github.com/zhpd/chatgpt-plus](https://github.com/zhpd/chatgpt-plus)
 It includes features such as: 
- 📦 a full ChatGPT client; 
- 🚀 built with Nextjs & Nestjs for quick start-up; 
- 📱 responsive design for mobile access; 
- 🌈 support for multiple themes, day/night mode;
- 🌍 internationalization support, currently supporting Chinese and English; 
- 📦 support for custom prompts, view online recommended prompts; 
- 🎨 use of CSS-in-JS technology for theme customization; 
- 📦 support for Docker & Vercel deployment.

I would like to request you to add my project to the awesome list. Thank you very much!
![image](https://user-images.githubusercontent.com/11941825/233058800-22d7bf6f-fd26-48f1-a74e-983dffa518fc.png)
![image](https://user-images.githubusercontent.com/11941825/233058830-c3825e10-810b-435b-9838-81324a2b2ed4.png)

### Proposed workflow

(none)

### Additional information

(none)

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/233250429-a3ffb089-7bc5-41f7-8967-854871019218.png)

Buggy
