### ISSUE TITLE
requests.exceptions.HTTPError: 524 Server Error:  for url: https://bypass.churchless.tech/conversation

### ISSUE THREAD

**Issue by gogoods** [acheong08/ChatGPT#1362]
![image](https://user-images.githubusercontent.com/3422759/233830354-df9f0461-5f5c-4974-a222-2da0e630d7d0.png)
![image](https://user-images.githubusercontent.com/3422759/233830374-b2cd0899-0a0d-465d-97d5-df3c6be66d5e.png)

@acheong08 
Excuse me, is this OPENAI's server error? just wait for them to fix?

**Comment by acheong08** [comment]
check again?

**Comment by acheong08** [comment]
I just updated the server to make it more reliable.

**Comment by gogoods** [comment]
@acheong08 
Upgraded revChatGP and it stll existed!

But the day before yesterday I  changed my server(public ip), it's ok!

Maybe my previous server ip was blocked? Th errmsg was confusing...

**Comment by yendeus** [comment]
Hi, I am having the exact same error right now

**Comment by acheong08** [comment]
Fixed

**Comment by vgdh** [comment]
have the same issue

**Comment by acheong08** [comment]
Must be a temporary error. *works on my computer*
