### ISSUE TITLE
[Feature Request]: Add free OPENAI API support without account and KEY.

### ISSUE THREAD

**Issue by ClassmateLin** [acheong08/ChatGPT#1366]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Call Vercel API to get free gpt-3.5-turbo.

### Proposed workflow

vercel provides free [AI Playground](https://play.vercel.ai/).
Anonymous users can use it 10 times for free, but they can always use it for free by changing user-agent.
The repository has implemented: `https://github.com/ClassmateLin/free-chatgpt`.
Request to add to module: revChatGPT.

**Comment by acheong08** [comment]
Does this support conversations?

**Comment by Beckjiang** [comment]
@acheong08 
Based on revChatGPT, I have implemented a compatible interface layer for Chat API, supporting GPT-3.5 and GPT-4 (requires a paid account). Session persistence is implemented through API keys. 

May be similar to chatgpt-to-api.
https://github.com/Beckjiang/chatgpt-api
