### ISSUE TITLE
Could you provide a different method to logging into OpenAi?

### ISSUE THREAD

**Issue by Maki9009** [acheong08/ChatGPT#137]
Since I can't log in into OpenAi natively, I authenticate using my google account. so i cant really use your login method here.

**Comment by thehemi** [comment]
Why don't you log in once, and then supply the authentication token from the browser (F12). The code will refresh the session token.

**Comment by alberduris** [comment]
Yes, you can! See #96 

We are currently working on improving the docs to make this clearer.

**Comment by acheong08** [comment]
Docs are up to date
