### ISSUE TITLE
Able to change the name of the bot [Feature Request]: 

### ISSUE THREAD

**Issue by RavenVR** [acheong08/ChatGPT#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I'm working on a chatGPT discord bot with context and I feel like there should be a way to rename the bot to what ever you want so instead of:
I'm ChatGPT, a language model developed by OpenAI. You can call me ChatGPT or simply Chat.

it could be:
I'm A Discord Chat Bot, a language model developed by OpenAI. You can call me ChatGPT or simply Chat.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
Put as system prompt for V3. For V1, just tell it to in the first prompt
