### ISSUE TITLE
[Feature Request]: Add support for plugin

### ISSUE THREAD

**Issue by PlexPt** [acheong08/ChatGPT#1374]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Add support for plugin

### Proposed workflow

1. Add support for plugin

### Additional information

Add support for plugin

**Comment by Erol444** [comment]
Hi @acheong08 ,
`POST` request below to `https://chat.openai.com/backend-api/conversation`. I am using `Wolfram` plugin. I am not sure how plugin names are mapped to IDs..
```
{
  "action": "next",
  "messages": [
    {
      "id": "aaa2a960-2fb2-4ad9-8b5b-424ac4158d10",
      "author": { "role": "user" },
      "content": {
        "content_type": "text",
        "parts": [
          "Three positive numbers are presented to you. These figures can be multiplied and added together. Your outcome will be the same. What numbers are there?"
        ]
      }
    }
  ],
  "parent_message_id": "aaa195ef-c616-411e-bcfc-b7d14ee575dd",
  "model": "gpt-4-plugins",
  "plugin_ids": ["plugin-d1d6eb04-3375-40aa-940a-c2fc57ce0f51"],
  "timezone_offset_min": -120,
  "history_and_training_disabled": false
}
```

**Comment by acheong08** [comment]
Supported!
