### ISSUE TITLE
[Bug]: cloudflare blocked

### ISSUE THREAD

**Issue by cncbec** [acheong08/ChatGPT#1384]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://github.com/acheong08/ChatGPT/assets/54312958/391294bf-d462-4137-9089-f872506e0d83)

### Steps to reproduce the problem

![image](https://github.com/acheong08/ChatGPT/assets/54312958/11a42b69-56f3-4e5e-aba6-3603000f3e0c)

### What should have happened?

maybe try a new method?

### Version where the problem happens

5.1

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
python my-custom-file.py
```

### Console logs

```Shell
revChatGPT\V1.py", line 675, in __check_response
```

**Comment by acheong08** [comment]
fixed
