### ISSUE TITLE
[Bug]: Why I had set the conversation_id variable  ,but every time new conversation was still created

### ISSUE THREAD

**Issue by lnxknl4** [acheong08/ChatGPT#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Every chat was created with a new covnerstion

### Steps to reproduce the problem

I just set config conversation_id varibel to a fixed number, Just Started it was running normally , Later it running with every chat with new conversation.

### What should have happened?

There are someone else have met the same problem, So I can know this is not my config caused.

### Version where the problem happens

revChatGPT                              5.0.0

### What Python version are you running this with?

Python 3.10.10

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
I add print the conversation_id varible returned , it was different wiht my setted fixed variable
```

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/5.1.3

**Comment by d1h1r1** [comment]
现在可以了吗？我也是设置了conversation_id变量，但每次仍然创建新对话
