### ISSUE TITLE
[Feature Request]: V3 version of ask_stream doesn't request results by streaming

### ISSUE THREAD

**Issue by whiteeat** [acheong08/ChatGPT#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

As title says The V3 version of ask_stream doesn't request results by streaming. Will it be changed to do request in a real streaming way in the future?

### Proposed workflow

None

**Comment by acheong08** [comment]
It does stream

**Comment by whiteeat** [comment]
So sorry! I think I didn't read the code carefully enough and use it in a wrong way. 

> It does stream. What do you mean "real streaming"
