### ISSUE TITLE
[Feature Request]: GPT-4 (Mobile, V2)

### ISSUE THREAD

**Issue by WhiteCranes** [acheong08/ChatGPT#1408]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

What is the difference between the post_messages function and the ask function? Also, how to use GPT-4 (Mobile, V2)?What is the difference between the post_messages function and the ask function? Also, how to use GPT-4 (Mobile, V2)?

### Proposed workflow

What is the difference between the post_messages function and the ask function? Also, how to use GPT-4 (Mobile, V2)?

### Additional information

What is the difference between the post_messages function and the ask function? Also, how to use GPT-4 (Mobile, V2)?

**Comment by WhiteCranes** [comment]
Is anyone there? Why isn't anyone replying to me? Don't you all want to use the UNLIMITED GPT-4 (Mobile, V2)? Or is there already a way to use it?

**Comment by WhiteCranes** [comment]
I need your help.

**Comment by WhiteCranes** [comment]
I need your help.

**Comment by acheong08** [comment]
https://twitter.com/acheong08/status/1669893977762574338

I'll try to add support now

**Comment by acheong08** [comment]
Edit: Hey, it's already supported. Just in `config.json`: `"model":"gpt-4-mobile"`

**Comment by WhiteCranes** [comment]
> Edit: Hey, it's already supported. Just in `config.json`: `"model":"gpt-4-mobile"`

thx
