### ISSUE TITLE
[Feature Request]: 建一个chatGPT扩展api讨论群微信讨论群是否可以？

### ISSUE THREAD

**Issue by kuaitoukuai** [acheong08/ChatGPT#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![915020ec1d2d009fd8bbbfa184e6b3d](https://github.com/acheong08/ChatGPT/assets/73692477/c2d3aa7f-b4e3-49d5-b967-ed4df8f36d0e)

### Proposed workflow

[Feature Request]: 建一个chatGPT扩展api讨论群微信讨论群是否可以？

**Comment by InterestingDarkness** [comment]
哥，我不知道你要建微信群做什么。首先，微信就是一个垃圾到爆的软件，随便用几下就封号，连QQ都不如。其实，建群有什么用？吹水吗，一天几百条消息，也找不出几条有价值的

(English translated by DeepL)
I don't know what you need to do to build a WeChat group. First of all, WeChat is a garbage to burst software, just use a few times to seal the number, even QQ is not as good. In fact, what is the use of building a group? The actual fact is that you will be able to find a few valuable messages a day.

**Comment by acheong08** [comment]
My wechat account is banned and can't join groups. We have a Discord and Matrix is also an option

**Comment by zwluoqi** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues and checked the recent builds/commits
> 
> ### What would your feature do ?
> 
> ![915020ec1d2d009fd8bbbfa184e6b3d](https://github.com/acheong08/ChatGPT/assets/73692477/c2d3aa7f-b4e3-49d5-b967-ed4df8f36d0e)
> 
> ### Proposed workflow
> 
> [Feature Request]: 建一个chatGPT扩展api讨论群微信讨论群是否可以？
> 
> ### Additional information
> 
> _No response_
傻逼玩意儿，导流都开始在这里了，操你妈逼。
（Motherfucker, the diversion's starting here. Fuck you.）

**Comment by acheong08** [comment]
https://discord.gg/9K2BvbXEHT
