### ISSUE TITLE
[Feature Request]: Does it support function_call calls?

### ISSUE THREAD

**Issue by nowindnowave** [acheong08/ChatGPT#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Does the latest version support the function_call call of the openai official website?

### Proposed workflow

 Can it be added? Thank you

**Comment by nowindnowave** [comment]
I have achieved it

**Comment by IAn2018cs** [comment]
> I have achieved it

Can it be open sourced?

**Comment by acheong08** [comment]
It's just prompting with the new model
