### ISSUE TITLE
[Bug]:  API calls to the model of gpt-3.5-turbo may result in errors

### ISSUE THREAD

**Issue by ainndejj11** [acheong08/ChatGPT#1442]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Using the same network and OpenAI key
By calling the gpt-3.5-turbo model in my own python code, I can run it correctly

### Steps to reproduce the problem

Using the same network and OpenAI key
By calling the gpt-3.5-turbo model in my own python code, I can run it correctly

The code example is as follows：

    from langchain.llms import OpenAI
    openai_api_key = ' '
    llm = OpenAI(model_name='gpt-3.5-turbo', openai_api_key=openai_api_key)

    promit = "hello"
    result = llm(promit)
    print(result)

But calling this gpt-3.5 turbo model under another project will cause problems, The error message is as follows：
APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openapi.com', port=443): Max 
retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of 
protocol (_ssl.c:1131)')))

### What should have happened?

May I ask what is the reason and how should I solve it？？

### Version where the problem happens

.

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openapi.com', port=443): Max 
retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of 
protocol (_ssl.c:1131)')))
```

**Comment by acheong08** [comment]
SSL errors are caused by your own network
