### ISSUE TITLE
[Feature Request]: Automating captcha solver

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Use **math** to solve captcha 

### Proposed workflow

I'm not a very mathematical person but I remember implementing this a long time ago (but forgot how to)

1. Split the single challenge image into 6 options and 1 pointer
2. Remove background from captcha images
3. Find two points with pixels on the option image furthest away from each other
4. Determine pointing direction based on line between the two points
5. Repeat for pointer image
6. Find image with closest angle

### Additional information

Imdumbafandidkhowtodothis

**Comment by ItzMaxTV** [comment]
I don't think they only use directional captchas, right?

**Comment by acheong08** [comment]
For now, yes, they do

**Comment by ItzMaxTV** [comment]
> For now, yes, they do

Alright, I got an idea, I'll try to apply it and create a pull request.
Perhaps, not sure yet, but I think I can automate this..

**Comment by ItzMaxTV** [comment]
![3](https://github.com/acheong08/ChatGPT/assets/62325490/85a16f40-e23f-412d-932b-be10f8b8bac7)

It looks good till now..

**Comment by acheong08** [comment]
Thanks. This might be necessary again. Looks like they picked up on our updated fingerprint

**Comment by acheong08** [comment]
> ![3](https://user-images.githubusercontent.com/62325490/250187900-85a16f40-e23f-412d-932b-be10f8b8bac7.png)
> 
> It looks good till now..

This looks amazing. Any hints on how you're implementing this?

**Comment by ItzMaxTV** [comment]
> > ![3](https://user-images.githubusercontent.com/62325490/250187900-85a16f40-e23f-412d-932b-be10f8b8bac7.png)
> > It looks good till now..
> 
> This looks amazing. Any hints on how you're implementing this?

Yes it's actually really easy to do. I changed up the system a bit and started using YOLOv8 but it seems like we do have to train it on these kind of pictures.

1 - Use YOLOv8 or any model that can at least understand that the items in the images are objects so we could highlight them.
2 - Enumerate over all the items and use CV2 to draw a rectangle around them.

The issue now is that I've tried multiple ways to actually see how am I supposed to make it calculate the angle of the object. One is that we draw a box over each object, draw a line going from each corner to the other inside the box. Once we're done with that, we then calculate the angle of the lines compared to box and take the sum.

P.S. YOLOv8 can't detect it properly, so we need to find a better model or train YOLOv8..

**Comment by acheong08** [comment]
> The issue now is that I've tried multiple ways to actually see how am I supposed to make it calculate the angle of the object

If you are already putting a rectangle around it, is it possible to simply find the angle of the longest line of the rectangle?

**Comment by acheong08** [comment]
On another note, it seems the captcha now changes occasionally to other visual challenges. This would become futile

**Comment by acheong08** [comment]
I'm also tracking the status of my different APIs here: https://stats.churchless.tech/

And it seems I haven't been hitting any captchas since updating the fingerprint

**Comment by ItzMaxTV** [comment]
> > The issue now is that I've tried multiple ways to actually see how am I supposed to make it calculate the angle of the object
> 
> If you are already putting a rectangle around it, is it possible to simply find the angle of the longest line of the rectangle?

I actually haven't tried that, but true, this can actually work since this can easily determine if the finger is pointing up or to the side..



> On another note, it seems the captcha now changes occasionally to other visual challenges. This would become futile

That is unfortunate, it just means that this system can't work properly anymore..



> I'm also tracking the status of my different APIs here: https://stats.churchless.tech/
> 
> And it seems I haven't been hitting any captchas since updating the fingerprint

Finally some good news, do you think it'll stay this way?

**Comment by acheong08** [comment]
> Finally some good news, do you think it'll stay this way?

*It depends*

OpenAI can very easily enforce captcha on every request regardless of fingerprint at the press of a button. @linweiyuan is working on getting the fingerprint and so far it has led to pretty good results

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/ChatGPT/assets/36258159/530d7b75-0e37-4168-875d-9107a0093a7d)

Here's all the token endpoints I'm checking out right now.

**Comment by ItzMaxTV** [comment]
> ![image](https://user-images.githubusercontent.com/36258159/250291503-530d7b75-0e37-4168-875d-9107a0093a7d.png)
> 
> Here's all the token endpoints I'm monitoring right now. We could have a system to check for the one with the highest ping & success rate and fetch from there

Great idea to monitor multiple instances simultaneously..
