### ISSUE TITLE
6.7.3 version problem？

### ISSUE THREAD

**Issue by wqjuser** [acheong08/ChatGPT#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When using the V1 API method, if I add configs ['SERVER_SIDE_ARKOSE ']=True and use the gpt-4 model, OpenAI will be returned: {"error": "captcha required"} (code: 500). If I do not add configs ['SERVER_SIDE_ARKOSE']=True, status code 400 will be returned

### Steps to reproduce the problem

just use V1 api method to ask

### What should have happened?

should return result

### Version where the problem happens

6.7.3

### What Python version are you running this with?

3.10.11

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Setting PUID (You are a Plus user!): user-oEzDTm0z0Lj8lfVtyzsXXXXX:1688187432-p853r09C7ZdKDW76lq1mliqdHxIFbYToy0lhqZ2QG80%3D
Error: OpenAI: {"error":"captcha required"} (code: 500)

Setting PUID (You are a Plus user!): user-oEzDTm0z0Lj8lfVtyzsXXXXX:1688187036-l5zTarXrNsTLGw5gLYA2QFuslXp%2BmsK7dGvFqU5xHZY%3D
status code 400
Error: status code 400
```

**Comment by hzlujunyi** [comment]
@acheong08 Seems like the arkose is down.

**Comment by hzlujunyi** [comment]
@wqjuser Changing the get_arkose_token method to Pengzhile's is a temporary solution

**Comment by acheong08** [comment]
The current default is now server side akrose + captcha. The environment variable is now pretty much meaningless. 

The reason for the lack of client side arkose is due to the reverse engineering of captcha being written in Go

**Comment by acheong08** [comment]
> @acheong08 Seems like the URL for getting arkose is down.

Not sure why the reason for that is. Restarting the server fixed it

**Comment by wqjuser** [comment]
Thank you. I have tried it again and there are currently no issues
