### ISSUE TITLE
[Feature Request]: Additions to Awesome ChatGPT

### ISSUE THREAD

**Issue by adamlui** [acheong08/ChatGPT#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I am proposing to add these cool projects to your Awesome ChatGPT list by opening an issue per your instructions:

- [DuckDuckGPT](https://github.com/kudoai/duckduckgpt) - Adds ChatGPT to DuckDuckGo sidebar
- [BraveGPT](https://github.com/kudoai/bravegpt) - Adds ChatGPT to Brave Search sidebar
- [chatgpt.js](https://github.com/kudoai/chatgpt.js) - A powerful client-side JavaScript library for interacting w/ the ChatGPT DOM

### Proposed workflow

N/A

**Comment by acheong08** [comment]
👍🏻
