### ISSUE TITLE
[Bug]: Field missing. Details: {'conversation_id': 'abf665f2-3c8f-4725-8263-5893bb5847ff', 'message_id': 'b8fe1067-2610-4bea-b33b-93b099b3803b', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eEtljxtdnGEn9sCjBEKoPBeuGh7M'}}

### ISSUE THREAD

**Issue by ashishbinu** [acheong08/ChatGPT#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Today, the revChatGPT.V1 package broke. It was fine till yesterday.

### Steps to reproduce the problem

1. Install `revchatgpt` using `python -m pip install --upgrade revChatGPT`
2. `python3 -m revChatGPT.V1`
3. Type anything. For example - what is 2 + 2?

### What should have happened?

It should have given some kind of response and no error should have appeared.

### Version where the problem happens

```
Name: revChatGPT
Version: 6.8.3
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/ash/.local/lib/python3.11/site-packages
Requires: httpx, openai, OpenAIAuth, prompt-toolkit, requests, rich, tiktoken
Required-by:
```

### What Python version are you running this with?

Python 3.11.3

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Version: 6.8.3

Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You:
what is python?


Chatbot:

Traceback (most recent call last):
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1686, in main
    for data in chatbot.ask(prompt=prompt, auto_continue=True):
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 757, in ask
    yield from self.post_messages(
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 710, in post_messages
    yield from self.__send_request(
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 576, in __send_request
    raise ValueError(f"Field missing. Details: {str(line)}")
ValueError: Field missing. Details: {'conversation_id': 'abf665f2-3c8f-4725-8263-5893bb5847ff', 'message_id': 'b8fe1067-2610-4bea-b33b-93b099b3803b', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eEtljxtdnGEn9sCjBEKoPBeuGh7M'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1723, in <module>
    main(configure())
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 1708, in main
    raise error from exc
revChatGPT.typings.CLIError: command line program unknown error
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
```
```


### Additional information

It was fine till yesterday . Today it gave this error.

**Comment by dd4897** [comment]
same problem

**Comment by maaz-shaban** [comment]
Same problem.

**Comment by zigui123340** [comment]
Same problem.

**Comment by zeushera140** [comment]
same, any solution?

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/6.8.4

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/6.8.5

**Comment by dd4897** [comment]
![image](https://github.com/acheong08/ChatGPT/assets/115985522/8143a5bd-4b46-4678-9a29-4ea1c61e4e9b)
The response was successful but, for the last time, this error will be reported

**Comment by zigui123340** [comment]
> ![image](https://user-images.githubusercontent.com/115985522/254773431-8143a5bd-4b46-4678-9a29-4ea1c61e4e9b.png) The response was successful but, for the last time, this error will be reported

same

**Comment by dd4897** [comment]
> > ![image](https://user-images.githubusercontent.com/115985522/254773431-8143a5bd-4b46-4678-9a29-4ea1c61e4e9b.png) The response was successful but, for the last time, this error will be reported
> 
> same

so i change the code 
![img_v2_ef69e66a-e97b-47cd-9aa1-e2ab572dc74g](https://github.com/acheong08/ChatGPT/assets/115985522/178ab3b5-92d3-485d-bd62-d9b1c2b92039)
resovle the problem but the "end_turn":True  will  appear twice

**Comment by acheong08** [comment]
ig just continue when fields missing

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/6.8.6

**Comment by dd4897** [comment]
@acheong08 Thank you for all the hard work.

**Comment by zigui123340** [comment]
> https://github.com/acheong08/ChatGPT/releases/tag/6.8.6
谢谢!

**Comment by ashishbinu** [comment]
damn that was fast
