### ISSUE TITLE
ValueError: Field missing. Details: {'conversation_id': '289a9ec4-cf13-45f5-bc3f-f96046e487c7', 'message_id': 'a5be1cb9-610f-4c53-a019-73abfd2b68ab', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7eJ0uKhi6TSRvHoiBzCxVBTu7GA2v'}}

### ISSUE THREAD

**Issue by maaz-shaban** [acheong08/ChatGPT#1470]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

`ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_7696\1777530192.py in <module>
----> 1 response = generate_response_gpt(p_list, 'product_type')

~\AppData\Local\Temp\ipykernel_7696\2440906140.py in generate_response_gpt(products, attribute)
     10     # return prompt
     11     response = ''
---> 12     for data in chat.ask(prompt, model='gpt-3.5-turbo'):
     13         response = data['message']
     14 

~\anaconda3\lib\site-packages\revChatGPT\V1.py in ask(self, prompt, conversation_id, parent_id, model, plugin_ids, auto_continue, timeout, **kwargs)
    574         ]
    575 
--> 576         yield from self.post_messages(
    577             messages,
    578             conversation_id=conversation_id,

~\anaconda3\lib\site-packages\revChatGPT\V1.py in post_messages(self, messages, conversation_id, parent_id, plugin_ids, model, auto_continue, timeout, **kwargs)
    527             data["plugin_ids"] = plugin_ids
    528 
--> 529         yield from self.__send_request(
    530             data,
    531             timeout=timeout,

~\anaconda3\lib\site-packages\revChatGPT\V1.py in __send_request(self, data, auto_continue, timeout, **kwargs)
    399                 continue
    400             if not self.__check_fields(line):
--> 401                 raise ValueError(f"Field missing. Details: {str(line)}")
    402             if line.get("message").get("author").get("role") != "assistant":
    403                 continue`

### Steps to reproduce the problem

I am trying to simply call the ask function .

### What should have happened?

Generating error.

### Version where the problem happens

I also tried after updating it to the latest version, but it didn't solve the problem

### What Python version are you running this with?

3.9.13

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Nothin
```

### Console logs

```Shell
Nothing
```

**Comment by RiyanParvez** [comment]
I also have this

**Comment by WaleedSalahEldeen** [comment]
I have the same problem

**Comment by themw123** [comment]
same

**Comment by phamxtien** [comment]
I got the same problem and then fixed it by upgrade to version = "6.8.6"
