### ISSUE TITLE
[Feature Request]: personal advice

### ISSUE THREAD

**Issue by isJN** [acheong08/ChatGPT#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

use a new library

### Proposed workflow

ps: this is my personal opinion，If there's anything wrong, I'm sorry i'm just a rookie

Recently, when I reversed some websites, I found a library that is relatively easy to use and can bypass many restrictions.
from curl_cffi import requests
response=requests.get(url,proxiex,headers,impersonate='chrome110')

**Comment by isJN** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### What would your feature do ?
> use a new library
> 
> ### Proposed workflow
> ps: this is my personal opinion，If there's anything wrong, I'm sorry i'm just a rookie
> 
> Recently, when I reversed some websites, I found a library that is relatively easy to use and can bypass many restrictions. from curl_cffi import requests response=requests.get(url,proxiex,headers,impersonate='chrome110')
> 
> ### Additional information
> _No response_

**Comment by isJN** [comment]
> ### 这是否存在现有问题？
> * [x] 我已经搜索了现有问题并检查了最近的构建/提交
> 
> ### 您的功能会做什么？
> 使用新库
> 
> ### 建议的工作流程
> ps：这是我个人的看法，如果有什么不对劲对不起我只是一个菜鸟
> 
> 最近，当我反转一些网站时，我发现了一个相对易于使用并且可以绕过许多限制的库。从curl_cffi导入请求响应=请求.get（URL，proxiex，headers，impersonate='chrome110'）
> 
> ### 其他信息
> _无响应_

I read that the author's requests are all requests

**Comment by acheong08** [comment]
>  response=requests.get(url,proxiex,headers,impersonate='chrome110')

Missing streaming
