### ISSUE TITLE
No module named 'revChatGPT.asyncChatGPT'

### ISSUE THREAD

**Issue by Zero6992** [acheong08/ChatGPT#156]
I have updated revChatGPT to the latest version 0.0.33

But when I tried to import the async version `from revChatGPT.asyncChatGPT import Chatbot`

the error showed up
```
from revChatGPT.asyncChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.asyncChatGPT'
```

**Comment by acheong08** [comment]
Async is still unstable. I will look into that. Need @Harry-Jing's help

**Comment by Zero6992** [comment]
> Async is still unstable. I will look into that. Need @Harry-Jing's help

Btw, the import method in the docs may be incorrect, it should be like 
`from revChatGPT.revChatGPT import Chatbot`
instead of 
`import from revChatGPT.revChatGPT import Chatbot`

**Comment by Harry-Jing** [comment]
maybe the module issue?

**Comment by acheong08** [comment]
Yes

**Comment by acheong08** [comment]
`py_modules=["revChatGPT", "asyncChatGPT"],`

**Comment by acheong08** [comment]
Need to modify docs

**Comment by Harry-Jing** [comment]
is it fixed?
![image](https://user-images.githubusercontent.com/69247286/206446758-d07b9db9-774d-4520-81e6-8f9ceeda5f43.png)

**Comment by acheong08** [comment]
`from asyncChatGPT.asyncChatGPT import Chatbot` doesn't throw any errors for me
