### ISSUE TITLE
Hope it can name itself

### ISSUE THREAD

**Issue by cshimegi** [acheong08/ChatGPT#158]
**Is your feature request related to a problem? Please describe.**
I'm disappointed when I try to tell it to name itself.

**Describe the solution you'd like**
Even if it gives me a random name, I think it's fine.

**Describe alternatives you've considered**
If possible, I hope it can pick a name with some convincing reasons.

**Additional context**
Here is the error related to this.
<img width="1015" alt="Screenshot 2022-12-08 at 23 29 28" src="https://user-images.githubusercontent.com/67813918/206472349-7a6e5522-9839-4baa-be5d-ef54ae4796f1.png">

**Comment by acheong08** [comment]
It is down

**Comment by ausbitbank** [comment]
![image](https://user-images.githubusercontent.com/1692203/206605157-dd4a2250-9b1d-454d-849a-a849c52501a2.png)
It's being difficult but it does seem to be able to remember nicknames

**Comment by acheong08** [comment]
lol
