### ISSUE TITLE
Hope to support arm architecture.

### ISSUE THREAD

**Issue by xie-xuan** [acheong08/ChatGPT#162]
`OSError: /home/pi/.local/lib/python3.7/site-packages/tls_client/dependencies/tls-client-amd64.so: wrong ELF class: ELFCLASS64`
Hello, I try to build an online robot on the raspberry pi, but it shows that this library is for amd architecture. Hope to add support for arm architecture.

**Comment by acheong08** [comment]
There is a pull request on the way https://github.com/FlorianREGAZ/Python-Tls-Client/pull/15

**Comment by xie-xuan** [comment]
Thank you

**Comment by Mila432** [comment]
or you can remove tls client and use requests and it will work

**Comment by acheong08** [comment]
Does it? I was informed by rawandahmad698 that there are some steps that requires TLS client.

**Comment by acheong08** [comment]
I will do some testing

**Comment by Awoodwhale** [comment]
> `OSError: /home/pi/.local/lib/python3.7/site-packages/tls_client/dependencies/tls-client-amd64.so: wrong ELF class: ELFCLASS64` Hello, I try to build an online robot on the raspberry pi, but it shows that this library is for amd architecture. Hope to add support for arm architecture.

我也是arm用户，我手上有一个aarch64架构的设备，tls库的问题我解决了，解决办法如下：
1. 给你的arm机器配置go环境
2. 将[tls-client](https://github.com/bogdanfinn/tls-client)库clone下来
3. cd cffi_dist/
4. 执行`GOOS=linux CGO_ENABLED=1 GOARCH=arm64 go build -buildmode=c-shared -o ./tls-client-aarch64.so`
5. 获得bulid后的so文件
6. 将这个so文件cp到python tls_client库的dependencies文件夹中
7. 最后修改cffi.py的第12行`file_ext = '-x86.so' if "x86" in machine() else ('-aarch64.so' if "aarch" in machine() else '-amd64.so' )`

**Comment by Vector-Cross** [comment]
> > `OSError: /home/pi/.local/lib/python3.7/site-packages/tls_client/dependencies/tls-client-amd64.so: wrong ELF class: ELFCLASS64` Hello, I try to build an online robot on the raspberry pi, but it shows that this library is for amd architecture. Hope to add support for arm architecture.
> 
> 我也是arm用户，我手上有一个aarch64架构的设备，tls库的问题我解决了，解决办法如下：
> 
> 1. 给你的arm机器配置go环境
> 2. 将[tls-client](https://github.com/bogdanfinn/tls-client)库clone下来
> 3. cd cffi_dist/
> 4. 执行`GOOS=linux CGO_ENABLED=1 GOARCH=arm64 go build -buildmode=c-shared -o ./tls-client-aarch64.so`
> 5. 获得bulid后的so文件
> 6. 将这个so文件cp到python tls_client库的dependencies文件夹中
> 7. 最后修改cffi.py的第12行`file_ext = '-x86.so' if "x86" in machine() else ('-aarch64.so' if "aarch" in machine() else '-amd64.so' )`

兄弟，给力啊！
步骤1卡了我许久，最后按以下方式搞定，其中go1.16.4版本改为go1.18.4
https://blog.csdn.net/xiaoyou625/article/details/117195159
