### ISSUE TITLE
AttributeError: 'Chatbot' object has no attribute 'headers'

### ISSUE THREAD

**Issue by GeraBundur** [acheong08/ChatGPT#171]
**Issue**
AttributeError: 'Chatbot' object has no attribute 'headers'

**Code**
I'm running simple generic code and can't understand why I'm facing this error:

```
from revChatGPT.revChatGPT import Chatbot
import json

config = open('config.json')
chatbot = Chatbot(config, conversation_id=None)

response = chatbot.get_chat_response("Hello world", output="text")
print(response) 
```
**Full error:**
Traceback (most recent call last):
  File "...py", line 7, in <module>
    response = chatbot.get_chat_response("Hello world", output="text")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\revChatGPT.py", line 221, in get_chat_response
    return self.get_chat_text(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Programs\Python\Python311\Lib\site-packages\revChatGPT\revChatGPT.py", line 142, in get_chat_text
    s.headers = self.headers
                ^^^^^^^^^^^^
AttributeError: 'Chatbot' object has no attribute 'headers'

**Comment by acheong08** [comment]
The config should be a dictionary. You are passing it as string. Remember to load the config file via `json.loads`

**Comment by acheong08** [comment]
Read https://github.com/acheong08/ChatGPT/wiki/Developer-Docs carefully
