### ISSUE TITLE
Different Exception classes depending  on what went wrong

### ISSUE THREAD

**Issue by inverse** [acheong08/ChatGPT#172]
**Is your feature request related to a problem? Please describe.**

If someone implemented the library having different classes of exceptions would allow them to react better in their implementation. 

**Describe the solution you'd like**

- Providing a a base class for all Exceptions to extend from
- Having one for when credentials are missing
- Another for token expiration
- etc

**Describe alternatives you've considered**

Parsing the existing exception messages which may change.

**Comment by acheong08** [comment]
This is something that will be worked towards. Thank you for the suggestion

**Comment by Harry-Jing** [comment]
some draft I make. Can you give some suggestions?
ChatGPTException
├── InvalidFormat
|   ├── InvalidCredential
|   └── InvalidURL
└── NetworkError
    ├── HTTPError
    |   ├── TimeoutError
    |   └── HTTPStatusError
    ├── TokeneExpire
    └── LoginError

**Comment by acheong08** [comment]
> some draft I make. Can you give some suggestions?
> 
> ```
> ChatGPTException
> ├── InvalidFormat
> |   ├── InvalidCredential
> |   └── InvalidURL
> └── NetworkError
>     ├── HTTPError
>     |   ├── TimeoutError
>     |   └── HTTPStatusError
>     ├── TokeneExpire
>     └── LoginError
> ```

Some of these will have to be in the https://github.com/acheong08/OpenAIAuth repo. Auth error should be its own class outside of ChatGPT Exception probably since it's a different package
