### ISSUE TITLE
[BUG] I can't log in to OpenAI

### ISSUE THREAD

**Issue by LuckyHead11** [acheong08/ChatGPT#173]
Hey! I am trying to log in to openai so I can use ChatGPT in my flask program.
This has never happened before. I am using a class named ChatGPT to initialize ChatGPT

This is the error I'm getting, (With debug mode enabled)
`
Logging in...
Debugger enabled on OpenAIAuth
Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
You have been rate limited
Login failed
Traceback (most recent call last):
  File "j:\Dev\Python\ChatGptFlask\main.py", line 3, in <module>
    chatbot = ChatGpt()
              ^^^^^^^^^
  File "j:\Dev\Python\ChatGptFlask\chatgpt.py", line 11, in __init__
    self.bot = Chatbot(config, conversation_id=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\revChatGPT\revChatGPT.py", line 59, in __init__
    self.refresh_session()
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\revChatGPT\revChatGPT.py", line 307, in refresh_session
    raise exc
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\revChatGPT\revChatGPT.py", line 304, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\revChatGPT\revChatGPT.py", line 342, in login
    raise exc
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\revChatGPT\revChatGPT.py", line 335, in login
    auth.begin()
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 83, in begin
    self.part_two()
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 112, in part_two
    self.part_three(token=csrf_token)
  File "J:\Dev\Python\ChatGptFlask\venv\Lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 146, in part_three
    raise Exception("You have been rate limited.")
Exception: You have been rate limited.
`

`Exception: You have been rate limited.`

Sometimes it even throws and error like this: `State not found.`

**Comment by acheong08** [comment]
You need to retry a few times in a few minutes.

**Comment by acheong08** [comment]
This is due to rate limiting

**Comment by acheong08** [comment]
Check your email/password. Is it correct? If it is, it might be that your IP address has been greylisted. Use session token authentication instead

**Comment by LuckyHead11** [comment]
Ok hold up Im rate limited again :/

**Comment by acheong08** [comment]
Wait a few minutes. Be careful or your IP can get blacklisted

**Comment by LuckyHead11** [comment]
Ok... it works now. How long does an session token last?

**Comment by acheong08** [comment]
If you keep refreshing, one month. If you don't refresh it, it expires in one hour

**Comment by LuckyHead11** [comment]
Would refreshing be for example:
`self.bot.refresh_session()`

**Comment by acheong08** [comment]
yes

**Comment by LuckyHead11** [comment]
Sorry for the questions, but would it be bad practice to refresh the session everytime the user asks a question?

**Comment by acheong08** [comment]
That is what OpenAI's `https://chat.openai.com/chat` does lol. But yes. You don't need to do that.

I currently have a function in place that automatically refreshes the token if it fails. This is only available in `output="text"` mode

**Comment by LuckyHead11** [comment]
Ok thanks.

(And yes I know `chat.openai.com/chat` exists. I'm just taking up my own challenge my self.)

**Comment by acheong08** [comment]
There is no exact time but from my experience it's around 2 or 3 hours. The access token expires in 1 hour. When the access token expires, it triggers a refresh of the session token. As long as it isn't kept idle for over 2-4 hours, I would say you can keep it valid for a long time.

**Comment by yym68686** [comment]
> There is no exact time but from my experience it's around 2 or 3 hours. The access token expires in 1 hour. When the access token expires, it triggers a refresh of the session token. As long as it isn't kept idle for over 2-4 hours, I would say you can keep it valid for a long time.

I have two questions:

1. I set the session token to refresh automatically every time someone asks a question. If no one asks a question for a long time (2-4 hours), suddenly someone asks a question. Because the session token has expired, no matter how the session is refreshed automatically, the session cannot be valid. Is that right?

2. Can I use the `import schedule` module to automatically execute `refresh_session` function to make the session token always be valid? There are other ways to keep session token valid for a month?

**Comment by acheong08** [comment]
> I set the session token to refresh automatically every time someone asks a question. If no one asks a question for a long time (2-4 hours), suddenly someone asks a question. Because the session token has expired, no matter how the session is refreshed automatically, the session cannot be valid. Is that right?

Yes

> Can I use the import schedule module to automatically execute refresh_session function to make the session token always be valid? There are other ways to keep session token valid for a month?

Yes

**Comment by kxgong** [comment]
> Check your email/password. Is it correct? If it is, it might be that your IP address has been greylisted. Use session token authentication instead

Hi, how can I get my session token? Thanks.
