### ISSUE TITLE
Please include my Chatgpt YouTube auto reply to your list

### ISSUE THREAD

**Issue by sheldonchiu** [acheong08/ChatGPT#174]
Hi,

I use Chatgpt to code a bot to reply to YouTube comments using Chatgpt 😵‍💫
https://github.com/sheldonchiu/chatgpt-youtube-autoreply/

Please include this to your list. 🙏
The README is very rough at this moment, will fix it later

**Comment by acheong08** [comment]
This is a very interesting application (although sketchy. YouTube has enough bots as is lol). Added
