### ISSUE TITLE
Response not in correct format.

### ISSUE THREAD

**Issue by 7Cecil** [acheong08/ChatGPT#175]
![image](https://user-images.githubusercontent.com/64791735/206618539-aa93d14d-00c4-4456-a303-ab528774e6f3.png)

I updated the config file with the session token (only the session token) and it still asks for my email and password. Any ideas?

**Comment by acheong08** [comment]
Please follow the proper template. What version is this?

**Comment by 7Cecil** [comment]
Sorry mate. This is the latest version (0.0.33.4) running on windows 10.

**Comment by acheong08** [comment]
Ok. Will debug when I have the time

**Comment by acheong08** [comment]
Ah. Your token might be expired.

**Comment by acheong08** [comment]
Go to https://chat.openai.com/api/auth/session and check out the cookies

**Comment by 7Cecil** [comment]
Can you tell me how to refresh my token? It seems to always be the same.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

**Comment by 7Cecil** [comment]
Great! Finally got it working thanks to the Acess Token Authentication. However, the chatbot is saying the response is not in the correct format. What am I missing here? 

![image](https://user-images.githubusercontent.com/64791735/206620629-4d48a958-e307-4bcd-81dc-50e1866d3284.png)

**Comment by acheong08** [comment]
Try with `--debug` and `--text`

**Comment by 7Cecil** [comment]
Text:

![image](https://user-images.githubusercontent.com/64791735/206621117-b4f6aae1-683f-4b9d-8a6b-cfd5ea97563f.png)

**Comment by 7Cecil** [comment]
Debugging: 

![image](https://user-images.githubusercontent.com/64791735/206621183-7d26ffdc-4a7c-4344-8f46-717285bb5daf.png)

**Comment by acheong08** [comment]
Can you do it with both --debug and --text at once?

**Comment by Cubicpath** [comment]
OpenAI is currently having issues with their Auth0 login page as far as I can tell. I can't even log in on browser right now.

**Comment by 7Cecil** [comment]
![image](https://user-images.githubusercontent.com/64791735/206622024-7b1d46c7-da6e-4817-8b82-6d1ba3cba0f3.png)

Ah, I see. This must be related to Auth0 login issues then.

**Comment by acheong08** [comment]
It's working for me. It might be regional

**Comment by Cubicpath** [comment]
Yeah I'm encountering a range of issues, from login state not being provided (step-3), to everything succeeding except session-tokens (step-8)

> It's working for me. It might be regional

Interesting

**Comment by 7Cecil** [comment]
Weird, experimented a little bit with auth codes and I'm still getting the same error.

**Comment by acheong08** [comment]
The service should be back up (as of 2 seconds ago)

**Comment by Cubicpath** [comment]
Can confirm, working now

**Comment by 7Cecil** [comment]
![image](https://user-images.githubusercontent.com/64791735/206627040-329f314f-2ca8-442a-9eb2-eed1894976fc.png)
 
Damn... Probably my own problem then.

**Comment by Cubicpath** [comment]
@7Cecil You prob need to get a new key/token. It might have expired by now.

**Comment by 7Cecil** [comment]
How do I get a new token? Care to explain? I'm sorry btw, I'm just a beginner.

**Comment by Cubicpath** [comment]
This [wiki page](https://github.com/acheong08/ChatGPT/wiki/Setup) should explain the process.

**Comment by 7Cecil** [comment]
I've seen it, thanks. But my token seems to not refresh at all. I mean, will just logging-in again refresh my token?

**Comment by Cubicpath** [comment]
Hmmm... have you tried the refresh command in https://github.com/acheong08/ChatGPT/wiki/CLI-use?

**Comment by Cubicpath** [comment]
When you sign-out, your session token should get reset, causing any access tokens to be invalidated. You'll have to re-input everything from said session if that's the case.

Unrelated, but are you trying to use this as an API or a command-line tool?

I don't know the specifics, but if you aren't using this as an API, [PyChatGPT](https://github.com/rawandahmad698/PyChatGPT) has a better CLI. 

Or (Shameless plug) you can use my [GUI app](https://github.com/Cubicpath/ChatGPT-GUI) which handles all of this for you if thats something you prefer ;)

**Comment by 7Cecil** [comment]
Is your GUI app moderated/programmable? I mean, acheong's version does not send any input to the owners so we can get some extra answers without the good old "Hey, I can't provide you with that information". Does your version work the same way? Are the conversations with the bot overseen by anyone?

**Comment by Cubicpath** [comment]
The GUI itself isn't programmable (Other than source code editing), but the API Client is completely seperated from the GUI, asynchronous, and (theoretically) extensible. Also no, it doesn't send any moderation calls back to OpenAI.

Pros to using my Client as an API as opposed to an application:
- Asynchronous through the Qt event loop
- Ability to sign-in with email/password
- Multiple Concurrent Conversations
- Session persistence
- Some useful data structures (`Message`, `Conversation`, `User`)

Cons:

- It requires knowledge of PySide and Qt Signals
- It's not light-weight at all (~100MB of requirements)

It's probably not what you need but if you do decide to use it and need help, you can always raise an issue on the github page.
