### ISSUE TITLE
Please include my Chatgpt_PyBot reply to your list

### ISSUE THREAD

**Issue by liuhuanshuo** [acheong08/ChatGPT#176]
Hi,acheong

Based on your great idea, I used Rich to enrich the output (of course someone has already implemented it), and more, to add more guidelines, hopefully to be added to your list

https://github.com/liuhuanshuo/ChatGPT_PyBot

**Comment by acheong08** [comment]
> someone has already implemented it)

People have but I think your's is the only one up to date. Added

**Comment by alberduris** [comment]
It feels like these two projects should be merged. Text enrichment and more guidelines seem more like excellent additions to this project.

**Comment by acheong08** [comment]
True. This could be merged into `__main__.py`
