### ISSUE TITLE
Please include my Chatgpt BizWechatBot to your list

### ISSUE THREAD

**Issue by Gyronee** [acheong08/ChatGPT#178]
Hi acheong, 
    Base on your awesome work, I developed a BizWechat Bot to chat with chatgpt in Wechat
    would you like include this to your list ? thanks
    https://github.com/Gyronee/chatgpt-bizwechat-bot

**Comment by acheong08** [comment]
Thank you. I use WeChat often as well. Is it possible to use this with a normal WeChat account?

*Added

**Comment by Gyronee** [comment]
> 

yes，you can chat with bizwechat bot from a normal wecha account.  but your account need to be added to the bizwechat coporation.  The screenshot of my repository is from conversation which from a normal wechat account
