### ISSUE TITLE
Auto login when token expires

### ISSUE THREAD

**Issue by Thoxvi** [acheong08/ChatGPT#182]
```
{
    "detail": {
        "message": "Your authentication token has expired. Please try signing in again.",
        "type": "invalid_request_error",
        "param": null,
        "code": "token_expired"
    }
}
```

Maybe we can login in every 12 hours?

**Comment by acheong08** [comment]
Can someone give me an example of an expired token? Need it for testing and don't have one at hand

**Comment by acheong08** [comment]
I have updated the code (without publishing). If anyone could test it with an expired token and make a pull request if you find any flaws, it would be appreciated

**Comment by Thoxvi** [comment]
> I have updated the code (without publishing). If anyone could test it with an expired token and make a pull request if you find any flaws, it would be appreciated

Sorry I have logged back in

**Comment by gianlucaalfa** [comment]
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..yPe6WngYMEBhbUz8.kcVG-B8cYlg_0dotI6-kt2eMLFqVk8U8qpjoD8rsvaqZv_8jCrnnswY2Dfr0oFCP9JtS5FfljQakJgxWOg3R7bbYS7kJcxNIa7hScFMKgwJupqJpTPx2KFUiU656VkBsFgPDRiYppxhN2qZJyW4iUY6cby9qLmffHKLnjVDaRBjyEykAQR-5XjIL49ir1T799fk1UvX2xd5G4Gw2dktYZe9GGfHNWcRjy-TnZu1R8uQzT4Qgw5uoMavgA3e6OBIjkJSG9WGUXhq7qAHhrctHNw8S2XdOBHNnwr-VBKC_aaloxlv2C9zQwOX586kp-MJ532o4rPdFIoKtrp8ozR-7SZb3LJuww58nCh-8vdzD9Whcx_OSJ3IicJR0lU1LUb1Lhir733uwOJrXTxmPIxBs2TbPqwSUU_LFp0Q8h2n8ApnSPlkRBQyRfuVRLZSA6YQm1besE96u-vf9MNpkWdctZa5V7UmDi4gMlm0lABe-vIww0eDAfjvYq3W6QzDskP1sHW7FN3OOps79qzHSCrZWpELVGlS-hO5Mvv5Iiu8U1E9PuLWOaOvs985hp_Adx73Iro0xD48Tc76Tv4heYtK3cQ7el8LpjAAFw1yfT7ZdkcXxC_ALc5TwIiorsqN70xzQ2U0ak0qDnHIs44bj3To8C4jWC9EKUkga-p1azQ4B2wbpDwHmeKHfiP5bxKx6-dhr3KRqtkFBwuKIZWr_dW-ysTRd8LStw1Kt8c_6K1v4zRY1BlfO7T7OkJDkazl4atmefNe6Q6Oep8IRGHa9hnRxiCkMQGlXVgL16BdI5xcQuZ9GwWO2-xTtmfXMzCMiWrknaJlMzXD22bWZ1QnOTCtMBT1awFGhYoqkWLc3gUm1uQ2iLDaCN-3jVVXRwT40WPLdm_vQwXGLtsjiPTYqFm26PBcEZM68cgdU6if_LKfsNcnD6jZuzGQlBIIxOfnuud24Q5rr78PpqtaLFPyEYruAMiAQf_YUFH0qXTr4AtKZX9qKwSDoFkq6EDyJnVXj4r8eoyHK23s0QcFK9e1ZYrFHzaHbrJrt-Bf4jh-fv_RgVIIlzyUsRnmDSQHOBtvnIShyRIJqkedq3eZlSh9nOOHq-6ahv__sbAVJeU-rWHsQzlC7TJF1ZHrzPq26D9j32yXPmhUCL7JaDz_PvpYbPQdY77ClrJUbNy6IImMTl8dEG48JgqjuaU9dNrB3H8-Ev1Q9__KeUxE3x7lDRdwgaOKxMwad1Ovtrujg8bUni_-J-UMx3kgE1cg0UbcNS6JS_vids17cJJQQ8DXc5OUySVNreApIBwpr5FiadT_9H_XF2qKUhsR4QQvpMAy9vbXtbSE9YVSXMdD7VEWnTsm6LYIW6fFXo5iZg4yc8Zb5uuMP3UAL9H3hMOvgdUS6YY4KBsGF6KOme4LMAWk5d_YM7q3P_NLdf_-mhoz0NQLkkinFU_m_mlzYTTaSTXka4-yAP4p3CO_BsZYBd71XFjCngZBVRD6wT2pR6knWXPqT2rbEqGlSGBYKWPavX34BksiRKUB0PdmJumGWSEs4J-_oD5oNHz59gktWDjeuYsXzzdrJIRutSDGQo6xESvCMHQn2y6PZnh3E_D-eN7o-h5GarkKFErtxCa5jVgYyvWHin4aXJ2VbScqSGYuk6yVIhCpxbl_zHYX9qLE8q2mvMzdEJzoOs7kCO4wJBfQVri6oXRA9sbDyXk1ku7fGyIRj6CGF_wl107roh1okONu5WkggOsc5Nu3YLD7ROu6mWBEsvUmZ-d1TBAwkjFZDiDLgbKnt7CAevYTm_Pk_EqNAucuXI_P0gOTN76FHLhQXYRLS7d-38-AdBSpefFc3-cOKmB504l_sLAenlm9xmadLcjqxcj2V_oUpxLWT2YsccBsXp9VkLbz47rFLZGXMnYqdDtJ352Ie7RLr3NXJhDTcapFuba8yNE_DleZK_DM42jq_NhkeALZ0A7guR1CSDWgs_wj-HfeznNIttbJEQf6rGurD-gshc7cBVXvnQjd2NZOINT3aprLtmB545bpYuEV3aiK-zUugvrM9bfPSaXyeLFkWkhj98TGygZJ4YKRMoj62XRcdhredsTyfqeDoZP2CbGSXHVVGmAPEV8FD84NwQ0C-t9uotTDfcw6SzL6RXRz-NCOs0ny4xzLyYHqLqxl5-GngOotKotnraHRZWtljmpf4Ui_Dbb3xCMxvyGHxucdNCGuZ0Pe33YQ3rM52Lu5hcgtKmocW3_K4m_FqryRKwICOKH60KSiM8I4Zz7KlfCEI5TrvAN-diZfwOlNucYbBJIFS6rGGcr5CGpMXcLasKtcAqsg2JgDwtf42Ps-xb4T0_hntQ3VgzdgvnpbdhgyqLM-ge7xJy_cI.E5kgV8g6y73J3kn78xPdrQ

This is expired :) thank you for your work

**Comment by acheong08** [comment]
Thanks. I will test it out

**Comment by acheong08** [comment]
It works

**Comment by acheong08** [comment]
Done
