### ISSUE TITLE
[BUG] Incorrect response from OpenAI API

### ISSUE THREAD

**Issue by holymode** [acheong08/ChatGPT#195]
Currently running the async version in a discord bot and sometimes I get the "Incorrect response from OpenAI API" error. Im using the token login, I suspect it's due to the session timeout. As soon as I paste a new token in, its working fine. 

Or is there anything else I'm missing?

**Comment by acheong08** [comment]
Tokens expire. Why not use email/password?

**Comment by acheong08** [comment]
> Or is there anything else I'm missing?

No. Just normal token expiration

**Comment by acheong08** [comment]
Since the token is expiring, you can get a new one by following the instructions https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

Remember to update your revChatGPT as there has been some changes made that fixes a few bugs
