### ISSUE TITLE
[BUG] I keep getting the error that "'CaptchaSolver' is not defined" I have tried all three diffrent ways to credential, any guidance is appreciated

### ISSUE THREAD

**Issue by jmessaglia** [acheong08/ChatGPT#205]
**Describe the bug**
This seems to be an issure with the json, these are the diffrent codes ive put into the config.json (sometimes changing the tokens fixes it for a couple minutes but then it says 

Expecting value: line 1 column 1 (char 0)

Not really where to go from here these were the formats of json code ive used

{
    "session_token": "<put_session_tokens_here>"
}

{
    "email": "<put_email_here>",
    "password": "<put_password_here>"
}

{
	"Authorization":"<put_auth_tokens_here>"
}

I'm pretty new to coding, so anything is helpful

**Environment (Visual Studio Code):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: Windows 11
 - Python version: Python 3
 - ChatGPT Version: `pip3 show revChatGPT`
 - OpenAI Version: `pip3 show OpenAIAuth`

**Additional context**

**Comment by acheong08** [comment]
How are you encountering this issue? Could you provide the full output from `python3 -m revChatGPT --text --debug`?

**Comment by InstanceGG** [comment]
I get the same thing, This is the output 

`ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
Repo: github.com/acheong08/ChatGPT
Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Something went wrong! Please run with --debug to see the error.
name 'CaptchaSolver' is not defined`

**Comment by acheong08** [comment]
I think I found the bug. Fixing in progress

**Comment by acheong08** [comment]
Nevermind. I think I found the bug. What exact python version are you on (just to confirm)

**Comment by acheong08** [comment]
New release should fix this: https://github.com/acheong08/ChatGPT/releases/tag/0.0.34.2

Sorry for the inconvenience

**Comment by RemiPelloux** [comment]
Still have the error : 

%  python3 -m revChatGPT --text --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Something went wrong! Please run with --debug to see the error.
name 'CaptchaSolver' is not defined


Python 3.8.2

**Comment by tszdanger** [comment]
I've tested from Python version 3.6/3.7/3.8.2. Still this bug.

**Comment by acheong08** [comment]
It works for me on Python 3.10.6. I will downgrade and test. Use `pip3 install revChatGPT==0.0.34` while I fix it

**Comment by tszdanger** [comment]
I see. THX for that.

**Comment by RemiPelloux** [comment]
I think it's a virtual env issue with Jetbrain Pycharm , it doesnt work, but in terminal it works

**Comment by acheong08** [comment]
It works for me on 3.6/3.7/3.8.2

The issue might be if you use a vritual env as @RemiPelloux stated

**Comment by acheong08** [comment]
Everything died. Check out new https://github.com/acheong08/ChatGPT/wiki/Setup and update your version.

Cloudflare has killed email/password auth

**Comment by acheong08** [comment]
Captcha no longer works either
