### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'; 'revChatGPT' is not a package

### ISSUE THREAD

**Issue by ladypiapia** [acheong08/ChatGPT#207]
I have installed revChatGPT via `pip3 install revChatGPT`，but when I run  __main__.py ，errors occured , using command `pip list | grep revChatGPT`local  shows that revChatGPT installed successfully. Local environment and server both tried, but nothing found.it may be tiny problems or something like python path ,but took me long time.Hope someone can help me ,thanks so much

**Comment by acheong08** [comment]
What is `main.py`?

**Comment by baymax55** [comment]
how do I fix it, I have the same question

![image](https://user-images.githubusercontent.com/35788491/206978220-00c1f485-e3ef-4a7d-9c4d-9839a4cf6462.png)

**Comment by ZhengJunJ** [comment]
> 

from revChatGPT import Chatbot

**Comment by acheong08** [comment]
It's supposed to be `from revChatGPT.revChatGPT import Chatbot`

**Comment by baymax55** [comment]
> It's supposed to be `from revChatGPT.revChatGPT import Chatbot`

well, I do not know  why it does not work, just using local import is fine 
![image](https://user-images.githubusercontent.com/35788491/207044870-74f32c1f-b0a5-4bbf-95d1-12f09ddfa002.png)

**Comment by acheong08** [comment]
> > It's supposed to be `from revChatGPT.revChatGPT import Chatbot`
> 
> well, I do not know why it does not work, just using local import is fine ![image](https://user-images.githubusercontent.com/35788491/207044870-74f32c1f-b0a5-4bbf-95d1-12f09ddfa002.png)

Did you install it? If so, it might have something to do with the virtual environment of your IDE

**Comment by baymax55** [comment]
> > > It's supposed to be `from revChatGPT.revChatGPT import Chatbot`
> > 
> > 
> > well, I do not know why it does not work, just using local import is fine ![image](https://user-images.githubusercontent.com/35788491/207044870-74f32c1f-b0a5-4bbf-95d1-12f09ddfa002.png)
> 
> Did you install it? If so, it might have something to do with the virtual environment of your IDE

I'm not installed it , and it still does not work :
![image](https://user-images.githubusercontent.com/35788491/207049548-ae97c52d-306c-4b1d-997a-246281d61dff.png)

**Comment by baymax55** [comment]
> It's supposed to be `from revChatGPT.revChatGPT import Chatbot`

I finally found move code to the src directory is fine, thank you 

![image](https://user-images.githubusercontent.com/35788491/207051992-33ae8df9-bd97-4aa6-a472-a253c8545701.png)
