### ISSUE TITLE
set conversation_id error

### ISSUE THREAD

**Issue by chrisyy2003** [acheong08/ChatGPT#21]
here is my code, The first two get_chat_response is no problem, but I reset the conversation_id then call get_chat_response it will abort that `Too many requests, please slow down`

```
chatbot = Chatbot(config, conversation_id=None)
chatbot.refresh_session() 
# 1
resp = chatbot.get_chat_response('what is python')
print(resp)
# 2
resp = chatbot.get_chat_response('continue') 
print(resp)

# 3
id = resp['conversation_id']
chatbot = Chatbot(config, conversation_id=id)
resp = chatbot.get_chat_response('continue') 
print(resp)
```

![image](https://user-images.githubusercontent.com/63803385/205552186-d141c5ec-8949-4dd6-95b6-1480ccfb59f4.png)

**Comment by acheong08** [comment]
Same issue here: https://github.com/acheong08/ChatGPT/issues/7
 
You probably need to set the correct parent_id as well. Working on making it more clear. There are some quirks with the API I'm still unsure of

**Comment by chrisyy2003** [comment]
I'm using the instance of the chatbot cache temporarily，use a dict (user_id ==> chatbot instance)

And I found that I need to use a scheduler to call refresh every once in a while to refresh my token. Is it necessary to add some support that chatbot will refresh automatically?

**Comment by acheong08** [comment]
> Is it necessary to add some support that chatbot will refresh automatically?

This should not be part of the module logic. You can implement a scheduler yourself via threading or by counting the number of inputs and do so at a certain interval
