### ISSUE TITLE
[BUG] ValueError: Captcha detected

### ISSUE THREAD

**Issue by zeiyu314** [acheong08/ChatGPT#213]
Windows 10 using python3.10.4

And here's my code:
![image](https://user-images.githubusercontent.com/44489550/206859284-456f5fcf-b57b-4bc2-a830-e6b3c7b5dc26.png)

**Comment by acheong08** [comment]
You need to write a custom captcha handler: https://github.com/acheong08/ChatGPT/blob/7fcbfab3ec9439147d232332527dbe184f9debbe/src/revChatGPT/__main__.py#L10-L34

and pass it through via https://github.com/acheong08/ChatGPT/blob/7fcbfab3ec9439147d232332527dbe184f9debbe/src/revChatGPT/__main__.py#L95-L96

Documentation is currently lacking.
