### ISSUE TITLE
[BUG]这个数学题chatGPT是不是做错了

### ISSUE THREAD

**Issue by hkre** [acheong08/ChatGPT#215]
设f(x)=x-2,g(x) = 2x+1，则f(g(x))=

![image](https://user-images.githubusercontent.com/31304773/206861179-a874b96c-0b30-4cf8-8315-59ebd59def97.png)

**Comment by acheong08** [comment]
Not our problem

**Comment by Zero6992** [comment]
Your issue is related to Open AI's chatGPT, it is not exactly a bug too

But it also does not have anything to do with this repo

**Comment by chinosk114514** [comment]
1. chatGPT只是个语言模型，并不保证题能做对
2. 你来错仓库了
