### ISSUE TITLE
A parent class for 'revChatGPT' and 'asyncChatGPT'

### ISSUE THREAD

**Issue by snowmeow2** [acheong08/ChatGPT#218]
The two classes `revChatGPT.revChatGPT` and `asyncChatGPT.asyncChatGPT` share many methods and attributes in general.
The major difference between them is the async feature for getting the chat response.

In order to improve the maintainability and avoid the duplication in the code, it would be a good idea to create a parent class from which we can inherit all the common methods.

```python
class ChatGPT:
    def __init__(self, args):
        ...
    def common_method(self):
        ...
```
```python
class asyncChatGPT(ChatGPT):
    async def get_chat_response(self, args):
        ...

class revChatGPT(ChatGPT):
    def get_chat_response(self, args):
        ...
```

It would be a significant refactoring though.

**Comment by acheong08** [comment]
@snowmeow2 asyncChatGPT can just inherit the Chatbot class and override a few methods. I have changed it. Do you mind writing some documentation?
