### ISSUE TITLE
Async class changes

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#226]
https://github.com/acheong08/ChatGPT/blob/2da909091a734fc310290c0bcec483d8bfce6c00/src/revChatGPT/revChatGPT.py#L380-L523

@Harry-Jing Do you mind looking over this to see if any changes are required?

**Comment by Harry-Jing** [comment]
looks no problem

**Comment by acheong08** [comment]
I will be removing the independent asyncChatGPT package then. A lot of docs need to be updated.
