### ISSUE TITLE
How is the chatgpt agent website implemented？（just really wanna figure out）

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#229]

**Comment by acheong08** [comment]
Could you provide more details?

**Comment by zjrwtx** [comment]
I have seen a lot of people build almost the same as chatgpt website without agent software and registration login directly use, curious how this is achieved

**Comment by acheong08** [comment]
> I have seen a lot of people build almost the same as chatgpt website without agent software and registration login directly use, curious how this is achieved

They probably have a list of credentials stored beforehand which is cycled through upon each query added the the queue.

**Comment by firstciti** [comment]
> I have seen a lot of people build almost the same as chatgpt website without agent software and registration login directly use, curious how this is achieved

you mean you can use login/password on their site? or are you already logged in? can you provide example?

**Comment by acheong08** [comment]
> you mean you can use login/password on their site? or are you already logged in? can you provide example?

They are logged in on the back end (requires multiple phone numbers). As for the example, are you asking for a code example on how to do it?

**Comment by acheong08** [comment]
Please do note that this is not the official ChatGPT repository. You might be looking for https://github.com/OpenAI

**Comment by zjrwtx** [comment]
It is highly recommended that you write and build a website that users can use without logging in and proxy

**Comment by acheong08** [comment]
> It is highly recommended that you write and build a website that users can use without logging in and proxy

I want do that. However, I need a maintainer to keep this repository up and running while I work on that project. I already got a deal with https://github.com/PipedreamHQ to run an API on their service for free.

**Comment by zjrwtx** [comment]
> > It is highly recommended that you write and build a website that users can use without logging in and proxies
> 
> I want to do this. However, while I was working on the project, I needed a maintainer to keep this repository up and running. I've made an agreement with https://github.com/PipedreamHQ to run the API on their service for free.

get it,actually,I haven't seen anyone open source tutorials or code on how to do chatgpt without proxy and login,hopefully you could make it

**Comment by zjrwtx** [comment]
> > I have seen a lot of people build almost the same as chatgpt website without agent software and registration login directly use, curious how this is achieved
> 
> They probably have a list of credentials stored beforehand which is cycled through upon each query added the the queue.
here  are some examples
https://www.4spaces.org/2303.html

**Comment by acheong08** [comment]
Those are limited in speed and bandwidth. Since they exist, I won't be making a duplicate

**Comment by acheong08** [comment]
However, it does seem that they can be used as a base url. I will check it out
