### ISSUE TITLE
Chatbot inherits from AsyncChatbot

### ISSUE THREAD

**Issue by Harry-Jing** [acheong08/ChatGPT#238]
The method in Chatbot can directly return the value after AsyncChatbot runs `asyncio.run`.
This can also reduce code complexity.

**Comment by acheong08** [comment]
Could you show an example?

**Comment by Harry-Jing** [comment]
```python
import asyncio

class AsyncChatBot():
    def __init__(self):
        ...
    
    async def get_chat_response(self, prompt: str, output="text"):
        ...

class ChatBot(AsyncChatBot):
    def get_chat_response(self, prompt: str, output="text"):
        coroutine_object = super().get_chat_response(prompt, output=output)
        return asyncio.run(coroutine_object)
```

**Comment by Harry-Jing** [comment]
I'll try to do it

**Comment by acheong08** [comment]
Edit: Never mind. You used return rather than yield for `__async_generator_to_list`. Will update that

**Comment by Harry-Jing** [comment]
> Edit: Never mind. You used return rather than yield for `__async_generator_to_list`. Will update that

I have not find solution of async_generator to generator whithout using other packge
this is temporary solution

**Comment by acheong08** [comment]
I just brought it back to the non-async class.
