### ISSUE TITLE
[FEATURE] Consider overriding the login method in the async version

### ISSUE THREAD

**Issue by alexandreteles** [acheong08/ChatGPT#239]
**Is your feature request related to a problem? Please describe.**

Currently the `AsyncChatBot` class uses the synchronous method for login inherited from `ChatBot`. This isn't a problem in itself as most of the login steps are done synchronously, but in its current form there is no way to execute the captcha solving step asynchronously.

**Describe the solution you'd like**

Override the `login` method so the `captcha_solver` method can be awaited on. This should benefit users cycling through multiple accounts as the captcha solving operation (which is time consuming) doesn't block execution.

**Comment by Harry-Jing** [comment]
I will try to do that

**Comment by Harry-Jing** [comment]
It will change a lot to support async `login()`

**Comment by acheong08** [comment]
I would rather not have too much changed. I suppose a sync login is fine. It's difficult to do captcha async

**Comment by Harry-Jing** [comment]
I think is harld to let `class OpenAIAuth` async

**Comment by Harry-Jing** [comment]
may you can try `Threading` or `Multiprocessing`

**Comment by alexandreteles** [comment]
> may you can try `Threading` or `Multiprocessing`

It's fine. Developers can override the method themselves to support async captcha (that's what I did), it's just not ideal because with that we have to keep track of changes in the library to keep the methods in sync. But running the captcha asynchronously isn't hard at all, as long as there is a loop already running you can do something like:

```python
import concurrent.futures

async def solve_captcha(raw_svg):
    loop = asyncio.get_running_loop()
    with concurrent.future.ThreadPoolExecutor() as pool:
        result = await loop.run_in_executor(pool, lambda: captcha_solving_library.solve(raw_svg))
        return result
```

Thank you!
