### ISSUE TITLE
__get_chat_text [BUG]

### ISSUE THREAD

**Issue by zwa73** [acheong08/ChatGPT#241]
**Describe the bug**
In the latest version, there seems to be a problem getting replies (pip3 install revChatGPT --upgrade)
This error is not present in 0.0.34.2

Error handling request
Traceback (most recent call last):
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 196, in handle_request
    resp = await chat_server.send_thread_message(tid,msg)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 85, in send_thread_message
    resp =  await self.send_message(text,"text",tdata["conversation_id"],tdata["parent_id"])
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 73, in send_message
    return await self.main_chat._AsyncChatBot__get_chat_text(data)
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 452, in __get_chat_text
    if 'detail' in response.json().keys():
  File "E:\Python 3.9\lib\site-packages\httpx\_models.py", line 752, in json
    return jsonlib.loads(self.text, **kwargs)
  File "E:\Python 3.9\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\Python 3.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Python 3.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by acheong08** [comment]
Seems to be an issue with indentation. I am checking it out

**Comment by acheong08** [comment]
Sorry. Fixed https://github.com/acheong08/ChatGPT/releases/tag/0.0.37.2

**Comment by zwa73** [comment]
> Sorry. Fixed https://github.com/acheong08/ChatGPT/releases/tag/0.0.37.2

你好？
等待回复
Error handling request
Traceback (most recent call last):
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 197, in handle_request
    resp = await chat_server.send_thread_message(tid,msg)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 85, in send_thread_message
    resp =  await self.main_chat.get_chat_response(text,"text",tdata["conversation_id"],tdata["parent_id"])
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 547, in get_chat_response
    return await self.__get_chat_text(data)
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 501, in __get_chat_text
    if 'detail' in response.json().keys():
  File "E:\Python 3.9\lib\site-packages\httpx\_models.py", line 752, in json
    return jsonlib.loads(self.text, **kwargs)
  File "E:\Python 3.9\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\Python 3.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Python 3.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

It doesn't seem to have solved the problem
I have updated to version 0.0.37.2

**Comment by acheong08** [comment]
Hmm. I have to look into it more. Can you show some demo code I can test the async with?

**Comment by acheong08** [comment]
Oh I see the other issue. I will fix it

**Comment by zwa73** [comment]
`async def handle_request(request):
	json_data = await request.json()
	msg = json_data["message"]
	msg = re.sub('\r\n','\n',msg)
	tid = json_data["thread_id"]
	# AI回复
	resp = await chat_server.send_thread_message(tid,msg)
	if(resp):
		print(resp)
		# 将响应内容转为 json 字符串
		response_body_str = json.dumps(resp)
		return web.Response(text=response_body_str)
	return web.Response(text=json.dumps({"status": "错误"}))

app = web.Application()
app.add_routes([web.post('/', handle_request)])

web.run_app(app, host="127.0.0.1", port=25567)`

My py server

**Comment by acheong08** [comment]
Yeah. I found the bug. Sorry. Republishing https://github.com/acheong08/ChatGPT/releases/tag/0.0.37.3

If you do `pip3 uninstall revChatGPT && pip3 install revChatGPT==0.0.37.3` it should work (once it publishes properly)

**Comment by acheong08** [comment]
@zwa73 It has been published. Mind testing it?

**Comment by zwa73** [comment]
线程:test 接收消息:
你好吗？
等待回复
Error handling request
Traceback (most recent call last):
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\Python 3.9\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 196, in handle_request
    resp = await chat_server.send_thread_message(tid,msg)
  File "F:\Sosarciel\Sosarciel-GPT-HttpRobot\PyChatGPT-http\main.py", line 84, in send_thread_message
    resp =  await self.main_chat.get_chat_response(text,"text",tdata["conversation_id"],tdata["parent_id"])
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 555, in get_chat_response
    return await self.__get_chat_text(data)
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 518, in __get_chat_text
    if 'detail' in response.json():
  File "E:\Python 3.9\lib\site-packages\httpx\_models.py", line 752, in json
    return jsonlib.loads(self.text, **kwargs)
  File "E:\Python 3.9\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "E:\Python 3.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Python 3.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by acheong08** [comment]
It seems an exception is occurring even before that. I need some test code for async. Let me check

**Comment by zwa73** [comment]
'''
import asyncio

async def chat():
    print("Hello, world!")

async def main():
    await chat()

asyncio.run(main())
'''
like this?

**Comment by zwa73** [comment]
```
import asyncio

async def chat():
    print("Hello, world!")

async def main():
    await chat()

asyncio.run(main())
```
Like this? If you just want to run

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/0.0.38 by @Harry-Jing should fix this

**Comment by ltbd78** [comment]
Still receiving this error, strangely:
```python
JSONDecodeError                           Traceback (most recent call last)
Cell In [5], line 1
----> 1 response = chatbot.get_chat_response("Hello world")
      2 print(response)

File ~\.conda\envs\bot\lib\site-packages\revChatGPT\revChatGPT.py:528, in Chatbot.get_chat_response(self, prompt, output, conversation_id, parent_id)
    525 coroutine_object = super().get_chat_response(
    526     prompt, output, conversation_id, parent_id)
    527 try:
--> 528     return asyncio.run(coroutine_object)
    529 except RuntimeError:
    530     import nest_asyncio

File ~\.conda\envs\bot\lib\site-packages\nest_asyncio.py:35, in _patch_asyncio.<locals>.run(main, debug)
     33 task = asyncio.ensure_future(main)
     34 try:
---> 35     return loop.run_until_complete(task)
     36 finally:
     37     if not task.done():

File ~\.conda\envs\bot\lib\site-packages\nest_asyncio.py:89, in _patch_loop.<locals>.run_until_complete(self, future)
     86 if not f.done():
     87     raise RuntimeError(
     88         'Event loop stopped before Future completed.')
---> 89 return f.result()

File ~\.conda\envs\bot\lib\asyncio\futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File ~\.conda\envs\bot\lib\asyncio\tasks.py:256, in Task.__step(***failed resolving arguments***)
    252 try:
    253     if exc is None:
    254         # We use the `send` method directly, because coroutines
    255         # don't have `__iter__` and `__next__` methods.
--> 256         result = coro.send(None)
    257     else:
    258         result = coro.throw(exc)

File ~\.conda\envs\bot\lib\site-packages\revChatGPT\revChatGPT.py:249, in AsyncChatbot.get_chat_response(self, prompt, output, conversation_id, parent_id)
    247     self.parent_id_prev_queue.pop(0)
    248 if output == "text":
--> 249     return await self.__get_chat_text(data)
    250 elif output == "stream":
    251     return self.__get_chat_stream(data)

File ~\.conda\envs\bot\lib\site-packages\revChatGPT\revChatGPT.py:206, in AsyncChatbot.__get_chat_text(self, data)
    204         raise Exception("Not a JSON response") from exc2
    205     raise Exception("Incorrect response from OpenAI API") from exc
--> 206 response = json.loads(response)
    207 self.parent_id = response["message"]["id"]
    208 self.conversation_id = response["conversation_id"]

File ~\.conda\envs\bot\lib\json\__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File ~\.conda\envs\bot\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~\.conda\envs\bot\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

**Comment by acheong08** [comment]
I will do some checks

**Comment by Harry-Jing** [comment]
related to #261
