### ISSUE TITLE
[Community Vote]: Moderation or no moderation?

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#245]
According to @rawandahmad698 in https://github.com/rawandahmad698/PyChatGPT/discussions/103, enabling moderation might increase the quality of your responses. I have tested this theory and these are the results out of 20 tests:
6/20 of the responses were long/good with moderation on
5/20 of the responses were long/good with moderation off

Although this could be attributed to chance, there is a slight chance moderation increases response quality. However, this means you will get a content warning if you violate OpenAI's policies. 

A vote is thus necessary: Should I add the moderation feature?

Please vote here: https://github.com/acheong08/ChatGPT/discussions/244

**Comment by BLuFeNiX** [comment]
Can you just make it optional?

**Comment by acheong08** [comment]
> Can you just make it optional?

Yes. This question was more of what should be the default. However, this has been placed lower on the priorities list due to the current Cloudflare debacle

**Comment by Innovation1201** [comment]
I agree on making it optional.

**Comment by acheong08** [comment]
A lot of work going on currently due to the cloudflare mess. I will make this an option once that is stable
