### ISSUE TITLE
[BUG] Raise IndexError when OpenAI didn't respond correctly.

### ISSUE THREAD

**Issue by Zjh-819** [acheong08/ChatGPT#246]
**Describe the bug**
Input: Q: Yes or no: Did Solomon make up bigger percentage of Islamic prophets than Kings of Judah?
The response from OpenAI looks like:
```
{"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."}
```
```
Traceback (most recent call last):
  File "D:\anaconda3\envs\alg\lib\site-packages\revChatGPT\revChatGPT.py", line 187, in __get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\alg\lib\site-packages\revChatGPT\revChatGPT.py", line 195, in __get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ALL_FILE\PROJ\chatgpt_test\revChatPkg_Ver.py", line 55, in main
    response = chat.get_chat_response(inputs)
  File "D:\anaconda3\envs\alg\lib\site-packages\revChatGPT\revChatGPT.py", line 517, in get_chat_response
    return asyncio.run(coroutine_object)
  File "D:\anaconda3\envs\alg\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\anaconda3\envs\alg\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\anaconda3\envs\alg\lib\site-packages\revChatGPT\revChatGPT.py", line 240, in get_chat_response
    return await self.__get_chat_text(data)
  File "D:\anaconda3\envs\alg\lib\site-packages\revChatGPT\revChatGPT.py", line 199, in __get_chat_text
    raise Exception("Not a JSON response") from exc2
Exception: Not a JSON response
```

**To Reproduce**
There is no clear clue to Reproduce it. Seems occurs randomly depending on the network status.

**Expected behavior**
Should handle this exception.

**Environment *
Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: Windows11
 - Python version: 3.10.4
 - ChatGPT Version: 0.0.38.1

**Comment by acheong08** [comment]
> Should handle this exception.

Do you want this to be handled by the library or in `__main__.py`?

**Comment by Zjh-819** [comment]
> > Should handle this exception.
> 
> Do you want this to be handled by the library or in `__main__.py`?

By the library, maybe I think.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/pull/43 It was proposed to let users handle the errors and choose how to deal with them due to the dependencies: https://github.com/acheong08/ChatGPT/network/dependents. This may cause some conflicts.

I will allow main to continue on error but probably not change the way the library does it

**Comment by acheong08** [comment]
> File "D:\ALL_FILE\PROJ\chatgpt_test\revChatPkg_Ver.py",

It seems you are using your own code. I suggest you write `try` and `except` handlers in your code. I cannot change this as many of the dependencies use the errors to return a value.

**Comment by Zjh-819** [comment]
> > File "D:\ALL_FILE\PROJ\chatgpt_test\revChatPkg_Ver.py",
> 
> It seems you are using your own code. I suggest you write `try` and `except` handlers in your code. I cannot change this as many of the dependencies use the errors to return a value.

OK, Thank you.

**Comment by Immortality-IMT** [comment]
Maybe you should living in Disneyland and get back to reality. These are fabled characters of a fictional cult. Go see a psychiatrist.

**Comment by acheong08** [comment]
> Maybe you should living in Disneyland and get back to reality. These are fabled characters of a fictional cult. Go see a psychiatrist.

???

**Comment by Immortality-IMT** [comment]
You are an idiot as you are asking AI if Tigre was the real Lion King. Get help. AI doesn't want  your mentally ill questions, that is why it returned an error.
