### ISSUE TITLE
[BUG] svg2rlg Failed to load input file

### ISSUE THREAD

**Issue by jralduaveuthey** [acheong08/ChatGPT#247]
when doing` $ python3 -m revChatGPT --debug` I get:
```
...
Captcha extracted
Captcha saved to captcha.png
Failed to load input file! (Error reading file '<svg xmlns...
```

I am running it on a EC2 instance. The error comes from png = svg2rlg(svg) in the __main__.py

**Comment by acheong08** [comment]
Try https://github.com/acheong08/ChatGPT/releases/tag/0.0.38.2

I can't get a captcha so difficult to test

**Comment by acheong08** [comment]
https://github.com/Kozea/CairoSVG/issues/354

**Comment by acheong08** [comment]
I will add them as a dependency.

**Comment by acheong08** [comment]
Can you try out https://github.com/acheong08/ChatGPT/commit/05d92e3a02493bca290aab1ee94326c42c6dd7c7

(Need to clone and `pip3 install .`) I will publish if it works

**Comment by jralduaveuthey** [comment]
unfortunately still not working and I do not get any error, only this output:
```
...
Saved captcha.png
Login failed
Something went wrong! Please run with --debug to see the error.
a bytes-like object is required, not 'str'
```

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/0.0.38.4
