### ISSUE TITLE
[BUG] asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by delbarital** [acheong08/ChatGPT#248]
I keep getting this error when trying to work with the **output="text"** option. 
Streaming for the standard usage works fine. 

![image](https://user-images.githubusercontent.com/4951888/206909060-25a8e766-40c2-4cc0-80fd-e6b8675c0d29.png)

I'm using Google Colab

**Comment by acheong08** [comment]
Seems to be an issue with Google Colab running everything from within an async block. Works locally

**Comment by acheong08** [comment]
It is generally not recommended to have multiple layers of async

**Comment by alexandreteles** [comment]
You can try using [nest-asyncio](https://pypi.org/project/nest-asyncio/) like this:

```python
!pip install nest-asyncio
import nest_asyncio
nest_asyncio.apply()
```

It *generally* works but sometimes you have to manually patch an event loop.

**Comment by talwrii** [comment]
This question might be related: https://stackoverflow.com/questions/73084593/running-playwright-on-google-colab-gives-error-asyncio-run-cannot-be-called

**Comment by Harry-Jing** [comment]
I can happen in  jupyter notebook
