### ISSUE TITLE
[BUG] Can't get access token

### ISSUE THREAD

**Issue by maraxin** [acheong08/ChatGPT#251]
**Describe the bug**
I enter right email and password yet I still have an error

**To Reproduce**
1. enter email and password
2. try to start chatgpt

**Expected behavior**
Get access token

**Output**
![изображение](https://user-images.githubusercontent.com/53759232/206915037-3099cfed-c466-4b86-8fe9-f162e3833bdb.png)

**Environment (please complete the following information):**
Python 3.9.0

**Comment by acheong08** [comment]
ChatGPT auth seems to be down

**Comment by maraxin** [comment]
it have been shutdown for a long time then

**Comment by acheong08** [comment]
I'm trying to debug this right now. It's also failing on the tests

**Comment by acheong08** [comment]
Can you show the full error message in text form?

**Comment by acheong08** [comment]
> ![изображение](https://user-images.githubusercontent.com/53759232/206915227-bceeb8d6-7da9-4b73-a4ae-4fb20f936170.png) I also have this one, idk if it helps

It seems your IP address is preventing you from accessing their API. It might be blocked in your country or your country is blocked by openAI. Reference: https://github.com/acheong08/ChatGPT/issues/228

Using a VPN might help sometimes but if not, you can use a session token. The guide for that is here: https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

**Comment by maraxin** [comment]
Beginning part six
Beginning part seven
Request went through
Response code is 302
New state found
Beginning part eight
Error in part eight
Response: <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" type="image/svg+xml" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/favicon.svg"/><link rel="icon" type="image/png" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/favicon.png"/><link rel="mask-icon" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/mask-icon.svg" color="#000000"/><link rel="preconnect" href="https://cdn.openai.com"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap" rel="stylesheet"><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="An API for accessing new AI models developed by OpenAI"/><meta property="og:title" content="OpenAI API"/><meta property="og:image" content="https://beta.openai.com/curl.png"/><meta property="og:description" content="An API for accessing new AI models developed by OpenAI"/><meta property="og:url" content="https://beta.openai.com"/><link rel="manifest" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/manifest.json"/><title>OpenAI API</title><script nonce="31c4f93a95d5a25a4413e74cf90e9728" defer="defer" src="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/static/js/main.72b0aa02.js"></script><link href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/static/css/main.93ac87da.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
Status code: 200
Error in part seven
Exception: Auth0 did not issue an access token
Login failed
Something went wrong! Please run with --debug to see the error.
State not found

**Comment by maraxin** [comment]
Response: <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" type="image/svg+xml" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/favicon.svg"/><link rel="icon" type="image/png" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/favicon.png"/><link rel="mask-icon" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/mask-icon.svg" color="#000000"/><link rel="preconnect" href="https://cdn.openai.com"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap" rel="stylesheet"><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="An API for accessing new AI models developed by OpenAI"/><meta property="og:title" content="OpenAI API"/><meta property="og:image" content="https://beta.openai.com/curl.png"/><meta property="og:description" content="An API for accessing new AI models developed by OpenAI"/><meta property="og:url" content="https://beta.openai.com"/><link rel="manifest" href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/manifest.json"/><title>OpenAI API</title><script nonce="31c4f93a95d5a25a4413e74cf90e9728" defer="defer" src="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/static/js/main.72b0aa02.js"></script><link href="https://openaiapi-site.azureedge.net/public-assets/d/46c7d25c69/static/css/main.93ac87da.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
Status code: 200

**Comment by maraxin** [comment]
> The guide for that is here: https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

If only I could get the session token...

**Comment by acheong08** [comment]
> > The guide for that is here: [acheong08/ChatGPT/wiki/Setup#session-token-authentication](https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication)
> 
> If only I could get the session token...

Is something wrong with the website for you?

**Comment by acheong08** [comment]
If you need it, https://gpt.chatapi.art/ is a proxy for https://chat.openai.com/ which doesn't require authentication

**Comment by maraxin** [comment]
cool, I can't really make an account because it requires phone number

**Comment by acheong08** [comment]
> cool, I can't really make an account because it requires phone number

This repo doesn't work without an account either. The above link works without it though so you're good

**Comment by maraxin** [comment]
Thanks then

**Comment by mancunian1792** [comment]
Why not just use the proxy URL instead, for the repo ? Most issues happen due to authentication. Is there something i am missing @acheong08  ?

**Comment by acheong08** [comment]
> Why not just use the proxy URL instead, for the repo ? Most issues happen due to authentication. Is there something i am missing @acheong08 ?

The user doesn't have a phone number
