### ISSUE TITLE
[BUG] Not a JSON response

### ISSUE THREAD

**Issue by chrisyy2003** [acheong08/ChatGPT#252]
**Describe the bug**

sometime it will return `Not a JSON response` error, and i can't repeat this error because happens very randomly，do you ever had this problem before

**Comment by acheong08** [comment]
Yes. It is an issue with OpenAI's api being overloaded.

**Comment by matheusfillipe** [comment]
@acheong08 but that gets fixed when i manually change the session token. Here is the stack trace:

```
  File "/home/mattf/projects/test/chatgpt.py", line 29, in query
    return self.client.get_chat_response(message)['message']
  File "/home/mattf/projects/test/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 233, in get_chat_response
    return self.__get_chat_text(data)
  File "/home/mattf/projects/test/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 192, in __get_chat_text
    raise Exception("Not a JSON response") from exc2
Exception: Not a JSON response
```

Isn't it a matter of just refreshing the session on that case as well?

**Comment by zwa73** [comment]
It seems to be a problem, after I got this error, I created a new instance and it received it normally
Although it breaks again shortly after, I'm not sure if I should refresh_session or login, both functions are always reporting errors

**Comment by zwa73** [comment]
Creating new instances does solve this problem reliably
However, the error occurs again after 2 messages
Tried refresh and login to no avail
Resetting the conversation_id doesn't work either
Does anyone know what else gets refreshed in a new instance?

**Comment by zwa73** [comment]
Well, now that new instances can't be created either, this is a really hard problem to verify

     self.main_chat = self.main_chat = Chatbot(config, conversation_id=None)
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 89, in __init__
    self.refresh_session()
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 329, in refresh_session
    raise exc
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 326, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 362, in login
    raise exc
  File "E:\Python 3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 355, in login
    auth.begin()
  File "E:\Python 3.9\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 95, in begin
    raise Exception("API error")
Exception: API error

**Comment by KaiserBloo** [comment]
It seems like OpenAI have enabled Cloudflare's attack mode:
```
Debugger enabled on OpenAIAuth
Beginning auth process
Error in part one
Response: <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
```

**Comment by acheong08** [comment]
Cloudflare is much harder to bypass. Will take some time as I work on it

**Comment by matheusfillipe** [comment]
@acheong08 maybe this could help you https://github.com/lwthiker/curl-impersonate

**Comment by acheong08** [comment]
> @acheong08 maybe this could help you [lwthiker/curl-impersonate](https://github.com/lwthiker/curl-impersonate)

Cloudflare now shows up on normal clients as well. It won't do much
