### ISSUE TITLE
Integrated OpenAI's Whisper with chatgpt

### ISSUE THREAD

**Issue by rajuptvs** [acheong08/ChatGPT#255]
Hi, First of all thank you for such amazing work on this library. 

Wanted to share my small project where in I have integrated OpenAI whisper to detect speech-to-text and use that transcription as a text to chatgpt

Please find my repo here:
https://github.com/rajuptvs/Whisper-GPT

Screenshots of Demo: 
![image](https://user-images.githubusercontent.com/48201939/206924981-6948308f-ec5f-4e94-8c18-2134aee82e07.png)

Hoping if you like my project, you add it to the list on your readme. 

Thanks again for all the hard work.

**Comment by acheong08** [comment]
added
