### ISSUE TITLE
[BUG] Wrong response code

### ISSUE THREAD

**Issue by holymode** [acheong08/ChatGPT#258]
Is the token method currently still working? It was working fine earlier, but all of a sudden I get "Wrong response code". Even after updating the token in the config. 
It seems the __Secure-next-auth.session-token cookie changes every few mins now without doing anything. 
And yes, I'm on the newest version. 

Stack trace: 
```
File \venv\lib\site-packages\revChatGPT\revChatGPT.py", line 95, in __init__
    self.refresh_session()
  File \venv\lib\site-packages\revChatGPT\revChatGPT.py", line 296, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code

Process finished with exit code 1
```

**Comment by KaiserBloo** [comment]
[It seems like OpenAI have enabled Cloudflare's attack mode](https://github.com/acheong08/ChatGPT/issues/252#issuecomment-1345670969)

**Comment by acheong08** [comment]
Closing in favor of https://github.com/acheong08/ChatGPT/issues/261
