### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#264]
![image](https://user-images.githubusercontent.com/86822589/206950009-af377a6d-1c9f-42be-822a-d47435eb7f74.png)

**Comment by JohnnyIrvin** [comment]
Share code.

**Comment by zjrwtx** [comment]
> Share code.

just after typing my word,and then saw those feedback

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/206952532-57122b57-4f1d-4a68-abec-5cd6dd235d7d.png)

**Comment by YEDEDD** [comment]
> ![图片](https://user-images.githubusercontent.com/86822589/206952532-57122b57-4f1d-4a68-abec-5cd6dd235d7d.png)

你好，这个网页上chatgpt的网页还是这个项目可以部署这个网页，添加自己域名

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/261
