### ISSUE TITLE
Response not in correct format! Error when handling response, got valuesYPE html>

### ISSUE THREAD

**Issue by tongbao96** [acheong08/ChatGPT#265]
**Describe the bug**
i use the  session_token to access chatGPT, and when i input a question after "YOU:"，i got this error

**Output**
In the correct directory, run `python3 -m revChatGPT --debug`

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: `python -V`
 - ChatGPT Version: `pip3 show revChatGPT`
 - OpenAI Version: `pip3 show OpenAIAuth`

**Additional context**

**Comment by tongbao96** [comment]
1

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/261
