### ISSUE TITLE
when i input a question after "YOU", i got this error

### ISSUE THREAD

**Issue by tongbao96** [acheong08/ChatGPT#267]
D:\Anaconda3\python.exe E:/ChatGPT-main/src/revChatGPT/__main__.py

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...

You:
hellop

Chatbot: 
Response not in correct format!
Error when handling response, got valuesYPE html>

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/261
