### ISSUE TITLE
[BUG] TypeError: OpenAIAuth.__init__() got an unexpected keyword argument 'cf_clearance'

### ISSUE THREAD

**Issue by 1719pankaj** [acheong08/ChatGPT#269]
**Describe the bug**
Standard use returns 'TypeError: OpenAIAuth.__init__() got an unexpected keyword argument 'cf_clearance''

**To Reproduce**
1. Copy and paste the "Standard use" block from wiki and update it with credentials.
2. Add the "Getting Response" code block under it
3. Run.

**Expected behavior**
I should be getting a proper response from ChatGPT.

**Output**
/home/codespace/.python/current/bin/python3 /workspaces/codespaces-flask/interface.py
Traceback (most recent call last):
  File "/workspaces/codespaces-flask/interface.py", line 8, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 352, in refresh_session
    raise exc
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 349, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/home/codespace/.python/current/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 375, in login
    auth = OpenAIAuth(email, password, use_proxy=bool(
TypeError: OpenAIAuth.__init__() got an unexpected keyword argument 'cf_clearance'

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`

 - OS: Windows11
 - Python version: `3.11.1`
 - ChatGPT Version: `0.0.38.8`
 - OpenAI Version: `0.0.6`

 - OS: Ubuntu 20.04.5 LTS x86_64 (Codespaces)
 - Python version: `3.10.4`
 - ChatGPT Version: `0.0.38.8`
 - OpenAI Version: `0.0.6`

**Comment by gin-melodic** [comment]
You can test the command below.
```shell
$ pip3 uninstall OpenAIAuth 
$ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
```

**Comment by 1719pankaj** [comment]
@gin-melodic 
I tried and it still didn't work, 
It returns the same error as before

**Comment by lyzhang0113** [comment]
1. If you are using venv environment, make sure to uninstall then install using the pip inside your venv (e.g. venv/Scripts/pip.exe for windows)
2. After you've successfully upgraded OpenAIAuth, you need to set `session_token`, `cf_clearance`, and `user_agent` in your config.json. [Instructions](https://github.com/acheong08/ChatGPT/wiki/Setup)

**Comment by YIDE721** [comment]
> You can test the command below.
> 
> ```shell
> $ pip3 uninstall OpenAIAuth 
> $ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> ```

<img width="831" alt="image" src="https://user-images.githubusercontent.com/109189715/206989019-ab179fa4-8f02-4fbc-8d0f-1b3698cf28f2.png">
 Still something wrong

**Comment by Gingmzmzx** [comment]
> > You can test the command below.
> > ```shell
> > $ pip3 uninstall OpenAIAuth 
> > $ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> > ```
> 
> <img alt="image" width="831" src="https://user-images.githubusercontent.com/109189715/206989019-ab179fa4-8f02-4fbc-8d0f-1b3698cf28f2.png">
> 
> Still something wrong

same problem

**Comment by lyzhang0113** [comment]
> > > You can test the command below.
> > > ```shell
> > > $ pip3 uninstall OpenAIAuth 
> > > $ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> > > ```
> > 
> > 
> > <img alt="image" width="831" src="https://user-images.githubusercontent.com/109189715/206989019-ab179fa4-8f02-4fbc-8d0f-1b3698cf28f2.png">
> > Still something wrong
> 
> same problem

Y'all tried my solution?


> 2\. After you've successfully upgraded OpenAIAuth, you need to set `session_token`, `cf_clearance`, and `user_agent` in your config.json. [Instructions](https://github.com/acheong08/ChatGPT/wiki/Setup)

**Comment by Gingmzmzx** [comment]
> > > > You can test the command below.
> > > > ```shell
> > > > $ pip3 uninstall OpenAIAuth 
> > > > $ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> > > > ```
> > > 
> > > 
> > > <img alt="image" width="831" src="https://user-images.githubusercontent.com/109189715/206989019-ab179fa4-8f02-4fbc-8d0f-1b3698cf28f2.png">
> > > Still something wrong
> > 
> > 
> > same problem
> 
> Y'all tried my solution?
> 
> > 2. After you've successfully upgraded OpenAIAuth, you need to set `session_token`, `cf_clearance`, and `user_agent` in your config.json. [Instructions](https://github.com/acheong08/ChatGPT/wiki/Setup)

Thanks, but it still seems to have some problems
![image](https://user-images.githubusercontent.com/49107602/206996150-cc703599-e28f-4a76-956a-3ab7c41f5322.png)
![image](https://user-images.githubusercontent.com/49107602/206996185-96b0ca41-a569-4bf1-a37f-dcf30d2c9c0e.png)

**Comment by Gingmzmzx** [comment]
> > > > You can test the command below.
> > > > ```shell
> > > > $ pip3 uninstall OpenAIAuth 
> > > > $ pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> > > > ```
> > > 
> > > 
> > > <img alt="image" width="831" src="https://user-images.githubusercontent.com/109189715/206989019-ab179fa4-8f02-4fbc-8d0f-1b3698cf28f2.png">
> > > Still something wrong
> > 
> > 
> > same problem
> 
> Y'all tried my solution?
> 
> > 2. After you've successfully upgraded OpenAIAuth, you need to set `session_token`, `cf_clearance`, and `user_agent` in your config.json. [Instructions](https://github.com/acheong08/ChatGPT/wiki/Setup)

Thanks, but it still seems to have some problems
![image](https://user-images.githubusercontent.com/49107602/206996782-99faf228-0505-4d30-9d6e-2f75156e735e.png)
![image](https://user-images.githubusercontent.com/49107602/206996859-653f691c-c7c1-41f8-a7f2-303ef3540805.png)

**Comment by 1719pankaj** [comment]
![Screenshot 2022-12-12 153130](https://user-images.githubusercontent.com/69200242/207017727-85207e60-9130-4b28-a8c9-86820ef0ba0f.png)

I just added the session token, cf token, and user_agent. I worked. The instructions say I just need my email and password but adding these seems to do the trick.

**Comment by Gingmzmzx** [comment]
Thank you, I just tried to succeed.
I have always deployed on my VPS before, but always prompted 403
Later, I tried to deploy in the local environment, and he succeeded

**Comment by kyleliang919** [comment]
> ```shell
> pip3 install git+https://github.com/acheong08/OpenAIAuth.git@main
> ```

Where do I get those?

**Comment by kyleliang919** [comment]
> ![Screenshot 2022-12-12 153130](https://user-images.githubusercontent.com/69200242/207017727-85207e60-9130-4b28-a8c9-86820ef0ba0f.png)
> 
> I just added the session token, cf token, and user_agent. I worked. The instructions say I just need my email and password but adding these seems to do the trick.

Where can I find session token, cf token, and user_agent?

**Comment by acheong08** [comment]
Read the updated wiki
