### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by Uzay-G** [acheong08/ChatGPT#27]
I run:

```python
chatbot = Chatbot(config, conversation_id=None)
chatbot.reset_chat()
chatbot.refresh_session()
resp = chatbot.get_chat_response("Complete the following blog post:\n" + dataobj.content, output="text")
print(resp["message"])
```
and get:

`TypeError: 'generator' object is not subscriptable`

This is referring to the `resp` object.

Thanks for your help, and for making the project in general!

**Comment by acheong0** [comment]
I spot the issue. In trying to support streams, I broke the normal returns

**Comment by acheong08** [comment]
Oops wrong account

**Comment by acheong08** [comment]
New version published. Fixed

`pip3 install revChatGPT -- upgrade`
