### ISSUE TITLE
[BUG]raise Exception("Wrong response code")

### ISSUE THREAD

**Issue by Longyichen** [acheong08/ChatGPT#273]
**Describe the bug**
I'm getting this error using chatbot on the server.
I confirmed that the sessionid etc I provided is correct as I don't get the error when running it on my own mac computer. And I'm configuring the same config file for them.

**To Reproduce**
``
from revChatGPT.revChatGPT import AsyncChatbot as Chatbot
import json

async def handle_response(prompt) -> str:
    chatbot.refresh_session()
    response = await chatbot.get_chat_response(prompt, output="text")
    responseMessage = response['message']

    return responseMessage

def get_config() -> dict:
    import os
    # get config.json path
    config_dir = os.path.abspath(__file__ + "/../../")
    config_name = 'config.json'
    config_path = os.path.join(config_dir, config_name)

    with open(config_path, 'r') as f:
        data = json.load(f)

    return data

data = get_config()

config = {
    "cf_clearance": data['cf_clearance'],
    "user_agent": data['user_agent'],
    "session_token" : data['session_token']
}

chatbot = Chatbot(config, conversation_id=None)
``

**Expected behavior**
Normal connection establishment

**Output**
Traceback (most recent call last):
  File "/root/chatGPT-discord-bot/onmessage.py", line 3, in <module>
    from src import responses
  File "/root/chatGPT-discord-bot/src/responses.py", line 34, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code

**Comment by cibernicola** [comment]
not working:
`selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service C:\Users\*******\appdata\roaming\undetected_chromedriver\e0609fc12f4117e7_chromedriver.exe`

It doesn't "move" from wlcome screen
![image](https://user-images.githubusercontent.com/4579387/207030874-105023d5-3cbe-4172-9594-7ee9a9a52852.png)

**Comment by acheong08** [comment]
An issue with windows. Check out https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc for solutions
