### ISSUE TITLE
[BUG] Wrong response code in server

### ISSUE THREAD

**Issue by rivo2302** [acheong08/ChatGPT#275]
I got Wrong response code when I launch the projet in my local machine it works correctly but when I run it in a serveur  I got error : Wrong response code,

**Comment by acheong08** [comment]
Reference https://github.com/acheong08/ChatGPT/issues/261

Upgrade to https://github.com/acheong08/ChatGPT/releases/tag/0.0.a40

Only session tokens are supported now
