### ISSUE TITLE
[BUG] Where to put the config.json file

### ISSUE THREAD

**Issue by BlueSkyLT** [acheong08/ChatGPT#276]
**Describe the bug**
I have run `pip3 install revChatGPT --upgrade` in a new conda environment, but I don't know where to find the `/revChatGPT` folder to put the `config.json` file. I have tried creating `C:\Users\MY_USER_NAME\.config\revChatGPT\config.json` and it doesn't work.

The instruction:
Make the necessary changes in `config.json.example` and save as `config.json` in the current working directory, in `$XDG_CONFIG_HOME/revChatGPT/config.json`, or in `$HOME/revChatGPT/config.json`.

**Output**
```
(chatgpt) C:\Users\MY_USER_NAME>python -m revChatGPT --debug
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Please create and populate ./config.json, $XDG_CONFIG_HOME/revChatGPT/config.json, or ~/.config/revChatGPT/config.json to continue
```

**Environment (please complete the following information):**
Windows

**Comment by acheong08** [comment]
In `C:\Users\MY_USER_NAME`
