### ISSUE TITLE
TypeError: object generator can't be used in 'await' expression

### ISSUE THREAD

**Issue by arwooy** [acheong08/ChatGPT#278]
when run this：

async def printMessage():
    async for i in await chatbot.get_chat_response("hello", output="stream"):
        print(i['message'])

asyncio.run(printMessage())

error report：
    async for i in await chatbot.get_chat_response("hello", output="stream"):
TypeError: object generator can't be used in 'await' expression

**Comment by acheong08** [comment]
As it says, you can't use await for streams. If you want to stream data, using a normal loop through the normal Chatbot with output="stream" would send the data asynchronously

**Comment by n3d1117** [comment]
@arwooy make sure you import the async version of the chatbot:

`from revChatGPT.revChatGPT import AsyncChatbot`

works for me with Python 3.10+
