### ISSUE TITLE
[BUG]Error when handling response, got valuesil

### ISSUE THREAD

**Issue by 7235201** [acheong08/ChatGPT#279]
**Describe the bug**
when long text,ofent
"Response not in correct format!
Error when handling response, got valuesil"":""Too many requests, please slow down""
how to fix,thks

**Comment by acheong08** [comment]
You might have to sign out of the web version

**Comment by 7235201** [comment]
also often
Invalid status code: 403
Something went wrong!

**Comment by 7235201** [comment]
You mean this?
Found user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/108.0.5359.98 Safari/537.36

**Comment by acheong08** [comment]
What version are you on?

**Comment by acheong08** [comment]
Please follow https://github.com/acheong08/ChatGPT/wiki/Setup and do `pip3 install revChatGPT==0.0.a42` (Doesn't work with servers)

**Comment by acheong08** [comment]
The wiki has been updated with more details https://github.com/acheong08/ChatGPT/wiki/Setup

Closing in favor of https://github.com/acheong08/ChatGPT/issues/261

**Comment by 7235201** [comment]
Yes, so I have installed a42, but I found I cant login chatgpt

**Comment by acheong08** [comment]
email/password doesn't work anymore. Use session tokens

**Comment by acheong08** [comment]
Please read wiki carefully

**Comment by 7235201** [comment]
That's chatgpt problem,now I can login chatgpt web 
I have filled 3 tokens
but a42 always show 
Waiting for cookies...
but 38 dont show that 
why?
