### ISSUE TITLE
Serverless ChatGPT Telegram bot

### ISSUE THREAD

**Issue by franalgaba** [acheong08/ChatGPT#28]
Hi!

I created a serverless Telegram bot for ChatGPT using AWS Lambda. The implementation is based on your reverse-engineering API. Credits to you in my `README.md`

https://github.com/franalgaba/chatgpt-telegram-bot-serverless

Thank you :)
Fran.

**Comment by acheong08** [comment]
Added to the list. This is pretty cool. Something I will probably use myself while on mobile.
