### ISSUE TITLE
[BUG]   Message: Cannot connect to chrome at 127.0.0.1:38717 on server

### ISSUE THREAD

**Issue by rivo2302** [acheong08/ChatGPT#280]
In my production server , I have got tshis error :

 Message: unknown error: cannot connect to chrome at 127.0.0.1:38717
from chrome not reachable
Stacktrace:
#0 0x55d1e6d7e2a3 <unknown>
#1 0x55d1e6b3cdfd <unknown>
#2 0x55d1e6b2b14b <unknown>
#3 0x55d1e6b69843 <unknown>
#4 0x55d1e6b60f89 <unknown>
#5 0x55d1e6ba20b7 <unknown>
#6 0x55d1e6ba1a5f <unknown>
#7 0x55d1e6b99903 <unknown>
#8 0x55d1e6b6cece <unknown>
#9 0x55d1e6b6dfde <unknown>
#10 0x55d1e6dce63e <unknown>
#11 0x55d1e6dd1b79 <unknown>
#12 0x55d1e6db489e <unknown>
#13 0x55d1e6dd2a83 <unknown>
#14 0x55d1e6da7505 <unknown>
#15 0x55d1e6df3ca8 <unknown>
#16 0x55d1e6df3e36 <unknown>
#17 0x55d1e6e0f333 <unknown>
#18 0x7f8822dcb609 start_thread

**Comment by acheong08** [comment]
Servers don't work at the moment due to https://github.com/acheong08/ChatGPT/issues/261. We/I am working towards bypassing Cloudflare but that could take a while

**Comment by acheong08** [comment]
Check out the updated wiki https://github.com/acheong08/ChatGPT/wiki/Setup
