### ISSUE TITLE
[BUG]TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by fzp0424** [acheong08/ChatGPT#281]
**Describe the bug**
Hi, I am a beginner. When I follow **Initial Step**, it returns
![1670854466280](https://user-images.githubusercontent.com/102568752/207067897-e655e879-b3a1-4055-9c84-f87f2008d324.jpg)

**To Reproduce**
1. Go to 'Initial Step'
2. See error
![image](https://user-images.githubusercontent.com/102568752/207068651-7d5ac300-f9de-410d-9347-5b15f9508514.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/102568752/207068801-d9328e06-6e1c-4576-b57d-fccd8fc8807d.png)

**Output**
In the correct directory, run `python3 -m revChatGPT --debug`
![image](https://user-images.githubusercontent.com/102568752/207069456-7bb2deb2-bd13-492d-9a40-27560895f96c.png)
And sometimes it reported this error
**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: Linux
 - Python version: 3.9.7
 - ChatGPT Version: 0.0.38.8
 - OpenAI Version: 0.0.6

**Additional context**

**Comment by acheong08** [comment]
The 403 error is due to https://github.com/acheong08/ChatGPT/issues/261

You need to do do `pip3 install revChatGPT==0.0.a42`

**Comment by acheong08** [comment]
Closing in favor of https://github.com/acheong08/ChatGPT/issues/261 and wiki has been updated https://github.com/acheong08/ChatGPT/wiki/Setup for better instructions
