### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Shiro2568** [acheong08/ChatGPT#283]
When sending a message to the bot, an error appears - 
```
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

Can you suggest what to do at this moment?

**Comment by acheong08** [comment]
A lot of things has changed. Please refer to the readme notice and https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by acheong08** [comment]
This is a duplicate of https://github.com/acheong08/ChatGPT/issues/261

**Comment by Shiro2568** [comment]
Thank u!
