### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Shiro2568** [acheong08/ChatGPT#284]
When sending messages to the bot, I get an error -
 ```
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

Can you suggest what to do?

**Comment by eliksr** [comment]
I'm working with `revChatGPT==0.0.a42` and after ~60 prompts I get the json error:
`File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/site-packages/revChatGPT/revChatGPT.py:547, in Chatbot.get_chat_response(self, prompt, output, conversation_id, parent_id)
    544 coroutine_object = super().get_chat_response(
    545     prompt, output, conversation_id, parent_id)
    546 try:
--> 547     return asyncio.run(coroutine_object)
    548 except RuntimeError:
    549     import nest_asyncio

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/site-packages/nest_asyncio.py:38, in _patch_asyncio.<locals>.run(main, debug)
     36 task = asyncio.ensure_future(main)
     37 try:
---> 38     return loop.run_until_complete(task)
     39 finally:
     40     if not task.done():

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/site-packages/nest_asyncio.py:81, in _patch_loop.<locals>.run_until_complete(self, future)
     78 if not f.done():
     79     raise RuntimeError(
     80         'Event loop stopped before Future completed.')
---> 81 return f.result()

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/asyncio/tasks.py:256, in Task.__step(***failed resolving arguments***)
    252 try:
    253     if exc is None:
    254         # We use the `send` method directly, because coroutines
    255         # don't have `__iter__` and `__next__` methods.
--> 256         result = coro.send(None)
    257     else:
    258         result = coro.throw(exc)

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/site-packages/revChatGPT/revChatGPT.py:255, in AsyncChatbot.get_chat_response(self, prompt, output, conversation_id, parent_id)
    253     self.parent_id_prev_queue.pop(0)
    254 if output == "text":
--> 255     return await self.__get_chat_text(data)
    256 elif output == "stream":
    257     return self.__get_chat_stream(data)

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/site-packages/revChatGPT/revChatGPT.py:211, in AsyncChatbot.__get_chat_text(self, data)
    209         raise Exception("Not a JSON response") from exc2
    210     raise Exception("Incorrect response from OpenAI API") from exc
--> 211 response = json.loads(response)
    212 self.parent_id = response["message"]["id"]
    213 self.conversation_id = response["conversation_id"]

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~/opt/anaconda3/envs/dev_3_9/lib/python3.9/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 3 (char 2)`

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/207084064-893f4958-b671-49ae-a5d8-c10e80fbd3e5.png)

ChatGPT unstable right now

**Comment by eliksr** [comment]
OK that makes sense :)
Thanks!!
