### ISSUE TITLE
How to deploy on the server

### ISSUE THREAD

**Issue by hbchen121** [acheong08/ChatGPT#285]
The tutorial on how to deploy on the server is a little unclear. Can you explain in detail how to obtain cf_clearance and user_agent on the server?

**Comment by yym68686** [comment]
Same issue here.

**Comment by hbchen121** [comment]
> It's a bit difficult right now. You have to set your server as a VPN and tunnel your client traffic there. Then extract the `cf_clearance` and `user_agent` from your local computer and upload the config onto the server. It can't refresh the `cf_clearance` on the server so it only lasts for ~2 hours. I will work on reversing the Cloudflare system tomorrow.

Thanks, maybe this git will help you: https://github.com/vvanglro/cf-clearance
