### ISSUE TITLE
[bug] can login (server)

### ISSUE THREAD

**Issue by lsfrDev** [acheong08/ChatGPT#289]
I've entered all the values required like cf_clearnce, user_agent, session_token

but the same error happens 

```
Traceback (most recent call last):
  File "3.py", line 14, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```

**Comment by moeseif** [comment]
the user-agent is not showing any more in the view inspect . is this true ?

**Comment by BLuFeNiX** [comment]
@moeseif You are looking in the wrong place. Your browser sends the user agent in the request.

**Comment by lhuaizhong** [comment]
> I've entered all the values required like cf_clearnce, user_agent, session_token
> 
> but the same error happens
> 
> ```
> Traceback (most recent call last):
>   File "3.py", line 14, in <module>
>     chatbot = Chatbot(config, conversation_id=None)
>   File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
>     self.refresh_session()
>   File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
>     raise Exception("Wrong response code")
> Exception: Wrong response code
> ```

Same here.

**Comment by lhuaizhong** [comment]
> > I've entered all the values required like cf_clearnce, user_agent, session_token
> > but the same error happens
> > ```
> > Traceback (most recent call last):
> >   File "3.py", line 14, in <module>
> >     chatbot = Chatbot(config, conversation_id=None)
> >   File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
> >     self.refresh_session()
> >   File "/home/runner/celebrity-infos/venv/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
> >     raise Exception("Wrong response code")
> > Exception: Wrong response code
> > ```
> 
> Same here.

(base) root@ubuntu:~/chatgpt# python wechat_chatgpt.py 
Traceback (most recent call last):
  File "wechat_chatgpt.py", line 32, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/root/miniconda3/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/root/miniconda3/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
(base) root@ubuntu:~/chatgpt#

**Comment by lhuaizhong** [comment]
> @lhuaizhong https://github.com/acheong08/ChatGPT/wiki/setup
> 
> The user agent and IP must be the same as the one used to get the clearance

Yes, I have set up a VPN on my server and then accessed OpenAI through the VPN using a browser.

**Comment by DTDwind** [comment]
I've entered all the values required like cf_clearnce, user_agent, session_token

but the same error happens......

```
Debugger enabled on OpenAIAuth
SLIL2suuATTo8RQ0gCBvZPLN96Z7kz5YQNFlXh59q6I-1670919517-0-1-bbbaa7b3.f9387a27.ecbbf853-160
Invalid status code: 403
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "chatgpt.py", line 42, in <module>
    chatbot = Chatbot(config, conversation_id=None,debug=True)
  File "/home/dtdwind/.local/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/home/dtdwind/.local/lib/python3.8/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```
