### ISSUE TITLE
[BUG] Filter Still Causing Problems

### ISSUE THREAD

**Issue by easyssss** [acheong08/ChatGPT#296]
I keep getting the following error, but only when the bot's response is something that would go against the filters. "Response not in correct format!
peer closed connection without sending complete message body (incomplete chunked read)"
If I try to send any more messages in that session, I get this error message: "Response not in correct format!
Error when handling response, got valuesil":"Too many requests, please slow down". This happens regardless of how many messages have been sent or how many words, and it only happens after the bot would normally cut off in the browser.  I can have extremely long conversations without issue or errors saying "too many requests."

**Output**
Running in debug mode did not provide any additional info.

**Comment by f1nniboy** [comment]
I have the same issue, but it only occurs when the AI generates long texts (>1000 characters)

**Comment by acheong08** [comment]
This is not a filter issue. The same bug occurs on the OpenAI website. It's bad engineering on their part
