### ISSUE TITLE
Circular dependency error in import when using pip package

### ISSUE THREAD

**Issue by moozilla** [acheong08/ChatGPT#3]
When I try to run the example code, I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/moozilla/git/chatgpt_tool/main.py", line 1, in <module>
    import revChatGPT
  File "/Users/moozilla/git/chatgpt_tool/venv/lib/python3.10/site-packages/revChatGPT/__init__.py", line 1, in <module>
    from revChatGPT import Chatbot
ImportError: cannot import name 'Chatbot' from partially initialized module 'revChatGPT' (most likely due to a circular import)
```

I was able to fix it by commenting out the `from revChatGPT import Chatbot` line in `__init__.py`.

**Comment by acheong08** [comment]
> When I try to run the example code, I'm getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/moozilla/git/chatgpt_tool/main.py", line 1, in <module>
>     import revChatGPT
>   File "/Users/moozilla/git/chatgpt_tool/venv/lib/python3.10/site-packages/revChatGPT/__init__.py", line 1, in <module>
>     from revChatGPT import Chatbot
> ImportError: cannot import name 'Chatbot' from partially initialized module 'revChatGPT' (most likely due to a circular import)
> ```
> 
> I was able to fix it by commenting out the `from revChatGPT import Chatbot` line in `__init__.py`.

Sorry. Fixing that now

**Comment by acheong08** [comment]
Fixed. `pip3 install revChatGPT --upgrade`

**Comment by moozilla** [comment]
Thanks! I can confirm the fix is working on my end.
