### ISSUE TITLE
[BUG] Cookies about Cloudflare are obtained but not available

### ISSUE THREAD

**Issue by JanYork** [acheong08/ChatGPT#300]
Description of the problem: I used Python to automate the acquisition of Cloudflare's Cookies, and he gave me the following log:

LOG: Starting to fetch Cloudflare cookies
cf-shit replied:
{'success': True, 'msg': 'cf challenge success', 'user_agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.3, 'cookies': {'cf_clearance': 'LfTk3H9HJTJlysT9umRTqB7Fq9GRMTB2qYL9F5bfMt8-1670914754-0-1-5dd76e1c.f52442a.2e654d20-160', '__Host-next-auth.csrf-token': 'a177c47fc2334de9879dabf103acd0e843c636b019ccd822d0ab42054e811348%7C15c0bfe469904f935fca081f2b5f3d90bcef5d9dc80d3f57ac35c7faf8b69220', '__Secure-next-auth.callback-url': 'https%3A%2F%2Fchat.openai.com', '__cf_bm': '77MrN4kp0k5cgR74E30ZkZiSlH7LAakAf4bMaEy8jOk-1670914755-0-AQpxq8xgWdg14wXktj7F/XhEzvDT3cHT9ANri82kl2fSn63pTsZZVzYJNUknmFylG2UF6X55MCAmQf0NpfotRVST8FCOoYQViJOrAic26AH5BxXTPj83NlYAb1yw+ZUneMHQZRH51bkSKuTCrczTxukJCOycoFiQ4RQLu4tOyZbhxCqMwvgi6pDOEP1OLlFu2g=='}}
get success

But the program gives me an error like this:
Traceback (most recent call last):
  File "C:\Users\woo-m\Desktop\QQ机器人-linux自动获取Cf Cookie\py\chat-gpt-qbot.py", line 285, in <module>
    chatbot = Chatbot(config, conversation_id=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woo-m\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "C:\Users\woo-m\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\revChatGPT.py", line 307, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code

I found this piece of code through debugging: "self.base_url + "api/auth/session" request, the return is 403

I don't understand, my session-token is available, Cloudflare's cookie is also available, why the program returns 403, is this solution flawed? I hope to get your advice, thanks

**Comment by kyleliang919** [comment]
same issue here. I believe I input all the correct information, still getting 403.

**Comment by JanYork** [comment]
> 同样的问题在这里。我相信我输入了所有正确的信息，仍然得到 403。

Wow, boss, are you an overseas Chinese?

**Comment by acheong08** [comment]
> same issue here. I believe I input all the correct information, still getting 403.

What are you inputting. If you're using the version with chrome, do not enter the user agent and cf_clearance manually.

**Comment by acheong08** [comment]
I am working on bypassing Cloudflare today. Looking into either script based bypass or https://github.com/vvanglro/cf-clearance

**Comment by JanYork** [comment]
> I am working on bypassing Cloudflare today. Looking into either script based bypass or https://github.com/vvanglro/cf-clearance

Thank you so much, come on, I need this badly, he is very interesting and can bring a lot of help to my group chat

**Comment by kyleliang919** [comment]
> o

I see. Thank you so much! I just removed the user_agent and cf_clearance and it worked!!!!

**Comment by JanYork** [comment]
> > o
> 
> I see. Thank you so much! I just removed the user_agent and cf_clearance and it worked!!!!

Can it run normally? Both my user_agent and cf_clearance are automatically obtained by the script, and the callback of the request is 403

**Comment by SuperWildFireFox** [comment]
still 403 yet,don't know why

**Comment by kyleliang919** [comment]
> 

Try removing both of them from the config and use a session token from a chrome browser.

**Comment by JanYork** [comment]
> still 403 yet,don't know why

It seems that this solution cannot be successfully bypassed this time. I tried many times. Since the morning, I have only succeeded twice until now, and it failed again when the automatic update was performed for the second time.

**Comment by JanYork** [comment]
> > 
> 
> Try removing both of them from the config and use a session token from a chrome browser.

But the expiration time of the token is only about 2 hours, which is inconvenient

**Comment by acheong08** [comment]
> > > 
> > 
> > 
> > Try removing both of them from the config and use a session token from a chrome browser.
> 
> But the expiration time of the token is only about 2 hours, which is inconvenient

I am working on it. You have no idea how complex Cloudflare's javascript is

**Comment by JanYork** [comment]
> > > > 
> > > 
> > > 
> > > Try removing both of them from the config and use a session token from a chrome browser.
> > 
> > 
> > But the expiration time of the token is only about 2 hours, which is inconvenient
> 
> I am working on it. You have no idea how complex Cloudflare's javascript is

It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on

**Comment by acheong08** [comment]
> It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on

The issue is in JavaScript which I am not familiar with either.

**Comment by JanYork** [comment]
> > It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on
> 
> The issue is in JavaScript which I am not familiar with either.

I don't think you need to write the bypass mechanism yourself, why don't you try to look at this warehouse, https://github.com/VeNoMouS/cloudscraper

**Comment by acheong08** [comment]
> > > It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on
> > 
> > 
> > The issue is in JavaScript which I am not familiar with either.
> 
> I don't think you need to write the bypass mechanism yourself, why don't you try to look at this warehouse, [VeNoMouS/cloudscraper](https://github.com/VeNoMouS/cloudscraper)

I have. It doesn't support CloudflareV2. The author wants people to pay $60/month for the closed source version

**Comment by JanYork** [comment]
> > > > It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on
> > > 
> > > 
> > > The issue is in JavaScript which I am not familiar with either.
> > 
> > 
> > I don't think you need to write the bypass mechanism yourself, why don't you try to look at this warehouse, [VeNoMouS/cloudscraper](https://github.com/VeNoMouS/cloudscraper)
> 
> I have. It doesn't support CloudflareV2. The author wants people to pay $60/month for the closed source version

Oh, this is too expensive, it seems there is no way, I will try to find other warehouses, it may be very difficult to bypass by myself.

**Comment by kyleliang919** [comment]
@acheong08 @JanYork  you guys are doing God's work, I wish you the best of luck of figuring this out!
ps: Even chatgpt doesn't know how to do this
`response = bot.get_chat_response("How to byplass CloudflareV2 authentication in javescript?")`
> response['message']: I'm sorry, but I don't have information about bypassing authentication for specific websites. Additionally, attempting to bypass authentication for a website without proper authorization is a violation of the site's terms of service and could be illegal. I would recommend against trying to bypass any website's authentication measures.

**Comment by SuperWildFireFox** [comment]
@kyleliang919 sir,need I use token by google login?

**Comment by JanYork** [comment]
> > It seems very difficult, I really want to find a way with you, but I am not very familiar with python, so I can only say come on
> 
> The issue is in JavaScript which I am not familiar with either.

I have an idea, since it cannot be verified by the machine, can we try to use a real browser to bypass it? Such as Splash

**Comment by kyleliang919** [comment]
> @kyleliang919 sir,need I use token by google login?
hum, can you even login with a google account? I tried and couldn't do that, since there is no password associated.

**Comment by SuperWildFireFox** [comment]
I install a desktop on my server and use revChatGPT==0.0.42.1,but it always respond 403 even if we use fresh token in same machine chrome browser.

**Comment by JanYork** [comment]
I found several projects that may achieve perfect bypass in https://github.com/topics/anti-bot-page , I don’t know if it will help you.
For example: proxy access https://github.com/NoahCardoza/CloudProxy
Or find https://github.com/Anorov/cloudflare-scrape , I don’t know if you can bypass the V2 version

**Comment by Seventher** [comment]
I had the same problem. I created a new py file in the project directory and wrote:

---------------------------------
from revChatGPT.revChatGPT import Chatbot

# For the config please go here:
# https://github.com/acheong08/ChatGPT/wiki/Setup
config = {
"seesion_token": "mytoken"
#"proxy": "<HTTP/HTTPS_PROXY>"
}

chatbot = Chatbot(config, conversation_id=None)

response = chatbot.get_chat_response("Hello world", output="text")
print(response)

------------------------------------------
After executing the program, there were always errors. After locating, I found that around line 300 of revChatGPT.py, response returned a value of 403. I was very confused

**Comment by JanYork** [comment]
> I'm using Windows. Is this related?

No, this should be blocked by CloudflareV2's anti-human-computer policy
