### ISSUE TITLE
how to solve it

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#304]
![image](https://user-images.githubusercontent.com/86822589/207307131-a3d979ca-07cd-4cb0-bdec-e2bf15824f48.png)

**Comment by acheong08** [comment]
I am in the process of fixing https://github.com/acheong08/ChatGPT/issues/261

**Comment by ccemoji** [comment]
I meet the same question.Execute with command line with '--debug' to get more information and then solve it.

**Comment by acheong08** [comment]
Check the updated wiki. https://github.com/acheong08/ChatGPT/wiki/Setup

Everything broke. need to upgrade
