### ISSUE TITLE
Error when handling response, got valuesYPE html>[BUG]

### ISSUE THREAD

**Issue by ccemoji** [acheong08/ChatGPT#306]
message:

Logging in...

You:
Hello

Chatbot: 
Response not in correct format!
Error when handling response, got valuesYPE html>

How can I solve this problem?I can't even understand it.

**Comment by acheong08** [comment]
What version are you running?

**Comment by acheong08** [comment]
I mean `revChatGPT` version

`pip3 show revChatGPT`

**Comment by ccemoji** [comment]
Name: revChatGPT
Version: 0.0.43
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: d:\python\lib\site-packages
Requires: playwright, nest-asyncio, OpenAIAuth, httpx, cf-clearance2
Required-by:


I have used the commend "pip3 install --upgrade revChatGPT"

**Comment by acheong08** [comment]
Does the Chrome window show up at all?

**Comment by acheong08** [comment]
Try deleting your `config.json` and keep it deleted. Then run `revChatGPT --debug`

**Comment by acheong08** [comment]
Follow the command instructions. Do `playwright install`

**Comment by longkt90** [comment]
Cannot start with similar error as well:
`pip3 show revChatGPT`
Name: revChatGPT
Version: 0.0.43
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/deployer/.local/lib/python3.10/site-packages
Requires: cf-clearance2, httpx, nest-asyncio, OpenAIAuth, playwright
Required-by:


`revChatGPT --debug`
return:
```
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by ccemoji** [comment]
playwright install
Downloading FFMPEG playwright build v1008 from https://playwright.azureedge.net/builds/ffmpeg/1008/ffmpeg-win64.zip
1.4 Mb [====================] 100% 0.0s
FFMPEG playwright build v1008 downloaded to C:\Users\cc\AppData\Local\ms-playwright\ffmpeg-1008
Downloading Firefox 106.0 (playwright build v1364) from https://playwright.azureedge.net/builds/firefox/1364/firefox-win64.zip
78.3 Mb [====================] 100% 0.0s
Firefox 106.0 (playwright build v1364) downloaded to C:\Users\cc\AppData\Local\ms-playwright\firefox-1364
Downloading Webkit 16.4 (playwright build v1735) from https://playwright.azureedge.net/builds/webkit/1735/webkit-win64.zip
73.6 Mb [====================] 100% 0.0s
Webkit 16.4 (playwright build v1735) downloaded to C:\Users\cc\AppData\Local\ms-playwright\webkit-1735


After I installed ,I use command "revChatGPT --debug" and it gives the same wrong message.

**Comment by acheong08** [comment]
That's a bit strange. Check https://github.com/microsoft/playwright/issues and see if a solution can be found there

**Comment by ccemoji** [comment]
After I download Chorme from Google instead of cmd,the Chrome window show up,but it still doesn't work.Maybe it is because of proxy.I open the proxy before open the Chrome,and I close the proxy after Chrome close,and I keep closing proxy while Chrome open twice,but it doesn't work.The first time, the browser was closed immediately after the login interface was opened. The second time, it was still the same, and the program was stopped and an error was reported.

Here is the message:

Logging in...
Waiting for cookies...
Waiting for cookies...
Traceback (most recent call last):
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\revChatGPT.py", line 322, in refresh_session
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\__main__.py", line 185, in <module>
    main()
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\__main__.py", line 181, in main
    configure()
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\__main__.py", line 74, in configure
    chatGPT_main(config, debug)
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\__main__.py", line 86, in chatGPT_main
    chatbot = Chatbot(config, debug=debug,
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\revChatGPT.py", line 100, in __init__
    self.refresh_session()
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\revChatGPT.py", line 311, in refresh_session
    self.refresh_session()
  File "c:\Users\cc\Desktop\ChatGPT-main\src\revChatGPT\revChatGPT.py", line 342, in refresh_session
    raise Exception("Failed to refresh session")
Exception: Failed to refresh session

**Comment by ccemoji** [comment]
I have already solved the question,use' playwright install' to download,if it didn't work,then find the catalogue to delete it and use this command again.
