### ISSUE TITLE
Loop to create/close browser window, can't log in[BUG]

### ISSUE THREAD

**Issue by zwa73** [acheong08/ChatGPT#307]
The open browser will arrive at this URL, close it, and repeat the process.
https://chat.openai.com/auth/login

Windows OS is used

**Comment by zwa73** [comment]
python3.9 -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
PvQFDAhJwO4_A2p_UmMOqD5MXcs0lzQI9phfXFFJL8E-1670938295-0-1-6a9c3b2e.29526de.3d9d64ce-160
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
cf challenge fail
Something went wrong! Please run with --debug to see the error.
cf challenge fail


It seems that debug mode is not turned on properly?
Did I make a mistake somewhere?

**Comment by zwa73** [comment]
```
python3.9 -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
WHPYRbv69fa3yf09tysTyiOiWcI_N1HWtToxkexXHV8-1670938698-0-1-6a9c3b2e.29526de.3d9d64ce-160
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
d63UbYXOZZMzyrgMLThLueARxn8POdTX_wAfELWPjTY-1670938753-0-1-6a9c3b2e.29526de.3d9d64ce-250
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
```

This is leaving the config empty and logging in manually

**Comment by acheong08** [comment]
> This is leaving the config empty and logging in manually

I think leaving the config empty is the best way to go for now

**Comment by RIP-GitHub** [comment]
> > 本会将配置留空并手动登录
> 
> 我认为将配置留空是目前最好的方法

I met the same problem, and I think the IP I'm using is one that has been flagged by Cloudflare's risk control. maybe can use more safe ip？

**Comment by RIP-GitHub** [comment]
> > This is leaving the config empty and logging in manually
> 
> I think leaving the config empty is the best way to go for now

I met the same problem, and I think the IP I'm using is one that has been flagged by Cloudflare's risk control. maybe can use more safe ip？

**Comment by acheong08** [comment]
> I met the same problem, and I think the IP I'm using is one that has been flagged by Cloudflare's risk control. maybe can use more safe ip？

That is a solution. If you have a desktop, you can also manually solve the captchas

**Comment by acheong08** [comment]
According to our [discord](https://discord.gg/RvBkdcYUrH) community, it is an issue with proxies. Please join the server and ask around the #中文 community

**Comment by thomashooo** [comment]
先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，第二次打开就不再打开了。并正确获取参数了。

**Comment by IIRtyj** [comment]
> 

还是不太行啊 关代理之后第二次打开浏览器上出红字，弹了好几遍浏览器窗口，刚验证成功 还没到登陆那步就关了

**Comment by ITerydh** [comment]
> 

i successed

**Comment by ITerydh** [comment]
> 先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

我成功了

**Comment by acheong08** [comment]
@ITerydh > 我成功了

How did you do it? Mind sharing?

怎么做到的？方便分享吗？

**Comment by ITerydh** [comment]
> How did you do it? Mind sharing?

As @thomashooo said above, manually verify and login the account when the browser is opened for the first time, and then close the VPN at the moment of entering openai

**Comment by ITerydh** [comment]
> @ITerydh > 我成功了
> 
> How did you do it? Mind sharing?
> 
> 怎么做到的？方便分享吗？

I can write a repo to your list? To show the use in China and Windows.

**Comment by acheong08** [comment]
> I can write a repo to your list? To show the use in China and Windows.

Yes please. I will put it up top so people can see

**Comment by ITerydh** [comment]
my repo is [https://github.com/AIGCT/EASYChatGPT](https://github.com/AIGCT/EASYChatGPT)

**Comment by acheong08** [comment]
@ITerydh Added

**Comment by acheong08** [comment]
Thanks for the help

**Comment by ITerydh** [comment]
> Thanks for the help

This library needs us to refuel together, haha, thanks for the help from your `revChatGPT`

**Comment by Hustcketlyj** [comment]
> 先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

老哥你太牛了 救我狗命

**Comment by RIP-GitHub** [comment]
> 先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

Success too，thanks！

**Comment by zwa73** [comment]
确实有用，不过似乎发送消息时又会尝试刷新对话，再次弹出浏览器界面，再循环这个过程
