### ISSUE TITLE
[BUG] cf challenge fail

### ISSUE THREAD

**Issue by guzy0324** [acheong08/ChatGPT#308]
**Describe the bug**

Get 403 even if it have successfully got the cf_cookies.

**To Reproduce**

my config.json:

```
{
    "session_token": "...",
    "proxy": "socks5://127.0.0.1:1080"
}
```

**Expected behavior**

**Output**

```
$ revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
cf challenge fail
Something went wrong! Please run with --debug to see the error.
cf challenge fail
```

**Environment (please complete the following information):**

 - OS: Linux
 - Python version: Python 3.10.8
 - ChatGPT Version: 0.0.42.2
 - OpenAI Version: 0.0.6

**Additional context**

**Comment by acheong08** [comment]
Remove the session token from the config and try to log in from the browser. I'm not sure whether the proxy had an effect

**Comment by guzy0324** [comment]
> I tried this, and it reported the same error.

**Comment by acheong08** [comment]
If this is a server, it might mean captcha was triggered

**Comment by acheong08** [comment]
If it's desktop, please try to complete the captcha

**Comment by guzy0324** [comment]
> If it's desktop, please try to complete the captcha
I had completed all the captcha and successfully logged in, but then the error was reported in the terminal.

**Comment by guzy0324** [comment]
> If it's desktop, please try to complete the captcha

After I successfully logged in, the browser kept refreshing, and finally the cf challenge failure was reported in the terminal.

**Comment by guzy0324** [comment]
> If it's desktop, please try to complete the captcha

This is the output in the terminal.

```
$ export all_proxy=socks5://127.0.0.1:1080/
$ revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
sMVYRKOV3qio1JIwfo0Pg1ozYR1p.ZDrfS0qOb8oArU-1670944284-0-1-eb2af81b.d1491455.bc2ba7fb-160
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
cf challenge fail
Something went wrong! Please run with --debug to see the error.
cf challenge fail
```

**Comment by MrNiebit** [comment]
My verification code has passed. Chrome will flash back and automatically retry

**Comment by acheong08** [comment]
Strange. it shows that it succeeded but still failed. I'll look into it

**Comment by acheong08** [comment]
According to the Chinese channel, this seems to be an issue with proxies.

Discussion: https://discord.gg/RvBkdcYUrH

**Comment by loveher147** [comment]
You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
December 14, 2022 - 00:44:48
Django version 3.2.5, using settings 'chatgpt.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Logging in...
Debugger enabled on OpenAIAuth
t2AZ5zCT3BFKdf6IBggdiVVsG5.fe9b5ee3.aed02665-160
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
cf challenge fail
