### ISSUE TITLE
TLS-based ChatGPT API Client

### ISSUE THREAD

**Issue by rawandahmad698** [acheong08/ChatGPT#31]
Hi, 

Great project. Thanks for open sourcing. Two days ago I created this and decided to open source it today since many people dm'ed me about it, The code creates & manages access_tokens for you without the whole browser overhead. It's open source

https://github.com/rawandahmad698/PyChatGPT

Can we get this added to the Awesome ChatGPT list? 
or maybe incorporate this into your own code, and remove the need for a user to F12 and manually get a token?

**Comment by acheong08** [comment]
Hello. Thank you for writing this. I have added it onto my list. Can you make a LICENSE file so I am legally allowed to reference it for use in my own code?

**Comment by rawandahmad698** [comment]
Yep sure, idk how I forgot that

**Comment by rawandahmad698** [comment]
Done

**Comment by acheong08** [comment]
Thank you so much. I've got a rudimentary auth system working with your code. Will push once stable

**Comment by acheong08** [comment]
Pushed. Unreleased due to lack of testing
