### ISSUE TITLE
Request to add my project to the AwesomeChatGPT List

### ISSUE THREAD

**Issue by cwyrwas** [acheong08/ChatGPT#314]
I've built a project which uses your ChatGPT module to automatically generate TikTok/Short Form Content videos. The user can specify a video topic, otherwise one will be randomly selected. The program then uses ChatGPT to generate a video script. 

The script's text is then converted to .mp3 via TTS. Images are automatically fetched from Unsplash. Then, using MoviePy - the program compiles everything together and renders a video. 

I've got some pretty interesting results out of it so far. It's definitely still a work in progress, and I'm not a Python dev. Most of my experience is with other languages, but I haven't encountered any issues so far. 

https://github.com/cwyrwas/ChatGPT-Content-Generator

**Comment by acheong08** [comment]
> I'm not a Python dev

Nor am I. I prefer Go. This API is just too unstable for Go though.

Added
