### ISSUE TITLE
New OpenAI account sign up automation

### ISSUE THREAD

**Issue by Innovation1201** [acheong08/ChatGPT#318]
Is there currently a way to automatically create a new account on openai with their API?

Would love it if I could get new users as part of the API.

Curious if you know of any workarounds

**Comment by manolol1** [comment]
I guess it would be pretty much impossible to automatically create new accounts, as you need a phone number and an e-mail address for registration.

**Comment by Robinfxa** [comment]
Unless you use "Cloud Receive SMS" and disposable emails to get the job done, this is often unsustainable unless you can find a better platform. (OpenAI also refuses to register its accounts with virtual cell phone numbers.)

**Comment by Coolboy263** [comment]
I have found a service which provide cloud sms service, i am really in need of openAi account sign up automation

**Comment by adi6409** [comment]
if you are willing to tell me which service you found, i'm more than happy to write the code that automatically creates the accounts.

**Comment by jramke** [comment]
i was also trying something like that so users dont need to provide the open api key. But i found this and wonder if its even legal 
[https://replit.com/bounties/@SamuelSmith68/automate-openai-acco?t=applications](https://replit.com/bounties/@SamuelSmith68/automate-openai-acco?t=applications)

**Comment by adi6409** [comment]
If you're seriously saying this then you really shouldn't use the reverse
proxys. It is legal, it just breaks the TOS.

**Comment by Coolboy263** [comment]
The service website is https://sms-man.com/ it has an api section https://sms-man.com/api which explains how to automatically buy sms and get the verification code (you can only receive one sms verification from openai on that number)

**Comment by acheong08** [comment]
I am personally using https://smspool.net/ to create my accounts. Worked so far but a bit expensive ($0.2 per account).

**Comment by acheong08** [comment]
I would recommend against making scripts like this publicly available as people from OpenAI have warned me that doing so could lead to a decrease/removal of free credits.

**Comment by Coolboy263** [comment]
What country did you choose to get to the price of 0.2$? I tried a lot of
countries but it only keep showing 0.6$-0.7$
