### ISSUE TITLE
[BUG] Error when logging in: "There is no current  loop in thread 'MainThread'"

### ISSUE THREAD

**Issue by M3cubo** [acheong08/ChatGPT#322]
**Describe the bug**
When using the command `revChatGPT`, it doesn't initiallize correctly, and an error is shown: `Error when logging in: "There is no current  loop in thread 'MainThread'"`

**Output**
![imagen](https://user-images.githubusercontent.com/1382596/207465320-47dc911d-3473-4108-b80b-072d61bc0dff.png)

**Environment (please complete the following information):**
NAME="Linux Mint"
VERSION="21 (Vanessa)"
`

**Additional context**
I have updated the values of _session_token_ and _cf_clearance_ and still not working. Also, have updated to this package:
![imagen](https://user-images.githubusercontent.com/1382596/207466190-de4a7e63-9391-490b-8497-591d2be30fe6.png)

**Comment by acheong08** [comment]
> I have updated the values of session_token and cf_clearance and still not working. Also, have updated to this package:

Delete `config.json` completely and update to the latest version. Without `config.json`, log in to the openai website via the popup chrome window.
