### ISSUE TITLE
[BUG]Exception: cf challenge fail

### ISSUE THREAD

**Issue by 7235201** [acheong08/ChatGPT#324]
raise Exception("cf challenge fail")
Exception: cf challenge fail

config = {
   
    "accept_language":"en-US,en"
    #"proxy": "<HTTP/HTTPS_PROXY>"

}

chatbot = Chatbot(config,True)

I delete session token ,then login the pop window,
same,
loop some time,
show error

**Comment by hbchen121** [comment]
I have same issue and then add `http://127.0.0.1:8000/` to config. It solved.

**Comment by loveher147** [comment]
> 

is  "http://127.0.0.1:8000/" your proxy ? thanks?

**Comment by acheong08** [comment]
先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

**Comment by loveher147** [comment]
> 如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

谢谢，原来你是中国人。谢谢大神。

**Comment by acheong08** [comment]
> 原来你是中国人

不是中国人，只是住在中国。

> 谢谢

不用谢。

**Comment by loveher147** [comment]
> 先开着代理，运行，等首次浏览器自动关闭了，立马关上代理，建议设置全局快捷键来按。如果顺利完成，浏览器第二次自动打开之后。就能并正确获取参数了。

在中国只有这一个方法哈？

**Comment by loveher147** [comment]
> > 在中国只有这一个方法哈？
> 
> 我用VPN就不用那么麻烦。

我也是用的vpn，12vpn会员。刚才试了一下，已经很快手速断开vpn了。您的意思是用vpn模拟到国外，就不会有这个问题吗？

**Comment by loveher147** [comment]
我到国外买一台服务器 会出现这样的问题么？

**Comment by acheong08** [comment]
> 我也是用的vpn，12vpn会员。刚才试了一下，已经很快手速断开vpn了。您的意思是用vpn模拟到国外，就不会有这个问题吗？

国内VPN不靠谱

> 我到国外买一台服务器 会出现这样的问题么？

我就是在DigitalOcean上住的一个服务器。有点贵（USD$5/月）
