### ISSUE TITLE
no actual meaning of async get_cf_cookies()

### ISSUE THREAD

**Issue by Harry-Jing** [acheong08/ChatGPT#325]
`get_cf_cookies()` only have internal use and use `async.run`. So it cannot await when calling.

Make `refresh_session()`  also awaitable will make `async get_cf_cookies()` more useful

**Comment by acheong08** [comment]
Got it. Do i have to override it in the standard Chatbot class and do asyncio.run for super().?

**Comment by acheong08** [comment]
Fixed in https://github.com/acheong08/ChatGPT/releases/tag/0.0.43.3
