### ISSUE TITLE
Redundant check in get_cf_cookies

### ISSUE THREAD

**Issue by gab-umich** [acheong08/ChatGPT#328]
Looks like this check leads to the same result either way.
https://github.com/acheong08/ChatGPT/blob/e11b7662d9f701015ff6bc00bd06bd471b9c9378/src/revChatGPT/revChatGPT.py#L370-L373

From what I can see this could be introduced by mistake in 6d78d039f58ec7c4ad1c165536a90031597833fa.

**Comment by acheong08** [comment]
Yup. It was a mistake. Fixing
