### ISSUE TITLE
[BUG] RuntimeWarning: coroutine 'AsyncChatbot.refresh_session' was never awaited

### ISSUE THREAD

**Issue by jackwu502** [acheong08/ChatGPT#329]
The following error occurred when the code ran to this line: chatbot = Chatbot(config, conversation_id=None)

**_"asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'AsyncChatbot.refresh_session' was never awaited_**

Does anyone know how to solve it? I have already upgraded revChatGPT to the latest version. Thanks.

**Comment by acheong08** [comment]
There are some bugs with the latest version. Try https://github.com/acheong08/ChatGPT/releases/tag/0.0.43.2

**Comment by acheong08** [comment]
(The latest pip version is 0.0.43.4)

**Comment by ngillespie1** [comment]
> There are some bugs with the latest version. Try https://github.com/acheong08/ChatGPT/releases/tag/0.0.43.2

Bug is contained within the latest version:

`C:\script\Media>"C:\python\3.7.9\python.exe" curated.py
Traceback (most recent call last):
  File "curated.py", line 19, in <module>
    chatbot = Chatbot({
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 480, in __init__
    debug, request_timeout, captcha_solver, base_url, max_rollbacks))
  File "C:\python\3.7.9\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\python\3.7.9\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 111, in __init__
    await self.refresh_session()
  File "C:\python\3.7.9\lib\site-packages\revChatGPT\revChatGPT.py", line 483, in refresh_session
    return asyncio.run(super().refresh_session())
  File "C:\python\3.7.9\lib\asyncio\runners.py", line 34, in run
    "asyncio.run() cannot be called from a running event loop")
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'AsyncChatbot.refresh_session' was never awaited

C:\script\Media>"C:\python\3.7.9\python.exe" -m pip show revchatgpt
Name: revChatGPT
Version: 0.0.43.4
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: c:\python\3.7.9\lib\site-packages
Requires: cf-clearance2, httpx, nest-asyncio, OpenAIAuth, playwright
Required-by:
`

**Comment by acheong08** [comment]
> Bug is contained within the latest version:

Yes. You have to downgrade `pip3 install revChatGPT==0.0.43.2`

**Comment by acheong08** [comment]
I am sorry.

**Comment by jackwu502** [comment]
Yes, I was using 0.0.43.4. After I downgrade it to 0.0.43.2, I run the code again. 

Then I got the following error: 

Traceback (most recent call last):
  File "try_gpt.py", line 37, in <module>
    response = chatbot.get_chat_response(question, output="text")
  File "/home/jack/anaconda3/envs/py_chatgpt/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 537, in get_chat_response
    asyncio.run(__async_func_for_check()) #Check if running in nest use of asyncio.run()
NameError: name '_Chatbot__async_func_for_check' is not defined

Do you know how to solve it? Thanks!

**Comment by ngillespie1** [comment]
> I am sorry.

Don't be silly I missed the downgrade requirement. Don't be sorry also you're doing gods work!

**Comment by acheong08** [comment]
> Yes, I was using 0.0.43.4. After I downgrade it to 0.0.43.2, I run the code again.
> 
> Then I got the following error:
> 
> Traceback (most recent call last): File "try_gpt.py", line 37, in response = chatbot.get_chat_response(question, output="text") File "/home/jack/anaconda3/envs/py_chatgpt/lib/python3.7/site-packages/revChatGPT/revChatGPT.py", line 537, in get_chat_response asyncio.run(__async_func_for_check()) #Check if running in nest use of asyncio.run() NameError: name '_Chatbot__async_func_for_check' is not defined
> 
> Do you know how to solve it? Thanks!

Seems to be an issue with it not finding pre-defined methods from the package. I am updating

**Comment by acheong08** [comment]
@jackwu502 Updated https://github.com/acheong08/ChatGPT/releases/tag/0.0.44
