### ISSUE TITLE
Error refreshing session {}

### ISSUE THREAD

**Issue by NiccoloSalvini** [acheong08/ChatGPT#33]
Hi,

I am writing a Telegram bot via `python-telegram-bot` to interact with ChatGPT. I have defined some env vars i.e. `CHATGPT_AUTH_KEY` (this I got from /beta) and `CHATGPT_SESSION_TOKEN` as the tutorial points out. This is the code:

```
# ChatGPT
chatgpt = Chatbot({"Authorization":ENVIRONMENT.CHATGPT_AUTH_KEY, "session_token": ENVIRONMENT.CHATGPT_SESSION_TOKEN}, conversation_id=None)
chatgpt.reset_chat()
```

However when I refresh the session `chatgpt.refresh_session()`I get:

```
Error refreshing session
{}
```

So I inspected the  `chatgpt.headers` and that gives:
```
{'Accept': 'application/json',
 'Authorization': 'Bearer sk-WpVb8p90gjkYwwglGlYyT3BlbkFJ6eRims************',
 'Content-Type': 'application/json'}
```

There's no 'session_token' in there. It looks `Chatbot` is not able to grab the `session_token` header and related value. I tried to supply also empty `Authorization` header to see if it was something related to passing configuration but in that case I got:

```
{'Accept': 'application/json',
 'Authorization': 'Bearer ',
 'Content-Type': 'application/json'}
```

I triend also to `chatgpt.refresh_headers` but that still does not fix the problem.

Do you have any suggestions?

**Comment by acheong08** [comment]
I just updated the code to allow email/password authentication. I'll look into this issue as well

**Comment by acheong08** [comment]
Do `pip3 install revChatGPT --upgrade` to update to the latest version

**Comment by NiccoloSalvini** [comment]
> I just updated the code to allow email/password authentication. I'll look into this issue as well

I tried with that:

```
config = {
    "email": ENVIRONMENT.OPENAI_MAIL,
    "password": ENVIRONMENT.OPENAI_PWD,
}
chatgpt = Chatbot(config, conversation_id=None)
```

and that says: `Not in config`



If I proceed further with `chatgpt.refresh_session()` I get:

```
Logging in...
Error refreshing session
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by acheong08** [comment]
> Not in config

This was just for debugging. Removed the print statement
