### ISSUE TITLE
[BUG] Exception: Failed to refresh session

### ISSUE THREAD

**Issue by RizkyNugroho666** [acheong08/ChatGPT#330]
**Im using the latest version 0.0.43**
**My code in responses.py**
from revChatGPT.revChatGPT import Chatbot
import os

SESSION_TOKEN = ""

config = {"Authorization": '<Auth>', "session_token": SESSION_TOKEN}

chatbot = Chatbot(config, conversation_id=None)
chatbot.refresh_session()

def handle_response(message) -> str:
    prompt = message
    response = chatbot.get_chat_response(prompt)
    responseMessage = response["message"]

    return responseMessage

**The error**
Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 333, in refresh_session
    raise Exception
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "f:/Project/Python/AJB Discord Bot/ai.py", line 2, in <module>
    import responses
  File "f:\Project\Python\AJB Discord Bot\responses.py", line 8, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 112, in __init__
    self.refresh_session()
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 353, in refresh_session
    raise Exception("Failed to refresh session") from exc
Exception: Failed to refresh session

**Comment by jackielics** [comment]
> **Im using the latest version 0.0.43** **My code in responses.py** from revChatGPT.revChatGPT import Chatbot import os
> 
> SESSION_TOKEN = ""
> 
> config = {"Authorization": '', "session_token": SESSION_TOKEN}
> 
> chatbot = Chatbot(config, conversation_id=None) chatbot.refresh_session()
> 
> def handle_response(message) -> str: prompt = message response = chatbot.get_chat_response(prompt) responseMessage = response["message"]
> 
> ```
> return responseMessage
> ```
> 
> **The error** Traceback (most recent call last): File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 333, in refresh_session raise Exception Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "f:/Project/Python/AJB Discord Bot/ai.py", line 2, in import responses File "f:\Project\Python\AJB Discord Bot\responses.py", line 8, in chatbot = Chatbot(config, conversation_id=None) File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 112, in **init** self.refresh_session() File "C:\Users\gamer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\revChatGPT\revChatGPT.py", line 353, in refresh_session raise Exception("Failed to refresh session") from exc Exception: Failed to refresh session

I've checked the official website. It seems like that there is no SESSON_TOKEN anymore.
![image](https://user-images.githubusercontent.com/55891169/207521825-51d699e7-2bba-4261-bc47-67a3214f5f14.png)

**Comment by RizkyNugroho666** [comment]
> > I've checked the official website. It seems like that there is no SESSON_TOKEN anymore.
> 
> Are you logged in?

After i logged in, browser closed . and it shows me this error

RuntimeError: There is no current event loop in thread 'MainThread'.
