### ISSUE TITLE
[BUG]Login with Google account rejected

### ISSUE THREAD

**Issue by Seventher** [acheong08/ChatGPT#334]
Google rejected me when I used my Google social media account for verification.

Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by acheong08** [comment]
Are you using a proxy? 

If not, it might be that Google is more advanced than cloudflare and can detect a controlled instance of Chrome. I will work towards supporting firefox as an alternative.

**Comment by wangqiusheng1983** [comment]
I am so too!
This browser reject!
how to chose firefox as an alternative?

**Comment by hfyydd** [comment]
firefox is the same. all browsers can't login

**Comment by SamuelChih** [comment]
![image](https://user-images.githubusercontent.com/30818360/207750373-7ea0f72d-75d5-47cf-901d-c2525dda86e8.png)
Got the same error here
