### ISSUE TITLE
Centos7.0 server can't work because of the unsupport of playwright?

### ISSUE THREAD

**Issue by YoungXu06** [acheong08/ChatGPT#338]
I can't work the project out in my centos7.0 server, because missing dependencies for playwright wouldn't be fixed with all efforts?

**Comment by luckcul** [comment]
It works . I can run the project in centos7 server

**Comment by YoungXu06** [comment]
> It works . I can run the project in centos7 server

你好，请问你有遇到这个错误：`Host system is missing dependencies to run browsers`，安装之后还是提醒的问题吗？怎么解决的？

**Comment by acheong08** [comment]
> 你好，请问你有遇到这个错误：Host system is missing dependencies to run browsers，安装之后还是提醒的问题吗？怎么解决的？

少了Desktop environment.搜索Xvfb

**Comment by YoungXu06** [comment]
> 

@acheong08 安装Xvfb后还是有同样的报错，安装了那三个缺失依赖后也还是会提示同样的错误
![企业微信截图_16710120497667](https://user-images.githubusercontent.com/14051806/207565297-ef690d12-3b50-4093-b21d-128ada7e15fb.png)

**Comment by acheong08** [comment]
`sudo apt install libatk-bridge2.0-0`
`sudo apt install libatspi2.0-`
`sudo apt install libxkbcommon0`

**Comment by YoungXu06** [comment]
> 

centos我通过`yum -y install libatk-bridge-2.0.so.0 libatspi.so.0 libxkbcommon.so.0` 安装了，截图里面有。意思是yum install不可以？

**Comment by acheong08** [comment]
名字应该错了。没有`.so`。更apt一样我猜想

**Comment by YoungXu06** [comment]
> 网上搜一搜

嗯，换了一台机器，用这个[issue](https://github.com/microsoft/playwright-python/issues/498#issuecomment-778889124)的方案解决了依赖报错的问题。

**Comment by ZRHann** [comment]
请问一下
```
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝

```
是需要执行xvfb-run命令吗？<your-playwright-app>需要填什么？搜索没找到答案。

**Comment by ZRHann** [comment]
> 请问一下
> 
> ```
> ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
> ║ Looks like you launched a headed browser without having a XServer running.                     ║
> ║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
> ║                                                                                                ║
> ║ <3 Playwright Team                                                                             ║
> ╚════════════════════════════════════════════════════════════════════════════════════════════════╝
> ```
> 
> 是需要执行xvfb-run命令吗？`<your-playwright-app>`需要填什么？搜索没找到答案。

已解决，直接`xvfb-run python3 test.py`
