### ISSUE TITLE
[BUG] it keeps asking me to log in

### ISSUE THREAD

**Issue by RizkyNugroho666** [acheong08/ChatGPT#341]
it works, but everytime i start the program, it opens the Chromium and open the chatgpt login page, i logged in manually, and then the browser closed automatically and sent me the AI's output, but if i start the program again, it asking me to log in manually again, my default browser is Chrome

**Comment by pvanallen** [comment]
I see the same thing - this is on macOS 13.0.1. I could not find a way to install Xvfb on Mac to avoid the browser login every time I run the test python program. It works fine when I login with Chromium, but unfortunately I have to put in Capcha and credentials every time.

**Comment by acheong08** [comment]
> it works, but everytime i start the program, it opens the Chromium and open the chatgpt login page, i logged in manually, and then the browser closed automatically and sent me the AI's output, but if i start the program again, it asking me to log in manually again, my default browser is Chrome

Yes. Every time you restart the program, you must log in via Chromium. This is due to both playwright's limitations as well as the Cloudflare protections. We are currently unable to log in automatically via email/password.

**Comment by acheong08** [comment]
> I see the same thing - this is on macOS 13.0.1. I could not find a way to install Xvfb on Mac to avoid the browser login every time I run the test python program. It works fine when I login with Chromium, but unfortunately I have to put in Capcha and credentials every time.

You can dump the session token from `chatbot.config['session_token']` when you log in and load it from a json or dict next time you start the program to prevent having to log in.

**Comment by pvanallen** [comment]
@acheong08 thanks, that worked! I still see Chromium go by, but no need to put in credentials, etc.

**Comment by acheong08** [comment]
> @acheong08 thanks, that worked! I still see Chromium go by, but no need to put in credentials, etc.

The Chromium is for the cloudflare bypass. I hope to remove it once a full bypass can be written. The solutions found so far are too expensive for an open source project.

**Comment by pvanallen** [comment]
I understand. It's okay for now though. I don't mind the Chromium thing.
