### ISSUE TITLE
[BUG]Chromium windows closes before having chance to login

### ISSUE THREAD

**Issue by beaver316** [acheong08/ChatGPT#345]
**Describe the bug**
When I run the command "python -m revChatGPT --debug" to start the app, a Chromium window opens and performs the checks which succeed. I then momentarily see the Login button but the window closes immediately and I cannot login. The terminal looks like this:

```
Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
srNj9_D2Z.OpZc1tY7TJAGwye38OWCY1opT8evFkg2I-1671017246-0-1-706e89cf.10a57ea3.319277a9-160
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Empty response
Probably invalid session token
Something went wrong! Please run with --debug to see the error.
Failed to refresh session
```

 - OS: Windows
 - Python version: 3.11.1
 - ChatGPT Version: 0.0.44
 - OpenAI Version: 0.0.6

**Comment by acheong08** [comment]
Delete `config.json` and don't make a `config.json`. Log in from the browser. Don't use session token.

**Comment by beaver316** [comment]
That did the trick. Thank you
