### ISSUE TITLE
Mac m1 lxml not compiled 

### ISSUE THREAD

**Issue by abd-als** [acheong08/ChatGPT#348]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: greenlet, playwright, httpcore, httpx, cf-clearance2, revChatGPT
  Running setup.py install for greenlet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for greenlet did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      running install
      /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-310
      creating build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      creating build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      creating build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_version.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_gc.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/leakcheck.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_generator.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_greenlet_trash.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_throw.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      running egg_info
      writing src/greenlet.egg-info/PKG-INFO
      writing dependency_links to src/greenlet.egg-info/dependency_links.txt
      writing requirements to src/greenlet.egg-info/requires.txt
      writing top-level names to src/greenlet.egg-info/top_level.txt
      reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching 'benchmarks/*.json'
      no previously-included directories found matching 'docs/_build'
      warning: no files found matching '*.py' under directory 'appveyor'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '.coverage' found anywhere in distribution
      adding license file 'LICENSE'
      adding license file 'LICENSE.PSF'
      adding license file 'AUTHORS'
      writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
      copying src/greenlet/greenlet.cpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_allocator.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_compiler_compat.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_cpython_compat.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_exceptions.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_greenlet.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_internal.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_refs.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_slp_switch.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_thread_state.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_thread_state_dict_cleanup.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/greenlet_thread_support.hpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/slp_platformselect.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet
      copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_arm64_masm.asm -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_arm64_masm.obj -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_arm64_msvc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/platform
      copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-11.0-arm64-cpython-310/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.macosx-11.0-arm64-cpython-310
      creating build/temp.macosx-11.0-arm64-cpython-310/src
      creating build/temp.macosx-11.0-arm64-cpython-310/src/greenlet
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -I/opt/homebrew/Caskroom/miniforge/base/include/python3.10 -c src/greenlet/greenlet.cpp -o build/temp.macosx-11.0-arm64-cpython-310/src/greenlet/greenlet.o --std=gnu++11
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> greenlet

**Comment by acheong08** [comment]
> greenlet

This is not a dependency of this project. It might be from elsewhere
