### ISSUE TITLE
MacOS: got 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by TccccD** [acheong08/ChatGPT#35]
When I use
`from revChatGPT.revChatGPT import Chatbot`
there is an error: 
`139 (interrupted by signal 11: SIGSEGV)`

@acheong08

**Comment by lafroujianas** [comment]
I have python 3.10.8, having the same issue : Segmentation fault: 11
OS : Macos catalina

**Comment by acheong08** [comment]
Data streaming might not work with MacOS.

I just updated the code again. `pip3 install revChatGPT --upgrade`

It is probably an issue with data streams. Streaming is now optional with `--stream`

Running normally should work now

**Comment by acheong08** [comment]
@TccccD @lafroujianas Could you test this?

**Comment by lafroujianas** [comment]
Still getting "Segmentation fault: 11" on macos catalina

**Comment by acheong08** [comment]
What python version?

**Comment by acheong08** [comment]
I don't use MacOS so I can't really replicate. You can try using gbd to debug

**Comment by lafroujianas** [comment]
Python 3.10.8

**Comment by acheong08** [comment]
I have no idea why this is happening. Might need feedback from more MacOS users. I have not used any advanced Python, only basic requests, json, and bs4. Can you show the full output? Does it crash immediately or is there a certain point at which it crashes?

**Comment by lafroujianas** [comment]
<img width="422" alt="Screenshot 2022-12-05 at 17 37 47" src="https://user-images.githubusercontent.com/20706509/205692349-0077388d-5f8b-48d4-a810-a5403c12d730.png">

**Comment by lafroujianas** [comment]
I think the issue is from : in revChatGPT.py import tls_client

If I remove the line, the code is executed (with error), with with node Segmentation fault

**Comment by rawandahmad698** [comment]
I'm on MacOS, and I have Python 3.6 to 3.11, Code works ok. This is not an issue with tls_client, but a misconfiguration in your system which makes tls_client fail.

**Comment by acheong08** [comment]
https://stackoverflow.com/questions/49414841/process-finished-with-exit-code-139-interrupted-by-signal-11-sigsegv

**Comment by acheong08** [comment]
Arm and 32bit are not supported yet. https://github.com/FlorianREGAZ/Python-Tls-Client/issues

You must use session tokens if you're on one of these platforms

**Comment by Adrianczuk** [comment]
> I have python 3.10.8, having the same issue : Segmentation fault: 11 OS : Macos catalina

I was experiencing the same issue; updating from Catalina to Big Sur resolved it for me.

**Comment by emileindik** [comment]
Upgrading from Mac OS Catalina solved it for me.

**Comment by pen-ho** [comment]
Upgrading from Mac OS Catalina solved it for me. +1

**Comment by xs-fj** [comment]
same error on my ubuntu 20; ...

**Comment by acheong08** [comment]
@xs-fj You might be using 32bit Python

**Comment by longnight** [comment]
/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

Same errors; run in 64bit ubuntu 20 ...

**Comment by papachef08** [comment]
tls-client uses closed soured libs from anywhere (tls-client-x86.dylib). As we don't know, where this lib comes from and what is does, this is a real security issue. Remember: you provide this source with username and password or even with access tokens. (Maybe the source sends it to somewhere ... ;-)
