### ISSUE TITLE
[BUG] Config.json location

### ISSUE THREAD

**Issue by Jamisonfitz** [acheong08/ChatGPT#351]
Where should the config.json be placed?

I've tried several locations, I'd assume "C:\Users\USER\AppData\Roaming\Python\Python311\site-packages\revChatGPT" but placing it there still returns no config upon launch.

**Comment by acheong08** [comment]
You don't need a `config.json` if you can log in via the browser. If you do need it for some reason, put it in your working directory. That tends to be at `C:\Users\USER\`

**Comment by Jamisonfitz** [comment]
> You don't need a `config.json` if you can log in via the browser. If you do need it for some reason, put it in your working directory. That tends to be at `C:\Users\USER\`

That worked perfectly, thank you!

**Comment by merrychrishna** [comment]
that didnt work for me but im using mysys2 for windows 10. how can i figure this out? i want to override the session token please.

**Comment by acheong08** [comment]
There were a lot of changes since this issue was opened. Read https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by merrychrishna** [comment]
I read that bits it's not clear. It does t even show the path of where to
put the config file and the -h help menu doesn't show what parameter to use
if we want to use Hotmail email and pass instead.

**Comment by acheong08** [comment]
It was quite clear that the configuration should be in the "current working directory" which tends to be `~` for Linux

**Comment by merrychrishna** [comment]
its not clear enough. nowhere on the page does it say to put the
config.json in the current working directory. and i have pasted all
optional parameters in the config file and have put in my hotmail email and
password and set ishotmail to true and verbose to true and have opened my
chrome browser but its still asking for a session token.  [image: image.png]

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/215306612-453e090c-105b-4e10-98f9-a5d699a7f0ec.png)

**Comment by acheong08** [comment]
Remove parts of the config that are optional

**Comment by acheong08** [comment]
and the conversation id, diver exec path, etc should all also be removed

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/215339559-12d3e1de-ac0c-4a5f-9ce9-1e35fff1fbd6.png)
![image](https://user-images.githubusercontent.com/59185469/215339590-783eb1bd-6c2e-4ae2-a8fa-251f2a7fda17.png)


its still not working. theres only an option for sessoin token in chatgpt-lite.

**Comment by acheong08** [comment]
Ah you're in the wrong repo

**Comment by acheong08** [comment]
ChatGPT lite is here: https://github.com/acheong08/ChatGPT-lite

**Comment by merrychrishna** [comment]
i dont think so. i followed your instructions from your like you just postsed. 
![image](https://user-images.githubusercontent.com/59185469/215364702-60c7026e-4d82-4821-929c-496ff5c18f10.png)

**Comment by merrychrishna** [comment]
why did you close the thread? you didnt fix my issue.

**Comment by acheong08** [comment]
Because you are using ChatGPT-lite. Open an issue there

**Comment by acheong08** [comment]
And the issue here is also that you are using a placeholder for the session token. You need to get the actual session token from the cookies on chat.openai.com
