### ISSUE TITLE
[BUG]cf challenge fail & Failed to refresh session

### ISSUE THREAD

**Issue by Ant0082** [acheong08/ChatGPT#352]
**Describe the bug**
run cmd with "xvfb-run python -m revChatGPT --debug --text" get error: cf challenge fail & Failed to refresh session

**To Reproduce**
run cmd:
xvfb-run python -m revChatGPT --debug --text

**Output**
```cmd
(glm_env) [root@VM-0-71-centos ChatGPT]# xvfb-run python -m revChatGPT --debug --text

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging

Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
cf challenge fail
Something went wrong! Please run with --debug to see the error.
cf challenge fail
```

**Environment (please complete the following information):**
 - OS: [CentOS 7.0]
 - Python version: `Python 3.8.15`
 - ChatGPT Version: `0.0.44`
 - OpenAI Version: `0.0.6`

**Comment by Ant0082** [comment]
attach config.json

{
  "session_token":"xxxxx"
}

**Comment by skippyyy** [comment]
If cf challenge is failing consistently then get a proxy (preferably a clean one).
if you have tried several proxies, even residential, and you are still failing the cf challenge then change the browser's user-agent.
As for the failed to refresh session token then from time to time you need to manually get a new one so just login manually using your browser and fetch the token and insert it in the config.json file.

**Comment by Ant0082** [comment]
1. where to get a proxy? 
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
{
      "proxy":"http://127.0.0.1:7890"
}
Is this the way to fill in?
2. Can you give a sample config.json file?
