### ISSUE TITLE
How to run headless mode ?

### ISSUE THREAD

**Issue by fire17** [acheong08/ChatGPT#353]
Can anyone please share how to start revChatGPT in headless mode ,
im running in wsl2 , followed the installation docs
but havn't seen how to run in headless mode

id hope there's a flag somewhere for this and i wont have to manually edit playwrite installation to run headlessly
thanks !

**Comment by fire17** [comment]
I'm trying to use 
 ```
Xvfb :1 -screen 0 1024x768x24
```
but i still cant manage to use revChatGPT either the tool nor using it in python
![image](https://user-images.githubusercontent.com/9356048/207650195-47caacfb-16cc-482d-a821-bbfd2b839176.png)
![image](https://user-images.githubusercontent.com/9356048/207650394-9758ad2a-f2bb-4686-a0af-9a40feec3ea8.png)

**Comment by skippyyy** [comment]
What works for me is that I open a new GNU screen session using `screen -S <name>` , and inside the screen I just run `xvfb-run python3 index.py`, works like a charm.

**Comment by fire17** [comment]
![image](https://user-images.githubusercontent.com/9356048/207682570-2b0c2f26-5642-48d4-b847-feb63f99a978.png)
__Secure-next-auth.session-token seems to be changing all the time, maybe thats the problem??

anyhow im still not able to run this, can you recommend how to reinstall everything from scratch maybe ?
thanks for the quick response !! :D

**Comment by skippyyy** [comment]
It seems like the script does run with xvfb, the error you are seeing is related to the revChatGPT CLI, try and run it with `--debug` arg like it says so you can check what the error specifically is.
Also, yes, the session-token is being invalidated quite frequently, maybe once or twice a day.
At the moment, there is no implementation to automate login, so you have to import the cookies into the config.json file manually.

No worries :)

**Comment by anribras** [comment]
Make sure you have Xvfb installed : 
```sh
Xvfb :99 -ac 2>/dev/null & 
export DISPLAY=:99 
```
