### ISSUE TITLE
[BUG]Will all of your code work? After I manually log in gpt, I will exit, and keep opening the browser to log in. The picture shown below is displayed.

### ISSUE THREAD

**Issue by qinjinghue** [acheong08/ChatGPT#354]
<img width="1039" alt="ChatGpT is at" src="https://user-images.githubusercontent.com/54343900/207648800-f9a6be4f-1694-450f-9cd1-f05db0a7ec4f.png">

**Comment by acheong08** [comment]
ChatGPT is experiencing high load. it will take a while for it to become functional again. This is a server issue and not related to this repo

**Comment by acheong08** [comment]
The login page is down

**Comment by acheong08** [comment]
You must wait

**Comment by qinjinghue** [comment]
> 
The problem was that when I logged in successfully, I would automatically exit and keep opening chrome

**Comment by acheong08** [comment]
If you're in China:
连接代理后运行，等待首次浏览器自动关闭后，立即关闭代理，建议设置全局代理运行。如果顺利完成，等待浏览器第二次自动打开后。将会正确获取到参数。

**Comment by qinjinghue** [comment]
> If you're in China: 连接代理后运行，等待首次浏览器自动关闭后，立即关闭代理，建议设置全局代理运行。如果顺利完成，等待浏览器第二次自动打开后。将会正确获取到参数。

I see. I'll have a try

**Comment by qinjinghue** [comment]
> If you're in China:
> 
> 连接代理后运行，等待首次浏览器自动关闭后，立即关闭代理，建议设置全局代理运行。如果顺利完成，等待浏览器第二次自动打开后。将会正确获取到参数。


我按照你的方法试了下。还是出现上面的图片。应该是被识别到机器人了？我可以走到这一步![image](https://user-images.githubusercontent.com/54343900/207656615-4bb1f5c5-1cfc-48f6-918f-ec6631fc708f.jpeg)

**Comment by qinjinghue** [comment]
第一个窗口登陆成功的一瞬间，我去关闭了代理。命令窗口输入问题。仍然没有正常工作，但是也没有一直打开chrome了。为了解决这个问题，我在config.json中配了我的代理。貌似也不行。![image](https://user-images.githubusercontent.com/54343900/207661095-3eae6071-17fc-4b6b-9bbc-ef53ee9ca197.jpeg)然后我又恢复了配置文件。再次运行卡住了![image](https://user-images.githubusercontent.com/54343900/207661339-1f4a8d27-4b29-47f3-a7ae-53b377c7be43.jpeg)我打算明天人少的时候再试一试。
