### ISSUE TITLE
how to solve it

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#358]
![image](https://user-images.githubusercontent.com/86822589/207755571-3640523a-34db-41ec-a993-7d60cfaa1b8c.png)

**Comment by zjrwtx** [comment]
I used the proxy, and I closed the proxy as soon as I logged in for the first time, but still

**Comment by Glowin** [comment]
可能的原因是你的IP被 cloudflare 给拉黑了。
The possible reason is that your IP was blocked by cloudflare.
