### ISSUE TITLE
Exception: Error when handling response, got valuesil":"Too many requests in 1 hour. Try again later."

### ISSUE THREAD

**Issue by MichaelCaohn** [acheong08/ChatGPT#362]
I am trying to run the following code for testing: (I am using the latest version of revChatGPT and running it on the desktop (not server))

```
from revChatGPT.revChatGPT import Chatbot

config = {
    "session_token": "my_session_token",
    #"proxy": "<HTTP/HTTPS_PROXY>"
}
response = chatbot.get_chat_response("Hello world", output="stream")
for res in response:
    print(res['message'])
    print("==================")
```
It returns me the following error:
```
File ~/miniconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py:531, in __get_chat_stream(self, data)
    522 def get_chat_response(self, prompt: str, output="text", conversation_id=None, parent_id=None) -> dict or None:
    523     """
    524     Get the chat response.
    525 
    526     :param prompt: The message sent to the chatbot
    527     :type prompt: :obj:`str`
    528 
    529     :param output: The output type `text` or `stream`
    530     :type output: :obj:`str`, optional
--> 531 
    532     :return: The chat response `{"message": "Returned messages", "conversation_id": "conversation ID", "parent_id": "parent ID"}` or None
    533     :rtype: :obj:`dict` or :obj:`None`
    534     """
    535     try:
    536         # Check if running in nest use of asyncio.run()
    537         asyncio.run(self.__async_func_for_check())

Exception: Error when handling response, got valuesil":"Too many requests in 1 hour. Try again later."
```
It seems I have sent too many requests, however, I haven't sent any requests in recent 1 hour. I also have tried manually type in some prompt, the ChatGPT website can show me some result:
![image](https://user-images.githubusercontent.com/22003919/207775508-59f50da9-c4d9-400a-9cd0-50d973ab7745.png)

Can anyone help to see what's wrong with it?

**Comment by acheong08** [comment]
I'm getting this error on the website as well. Might be something to do with IP addresses and hyperactive cloudflare.

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/207776353-c44f4159-e740-415a-abf6-b434e142d86c.png)

**Comment by acheong08** [comment]
I switched VPN and now it works

**Comment by MichaelCaohn** [comment]
Thank you very much for the reply.

From my side, everything is normal on the website. 
![image](https://user-images.githubusercontent.com/22003919/207777760-f3420a12-e81d-4099-a59b-428bc200e44b.png)

However, my program always return me this error. "Exception: Error when handling response, got valuesil":"Too many requests in 1 hour. Try again later.""
```
from revChatGPT.revChatGPT import Chatbot

config = {
    "session_token": "my_session_token",
    #"proxy": "<HTTP/HTTPS_PROXY>"
}
response = chatbot.get_chat_response("Hello world", output="stream")
for res in response:
    print(res['message'])
    print("==================")
```

Is there anything wrong with the code I wrote?

**Comment by Ukenn2112** [comment]
I have the same problem, it works fine in the first conversation, but when I do the next conversation it reports an error
But on the website it's all normal

**Comment by acheong08** [comment]
Most people are getting this error. The entire project might have to be scrapped. I will work on a complete workaround next week via a completely different method of interacting with the API. I will likely archive this project and begin working on the other method shortly. I don't think I can fix this issue. (It has something to do with TLS fingerprinting which is programmatically impossible in Python as a language)
