### ISSUE TITLE
[Question]  How is the GO server/api used with this python library?

### ISSUE THREAD

**Issue by mgpai22** [acheong08/ChatGPT#365]
Do we at all need to run our own go api?

**Comment by acheong08** [comment]
It's not used at all. It is a completely different project

**Comment by mgpai22** [comment]
What are the benefits of the GO api?

**Comment by acheong08** [comment]
You can pool a ton of accounts and cycle through them. Account rate limits are less of a problem

**Comment by mgpai22** [comment]
Ahh I see, is there an easy way to used it with your python lib?

**Comment by acheong08** [comment]
Not yet. I will make a separate python lib for it.
