### ISSUE TITLE
Not sure if a bug or just me [BUG]

### ISSUE THREAD

**Issue by amFarrouk** [acheong08/ChatGPT#366]
first of all this is really amazing, second  "session_token": "<token>", this is my api key or what exactly ? i tried my api key but receiving this "TypeError: expected str, bytes or os.PathLike object, not NoneType"

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by amFarrouk** [comment]
i'm really sorry i should have seen that thnx 🙏🙏
