### ISSUE TITLE
[BUG] Doesn't work with Cyrillic

### ISSUE THREAD

**Issue by Bainky** [acheong08/ChatGPT#369]
**Describe the bug**

When you try to send questions written in Russian, they knock out an error.
```
Traceback (most recent call last):
  File "E:\Documents\Projects\gpt.py", line 1993, in <module>
    response = chatbot.ask(text, conversation_id=None, parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\ChatGPT.py", line 50, in ask
    response = self.session.post(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 369, in post
    return self.execute_request(method="POST", url=url, data=data, json=json, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 326, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

Input: "как узнать дату с помощью python?"
Version 0.0.46

**Comment by acheong08** [comment]
This seems to be a bug with Golang for one of our dependencies. The full set of unicode isn't fully supported with their standard library.

**Comment by DeakosS** [comment]
I encountered the same problem and solved it by changing the timeout_seconds in the sessions.py, because I need to generate a relatively long text.
`def execute_request(
        self,
        method: str,
        url: str,
        params: Optional[dict] = None,  # Optional[dict[str, str]]
        data: Optional[Union[str, dict]] = None,
        headers: Optional[dict] = None,  # Optional[dict[str, str]]
        cookies: Optional[dict] = None,  # Optional[dict[str, str]]
        json: Optional[dict] = None,  # Optional[dict]
        allow_redirects: Optional[bool] = False,
        insecure_skip_verify: Optional[bool] = False,
        timeout_seconds: Optional[int] = 300,  **# THE VAULE OF THIS OPTIONAL SHOULD BE LONGER**
        proxy: Optional[dict] = None  # Optional[dict[str, str]]
    ):`

**Comment by acheong08** [comment]
I might need to fork TLS-client to fix this

**Comment by acheong08** [comment]
I got a fork of the TLS client with the tweaks. I will be publishing it soon (my internet connection is slow so it's taking a while to upload)

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/0.0.47.1
