### ISSUE TITLE
[BUG] undetected_chromedriver not updating clearance

### ISSUE THREAD

**Issue by pengfan7758258** [acheong08/ChatGPT#370]
<img width="847" alt="1" src="https://user-images.githubusercontent.com/62168810/209632175-f7c9bd35-089d-4d8d-9910-b92bca1ad652.png">

**Comment by acheong08** [comment]
What version?

Also, venv breaks undetected_chromedriver sometimes. Other than that, the headers seem to be unable to update. I will work on better design to prevent such edge cases

**Comment by pengfan7758258** [comment]
<img width="649" alt="1" src="https://user-images.githubusercontent.com/62168810/209634261-75c9a4e9-73f7-4ed3-b74f-8f6aef8d2cfa.png">
Is there any good way to solve the current situation? Or provide your version?

**Comment by acheong08** [comment]
It works normally for me. I am optimizing the system now so hopefully it works for you sson

**Comment by acheong08** [comment]
I have just made a lot of fixes in the logic. It should work on the latest release now

**Comment by acheong08** [comment]
I think the issue is the same as https://github.com/acheong08/ChatGPT/issues/377
