### ISSUE TITLE
[BUG] Client.Timeout or context cancellation while reading body

### ISSUE THREAD

**Issue by elhombrejd** [acheong08/ChatGPT#372]
After a while and connecting 4 out of 5 times (1 of those having a closed connection), I ended up with the following error:

tls_client.exceptions.TLSClientExeption: net/http: request canceled (Client.Timeout or context cancellation while reading body)

ChatGPT receives the question and initiates the context but I can't seem to find also an answer on the actual app too.

Maybe the connection is being closed too soon?

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/369

`pip3 install --upgrade revChatGPT`. If this doesn't fix it, then it could be something wrong on OpenAI's side

**Comment by elhombrejd** [comment]
It fixed indeed.

But funny enough, I had a fresh install yesterday so I had updated everything. But TLS indeed updated when I forced it.

Thanks.
