### ISSUE TITLE
[BUG]If you open chrome multiple times after filling in the token, it cannot be used

### ISSUE THREAD

**Issue by MuBai-He** [acheong08/ChatGPT#375]

**Comment by MuBai-He** [comment]
I use pychatgpt and it works fine

**Comment by acheong08** [comment]
I think it could be an IDE issue which prevents the driver from connecting to the chrome port. Try running outside an env

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/377

Might be proxy
