### ISSUE TITLE
Telegram bot with Markdown support

### ISSUE THREAD

**Issue by n3d1117** [acheong08/ChatGPT#38]
Hi!

Awesome work on the `revChatGPT` package! I created a Telegram bot using `python-telegram-bot` based on your work. I have included credits in the project's README file, and I wanted to make sure you were aware of the project.

The bot includes markdown support and automatically refreshes the session when an error is encountered. You can check it out here: https://github.com/n3d1117/chatgpt-telegram-bot

Thanks again!

**Comment by acheong08** [comment]
> The bot includes markdown support and automatically refreshes the session when an error is encountered

This is amazing. Do you mind adding a LICENSE file so I may legally reference it to implement my own session error checking?

Added to list.

**Comment by n3d1117** [comment]
Thanks! 
> Do you mind adding a LICENSE file so I may legally reference it to implement my own session error checking?

Absolutely! There's a [GPL-2.0 license](https://github.com/n3d1117/chatgpt-telegram-bot/blob/main/LICENSE) license already, does that work for you?

**Comment by n3d1117** [comment]
> I have been using it for a few days and I must say, it is absolutely amazing. Thank you for your work!

Thank you @acheong08 and for your amazing work on this library!
Just added a pretty cool feature, live answer updating as the bot types, using stream response 😄
