### ISSUE TITLE
机器人返回的信息会有缺失的情况

### ISSUE THREAD

**Issue by x7peeps** [acheong08/ChatGPT#388]
看源码有config 里有      - --max-line-length=80  

但是我在调用的时候
```
from revChatGPT.ChatGPT import Chatbot
```
不知道如何调整这个参数，现在机器人返回的信息会有缺失的情况

**Comment by acheong08** [comment]
> 看源码有config 里有 - --max-line-length=80

这是 IDE config。不是这个library
