### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pannet1** [acheong08/ChatGPT#389]
`
revChatGPT --debug          
        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        Run with --debug to enable debugging
        
Type '!help' to show commands
Press enter twice to submit your question.

Debugging enabled.
Logging in...
Debugger enabled on OpenAIAuth
Something went wrong! Please run with --debug to see the error.
asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'AsyncChatbot.refresh_session' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

`

**Comment by acheong08** [comment]
You haven't updated.
`pip3 install --upgrade revChatGPT`

**Comment by pannet1** [comment]
that was very fast @acheong08 awesome.
