### ISSUE TITLE
[BUG]Infinite loop after successful login (Proxy issues)

### ISSUE THREAD

**Issue by wwb306** [acheong08/ChatGPT#390]
**Describe the bug**
After the corresponding configuration and successful operation, it shows that the login is successful, but after that, the browser is opened and closed continuously
![image](https://user-images.githubusercontent.com/16029451/209941826-993a0876-6f0d-470b-a26b-1a8cf57defd3.png)

**Comment by acheong08** [comment]
Are you using a proxy?

**Comment by wwb306** [comment]
Yes, but even if I remove the proxy, the result is the same as before

**Comment by acheong08** [comment]
If you're in China, there are issues with both proxy and no proxy. You probably need a global VPN.

**Comment by oscarklv** [comment]
I met the same condition. Infinite loop after successful login
How to use  https://vpn.fail/

**Comment by acheong08** [comment]
You can either use WireGuard or OpenVPN. I'm sure there are online tutorials for that.

**Comment by acheong08** [comment]
It could also be https://github.com/acheong08/ChatGPT/issues/385. Closing in favor of that one and tracking things there.
