### ISSUE TITLE
[BUG] Linux Headless Chrome

### ISSUE THREAD

**Issue by xsa-dev** [acheong08/ChatGPT#392]
**Infinity bug with cloudfire check**
I start using ChatGPT and had loop on this messages:
```
xsa@ununtu:/home/chatgpt-tg# python3 -m revChatGPT --debug

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Waiting for captcha to be solved...
Captcha solved successfully!
Spawning browser...
Spawning browser...
Browser spawned.
```

**To Reproduce**
1. python3 -m revChatGPT --debug

**Expected behavior**
Login successful and ChatGPT ready to interact with me 

**Output**
In the correct directory, run `python3 -m revChatGPT --debug`

**Environment (please complete the following information):**

Please update your packages before reporting! `pip3 install --upgrade OpenAIAuth revChatGPT`
 - OS: Linux
 - Python version: `python3.10`
 - ChatGPT Version: 
```
Name: revChatGPT
Version: 0.0.48.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: 2captcha-python, selenium, tls-client-for-chatGPT, undetected-chromedriver
Required-by: 
```
 - OpenAI Version: `pip3 show OpenAIAuth`
```
Name: OpenAIAuth
Version: 0.0.6
Summary: OpenAI Authentication Reverse Engineered
Home-page: https://github.com/acheong08/OpenAIAuth
Author: Rawand Ahmed Shaswar and Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: tls-client
Required-by: 
```

**Additional context**
Freeze on this 
<img width="1104" alt="Screenshot 2022-12-29 at 19 28 06" src="https://user-images.githubusercontent.com/16959353/209981784-a53e3ccc-874a-4797-b555-3341fb436a04.png">

**Comment by acheong08** [comment]
Headless doesn't work 100% of the time. It is recommended to be headful or with Xvfb. You must solve cloudflare captcha manually for now.
