### ISSUE TITLE
 the response is incompleted sometimes

### ISSUE THREAD

**Issue by x7peeps** [acheong08/ChatGPT#393]
i finished configuration and the chatgpt working good , but i found the response is incompleted sometimes, the i try to find the solution 
1. i trace to the ask(), then i found it used execute_request() function to do request then i try to change timeout_seconds arg to 1000sec ,expect to get more lines response , but still limited.
2.  then i try to find out if the webpage the same question responsed limited, yes, it is , but i traced the request ,i found it will faultly send the request uri to server ```conversations?offset=0&limit=20``` , i wounder the limit is the key to solve , and 
 
my quest is how to solve the limit of the response ? any solution?

**Comment by acheong08** [comment]
There is no solution. OpenAI blocks long requests. You can let them continue by sending "continue" which lets ChatGPT continue from the last word.

**Comment by x7peeps** [comment]
> There is no solution. OpenAI blocks long requests. You can let them continue by sending "continue" which lets ChatGPT continue from the last word.

it is an acceptable solution ,thx

**Comment by x7peeps** [comment]
close
