### ISSUE TITLE
Community Request: Detailed Windows tutorial (by acheong08)

### ISSUE THREAD

**Issue by SamuelXGMM** [acheong08/ChatGPT#397]

**Comment by acheong08** [comment]
I don't have Windows. Gonna need some community members to help me out here

**Comment by IJoseph23** [comment]
> I don't have Windows. Gonna need some community members to help me out here

Have you ever heard of Parallels if you have Mac or VirtualBox if you have Linux?

**Comment by acheong08** [comment]
I do have a virtual machine but my computer isn't powerful enough to keep it functional. It takes around 10 minutes to boot and freezes every few seconds. Even optimal performance is at around 5s/frame. I would rather not attempt debugging in that environment, especially with the need to load up selenium and occasionally solve captcha.

(I've tried but the browser took forever to open and I kept failing Cloudflare's captcha)

**Comment by elmiedo** [comment]
> _No description provided._

Step 1: Run WSL service
Step 2: RTFM4Linux

**Comment by SamuelXGMM** [comment]
alright anyone atleast tell me how will i be able to access the unfiltered content without breaking tos

**Comment by acheong08** [comment]
> alright anyone atleast tell me how will i be able to access the unfiltered content without breaking tos

Might as well use InstructGPT (pretty much the same thing but without "I am an AI assistent" bs)

**Comment by SamuelXGMM** [comment]
i will let you know where it worked or not with wsl or maybe ill do it in virtual machine with linux

**Comment by SamuelXGMM** [comment]
and close this issue asap after it works and sorry for bad english i dont speak english
