### ISSUE TITLE
[BUG]can''t get CloudFare automatically

### ISSUE THREAD

**Issue by gnohgnailoug** [acheong08/ChatGPT#400]
**Describe the bug**
Hello acheong08. There is a promblem happening. when I try to start a conversation by this code "chatbot = Chatbot(config, conversation_id=None, parent_id=None) ", the program will start a new browser window. But the window will stay at this page (like the image below)and the program can't get the CloudFare automatically. No bugs happen in this process. I'll appreciate it if  you can help me.
![image](https://user-images.githubusercontent.com/69443774/210159131-4e859720-3057-4e93-8a71-6e6149e92880.png)

**Comment by acheong08** [comment]
Show command line log

**Comment by gnohgnailoug** [comment]
> t

thanks to your reply. Do you mean this?
![image](https://user-images.githubusercontent.com/69443774/210159223-35eb1953-8758-4d4d-9322-b3326ad23fdb.png)

**Comment by acheong08** [comment]
Yes. It seems it failed to connect to the driver. Not quite sure why. Any additional context?

**Comment by gnohgnailoug** [comment]
> Yes. It seems it failed to connect to the driver. Not quite sure why. Any additional context?

Hello. When this problem happens, I just follow the configuration steps you mentione in this repo to relogin my account. But this problem still exist. I think there's no invalid operation in the process of logining.

**Comment by acheong08** [comment]
Check out https://github.com/acheong08/ChatGPT-lite. It solves all the annoying browser problems at the cost of your privacy

**Comment by gnohgnailoug** [comment]
> Check out https://github.com/acheong08/ChatGPT-lite. It solves all the annoying browser problems at the cost of your privacy

Thanks. I find this problem was solved after I restart my computer. Thanks again, this repo is really helpful :).

**Comment by XinzheShen182** [comment]
I tried both Email and token. The access api/auth/session is 403, and then refresh constantly
![image](https://user-images.githubusercontent.com/60874308/211253422-3741f761-6c17-4608-b25f-9022a63a8000.png)

**Comment by acheong08** [comment]
https://github.com/FlorianREGAZ/Python-Tls-Client/issues/26

Could be this
