### ISSUE TITLE
error unkown help needed[BUG]

### ISSUE THREAD

**Issue by SamuelXGMM** [acheong08/ChatGPT#401]
python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

No config file found.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 114, in <module>
    main()
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 110, in main
    chatGPT_main(configure())
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 39, in configure
    raise Exception("No config file found.")
Exception: No config file found.

**Comment by SamuelXGMM** [comment]
afther using this command python3 -m revChatGPT it show me the above error

**Comment by SamuelXGMM** [comment]
and instructions needed please from her on afther that command what need to do or waht am i supposed to do to get unfiltered content

**Comment by SamuelXGMM** [comment]
and oh how to do this you said i did all 34 steps but 5th i dont know how to do that at all
5.Paste it into config.json in the current working directory

**Comment by SamuelXGMM** [comment]
python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 114, in <module>
    main()
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 110, in main
    chatGPT_main(configure())
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 36, in configure
    config = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 2501)

**Comment by acheong08** [comment]
Your config file is invalid. Improper JSON format

**Comment by SamuelXGMM** [comment]
i dont know what but i just created and put it somewhere

**Comment by SamuelXGMM** [comment]
can you please provide instruction if possible

**Comment by SamuelXGMM** [comment]
sorry if i asked you but i really dont know what im doing

**Comment by acheong08** [comment]
In config.json
```json
{
	"session_token": "<session token here>"
}
```

**Comment by SamuelXGMM** [comment]
and where is that config file supposed to be idk

**Comment by SamuelXGMM** [comment]
i have the token copied

**Comment by acheong08** [comment]
> and where is that config file supposed to be idk

Whatever your current working directory is

**Comment by acheong08** [comment]
Or any of these directories: https://github.com/acheong08/ChatGPT/pull/211

**Comment by SamuelXGMM** [comment]
really sorry dude i dont know what is the current direactory mean  can yiou please provide me a example for path cause i really am sorry im very new to linux and all and this is my first time using linux

**Comment by acheong08** [comment]
`~/` is the default cwd for linux

**Comment by SamuelXGMM** [comment]
wait let me check

**Comment by SamuelXGMM** [comment]
and what needs to be in that config.json file

**Comment by acheong08** [comment]
Either your session token or email/password/2captcha. Check wiki

**Comment by SamuelXGMM** [comment]
let me do that and ill tell you how it went and oh doi i need to include "<>" or just do clear everything in "paste here the token"

**Comment by acheong08** [comment]
yes just paste the token. no <>

**Comment by SamuelXGMM** [comment]
alright ill tell you how it went in a  min

**Comment by SamuelXGMM** [comment]
it says 
python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 114, in <module>
    main()
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 110, in main
    chatGPT_main(configure())
  File "/home/samuel/.local/lib/python3.10/site-packages/revChatGPT/__main__.py", line 36, in configure
    config = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 2501)

**Comment by SamuelXGMM** [comment]
and after using sudo command for revchatgpt it says
/usr/bin/python3: No module named revChatGPT

**Comment by acheong08** [comment]
No sudo

**Comment by acheong08** [comment]
And the config is invalid again

**Comment by SamuelXGMM** [comment]
wait let me send you the example of config i did

**Comment by SamuelXGMM** [comment]
this is just an example 

{ "session_token": "session token here" }

{
  "email": "email",
  "password": "password",
  "captcha": "2captcha token here"
}

**Comment by acheong08** [comment]
You only need one of those

**Comment by SamuelXGMM** [comment]
you mean only token would be enough?

**Comment by acheong08** [comment]
Yes

**Comment by SamuelXGMM** [comment]
now i need to chat in terminal?

**Comment by acheong08** [comment]
If you want? That is just the demo. It's meant for building bots and stuff

**Comment by SamuelXGMM** [comment]
then how can i access unfiltered chat?

**Comment by acheong08** [comment]
It is unfiltered but the model still censored. You might be looking for InstructGPT

**Comment by SamuelXGMM** [comment]
its says you in terminal i said hey and never responded back to me

**Comment by SamuelXGMM** [comment]
but you said in the reddit post it did all the nsfw stuff

**Comment by SamuelXGMM** [comment]
you said it chatted nsfw works in reddit post

**Comment by acheong08** [comment]
It works. Requires specific prompting

**Comment by SamuelXGMM** [comment]
what kind of prompting and oh i say this and no response back

python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!

You:
hey 

it just stuck there 

any solution?

**Comment by acheong08** [comment]
Prompting example: https://github.com/acheong08/ChatGPT/issues/10#issuecomment-1336429259

**Comment by SamuelXGMM** [comment]
and thank you so much for being so patient with me and why it got stuck there

**Comment by acheong08** [comment]
> it just stuck there


Slow internet?

**Comment by SamuelXGMM** [comment]
no its very speed 500mbps

**Comment by acheong08** [comment]
Might be something wrong with OpenAI. It freezing there means it is not responding. Wait a bit, it might load

**Comment by SamuelXGMM** [comment]
alright ill let y'know what happened it like 5 minutes

**Comment by SamuelXGMM** [comment]
still stuck and if it for windows where do i need to store the config.json file

**Comment by SamuelXGMM** [comment]
i got it working windows too but still stuck why? no response back

**Comment by SamuelXGMM** [comment]
it works when i says nothing but if i says something it gets stuck why?

**Comment by SamuelXGMM** [comment]
see

$ python3 -m revChatGPT

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!

You:

Chatbot: 

Hello! How can I help you today?

You:
Chatbot: 
I'm here to assist you with any questions or problems you might have. Is there anything specific you would like to know or discuss?

You:
are you?

**Comment by SamuelXGMM** [comment]
if i click enter without saying anything it works but if i says something it just stuck right there

**Comment by SamuelXGMM** [comment]
oh shit sorry it works i have to double click to send the request sorry and thank you so very much for being patient with me and take-care.
