### ISSUE TITLE
Failed to Refresh Session

### ISSUE THREAD

**Issue by easyssss** [acheong08/ChatGPT#403]
Upon using the "python3 -m revChatGPT" command I get the following response:
Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Failed to refresh session!
Failed to refresh session!
Failed to refresh session!

With the "failed to refresh session!" repeating infinitely. 

**Output**
--debug results in the same output

**Comment by PortRoyale** [comment]
I am getting the same. Although, it is my first time using this.

**Comment by Jamminroot** [comment]
Yup, started to see this, as well. Probably a new CF protection I've seen on my other app

**Comment by acheong08** [comment]
Happening occasionally for me as well. Not sure what the exact cause is as it is inconsistent.

**Comment by mediacutlet** [comment]
+1 happening consistently for me today after 3 days of uptime without issue. Have tried clearing browser cache and re-initiating the session several times.

**Comment by randyzhao** [comment]
Seeing this too. Has anyone solved this problem?

**Comment by DiamondDemon669** [comment]
Hmm I think I know whats causing this. the session refresh call generates a new session token and expires the previous one, but its hard to grab the real session token since the website constantly refreshes the token. If the session token is not real, it cant refresh the token

**Comment by acheong08** [comment]
I think you might need to close the site the moment you get your session token to prevent it from refreshing outside of revChatGPT

**Comment by mixand** [comment]
Seeing this too. Has anyone solved this problem?

**Comment by mediacutlet** [comment]
@acheong08 I tried what you suggested a few times, the moment I see "cookie found" I close the browser and the issue persists. Good thought though. Have you had success with this strategy? Is it perhaps just precise timing?

**Comment by acheong08** [comment]
It very rarely happens to me and trying a few times usually gets things working. The reason I haven't fixed this is because I have no way of debugging something that only happens to myself 1% of the time.

**Comment by acheong08** [comment]
I really need some help with debugging cases where I can't replicate

**Comment by Jamminroot** [comment]
Sure, I'm interested in helping you sort this out, just let me know what kind of info you'd need. Started to happen to me 100% of times a few days ago

**Comment by mediacutlet** [comment]
Not sure how helpful this is @acheong08 but here is a screencapture of my experience: https://mediacutlet.com/git/132023.mp4

**Comment by acheong08** [comment]
> Not sure how helpful this is @acheong08 but here is a screencapture of my experience: [mediacutlet.com/git/132023.mp4](https://mediacutlet.com/git/132023.mp4)

Why are you trying to log in manually? Do not click the buttons. If you want to log in, you must use `config.json` to specify your email and password

**Comment by acheong08** [comment]
> Sure, I'm interested in helping you sort this out, just let me know what kind of info you'd need. Started to happen to me 100% of times a few days ago

Can you tweak the code to show response codes and response text?

**Comment by acheong08** [comment]
Need to know if it's a cloudflare 403 or OpenAI 404 or something else entirely

**Comment by acheong08** [comment]
Google is not supported at the moment. If you try to use Google, everything will fail. You can use session tokens instead which you can obtain if you are logged in via Google. Check the https://github.com/acheong08/ChatGPT/wiki/Setup for instructions on how to get that

**Comment by acheong08** [comment]
It seems that the issue here is that you did not provide a session token

**Comment by mediacutlet** [comment]
> Google is not supported at the moment. If you try to use Google, everything will fail. You can use session tokens instead which you can obtain if you are logged in via Google. Check the https://github.com/acheong08/ChatGPT/wiki/Setup for instructions on how to get that

This is how I have it set up. Perhaps the token expired an I need to generate a new one manually?

**Comment by acheong08** [comment]
Yes. You have to update the session token every now and then

**Comment by mediacutlet** [comment]
> Yes. You have to update the session token every now and then

Got it. Makes sense. Hope this helps others as well. Thanks for your work on this!!

**Comment by Jamminroot** [comment]
Still waiting for the refresh thing to happen

**Comment by Jamminroot** [comment]
Not sure what's going on. Im not getting anywhere:
```
[2023-01-03 15:09:48,259] WARNING        {connectionpool.py:812}                Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecfc3ed870>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/90c7f1d037c40ef347fca60faeb9f68d/se/log
```

I'll come back here with an update later today when I figure this out.

**Comment by Jamminroot** [comment]
It appears that in my case the issue was that I tried to run multiple instances of ChatGPTrev clients (2). Both of those were via session_tokens. If I only run one at a time, it seem to work

**Comment by mediacutlet** [comment]
Manually updating my session token in config.json fixed my issue.

**Comment by lijiazheng99** [comment]
The same error happened to me. Obtaining a session token from Chrome's incognito window fixed it.

**Comment by fsnaix** [comment]
I'm running it using an email + password config with 2captcha and for me, the session token failed to refresh after a day of running it constantly

**Comment by acheong08** [comment]
That is currently a flaw. I need to check for outdated tokens and log in again via status codes. Anyone know the status code or expired tokens?

**Comment by acheong08** [comment]
It should be a simple matter of
```py
if response.status_code == <status code>:
	self.refresh_cf_clearance()
```
something like that

**Comment by rebelzion** [comment]
> Google is not supported at the moment. If you try to use Google, everything will fail. You can use session tokens instead which you can obtain if you are logged in via Google. Check the https://github.com/acheong08/ChatGPT/wiki/Setup for instructions on how to get that

At first I also got the error `Failed to refresh session!` but after following the Setup carefully, ie. passing the correct `session_token` it worked for me.

**Comment by easyssss** [comment]
> Obtaining a session token from Chrome's incognito window fixed it.

Same here

**Comment by jordantkohn** [comment]
I was getting the same error. Then checked my session token which had changed since I first pasted it in. Updated that and it worked for me!

**Comment by QingShan-123** [comment]
> I'm running it using an email + password config with 2captcha and for me, the session token failed to refresh after a day of running it constantly

Could you guys tell me what should I fill in the filed of 2captcha？ It seems to be a simple question but not for me. Thank you guys

**Comment by Jamminroot** [comment]
You asked to answer if it's working for me, @QingShan-123, yes, it does.
For me to fix the issue I had to update the session token I grabbed from the browser. After that the problem was gone.
As for the 2captcha - I believe it's for 2captcha API key (paid service to solve captchas for you); Also, correct me if im wrong, I think you wouldn't need that with session_token mode

**Comment by QingShan-123** [comment]
> You asked to answer if it's working for me, @QingShan-123, yes, it does. For me to fix the issue I had to update the session token I grabbed from the browser. After that the problem was gone. As for the 2captcha - I believe it's for 2captcha API key (paid service to solve captchas for you); Also, correct me if im wrong, I think you wouldn't need that with session_token mode

Thank you for replying me! I am using the session token mode, but I encountered a problem, the program infinite loop "Failed to refresh session", so I try some other modes to make it work, but I failed!

**Comment by Jamminroot** [comment]
Try logging to your account normally with the browser and grab a session token again

**Comment by SeolhwaLee** [comment]
> Yes. You have to update the session token every now and then

I solved this problem by updating the session-token. I thought the session-token is the same all the time.

**Comment by classic-sasquatch-behavior** [comment]
in my case, I was first of all not using the correct session token, and secondly I was clicking stuff on the browser when it popped up

**Comment by acheong08** [comment]
> in my case, I was first of all not using the correct session token, and secondly I was clicking stuff in the browser when it popped up. just wait instead of clicking buttons when it opens

Yeah. Clicking things tend to mess stuff up
