### ISSUE TITLE
I have a project WebChat. Can I join your list?

### ISSUE THREAD

**Issue by hbchen121** [acheong08/ChatGPT#404]
intro: A web chatbot (WebChat) that uses the chatGPT api in your project.

my repo ad:

https://github.com/hbchen121/WebChat

In addition, I wrote a [tutorial](https://github.com/hbchen121/WebChat/tree/master/bots/chatGPT) to record how to build an environment on the server to use your api.

**Comment by acheong08** [comment]
Cool. Added
