### ISSUE TITLE
Lacks information about Py-Script

### ISSUE THREAD

**Issue by AdityaMohnot** [acheong08/ChatGPT#416]
**Is your feature request related to a problem? Please describe.**
You may not know about the recently developed and released Python Web Development Technology called Py-Script. Though it may sound self-explanatory I will still proceed to give a short descript on this Py-Script. It is basically Python code in an html file allowing us to use Python like JavaScript. You can learn how to use this technology from The official website, pyscript.net or from tutorials on Youtube.  Py-Scriot is still in it's early stages as it only came out in May 2022 and hence the website itself recommends not to use it for production. They request some time to improve this technology to the level where it can be used for production asit has many bud right now. The reason I am telling you all this is because when I used chatGPT to enquire on py-script it apparently did not have any information on this. Py-Script might become a widely used technology in the future and even if it doesn't I believe that chatGPT should still hold some information about it.

**Describe the solution you'd like**
I believe that it datasets need to be updated with this piece of information. I strongly suggest that chatGPT should hold some information on this Py-Script too.

**Comment by acheong08** [comment]
Not my problem. Contact @OpenAI
