### ISSUE TITLE
can you add proxy for request ? 

### ISSUE THREAD

**Issue by spotify2junkie** [acheong08/ChatGPT#42]
Hi Great project and awesome work, by any chance you can add proxy for request,just like we can pass in 
```
config = {
    "email": "xxx",
    "password": "",
    "https": ""
}
```
for request.

Thx again

**Comment by rawandahmad698** [comment]
Hi, this is already supported, proxies are directly passed to the `OpenAIAuth` class. 
be sure to pass `use_proxy=True` and `proxy="your_proxy" on the class

Read 
https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py#L128

**Comment by acheong08** [comment]
I will make this simpler and built into the Chatbot class later today

**Comment by pepi99** [comment]
> I will make this simpler and built into the Chatbot class later today

Eagerly waiting! :)

**Comment by Harry-Jing** [comment]
> I will make this simpler and built into the Chatbot class later today

thanks! This app is not available in my country, so a proxy support is important to me

**Comment by acheong08** [comment]
Added proxy support:
```json
config = {
    "email": "xxx",
    "password": "",
    "proxy": ""
}
```
Untested. Needs testing

**Comment by acheong08** [comment]
@Harry-Jing @rawandahmad698 It's a simple pass through and it should work. I don't have a proxy to test with. Mind trying it out? (On the latest commit)

**Comment by rawandahmad698** [comment]
Sure i'll report back here

**Comment by elboble** [comment]
> 

yes, the proxy section do the job
