### ISSUE TITLE
How to open a new conversation each time?

### ISSUE THREAD

**Issue by MichaelCaohn** [acheong08/ChatGPT#421]
Hi,

I have seen your code 
`response = chatbot.ask("Prompt", conversation_id=None, parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)
`
which states that the conversations are automatically saved when specifying conversation_id=None, and parent_id=None.

However, I would like to open a new conversation each time. How could I achieve this goal?

Thank you every much

**Comment by QingShan-123** [comment]
Hello，could you please let me know if you are able to use the program normally now? I am encountering the issue of "Failed to refresh session."
![image](https://user-images.githubusercontent.com/122095522/211018419-a862ba3a-87a1-4817-93e1-b5d28d4013a3.png)

**Comment by Jamminroot** [comment]
It's `chatbot.reset_chat()`

**Comment by MichaelCaohn** [comment]
Thank you very much, it solves me problem:)

**Comment by MichaelCaohn** [comment]
> Hello，could you please let me know if you are able to use the program normally now? I am encountering the issue of "Failed to refresh session." ![image](https://user-images.githubusercontent.com/122095522/211018419-a862ba3a-87a1-4817-93e1-b5d28d4013a3.png)

Hi, I can use the program normally.

**Comment by acheong08** [comment]
Fixed by https://github.com/acheong08/ChatGPT/releases/tag/0.1.1
