### ISSUE TITLE
revChatGPT forgot my conversation and created a new chat. How do I specify a previous conversation? [BUG]

### ISSUE THREAD

**Issue by Andy7737** [acheong08/ChatGPT#425]
I got rate limited and tried to get a new session-token. I am now able to use the API again, but it now creates a "New Chat" on launch. How do I specify a previous conversation so that I can continue the chat?

**Comment by xkat420** [comment]
I'm having the same issue, ill ask chatGPT if he can fix it lol.

**Comment by acheong08** [comment]
You will need to store conversation_id and parent_id somehow.

**Comment by acheong08** [comment]
This can't be done on the CLI. You have to program your own interface

**Comment by Andy7737** [comment]
Can't you specify the conversation_id and parent_id in the config.json? How do I find the correct IDs in the browser?

**Comment by acheong08** [comment]
I'm not sure if you can. A few new functions have been added to fetch conversations and history from the program but I haven't tested them out yet

**Comment by Andy7737** [comment]
The URL has a code for every chat with a bunch of numbers and letters. 
Like this:
https://chat.openai.com/chat/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
Is that relevant to conversation_id or parent_id in any way?

**Comment by ffernn-dev** [comment]
Hey I'd really like to know if there's a way to do this. It seems like it should be as simple as finding the conversation_id, but I don't know where to start with that.

**Comment by acheong08** [comment]
New feature was added a few releases back that allowed you to specify conversation_id and it would find the parent_id automatically

**Comment by acheong08** [comment]
You can go to you browser and copy the conversation_id from the URL

**Comment by ffernn-dev** [comment]
Alright I'm calling the bot with `Chatbot(config, conversation_id="f17e247d-1f2b-4c2c-938c-9ec16d55e5ce")` but still getting `{"detail":"Something went wrong, please try reloading the conversation."}`. Looking at previous issues it seems like this has to do with the parent_id being wrong but you said it should work it out automatically?

**Comment by ffernn-dev** [comment]
Alright I'm calling the bot with `Chatbot(config, conversation_id="xxxxxxxx-1f2b-4c2c-938c-9ec16d55e5ce")` but still getting `{"detail":"Something went wrong, please try reloading the conversation."}`. Looking at previous issues it seems like this has to do with the parent_id being wrong but you said it should work it out automatically?
