### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'tls_client_for_chatGPT'

### ISSUE THREAD

**Issue by saifalimz** [acheong08/ChatGPT#428]
To fix this, 

Change this line
From --> import tls_client_for_chatGPT as tls_client
To --> import tls_client
File --> ChatGPT.py

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/0.0.49.1

**Comment by acheong08** [comment]
Forgot about it when I updated the dependency
