### ISSUE TITLE
[BUG] Cyrrilic prompt cause tls_client.exceptions.TLSClientExeption: net/http: request canceled (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by DaveScream** [acheong08/ChatGPT#433]
**Describe the bug**
If use cyrrilic symbols in prompt, it appears on web version, but fail to get response.
![изображение](https://user-images.githubusercontent.com/3002276/211173932-94c1005a-4068-4be1-9f7d-ce9f1443d7a7.png)

`
Traceback (most recent call last):
  File "f:\Projects\SharikAI\my_revChatGPT.py", line 30, in <module>
    response = chatbot.ask(ask_text)
  File "f:\Projects\SharikAI\.venv\lib\site-packages\revChatGPT\ChatGPT.py", line 112, in ask 
    response = self.session.post(
  File "f:\Projects\SharikAI\.venv\lib\site-packages\tls_client\sessions.py", line 389, in post
    return self.execute_request(method="POST", url=url, data=data, json=json, **kwargs)       
  File "f:\Projects\SharikAI\.venv\lib\site-packages\tls_client\sessions.py", line 346, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: net/http: request canceled (Client.Timeout or context cancellation while reading body)
`

English works fine.

 - OS: Windows
 - Python version: 3.10
 - ChatGPT Version: latest

In browser developer mode. Cyrrilic payload works fine. Headers and payload looks same as in revChatGPT. But I cant see actual codepage because browser decode it for me.

**Comment by DaveScream** [comment]
found solution.
Project Uses https://pypi.org/project/tls-client/0.1.4/ and maintainer mention that "The syntax is inspired by [requests](https://github.com/psf/requests), so its very similar and there are only very few things that are different."

requests doc https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts
requests.get('https://github.com/', timeout=0.001)

so need to update sessions.py   line 335  and specify timeout:

`response = request(dumps(request_payload).encode('utf-8'), **timeout=timeout_seconds**)`

**Comment by Jamminroot** [comment]
Nice, had that a couple times today

**Comment by acheong08** [comment]
I think I do specify it. Not sure if the tls_client handles it correctly though
https://github.com/acheong08/ChatGPT/blob/fcd995acb9e3629ebc3883dac5f04a098d551daa/src/revChatGPT/ChatGPT.py#L112-L116

**Comment by Jamminroot** [comment]
Just tried with and without a fix - both do work atm

**Comment by Jamminroot** [comment]
It actually happens with both (with change suggested by OP and unchanged version), given the request is bit more complex than "Hello". Example:

`Сочини мне смешное стихотворение про кофе`.

Funny finding is that it seems to work if I disable timout with (`timeout_seconds = 0`).

A possible workaround (not necessarily valid, lol) is to inherit Session class and override `execute_request` so that it disables a timeout.
I suppose that the error happens bc of CF.

Corrections are welcome)

**Comment by Jamminroot** [comment]
That problem would basically happen with any request which would take more than 30s to handle.
I found a working reliable fix for it, just trying to understand it now

**Comment by Jamminroot** [comment]
As in: it wouldn't matter if its cyrillic, as far as I can see

**Comment by acheong08** [comment]
Merged
