### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by Nick-kel** [acheong08/ChatGPT#435]
What are the rate limits? Can multiple questions be asked synchronously?

**Comment by Jamminroot** [comment]
Would like to know answer to first question, too.
As for the second - definitely not (not from the same account), as It seem to be a limitation of ChatGPT itself. 
For my app (tg bot, with 2 accounts as requests handlers), with not too many users, I've made a hard-coded ratelimit of 30 sec for entire api bots and 2 min per user. Along with only serving a single request per user, that seems to be enough in my case

**Comment by Andy7737** [comment]
Rate limit of ~50 requests according to the dev in a different issue thread.

**Comment by Andy7737** [comment]
Rate limit of ~50 requests according to the dev in a different issue thread.

**Comment by Jamminroot** [comment]
I ran through the thread, I assume that limit is per-hour?

**Comment by Andy7737** [comment]
Yes, I believe so.

**Comment by SeolhwaLee** [comment]
I got this error, so which means they limited 50 queries per-hour?  

```
{"detail":{"message":"Rate limit reached for chat-gpt-48rpm-200ktpm in organization org-q1REn59xBJ4cdaluoPxVSFAU on requests per min. Limit: 48.000000 / min. Current: 50.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://beta.openai.com/account/billing to add a payment method.","type":"requests","param":null,"code":null}}
```

**Comment by Jamminroot** [comment]
From the response I think its safe to assume that limits are 48 requests **per minute** and there's a limit to length of requests per minute - `200ktpm`, I believe its 200k tokens per minute

**Comment by Jamminroot** [comment]
Tbh I'm a bit confused with the response. On one hand - it says `chat-gpt-...`, but on the other - It looks more like a limit for paid openai API

**Comment by acheong08** [comment]
It's a sign that OpenAI is probably working on a paid API

**Comment by Andy7737** [comment]
> Limit: 48.000000 / min
This suggests that the API limit might not be ~50 per hour but rather 48 per minute. At least that it is the limit that was hit here.

That's a lot of request though. Is this multiple users using the API via an app?

This line is not new though:
"Please add a payment method to your account to increase your rate limit. Visit https://beta.openai.com/account/billing to add a payment method."

I have seen reverences to this error in browser from people on the r/ChatGPT reddit several weeks back. This is a placeholder error for now, since there is no way of paying for a premium plan.

**Comment by Jamminroot** [comment]
It's hard for me to believe it's 48/minute, as you can't process 2 requests at a time, and even some plain requests like "Hi" would take a few seconds to process, so one account can barely produce 30/minute at very best, not even accounting harder ones which would take more than a minute.
I suppose that the message is some kind of a placeholder or WIP on OpenAI side (as suggested by acheon08)
