### ISSUE TITLE
Timeout - http: request canceled 

### ISSUE THREAD

**Issue by pleshkov631** [acheong08/ChatGPT#439]
Hi! Thank you for this wonderful tool.

I'm trying to get a long response, asking something like "write essay about cars for 1000 words"
And I'm getting exception Something went wrong!
`net/http: request canceled (Client.Timeout or context cancellation while reading body)`

How to increase timeout value? 
P.S. If I want to get shorter response it is working good ("write essay about cars for 100 words" is OK).

**Comment by acheong08** [comment]
Have you updated? It should have been fixed with https://github.com/acheong08/ChatGPT/pull/436

**Comment by pleshkov631** [comment]
Yes, it is ok, thanks!
