### ISSUE TITLE
[BUG] - Chromedriver bug: Cloudflare cookie not found

### ISSUE THREAD

**Issue by kreeyateee** [acheong08/ChatGPT#445]
i've had this running before. i am using the cookie, and have updated it.

gets upt o "Browser Spawned" and then seems to just do nothing. 

browser window showing the login screen.

**Comment by acheong08** [comment]
It's meant to close automatically. If it doesn't, it could be a chromedriver issue

**Comment by kreeyateee** [comment]
Any thoughts on troubleshooting this further? I had this working fine last
week.

**Comment by acheong08** [comment]
Check https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc if someone else has the same issue. You can add some print statements everywhere to log where exactly it gets stuck

**Comment by kreeyateee** [comment]
It doesn't display the found cloudflare cookie, basically just opens the
browser then sits there.

I'll have a crack at that in a bit and see what happens. It's odd as it
worked last week.

**Comment by moerv9** [comment]
It worked locally for me, but when deploying it on a Ubuntu Server it's also stuck at "Browser spawned." Sept and it seems to be stuck at 
`self.get_cf_cookies()` in line 472 in ChatGPT.py

I've added `option.add_argument("--headless")` to the Chrome Options but it didn't help...

<img width="932" alt="Screenshot 2023-01-10 at 14 27 40" src="https://user-images.githubusercontent.com/81798308/211566312-297add75-0081-40d0-ae3a-fd1eb658f0aa.png">

**Comment by acheong08** [comment]
It might be stuck on captcha by Cloudflare. Can't solve that automatically yet

**Comment by acheong08** [comment]
`--headless` doesn't work due to cloudflare

**Comment by acheong08** [comment]
Do you have xvfb installed?

**Comment by moerv9** [comment]
Yes. Without xvfb I could not even get above the _"Browser spawned!"_ stage.

I basically followed this: 
`
Install the X Virtual Framebuffer display server
    apt install xvfb -y
Set DISPLAY environmental variable to :1
    export DISPLAY=:1
Start a Xvfb process in the background
    Xvfb $DISPLAY -screen $DISPLAY 1280x1024x16 &`

**Comment by InquestGeronimo** [comment]
yea get the same bug, locally it works fine but via server it hangs at "Browser Spawned" stage.

**Comment by DanBmh** [comment]
> * Start a Xvfb process in the background
>   `Xvfb $DISPLAY -screen $DISPLAY 1280x1024x16 &`

For me this always failed with: `Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)` (in a newly created docker container). 

I could solve this by using a different display number (like `export DISPLAY=:123`)
