### ISSUE TITLE
[Question] Request after a long idle

### ISSUE THREAD

**Issue by Jamminroot** [acheong08/ChatGPT#446]
Hey!

It seems that having api wrapper I made for the library fails to process requests after a long idle period (5+ hours).

I was wondering if refreshing session is my responsibility? I have my wrapper for ChatGPT, which reads its config and handles few other things, and, when requested, forwards call to `ask()` of the library.
Should I add a background task to refresh a session - for example, every hour or so? Or should It be handled by the library? Iirc there's a `refresh_session()` call on every `ask()` call

**Comment by acheong08** [comment]
You can create a thread to handle session refresh and run it every hour. It could cause some problems if threading is used in the core library

**Comment by Jamminroot** [comment]
I meant the "uptime" :)

**Comment by acheong08** [comment]
Cloudflare doesn't track that

**Comment by Jamminroot** [comment]
Oh, didn't know that. Great, thanks a lot, and have a nice day o/
