### ISSUE TITLE
Can not login 

### ISSUE THREAD

**Issue by js19950276** [acheong08/ChatGPT#451]
I used two methods to login in 

* use session_token
![image](https://user-images.githubusercontent.com/45511344/211731136-b14ff96a-105b-47c0-8c2b-6ff77c1bdf44.png)
but when the chrome start login the openai , the browser will exit.

* use Microsoft 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/45511344/211731919-6a35e9cf-2d2f-4d11-a2f1-c37f8e2c3415.png">
everytime I use Microsoft to login , it will ask me to keep this login status. And the code will not work.

**If there are any way to login, please tell me, thx**

- macos 13.1
- python version 3.9
- revChatGPT version 0.1.1

**Comment by Troylee-rpi** [comment]
We are in the same situation ! Found cloudflare cookies, then the browser will be closed and no response can be obtained. Hope acheong08 can help us fix it. (probably bypass the cloudflare is needed)

**Comment by acheong08** [comment]
Are you guys in China? It could be a 1020 error (IP banned)

**Comment by acheong08** [comment]
Try modifying the code to print the HTTP status

**Comment by Troylee-rpi** [comment]
> Try modifying the code to print the HTTP status

Thanks for your reply! I used the proxy to avoid 1020 error. By the way,  I could run perfectly with your chatgpt-lite a few days ago.

**Comment by js19950276** [comment]
> Try modifying the code to print the HTTP status

**Comment by acheong08** [comment]
403 means expired session token

**Comment by js19950276** [comment]
> 403 means expired session token

{"user":{"id":"user-tnNGfk79xOpapLTm2yGQudjN","name":"蒋帅","email":"js19950726@gmail.com","image":"https://lh3.googleusercontent.com/a/AEdFTp58x6DqHXsHM_jRqlXANHsIrZS3czQikWPj0Tpx=s96-c","picture":"https://lh3.googleusercontent.com/a/AEdFTp58x6DqHXsHM_jRqlXANHsIrZS3czQikWPj0Tpx=s96-c","groups":[],"features":["saveHistory"]},"expires":"2023-02-15T09:10:59.841Z","accessToken":"g"}

They said my token will expire at 2023-02-15T09:10:59.841Z

**Comment by acheong08** [comment]
The expiration doesn't really mean anything. They invalidate it at random to throw people off

**Comment by acheong08** [comment]
You might want to look into a VPN
