### ISSUE TITLE
[BUG]  Max retries exceeded with url

### ISSUE THREAD

**Issue by qpwedev** [acheong08/ChatGPT#459]
**Description**                                                          
I am encountering a "MaxRetryError" when running my script which uses a valid token from GPT. The specific error message is: "HTTPConnectionPool(host='localhost', port=55494): Max retries exceeded with url: /session/e685b7fc06d4f74cd9c0f206f13ee0d4/se/log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a854d90>: Failed to establish a new connection: [Errno 61] Connection refused'))"

**Steps to Reproduce**                                                                                 
1. Run script using valid token from GPT.
1. See error.

**Expected behavior**                                 
Starting of script without errors.

**Environment**                                                                                         
 - OS: MacOS
 - Python version: 3.10.8
 - ChatGPT Version: 0.1.1

**Comment by acheong08** [comment]
Issue with Chrome. Make sure Google Chrome is installed and up to date. You must also install Chromedriver

**Comment by dfmode** [comment]
Solved. Somehow loggin library in python caused this error. Thank you for help

**Comment by jimaldon** [comment]
@qpwedev how did you solve it? I dont get this error with a VPN, but it keeps happening without it

**Comment by qpwedev** [comment]
Unfortunately I do not remember exactly but I thinks the problem was in the chrome driver

**Comment by jimaldon** [comment]
Okay found out why. My pihole instance was blocking openapi APi calls haha
