### ISSUE TITLE
[BUG] Long requests time out

### ISSUE THREAD

**Issue by Jamminroot** [acheong08/ChatGPT#463]
Hey, I see you've reverted the "temp fix" now, but that introduced the bug again - longer requests time out.

Sample request which would take ~1 minute to serve: `Сочини мне хайку о самурае и упавшем сервере в продакшене`

Not suggesting a fix, just highlighting the problem.

**Comment by acheong08** [comment]
It was causing other issues with my API. I'll reintroduce the temporary fix and try to work around that on the API side
