### ISSUE TITLE
[BUG] You can't get there from here

### ISSUE THREAD

**Issue by raronen** [acheong08/ChatGPT#466]
**Description**                                                          

**Steps to Reproduce**                                                                                 
Hi,

I'm authenticating with my microsoft account but I'm getting the following error in chrome:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/50779771/212414138-a15bc61e-af85-4290-be1c-8e0bbb1bba34.png">

Chrome version: 
109.0.5414.74
I tried Edge, but the tool fails with it.
I tried to install the extension, but it can't install it.

**Expected behavior**                                 

**Output**                                                                 
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**                                                                                         
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: windows
 - Python version: Python 3.10.2
 - ChatGPT Version: 0.2.1

**Additional context**

**Comment by acheong08** [comment]
wth is microsoft trying to force everyone to use Edge or install Microsoft Spyware?

**Comment by acheong08** [comment]
Use session tokens for now
