### ISSUE TITLE
Try Again?

### ISSUE THREAD

**Issue by easyssss** [acheong08/ChatGPT#47]
Is there any way to do the equivalent of hitting the "Try Again" button? It's kind of critical for getting around the content filtering.

**Comment by acheong08** [comment]
You can cache the parent id and conversation id manually and set it. I can try to implement this later. A pull request is also welcome

**Comment by easyssss** [comment]
I am unfortunately Very new to this. How would I manually set it?

**Comment by acheong08** [comment]
You must import this library and write a custom implementation. I will probably try to implement this later today so wait if you're willing

**Comment by easyssss** [comment]
Thank you so much. I have no problem waiting.

**Comment by xetru** [comment]
yea that would be really neat. waiting :)

**Comment by acheong08** [comment]
Working on it right now

**Comment by acheong08** [comment]
Supported.

**Comment by acheong08** [comment]
```
chatbot.rollback_conversation()
```

**Comment by easyssss** [comment]
While this is very useful, it doesn't seem to be the same function as the try again function. When using that function, the bot takes a different track. If it says one thing, and you hit try again, it will say something else. With the rollback, it tends to just repeat itself (or say something very similar). I've found other ways around the filters, so its not a huge issue, but figured I'd let you know.

**Comment by acheong08** [comment]
The rollback function moves back by one parent_id, meaning that you get to delete the last message from history. It is similar to try again but can only roll back by one message.

**Comment by acheong08** [comment]
For example:
You: <Question 1>

Chatbot: <Response to Q1>

You: <Question 2>

Chatbot: <Response to Q2>

You: !rolback

...

You: continue

Chatbot: <Continues from Q1>
