### ISSUE TITLE
[BUG] Session token will change when refresh the browser

### ISSUE THREAD

**Issue by quqxui** [acheong08/ChatGPT#473]
Session token will change when refreshing the browser, which makes it impossible to request automatically.

Can this package use the username and password rather than token?

**Comment by x7peeps** [comment]
same error

**Comment by rzbdz** [comment]
I don't think it possible when openai have Captcha, can only look forward for official api. Or you can try use some other library to build a login helper.

**Comment by acheong08** [comment]
Read Wiki. We support Microsoft login and email/password. Email/password login requires 2Captcha account.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/wiki/Setup#emailpassword-login-authentication

**Comment by acheong08** [comment]
> Session token will change when refreshing the browser, which makes it impossible to request automatically.

Once you get a session token, it is recommended that you close the browser. The session  token refreshes automatically when you make requests via this library
