### ISSUE TITLE
[Project List] Request to add voice skill to project list

### ISSUE THREAD

**Issue by DanBmh** [acheong08/ChatGPT#476]
Thanks for creating this cool library:)

I've built a voice skill for the open source voice assistant [Jaco](https://gitlab.com/Jaco-Assistant/Jaco-Master)  and would like to ask you if you could add a link to the skill (https://gitlab.com/DANBER/Jaco-AskChatGPT) to your project collection.

It's a bit similar to https://github.com/acheong08/ChatGPT/issues/255, but is integrated into a complete voice interface.

**Comment by DanBmh** [comment]
For all trying to setup the library with docker (and struggeling a bit, like me), you can find a working dockerfile [here](https://gitlab.com/DANBER/Jaco-AskChatGPT/-/blob/master/Containerfile_amd64). It uses a base image with some skill dependencies preinstalled (see (here)[https://gitlab.com/Jaco-Assistant/Jaco-Master/-/blob/master/runfiles/Containerfile_MasterBase_amd64]), but it should work to use a `docker.io/ubuntu:20.04` directly instead.

**Comment by acheong08** [comment]
Not quite sure how to add a GitLab repo to GitHub's listing

**Comment by acheong08** [comment]
I mirrored the repository and removed everything from the readme and replaced it with a link to your GitLab repo. Hopefully that works

**Comment by acheong08** [comment]
https://github.com/acheong08/Jaco-AskChatGPT/blob/3aafbb9409e014f038fd98e2b2c834a83e41f4f5/README.md?plain=1#L1
