### ISSUE TITLE
No response From chatGPT 

### ISSUE THREAD

**Issue by Abdallah-al-hallak** [acheong08/ChatGPT#477]
Hi,

I can LogIn but no response in chatGPT 
I pressed F12
code
: 
"invalid_api_key"
message
: 
"Incorrect API key provided:
I find this in the cosole

**Comment by adminha** [comment]
The error says clearly that your API key is invalid. Are you using the complete API key including "sk-" prefix? did you try to remove it?
----------------
https://chatgpttalk.com/

**Comment by acheong08** [comment]
You're supposed to use the session token, not the API key

**Comment by acheong08** [comment]
It's a cookie. Follow setup instructions in wiki
