### ISSUE TITLE
not a bug but a noob question

### ISSUE THREAD

**Issue by noonies** [acheong08/ChatGPT#490]
i have a problem when im trying to run it in replit.

"UnboundLocalError: local variable 'driver' referenced before assignment"

i searched everywhere but no luck.

**Comment by simonfalke-01** [comment]
Having the same issue here.

**Comment by acheong08** [comment]
Chromedriver issue. Duplicate of https://github.com/acheong08/ChatGPT/issues/381

**Comment by simonfalke-01** [comment]
I just had to install Chrome to fix this issue. I'm using macOS.
