### ISSUE TITLE
[BUG] TimeoutException

### ISSUE THREAD

**Issue by theartpiece** [acheong08/ChatGPT#491]
**Description**                                                          

I'm instantiating chatgpt bot via following API--
chatbot = Chatbot({
  "email": "<something>",
  "password": "<something>",
  "captcha": "<something>"
}, conversation_id=None, parent_id=None) # You can start a custom conversation

**Output**                                                                 
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`
File ~/miniconda3/envs/myenv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py:66, in Chatbot.__init__(self, config, conversation_id, parent_id, no_refresh)
     64         raise Exception("2Captcha API Key must be a string!")
     65     self.twocaptcha_key = config["captcha"]
---> 66     self.email_login(self.solve_captcha())
     67 else:
     68     raise Exception("Invalid config!")

File ~/miniconda3/envs/myenv/lib/python3.9/site-packages/revChatGPT/ChatGPT.py:433, in Chatbot.email_login(self, solved_captcha)
    430 driver.find_element(
    431     by=By.XPATH, value="//button[@type='submit']").click()
    432 # Wait for the password input field to appear
--> 433 WebDriverWait(driver, 60).until(EC.visibility_of_element_located(
    434     (By.ID, "password")))
    435 # Enter the password
    436 driver.find_element(by=By.ID, value="password").send_keys(
    437     self.config["password"])

File ~/miniconda3/envs/myenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:95, in WebDriverWait.until(self, method, message)
     93     if time.monotonic() > end_time:
     94         break
---> 95 raise TimeoutException(message, screen, stacktrace)

TimeoutException: Message: 
Stacktrace:
#0 0x55d5fa462303 <unknown>
#1 0x55d5fa236d37 <unknown>
#2 0x55d5fa2735b2 <unknown>
#3 0x55d5fa2736c1 <unknown>
#4 0x55d5fa2adb34 <unknown>
#5 0x55d5fa2939ad <unknown>
#6 0x55d5fa2ab88c <unknown>
#7 0x55d5fa293753 <unknown>
#8 0x55d5fa266a14 <unknown>
#9 0x55d5fa267b7e <unknown>
#10 0x55d5fa4b132e <unknown>
#11 0x55d5fa4b4c0e <unknown>
#12 0x55d5fa497610 <unknown>
#13 0x55d5fa4b5c23 <unknown>
#14 0x55d5fa489545 <unknown>
#15 0x55d5fa4d66a8 <unknown>
#16 0x55d5fa4d6836 <unknown>
#17 0x55d5fa4f1d13 <unknown>
#18 0x7fdd611d1609 start_thread

**Environment**                                                                                     
 - OS-- Linux
 - Python version: 3.9.7
 - ChatGPT Version: 0.3.1

**Comment by shelmingsong** [comment]
+1

#### Environment

- OS: macOS
- Python version: 3.10.7
- ChatGPT Version: 0.3.1

**Comment by acheong08** [comment]
@shelmingsong Are you using Miniconda as well?

**Comment by shelmingsong** [comment]
> @shelmingsong Are you using Miniconda as well?

no, I use pyenv.
