### ISSUE TITLE
Use revChatGPT in headless linux server / hosted online app

### ISSUE THREAD

**Issue by gustavz** [acheong08/ChatGPT#492]
I was not able to use `revChatGPT` in a hosted `streamlit` app (headless linux server), it only works in offline/local apps.
In hosted apps it seems to fail to open a new chrome window to log into the chatgppt session with error
```
local variable 'driver' referenced before assignment
```

deployed app: https://jaivus.streamlit.app/
repo: https://github.com/gustavz/jaivus

Is there a way to use `revChatGPT` in an online/hosted app, or is it only for offline/local usage?

**Comment by gustavz** [comment]
I tried it with installing 
```
chromium
chromium-driver
```
but that does not help

**Comment by acheong08** [comment]
Use Xvfb

**Comment by acheong08** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/743#issuecomment-1366847803

**Comment by ahmetkca** [comment]
@gustavz You can also take a look at this. https://github.com/ahmetkca/chatgpt-unofficial-api-docker/tree/my-docker-novnc
It might solve your problem. I designed this to be able to deploy to AWS.

**Comment by gustavz** [comment]
@acheong08 I am using xvfb, here is the full packages list i use to host: https://github.com/gustavz/jaivus/blob/main/packages.txt

**Comment by acheong08** [comment]
Official API just dropped yesterday. No more browsers needed

**Comment by acheong08** [comment]
Please read README

**Comment by gustavz** [comment]
nice! how do I use it, just pass my api key instead of the session key into `Chatbot`?

**Comment by acheong08** [comment]
`from revChatGPT.Official import Chatbot`

There are some minor differences in API which you can find documented in the [Wiki](https://github.com/acheong08/ChatGPT/wiki/revChatGPT)

**Comment by acheong08** [comment]
Example usage:
https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/Official.py#L347-L451

**Comment by gustavz** [comment]
great, works for me now thanks!
