### ISSUE TITLE
[BUG]We're currently processing too many requests. Please try again later.

### ISSUE THREAD

**Issue by siyuyuan** [acheong08/ChatGPT#497]
```
from revChatGPT.ChatGPT import Chatbot

chatbot = Chatbot({
  "session_token": "<YOUR_TOKEN>"
}, conversation_id=None, parent_id=None) # You can start a custom conversation

response = chatbot.ask("Prompt", conversation_id=None, parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)

print(response)
```

Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
{"detail":{"message":"We're currently processing too many requests. Please try again later."}}
Traceback (most recent call last):
  File "chatgpt_QG.py", line 48, in <module>
    response = chatbot.ask(prompt+Q+A, conversation_id=None, parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)
  File "/home/ysy/anaconda3/envs/ysy_env/lib/python3.8/site-packages/revChatGPT/ChatGPT.py", line 133, in ask
    raise HTTPError(f"Wrong response code: {response.status_code}! Refreshing session...")
requests.exceptions.HTTPError: Wrong response code: 429! Refreshing session...

**Comment by acheong08** [comment]
Issue with OpenAI. They're getting overloaded

**Comment by acheong08** [comment]
I will add documentation for Official API later today

**Comment by siyuyuan** [comment]
> 

wow! Thank you sooo much:)

**Comment by siyuyuan** [comment]
> I will add documentation for Official API later today

wow! Thank you sooo much:)

**Comment by acheong08** [comment]
@siyuyuan Released! https://github.com/acheong08/ChatGPT/releases/tag/1.0.1

**Comment by Rofltropter** [comment]
@acheong08 Reviewing this issue side-by-side with the same Microsoft Account authenticated, it seems to be fine to spit out an answer at the exact same moment as it fails via the Chatbot (unofficial) package. Believe there may be more to it than just load.

**Comment by siyuyuan** [comment]
> @siyuyuan Released! https://github.com/acheong08/ChatGPT/releases/tag/1.0.1

Thank you! But how much about the tokens for chatgpt api? is it same as text-davinci-003?

**Comment by siyuyuan** [comment]
> @acheong08 Reviewing this issue side-by-side with the same Microsoft Account authenticated, it seems to be fine to spit out an answer at the exact same moment as it fails via the Chatbot (unofficial) package. Believe there may be more to it than just load.

Yes:(. The answer can be generated through the official interface, but using the API will show overload. Still feels a little weird.

**Comment by siyuyuan** [comment]
> @siyuyuan Released! https://github.com/acheong08/ChatGPT/releases/tag/1.0.1

wonderful!!!!! Through your code, it is more convenient and faster for me to use chatgpt, thank you very much!!

**Comment by Rofltropter** [comment]
The official ChatGPT api is also censored and will call the moderation automatically. Any way around this @acheong08 ?

**Comment by acheong08** [comment]
There is no way around the official moderation for now since it's built in to the endpoint.

**Comment by acheong08** [comment]
> Thank you! But how much about the tokens for chatgpt api? is it same as text-davinci-003?

If you use an account without any credit, it still functions but doesn't charge a penny

**Comment by PANTHERWWE1** [comment]
I'm also facing the same on my account, any solutions yet ?

**Comment by acheong08** [comment]
This model is dead
