### ISSUE TITLE
[BUG] Doesn't return any response, goes on a loop

### ISSUE THREAD

**Issue by DawnSaju** [acheong08/ChatGPT#499]
Hello!

First of all thank you so much for this updated version, I'm so excited to try it out but I face an bug which just goes on a loop without any response from the api. 

![image](https://user-images.githubusercontent.com/70035674/215806112-48ead839-dfae-42f1-9e44-39526abab745.png)

**Comment by acheong08** [comment]
Enter twice to send request

**Comment by acheong08** [comment]
I added a few print statements later on lol
https://github.com/acheong08/ChatGPT/compare/1.0.1...1.0.2#diff-6439185fb851c0aa025b37d88d44fe4f990a9cc4a99553b178a3fe819f3ab6baR182-R190

**Comment by DawnSaju** [comment]
Got it. Thanks for the help!
