### ISSUE TITLE
Streaming responses

### ISSUE THREAD

**Issue by scottleibrand** [acheong08/ChatGPT#5]
The https://chat.openai.com/chat web interface begins displaying responses as soon as the model generates them, allowing you to begin reading lengthy responses much sooner.

Do you know how we would go about implementing a similar feature on the command line? It probably doesn't need to stream every word, but line by line streaming would be cool.

Happy to help, whether that means picking up where you left off or figuring it out from scratch...

**Comment by acheong08** [comment]
> Happy to help, whether that means picking up where you left off or figuring it out from scratch...

A pull request would be much appreciated.

**Comment by scottleibrand** [comment]
Ok, I'll try to take a look tomorrow. LMK if you find anything out about how it's done in the browser: I haven't done any research yet.

**Comment by A-kirami** [comment]
I implemented streaming response, but I don't know how to output it on the console.

**Comment by A-kirami** [comment]
> I implemented streaming response, but I don't know how to output it on the console.

I solved the problem, but the method was ugly.

**Comment by acheong08** [comment]
@A-kirami I have written a rough implementation of text streaming. Can you check if it works?

`get_chat_response(prompt, output="stream")` should `yield` each message.

```py
if __name__ == "__main__":
    with open("config.json", "r") as f:
        config = json.load(f)
    chatbot = Chatbot(config)
    if 'session_token' in config:
        chatbot.refresh_session()
    while True:
        prompt = input("You: ")
        for message in chatbot.get_chat_response(prompt, output="response"):
            print(message)
```
This should print out the message as it streams. I'm not sure how to deal with the console so that it is overwritten as more data comes in.

**Comment by A-kirami** [comment]
> @A-kirami I have written a rough implementation of text streaming. Can you check if it works as intended (It works for me but need verification)
> 
> `get_chat_response(prompt, output="stream")` should `yield` each message.
> 
> ```python
> if __name__ == "__main__":
>     with open("config.json", "r") as f:
>         config = json.load(f)
>     chatbot = Chatbot(config)
>     if 'session_token' in config:
>         chatbot.refresh_session()
>     while True:
>         prompt = input("You: ")
>         for message in chatbot.get_chat_response(prompt, output="stream"):
>             print(message)
> ```
> 
> This should print out the message as it streams. I'm not sure how to deal with the console so that it is overwritten as more data comes in.

It works normally. If you need to print it on the console, you can refer to the implementation here.

https://github.com/A-kirami/ChatGPT/blob/main/src/revChatGPT/__main__.py#L69-L81

**Comment by acheong08** [comment]
I am terrible at this. It keeps erasing the lines in my implementation

**Comment by acheong08** [comment]
I'll copy your code over and modify it

**Comment by acheong08** [comment]
This doesn't work in all terminals: 
```

Detected that the lines of output has been exceeded the height of terminal windows, which                     caused the former output remained and keep adding new lines.
检测到输出过程中, 输出行数曾大于命令行窗口行数, 这会导致输出清除不完整, 而使输出不停增长。请注意控制输出行数

```

**Comment by acheong08** [comment]
```
sys.stdout.write("\033[F\033[K")
```
This doesn't work properly in all terminals either for some reason. My hair is falling off lol

**Comment by acheong08** [comment]
The error seems to be that this deletes the number of lines it is aware of but in some terminals, line count is counted differently

**Comment by scottleibrand** [comment]
The approach I was attempting (but haven't perfected yet) is to only write a line once it is has completely loaded, rather than deleting lines after they're written. Would that work here?

**Comment by acheong08** [comment]
That is what I'm attempting to do. I write the whole message and then when a new one comes in, I try to delete the previous message. It's not clearing the right number of lines though.

**Comment by scottleibrand** [comment]
I'm suggesting you not try to delete the previous message (as I did with the please wait prompt), but rather keep track of how many lines you've written, and only write each new line.

**Comment by acheong08** [comment]
>  keep track of how many lines you've written

Tried that. An issue with this is that some environments treat lines differently. For example, my current omz shell treats each new line in the terminal as a new line (which changes depending on window size). However, Python can only see \n as new line

**Comment by acheong08** [comment]
I tried counting the characters and saving them, then deleting that number of characters when a new message comes in. However, \b isn't supported in some terminals either.

**Comment by acheong08** [comment]
Not even ChatGPT knows the solution to this...

**Comment by acheong08** [comment]
I think streaming is more suited for GUI applications. Terminals don't like overwrites

**Comment by scottleibrand** [comment]
Do you have a pointer to a commit that has streaming working but doesn't have the terminal stuff solved yet? I can restart my efforts from there.

**Comment by acheong08** [comment]
Streaming working on latest commit

**Comment by scottleibrand** [comment]
Of main or async-dev?

**Comment by acheong08** [comment]
main

**Comment by scottleibrand** [comment]
On that commit I'm getting
```
  File "/Users/sleibrand/src/ChatGPT/src/revChatGPT/__main__.py", line 70, in <module>
    print("Chatbot:", response['message'])
TypeError: 'generator' object is not subscriptable
```

**Comment by acheong08** [comment]
It returns a string

**Comment by scottleibrand** [comment]
I've been running it with `python3 -m revChatGPT` - is there another command-line you've been using?

**Comment by acheong08** [comment]
> I've been running it with `python3 -m revChatGPT` - is there another command-line you've been using?

It can only be implemented custom right now.

**Comment by acheong08** [comment]
Example code: https://github.com/acheong08/ChatGPT/issues/5#issuecomment-1336739996

**Comment by scottleibrand** [comment]
https://github.com/acheong08/ChatGPT/compare/main...scottleibrand:ChatGPT:async?expand=1

**Comment by scottleibrand** [comment]
https://github.com/acheong08/ChatGPT/pull/23

**Comment by acheong08** [comment]
@scottleibrand 
```
Chatbot: 
Something went wrong!
name 'formatted_parts' is not defined
```

**Comment by acheong08** [comment]
I ought to have some better way to detect auth errors

**Comment by scottleibrand** [comment]
Yeah, that has tripped me up a few times too. Can we store more persistent credentials to allow it to log in again?

**Comment by acheong08** [comment]
The thing with the next auth tokens is that it needs to be refreshed every hour. It stays valid that way. However, if you don't refresh it, it expires.

**Comment by acheong08** [comment]
I haven't figured out their hashing system on the login page. It hashes the password client side

**Comment by acheong08** [comment]
I'll open an issue for this
