### ISSUE TITLE
[BUG] ChatGPT also completes user's respond

### ISSUE THREAD

**Issue by code-yeongyu** [acheong08/ChatGPT#500]
**Description**

**Steps to Reproduce**
1. Ask ChatGPT about something
2. Sometimes it doesn't end by itself, but keep continues to answer as if it is an user.
	- video: https://user-images.githubusercontent.com/11153873/215934394-a09dd042-18bf-4272-bafc-eef4d2538d99.mov

**Expected behavior**
ChatGPT should stop giving the answer when the respond of ChatGPT is done.

**Output**
```
OfficialChatGPT --api_key api_key --stream
```

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: Python 3.9.15

 - ChatGPT Version: 1.0.4

**Additional context**

**Comment by acheong08** [comment]
Happens sometimes. I am looking for a solution. If you have any ideas, please inform me (probably some form of stop sequences)

**Comment by sudoskys** [comment]
https://github.com/LlmKira/llm-kira/blob/main/src/llm_kira/client/llms/openai.py#L214

**Comment by Ulysses0817** [comment]
maybe replace '\n\n\n' with '<|im_sep|>'  is ok?
It could be misleading if input prompt contains  '\n\n\n' or the text ends with '\n\n'.

reference: https://github.com/waylaidwanderer/node-chatgpt-api/blob/6aeb48d03e8c172c9ee974e814dd7e367805b92a/src/ChatGPTClient.js#L33
