### ISSUE TITLE
[BUG]InvalidRequestError(message="This model's maximum context length is 4097 tokens, however you requested 4116 tokens (1044 in your prompt; 3072 for the completion). Please reduce your prompt; or completion length.", param=None, code=None, http_status=400, request_id=None)

### ISSUE THREAD

**Issue by naruto716** [acheong08/ChatGPT#501]
InvalidRequestError(message="This model's maximum context length is 4097 tokens, however you requested 4116 tokens (1044 in your prompt; 3072 for the completion). Please reduce your prompt; or completion length.", param=None, code=None, http_status=400, request_id=None)

Currently I'm using the official api version of the lib, it worked like a charm at first but later this error occurred.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.0.7

**Comment by acheong08** [comment]
thanks
