### ISSUE TITLE
[BUG] Maximum context length Error

### ISSUE THREAD

**Issue by ghostiq** [acheong08/ChatGPT#503]
Hi there,

I am using Official (Browserless) version and I am getting:
`This model's maximum context length is 4097 tokens, however you requested 4506 tokens (3482 in your prompt; 1024 for the completion). Please reduce your prompt; or completion length.`

What is the best way to handle that? Probably I can delete chatbot and start again but I would love to continue chatting so that ChatGPT knows about our previous chatting. Am I right that our previous questions&answers are added to the next prompt?

Thank You

**Comment by acheong08** [comment]
What version are you using? I added some minor code to reduce the completion tokens based on prompt length

**Comment by acheong08** [comment]
I'll add some improvements to have the max prompt length as an input

**Comment by acheong08** [comment]
Oh it seems I missed it for streaming and async

**Comment by ghostiq** [comment]
I am using 1.0.0. I didn't expect so frequent updates, but I will update and try again after coffee break.

Thanks for that and fast answers ;)

**Comment by acheong08** [comment]
Don't update just yet. I'm fixing stuff

**Comment by acheong08** [comment]
It's all in beta/unstable due to this being so new

**Comment by acheong08** [comment]
Ok check https://github.com/acheong08/ChatGPT/releases/tag/1.0.8

**Comment by ghostiq** [comment]
I am on 1.0.8 now.

The fist try:
`This model's maximum context length is 4097 tokens, however you requested 4403 tokens (797 in your prompt; 3606 for the completion). Please reduce your prompt; or completion length.`

The second try:
`This model's maximum context length is 4097 tokens, however you requested 4346 tokens (692 in your prompt; 3654 for the completion). Please reduce your prompt; or completion length.`

Should I use a shorter prompt? Is there a limit there? I am using polish letters in both prompt and completion.
I don't have more credits, should I setup paid account at OpenAI maybe?

**Comment by acheong08** [comment]
Ok. Bad math on my part. The way I'm calculating tokens might be wrong

**Comment by acheong08** [comment]
> I don't have more credits, should I setup paid account at OpenAI maybe?

Don't. this doesn;t cost credits

**Comment by ghostiq** [comment]
Update 1.0.9

`This model's maximum context length is 4097 tokens, however you requested 4258 tokens (796 in your prompt; 3462 for the completion). Please reduce your prompt; or completion length.`

**Comment by shelmingsong** [comment]
I Use 1.0.9

```bash
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4293 tokens (405 in your prompt; 3888 for the completion). Please reduce your prompt; or completion length.

```

**Comment by acheong08** [comment]
damn it my math skills

**Comment by acheong08** [comment]
They say that one token is 4 characters on their website. Might be wrong

**Comment by acheong08** [comment]
Can you guys share your prompts?

**Comment by acheong08** [comment]
Need to check what my code calculates vs tokenizer

**Comment by acheong08** [comment]
Ah I see my mistake. Tokens are byte based so special characters actually count more. I will try to fix this.

**Comment by acheong08** [comment]
It's difficult to calculate tokens as they are calculated with an AI model itself https://stackoverflow.com/questions/72294775/how-do-i-know-how-much-tokens-a-gpt-3-request-used

https://platform.openai.com/tokenizer

**Comment by acheong08** [comment]
I think I found a solution. Trying it out

**Comment by acheong08** [comment]
I've added the official tiktoken by OpenAI to try to encode it for me. It will be slower the first time you run it as it caches a model (1MB)

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.0.10

**Comment by dalan2014** [comment]
In Python3.7, we can use Huggingface Transformer library to replace tiktoken. Just replace the following two places in Official.py:
`import tiktoken`
to
`from transformers import GPT2TokenizerFast`

`self.enc = tiktoken.get_encoding("gpt2")`
to
`self.enc = GPT2TokenizerFast.from_pretrained("gpt2")`
