### ISSUE TITLE
[BUG]InvalidRequestError(message="-103 is less than the minimum of 0 - 'max_tokens'", param=None, code=None, http_status=400, request_id=None)

### ISSUE THREAD

**Issue by naruto716** [acheong08/ChatGPT#506]
Thank you for fixing #501 
However, with the latest version, I'm encountered this:

> InvalidRequestError(message="-103 is less than the minimum of 0 - 'max_tokens'", param=None, code=None, http_status=400, request_id=None)

I noticed that in line 49 of official.py, you have 
`max_tokens=4000-len(prompt),`
However, in line 324, you have
`if len(prompt) > 4000 * 4:`
which means the maximum length of a prompt object can be larger than 4000.

Take it with a grain of salt, I just briefly skimmed through your code.

**Comment by acheong08** [comment]
I made a mistake with calculating tokens for special chars

**Comment by acheong08** [comment]
I'm fixing it right now

**Comment by naruto716** [comment]
> I'm fixing it right now

tysm!

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.0.10

Try it out. It should have fixed this (Using GPT-2 encoder as GPT-3 is not open source. Should be pretty much the same unless you do some recently added unicode)

**Comment by naruto716** [comment]
Ty!
