### ISSUE TITLE
Multi-Session ChatGPT support

### ISSUE THREAD

**Issue by shiyemin** [acheong08/ChatGPT#51]
Hi!

I created a set of Multi-Session ChatGPT API based on your work. I have included credits in the project's README file, and I wanted to make sure you were aware of the project.

The api supports multiple session in one service, which can generate output based on each user's context. You can check it out here: https://github.com/shiyemin/ChatGPT-MS

Thanks again!

**Comment by acheong08** [comment]
Thank you. This will help with https://github.com/acheong08/ChatGPT/issues/7. Added to list
