### ISSUE TITLE
[BUG] construct_prompt() remove old history too late for new completion

### ISSUE THREAD

**Issue by linzack** [acheong08/ChatGPT#511]
**Description**
Hi, since the maximum context length is 4097 tokens (new prompt + history + new completion), if the buffer is nearly full and new completion cost 500 tokens, there is no room for it.
it's because in the code, construct_prompt() function will remove old history only if (new prompt + history > 4000), the condition have not consider the token length of new completion incoming, also the length of history chat may vary, I think maybe we could keep remove history chat until 500 tokens reserved for the new completion.

**Steps to Reproduce**
1. keep chat until buffer full (near 4097 tokens)
2. find the reply from chatgpt cutting off early, not complete sentence

**Expected behavior**
every chat have long enough reply

version 1.0.10

**Additional context**
concept of code to change:
```
    def construct_prompt(self, new_prompt: str) -> str:
        """
        Construct prompt based on chat history and request
        """
        prompt = (
            self.base_prompt + self.history() + "User: " + new_prompt + "\nChatGPT:"
        )
        while True:
            if len(self.enc.encode(prompt)) > 3500: # reserved at least 500 tokens for new completion
                # Remove oldest chat
                self.chat_history.pop(0)
                # Construct prompt again
                prompt = self.construct_prompt(new_prompt)
            else:
                break
        return prompt
```
Thank you!

**Comment by acheong08** [comment]
A simple change. Could have opened a pull request.

Will fix

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.0.11
