### ISSUE TITLE
[BUG] That model does not exit

### ISSUE THREAD

**Issue by Leewaldoe** [acheong08/ChatGPT#515]
**Description**
I'm experiencing a strange error. The response message is simply "That model does not exit".

**Output**
```
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
<tk_button_send>click event <ButtonPress event state=Mod2 num=1 x=30 y=23>
{"detail":{"message":"That model does not exist","type":"invalid_request_error","param":null,"code":null}}
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1924, in __call__
    return self.func(*args)
  File "/home/user/programming/gpt/api-connector/tkinter-gpt/app/main.py", line 90, in bot_ask
    asyncio.run(self.wait_for_response(inputs_question))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/programming/gpt/api-connector/tkinter-gpt/app/main.py", line 77, in wait_for_response
    async for i in await self.chatbot.ask(inputs):
  File "/home/user/programming/gpt/api-connector/tkinter-gpt/venv/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 159, in ask
    raise HTTPError(
requests.exceptions.HTTPError: Wrong response code: 404! Refreshing session...
```

**Environment**
 - OS: Windows (WSL2)
 - Python version: python 3.10
 - ChatGPT Version: revChatGPT 1.0.11

**Comment by qcwthu** [comment]
I have the same problem. Does anyone know how to solve it?

**Comment by BNDSllx** [comment]
same problem

**Comment by acheong08** [comment]
Could be expired session tokens

**Comment by acheong08** [comment]
Maybe try using official API (no expiry)

**Comment by BNDSllx** [comment]
> Could be expired session tokens

I just updated session tokens about 3 hours ago

**Comment by acheong08** [comment]
Yeah use official API. The unofficial one is a bit unstable

**Comment by qcwthu** [comment]
How to use the official API?

**Comment by acheong08** [comment]
Check Readme. It has been updated.https://github.com/acheong08/ChatGPT#official-api-browserless

**Comment by Leewaldoe** [comment]
Regarding the official API. How long do you think before someone decides to shut it down?

**Comment by acheong08** [comment]
>  How long do you think before someone decides to shut it down

According to some connections of @transitive-bullshit, this won't be taken down as it's in use by YC/VC partners of OpenAI

**Comment by transitive-bullshit** [comment]
You will get this problem if you're using the old browser-based approach and it's still using `text-davinci-002-render`, which seems to no longer be valid.

From my testing, the browser-based version updated to use `text-davinci-002-render-next` and `text-davinci-002-render-paid` if you're on a pro chatgpt plan.

@acheong08 I think you just need to update these in the old version. I agree that you shouldn't encounter this issue using the new model fine-tuned for chat.

**Comment by acheong08** [comment]
@transitive-bullshit Thanks. Will fix

**Comment by acheong08** [comment]
Fixed

**Comment by acheong08** [comment]
> text-davinci-002-render-paid if you're on a pro chatgpt plan.

I won't be supporting paid tier

**Comment by assassingyk** [comment]
Official api also start to get "That model does not exist" error. Is there any chance we find the new model name for official api?

**Comment by F33RNI** [comment]
Same
`text-davinci-002-render-next` also not working =(

**Comment by 0xdevalias** [comment]
**See Also:**

- https://github.com/acheong08/ChatGPT/issues/504
- https://github.com/acheong08/ChatGPT/issues/517
- https://github.com/acheong08/ChatGPT/issues/523
- https://github.com/acheong08/ChatGPT/issues/530

**Comment by hunkim** [comment]
Hmm. Both do not work for me.

`GPT3 Error: That model does not exist`

**Comment by 0xdevalias** [comment]
> From my testing, the browser-based version updated to use `text-davinci-002-render-next` and `text-davinci-002-render-paid` if you're on a pro chatgpt plan.

Looking at the requests made from the browser version just now (non-paid), it seems to be using `text-davinci-002-render` (unsure what model the paid version would be using)

**Comment by acheong08** [comment]
These are just aliases for the model on the back end. The real name is not revealed
