### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'revChatGPT.Official'

### ISSUE THREAD

**Issue by gnohgnailoug** [acheong08/ChatGPT#518]
can't load module  'revChatGPT.Official' after i upgrade the revChatGPT
![image](https://user-images.githubusercontent.com/69443774/216283785-b8f8b528-0a0e-45b2-b618-157d0e348f25.png)

**Comment by acheong08** [comment]
If you're using an env, make sure it is also installed in the virtual environment

**Comment by gnohgnailoug** [comment]
> If you're using an env, make sure it is also installed in the virtual environment

thanks to your reply. Here is the files i download in anaconda, did i miss some files?

**Comment by acheong08** [comment]
You aren't meant to download the files. You're meant to do `pip3 install revChatGPT`. You're also missing `Official.py`

**Comment by gnohgnailoug** [comment]
> You aren't meant to download the files. You're meant to do `pip3 install revChatGPT`. You're also missing `Official.py`

Thanks to your help! I'll try it later
