### ISSUE TITLE
[BUG] openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by piotrstarzynski** [acheong08/ChatGPT#523]
Did they change something or the browserless method is no longer possible?

`openai.error.InvalidRequestError: That model does not exist`

**Comment by acheong08** [comment]
Well, it was good while it lasted. It seems we have been discovered

**Comment by gnohgnailoug** [comment]
I encountered this bug too
![image](https://user-images.githubusercontent.com/69443774/216363233-e091c60d-6cd0-40f7-9eeb-271fefac221d.png)

**Comment by hoblin** [comment]
Same on Official 
```
Traceback (most recent call last):
  File "/Users/hoblin/.asdf/installs/python/3.11.1/bin/OfficialChatGPT", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/revChatGPT/Official.py", line 256, in main
    response = chatbot.ask(PROMPT)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/revChatGPT/Official.py", line 41, in ask
    completion = openai.Completion.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/openai/api_requestor.py", line 227, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "/Users/hoblin/.asdf/installs/python/3.11.1/lib/python3.11/site-packages/openai/api_requestor.py", line 680, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
```

**Comment by acheong08** [comment]
Yes. It seems OpenAI has shut it down (we were technically unauthorized in the first place haha)

**Comment by hoblin** [comment]
Probably that's the reason =)
https://openai.com/blog/chatgpt-plus/

**Comment by acheong08** [comment]
They also killed the unofficial version temporarily by changing the API. Fix in progress

**Comment by jordandadams** [comment]
TEARS! I just built a working bot using this, but time to continue on I guess lol.

**Comment by jordandadams** [comment]
If I can help in anyway please let me know. I am guessing the unofficial is down also?

**Comment by doevent** [comment]
working again

**Comment by hoblin** [comment]
Did anybody tried to play with other dates in the engine name?
```text-chat-davinci-002-20230126```

**Comment by acheong08** [comment]
yes. no luck

**Comment by jordandadams** [comment]
> working again

Yes, my bot seems to be working also. Have you checked your API key to see if it is using tokens?

**Comment by acheong08** [comment]
Oh it works again for me as well

**Comment by player2I0** [comment]
yes for me too

**Comment by hoblin** [comment]
Time to close an issue. I wish all the issues would be solved like this one =)

**Comment by Wangyq0617** [comment]
In my project, the error occurred again

**Comment by Smiorld** [comment]
Same error again

**Comment by acheong08** [comment]
it's gone again. OpenAI trolling us.

**Comment by Smiorld** [comment]
Not for me though, still got the error

**Comment by jordandadams** [comment]
Yes, they are for sure trolling us no doubt.

**Comment by F33RNI** [comment]
Same

**Comment by F33RNI** [comment]
> Is this still an issue?

yeah

**Comment by qcwthu** [comment]
Is there any way we can use revChatGPT now？

**Comment by steffanjensen** [comment]
I got it to work again by changing it back to the original:
text-davinci-002-render

**Comment by qcwthu** [comment]
Is this for ChatGPT？

**Comment by jordandadams** [comment]
> I got it to work again by changing it back to the original:
> 
> text-davinci-002-render
> 
> 
> 
> Stopped working, I also see the session_token gets updated each hour, before it could go for days..
> 
> 
> 
> Be aware of this when you troubleshoot

So you have it working? Mind sharing where you made your change?

**Comment by F33RNI** [comment]
> > I got it to work again by changing it back to the original:
> > text-davinci-002-render
> > Stopped working, I also see the session_token gets updated each hour, before it could go for days..
> > Be aware of this when you troubleshoot
> 
> So you have it working? Mind sharing where you made your change?

No, that doesn't work either.

**Comment by acheong08** [comment]
New API doesn't work but old browser based method still exists

**Comment by acheong08** [comment]
Edit: I'm getting 400 for all the requests. Seems like they also found a way to block this

**Comment by acheong08** [comment]
This repo is now in a dead state. Will fix when new information gets found. Someone supposedly found the new model name but they are holding it hostage

**Comment by F33RNI** [comment]
> This repo is now in a dead state. Will fix when new information gets found. Someone supposedly found the new model name but they are holding it hostage

Maybe we can make some kind of bruteforcer for model names? 😅

**Comment by steffanjensen** [comment]
> This repo is now in a dead state. Will fix when new information gets found. Someone supposedly found the new model name but they are holding it hostage

Mine works again, this is really weird. I got the 404 just like you, took a 15 min shower..

Now it works again

**Comment by dkouyou** [comment]
> Mine works again, this is really weird. I got the 404 just like you, took a 15 min shower..
> 
> Now it works again

Using the Official API way or teh Reversed API way?

**Comment by steffanjensen** [comment]
> > Mine works again, this is really weird. I got the 404 just like you, took a 15 min shower..
> > Now it works again
> 
> Using the Official API way or teh Reversed API way?

Im using the reserved api.. ;)

**Comment by steffanjensen** [comment]
> > > Mine works again, this is really weird. I got the 404 just like you, took a 15 min shower..
> > > Now it works again
> > 
> > 
> > Using the Official API way or teh Reversed API way?
> 
> Im using the reserved api.. ;)

**Comment by acheong08** [comment]
> Looks like i misunderstod the entire thread, you guys was running the api browserless for free..
> 
> Didnt even know that, but yeah browser method still works

it does? it broke for me.

**Comment by amittell** [comment]
Nothing working for me either, browserless or brower method.

`openai.error.InvalidRequestError: That model does not exist` :(

**Comment by fengqingthu** [comment]
Not working for me either: `openai.error.InvalidRequestError: That model does not exist`

**Comment by dkouyou** [comment]
My script is running right now using the reversed API (browser method), with a session_token update 1-2 hours ago.

**Comment by antoine-lombardo** [comment]
This one is working for me: `text-davinci-003`

**Comment by F33RNI** [comment]
> This one is working for me: `text-davinci-003` [Here](https://github.com/wong2/chatgpt-google-extension/commit/5cb4c00799a4c2740201ef121e5fbe30d43c9eb1) is a way to fetch the available model names using the api.

Thank you very much! It worked! 🥳

**Comment by naruto716** [comment]
> This one is working for me: `text-davinci-003` [Here](https://github.com/wong2/chatgpt-google-extension/commit/5cb4c00799a4c2740201ef121e5fbe30d43c9eb1) is a way to fetch the available model names using the api.

This is the official API of GPT 3. It's stable, but not really as intelligent as ChatGPT.

**Comment by jordandadams** [comment]
> My script is running right now using the reversed API (browser method), with a session_token update 1-2 hours ago.

This may be a shot in the dark, but is it possible to use the *Browser Required* API with a discord bot?

**Comment by naruto716** [comment]
> > My script is running right now using the reversed API (browser method), with a session_token update 1-2 hours ago.
> 
> This may be a shot in the dark, but is it possible to use the _Browser Required_ API with a discord bot?

Yes and I made one. I’m wondering if that supports async tho.

**Comment by jordandadams** [comment]
> > > My script is running right now using the reversed API (browser method), with a session_token update 1-2 hours ago.
> > 
> > 
> > This may be a shot in the dark, but is it possible to use the _Browser Required_ API with a discord bot?
> 
> Yes and I made one. I’m wondering if that supports async tho.

I node or Python? Mine is currently built in Python and I am guessing I may need to switch over to Node?

**Comment by steffanjensen** [comment]
> My script is running right now using the reversed API (browser method), with a session_token update 1-2 hours ago.

@acheong08

**Comment by 0xdevalias** [comment]
**See Also:**

- https://github.com/acheong08/ChatGPT/issues/504
- https://github.com/acheong08/ChatGPT/issues/515
- https://github.com/acheong08/ChatGPT/issues/517
- https://github.com/acheong08/ChatGPT/issues/530

**Comment by acheong08** [comment]
Closing in favor of unified thread

**Comment by TryMee3** [comment]
openai.error.InvalidRequestError: That model does not exist

Its not working again...
Anyone having the same issue currently or recently?
i thot it was back like yesterday.

**Comment by Mr-Ma123** [comment]
text-davinci-003 no

**Comment by ghostas301** [comment]
print(openai.Model.list()) pour obtenir la liste des model fonctionnel

**Comment by 8bitaby** [comment]
OpenAI seems to be moving away from models designed for specific coding tasks, and instead general models that can handle both text and code.  Pass in ''code-davinci-002", to comply with the latest updates, please use "text-davinci-003".

**Comment by kmlacr** [comment]
> 

THE KING THANKS!! ITS WORKING NOW
