### ISSUE TITLE
[BUG]InvalidRequestError(message='That model does not exist', param=None, code=None, http_status=404, request_id=None)

### ISSUE THREAD

**Issue by naruto716** [acheong08/ChatGPT#525]
InvalidRequestError(message='That model does not exist', param=None, code=None, http_status=404, request_id=None)

Unfortunately, I think ChatGPT removed the model for the "official api" version of this project.

**Comment by Wangyq0617** [comment]
I just met the same problem
![image](https://user-images.githubusercontent.com/122850278/216364083-ea520c38-5897-4526-900c-9e34427df92e.png)

**Comment by acheong08** [comment]
Duplicate of #523 
And the answer is yes, they did
