### ISSUE TITLE
[BUG]can't get response but keep spawning browser

### ISSUE THREAD

**Issue by gnohgnailoug** [acheong08/ChatGPT#526]
I can't receive response by using browser API, and the program will keep spawning browser until exception "Clearance refreshing...". I'll appreciate it if you can help me.
![image](https://user-images.githubusercontent.com/69443774/216365949-96e0cc63-c02c-4b1a-9778-7a388fcb6b21.png)
![image](https://user-images.githubusercontent.com/69443774/216366022-2b82784f-c156-42ad-a816-3126a85ee32b.png)

**Comment by 0xdevalias** [comment]
**See Also:**

- https://github.com/acheong08/ChatGPT/issues/526
- https://github.com/acheong08/ChatGPT/issues/527
