### ISSUE TITLE
[BUG] Exception: No config file found.

### ISSUE THREAD

**Issue by kokozweeb** [acheong08/ChatGPT#531]
**Description**
![image_2023-02-03_000929342](https://user-images.githubusercontent.com/21144281/216471636-4867af9a-3844-4b27-8278-4ff72877f9a5.png)

**Steps to Reproduce**
¯\_(ツ)_/¯

**Expected behavior**
For it to see my config.json that has a token
![image_2023-02-03_001103366](https://user-images.githubusercontent.com/21144281/216471863-b21540f2-429f-4cd0-8810-a48689e4876a.png)

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`
This is a batch script in the same place as the setup.py and config.json
![image_2023-02-03_001223621](https://user-images.githubusercontent.com/21144281/216472068-9c4d4c7a-8f4a-42f8-8f88-f9e90bd8d435.png)

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: [e.g. Linux, MacOS, Windows]
 - Python version: python -V
 - ChatGPT Version: pip3 show revChatGPT
![image_2023-02-03_001223621](https://user-images.githubusercontent.com/21144281/216472068-9c4d4c7a-8f4a-42f8-8f88-f9e90bd8d435.png)

**Additional context**
None

**Comment by acheong08** [comment]
The config file should be in the CWD. `cd path/to/directory`.

**Comment by kokozweeb** [comment]
> 

![image_2023-02-03_030245392](https://user-images.githubusercontent.com/21144281/216494580-cd34723e-d06b-430f-a119-bbd403e89cc8.png)
You mean here right??

**Comment by kokozweeb** [comment]
Nevermind somehow batch script didn't use the directory where I opened the script from, idk why it should have automatically done that..

![image_2023-02-03_031635715](https://user-images.githubusercontent.com/21144281/216496416-cd1a123f-10f3-4eac-913f-6d1ed5557b34.png)

I fixed it by manually entering the cd in the batch script
