### ISSUE TITLE
that model dosent exist?they have change its name?

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#532]

**Comment by acheong08** [comment]
It was found. The name is being held hostage by a community member to force everyone to use his third party API and give him your API key (security risk)

**Comment by zjrwtx** [comment]
> It was found. The name is being held hostage by a community member to force everyone to use his third party API and give him your API key (security risk)
got it
so where is the link-address of  that community member？

**Comment by ExcaliburGO** [comment]
What do you mean by "is held hostage"? How would a community member obtain the name for himself? What is the third party API? Because honestly I can just make a fake account and use this API key with the third party API just to keep my app working.

**Comment by acheong08** [comment]
> Because honestly I can just make a fake account and use this API key with the third party API just to keep my app working.

That works fine

**Comment by acheong08** [comment]
> What do you mean by "is held hostage"? How would a community member obtain the name for himself? 

There were apparently two info leaks of the model names which were recently updated. The person who initially found the leak lost access but he maintained access. Probably paid Azure services. Refusing to share despite him getting initial access via the community.

**Comment by jordandadams** [comment]
> What do you mean by "is held hostage"? How would a community member obtain the name for himself? What is the third party API? Because honestly I can just make a fake account and use this API key with the third party API just to keep my app working.

Please let me know if you find, would love to get my bot working again.

**Comment by acheong08** [comment]
Closing in favor of unified thread
