### ISSUE TITLE
APIConnectionError

### ISSUE THREAD

**Issue by YQisme** [acheong08/ChatGPT#534]
> raise error.APIConnectionError(
> openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-chat-davinci-002-20230126/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol 
> (_ssl.c:1131)')))

I was able to run it yesterday, but I couldn't successfully run it today. How can I resolve this problem?

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/issues/533
