### ISSUE TITLE
[BUG] Infinite loop in get_cf_cookies and the chrome page view of "https://chat.openai.com/chat" is "Please stand by, while we are checking your browser"

### ISSUE THREAD

**Issue by OlivierShi** [acheong08/ChatGPT#535]
The program is hang by the infinite loop in get_cf-cookies function. And i debug into the response of chatgpt web page as below,
```
driver.Get("https://chat.openai.com/chat")
print(driver.page_source)
```
![image](https://user-images.githubusercontent.com/24621410/216538187-06425721-00bb-4662-9145-8f668d6bf107.png)

**Comment by acheong08** [comment]
Seems it fails to pass cloudflare. Try using official API (instructions in ReadMe)

**Comment by burakismlg53** [comment]
did you solve this problem?

**Comment by acheong08** [comment]
Not supported anymore.
