### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'tls_client'

### ISSUE THREAD

**Issue by frankShih** [acheong08/ChatGPT#536]
**Description**
Try to run the Python sample in readme.md
```python
from revChatGPT.ChatGPT import Chatbot
```
The error messages show up
```
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from revChatGPT.ChatGPT import Chatbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\revChatGPT\ChatGPT.py", line 7, in <module>
    import tls_client
ModuleNotFoundError: No module named 'tls_client'
>>>
```

**Steps to Reproduce**
1. `pip install openai==0.26.4`
2. `pip install revChatGPT==1.1.0`
3. `python`
4. `from revChatGPT.ChatGPT import Chatbot`

**Expected behavior**
Run the sample code without error

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

I execute the command above, same error occurs
And no error occurs when I execute `OfficialChatGPT -h`

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: Windows 11 21H2
 - Python version: 3.9.6 
 - ChatGPT Version: 1.1.0

**Additional context**
All I want to do is interacting with chatGPT using Python

**Comment by acheong08** [comment]
`pip3 install revChatGPT[unofficial]`

**Comment by Avnsx** [comment]
> `pip3 install revChatGPT[unofficial]`

How does this fix anything, as soon as I try using:
```python
from revChatGPT.ChatGPT import Chatbot

chatbot = Chatbot({
  "session_token": "<YOUR_TOKEN>"
}, conversation_id=None, parent_id=None) # You can start a custom conversation

response = chatbot.ask("Prompt", conversation_id=None, parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)

print(response)
``` all I get is the chromedriver window that shows me cloudflare detecting that it's an automated session

**Comment by acheong08** [comment]
> all I get is the chromedriver window that shows me cloudflare detecting that it's an automated session

Happens most of the time these days. Cloudflare is difficult to bypass. Better use the Official API (specified in readme)

**Comment by Avnsx** [comment]
@acheong08 what was the recently leaked davinci model string called again for the chatgpt version
