### ISSUE TITLE
[BUG] Unable to use the Official AsyncChatbot with ask_stream

### ISSUE THREAD

**Issue by Papawy** [acheong08/ChatGPT#537]
**Description**
I tried to use the async `ask_stream` variant of AsyncChatbot with Official API. I currently just use the `ask` function which works great but I would like to stream the answer.

**Steps to Reproduce**
I use this code:
```python
msg: discord.Message = None
  async for answer in chatgpt.ask_stream(prompt):
    if not msg:
      await message.reply(answer)
    else:
       await msg.edit(answer_msg.content + msg)
```
And I get:
```
ERROR: 'async for' requires an object with __aiter__ method, got coroutine
```

I guess I am using it wrong. I am not familiar with Python async generators.

Thanks!

**Expected behavior**
I would like to be able to stream answer asynchronously :slightly_smiling_face:.

**Output**
```
ERROR: 'async for' requires an object with __aiter__ method, got coroutine
```

**Environment**
I am using latest 1.1.1

**Comment by acheong08** [comment]
>  I am familiar with Python async generators.

I am not. Mind helping out? I don't know how streaming works with async

**Comment by Papawy** [comment]
Ah sorry. I often forgot the *not* _facepalm_. I am not familiar either.

**Comment by HelloWorldWinning** [comment]
> > I am familiar with Python async generators.
> 
> I am not. Mind helping out? I don't know how streaming works with async

https://github.com/openai/openai-python/blob/b23ecafe49133da9812d96cb693f656e0a223050/openai/api_resources/abstract/engine_api_resource.py#L239


hi,

**Comment by HelloWorldWinning** [comment]
> > I am familiar with Python async generators.
> 
> I am not. Mind helping out? I don't know how streaming works with async

https://github.com/acheong08/ChatGPT/issues/533#issuecomment-1414779079 
hi man, some one find "leaked" "official" model in your ChatGPT issues . 

i am using it. great!!!

**Comment by HelloWorldWinning** [comment]
> **Description** I tried to use the async `ask_stream` variant of AsyncChatbot with Official API. I currently just use the `ask` function which works great but I would like to stream the answer.
> 
> **Steps to Reproduce** I use this code:
> 
> ```python
> msg: discord.Message = None
>   async for answer in chatgpt.ask_stream(prompt):
>     if not msg:
>       await message.reply(answer)
>     else:
>        await msg.edit(answer_msg.content + msg)
> ```
> 
> And I get:
> 
> ```
> ERROR: 'async for' requires an object with __aiter__ method, got coroutine
> ```
> 
> I guess I am using it wrong. I am not familiar with Python async generators.
> 
> Thanks!
> 
> **Expected behavior** I would like to be able to stream answer asynchronously 🙂.
> 
> **Output**
> 
> ```
> ERROR: 'async for' requires an object with __aiter__ method, got coroutine
> ```
> 
> **Environment** I am using latest 1.1.1



https://github.com/openai/openai-python/blob/b23ecafe49133da9812d96cb693f656e0a223050/openai/api_resources/abstract/engine_api_resource.py#L239

official code

**Comment by acheong08** [comment]
I don't really know async

**Comment by acheong08** [comment]
But I have released new version which might or might not fix the bug

**Comment by HelloWorldWinning** [comment]
> But I have released new version which might or might not fix the bug

['text-chat-davinci-002-20221122']
