### ISSUE TITLE
Hope to report errors when restricted

### ISSUE THREAD

**Issue by Ukenn2112** [acheong08/ChatGPT#54]
I found that it seems to output no errors when restricted but only a json in the terminal

`{"detail":"Too many requests, please slow down"}`

**Comment by acheong08** [comment]
Need more error handling. Do you mind contributing and writing some error handlers and raise errors?

**Comment by Ukenn2112** [comment]
I just saw someone's PR perfect this part of the function https://github.com/acheong08/ChatGPT/pull/63
Thanks @snowmeow2
