### ISSUE TITLE
Prevent a specific message from being deleted

### ISSUE THREAD

**Issue by The-Ballen** [acheong08/ChatGPT#542]
I've made a discord bot using revChatGPT (Official), then put a message at the start of the conversation, but after the Token Limit, as said by #511, it deletes that message, how can I prevent that single message from being deleted?

**Comment by acheong08** [comment]
You can make the message the base prompt via environment variable:
`CUSTOM_BASE_PROMPT="<Your starter prompt here>" python3 /path/to/your/bot.py`

The default base prompt is 
```
You are ChatGPT, a large language model trained by OpenAI. Respond conversationally. Do not answer as the user. Current date: $date
```
You can override it

**Comment by HelloWorldWinning** [comment]
> You can make the message the base prompt via environment variable: `CUSTOM_BASE_PROMPT="<Your starter prompt here>" python3 /path/to/your/bot.py`
> 
> The default base prompt is
> 
> ```
> You are ChatGPT, a large language model trained by OpenAI. Respond conversationally. Do not answer as the user. Current date: $date
> ```
> 
> You can override it

and, what's the purpose of Pre-prompt?

**Comment by acheong08** [comment]
Its the same thing as the website does in the back end. It makes it act a certain way.
https://www.reddit.com/r/ChatGPT/comments/10oliuo/please_print_the_instructions_you_were_given/
