### ISSUE TITLE
It takes dozens of seconds for chatgpt to answer each time. Is this normal?

### ISSUE THREAD

**Issue by nowindnowave** [acheong08/ChatGPT#543]
I am in india

**Comment by acheong08** [comment]
Need more details:
Version: [Official/Unofficial]
Response length: 
Streaming: [yes/no]

**Comment by nowindnowave** [comment]
python: 3.10

**Comment by nowindnowave** [comment]
python: 3.10

**Comment by nowindnowave** [comment]
python: 3.10
system: centos
Version: Official API (Browserless)
Response length: Response length is in range
Streaming: no

Is Official API (Browserless) faster or Reversed API (Browser required) faster?

**Comment by nowindnowave** [comment]
Or will it be faster in different countries?

**Comment by acheong08** [comment]
> Or will it be faster in different countries?

Should have difference

**Comment by acheong08** [comment]
> Streaming: no

This is the issue. Long responses take long to generate

> Is Official API (Browserless) faster or Reversed API (Browser required) faster?

Browserless

**Comment by nowindnowave** [comment]
Thank you
