### ISSUE TITLE
Incorrect API key provided

### ISSUE THREAD

**Issue by narakai** [acheong08/ChatGPT#55]
Hi,

Thanks for the great work!
I have done !refresh and also try to login via my email & password, but still the error occurs:

{"detail":{"message":"Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}
Something went wrong!
Response is not in the correct format.

Please kindly advice.

**Comment by superswan** [comment]
Have you tried the latest commit?

**Comment by narakai** [comment]
yes, it's the latest commit.

**Comment by acheong08** [comment]
The service went down just now. It's back up

**Comment by acheong08** [comment]
Try again (with correct username and password)

**Comment by acheong08** [comment]
I haven't written handlers to check for validity of username and password

**Comment by zhwang1694** [comment]
I also meet such problem right now.
'''
{"detail":{"message":"Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}
'''

**Comment by acheong08** [comment]
Fixing right now

**Comment by acheong08** [comment]
@zhwang1694 @superswan 
I can't replicate this. Can you try again?

**Comment by superswan** [comment]
I get an error when attempting to authenticate with session key

**Comment by acheong08** [comment]
The API now blocks remote requests. I'm unsure if I can fix this

**Comment by moozilla** [comment]
I was able to fix this by adding a user agent header, will try to get a PR up

**Comment by acheong08** [comment]
Thank you so much

**Comment by zhwang1694** [comment]
@acheong08 @moozilla Thanks a lot.

**Comment by acheong08** [comment]
Fixed

**Comment by moozilla** [comment]
Looks like you beat me to it: https://github.com/moozilla/ChatGPT/commit/de86da168a962f415a2508c5fb16823827239967

**Comment by acheong08** [comment]
Superfast panic mode lol

**Comment by narakai** [comment]
Works fine now, thanks guys!

**Comment by imcda** [comment]
have update the latest version, but still got this error
```
{"detail":{"message":"Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}

```

and another alert

```
Captcha detected
```

**Comment by acheong08** [comment]
Captcha is not supported for this library as it requires writing to disk and having a desktop environment. Use https://github.com/rawandahmad698/PyChatGPT for proper Captcha support

**Comment by CheCoelho** [comment]
I am also having this issue -  I pass in my correct configuration and get a return value with the error data:  Request failed with status code 401 'Incorrect API key provided: sk----***************************************---. You can find your API key at https://beta.openai.com.'

**Comment by acheong08** [comment]
You're meant to use the session_token cookie, not API key. Read wiki/setup

**Comment by wxlund** [comment]
I am having the same error.  I just updated to GenieAI but the API KEY from ChatGPT was lost in the process.  I can not see where to input my API Key.  It prompted me the first time but I had an error with the paste and I'm lost as to where to place the correct key.  Mine shows:
`
An error occured. ChatGPT error 401: { "error": { "message": "Incorrect API key provided: Write a **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************ion.. You can find your API key at https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" } }' #

**Comment by acheong08** [comment]
For V3, use official API keys

**Comment by Okamiobidala** [comment]
Hi - So I have had this error message come up asking for a correct API key and giving me a place to find it, but when I follow the link I can't make and account or log into an existing account. I thought that I'd hit the jackpot when I found this thread but the solutions don't make sense to me - there are words and techniques I don't understand and I don't get why the app I payed for can just stop working like this : / Please - if you could - explain it to me like I'm five? I would be most grateful. - Thanks for reading

**Comment by acheong08** [comment]
> Hi - So I have had this error message come up asking for a correct API key and giving me a place to find it, but when I follow the link I can't make and account or log into an existing account. I thought that I'd hit the jackpot when I found this thread but the solutions don't make sense to me - there are words and techniques I don't understand and I don't get why the app I payed for can just stop working like this : / Please - if you could - explain it to me like I'm five? I would be most grateful. - Thanks for reading

What version are you using?

**Comment by Okamiobidala** [comment]
Version 1.2.8

Sent from my iPad

On 15 Apr 2023, at 08:10, Antonio Cheong ***@***.***> wrote:

﻿

Hi - So I have had this error message come up asking for a correct API key and giving me a place to find it, but when I follow the link I can't make and account or log into an existing account. I thought that I'd hit the jackpot when I found this thread but the solutions don't make sense to me - there are words and techniques I don't understand and I don't get why the app I payed for can just stop working like this : / Please - if you could - explain it to me like I'm five? I would be most grateful. - Thanks for reading

What version are you using?

**Comment by Okamiobidala** [comment]
Up and working now

Sent from my iPad

On 15 Apr 2023, at 08:10, Antonio Cheong ***@***.***> wrote:

﻿

Hi - So I have had this error message come up asking for a correct API key and giving me a place to find it, but when I follow the link I can't make and account or log into an existing account. I thought that I'd hit the jackpot when I found this thread but the solutions don't make sense to me - there are words and techniques I don't understand and I don't get why the app I payed for can just stop working like this : / Please - if you could - explain it to me like I'm five? I would be most grateful. - Thanks for reading

What version are you using?
