### ISSUE TITLE
Request for automatic connection

### ISSUE THREAD

**Issue by ofikodar** [acheong08/ChatGPT#550]
Hi,

I am building an app using the unofficial version and I am trying to find a way to retrieve the session token automatically when connecting to ChatGPT. The goal is to provide a minimal friction experience to the users.

I noticed that there is a different Chrome extension where the user just needs to click "connect with google" and the connection works seamlessly. I was wondering if there is a similar method or solution available for retrieving the session token automatically in ChatGPT.

Any help or guidance on this matter would be greatly appreciated. Thank you.

**Comment by acheong08** [comment]
Use Official version. You can handle the app on the backend and use API key

**Comment by acheong08** [comment]
No browsers anymore

**Comment by ofikodar** [comment]
Thanks for the quick response.
I tried to avoid the Official version since I am looking for a way to skip any additional steps for the users, such as creating or searching for their API key.

**Comment by acheong08** [comment]
What I'm saying is that you should write a back end which provides the service via your API key.
