### ISSUE TITLE
[BUG] openai.error.InvalidRequestError with engine "text-chat-davinci-002-20230126"

### ISSUE THREAD

**Issue by ofikodar** [acheong08/ChatGPT#551]
I am encountering an error when using the OpenAI API with the following code:

`completion = openai.Completion.create(
    engine="text-chat-davinci-002-20230126",
    prompt=prompt,
    temperature=0.5,
    max_tokens=4000 - int(len(prompt) / 3),
    stop=["\n\n\n"],
)`

I am receiving the error:
`openai.error.InvalidRequestError: That model does not exist`

Here is a code snippet that reproduces the error:
`from revChatGPT.Official import Chatbot

API_KEY = ''

if __name__ == '__main__':
    chatbot = Chatbot(API_KEY)
    response = chatbot.ask("this is a test")
    print(response)`

**Comment by acheong08** [comment]
Upgrade your library

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`
