### ISSUE TITLE
[BUG] Can't login, alway loop on "Found Cloudflare Cookie!"

### ISSUE THREAD

**Issue by iaston** [acheong08/ChatGPT#552]
**Description**
the config and python program:
![image](https://user-images.githubusercontent.com/11807657/216770853-812ae09a-f712-41e1-883e-e9b3a4cf20ac.png)

while running, alway ask for check if human:
![image](https://user-images.githubusercontent.com/11807657/216771650-a0a05e95-f5c6-498c-a82e-a46ac8286338.png)![image](https://user-images.githubusercontent.com/11807657/216771640-4a601c11-4136-4866-9a5b-a995c7d548a6.png)

sometime, after pass the human test, I have found it go to login page:
![image](https://user-images.githubusercontent.com/11807657/216771331-e7fe9d2f-c51c-43ec-8afc-fef70d5418ec.png)

but I,m sure the session is correctly.
![image](https://user-images.githubusercontent.com/11807657/216771608-2c5061ac-4e09-42d9-a5a0-1267c980205a.png)

System Info:
Win11 x64
Python 3.9.7
revChatGPT 1.1.3
![image](https://user-images.githubusercontent.com/11807657/216771078-6c7081bc-a47b-47fc-b31f-7ddc77299b90.png)

**Comment by acheong08** [comment]
I haven't been able to access chat.openai.com since last week.
![Screenshot from 2023-02-04 12-21-54](https://user-images.githubusercontent.com/36258159/216771726-eb999162-bd86-423e-b1a8-9ea54652f6b9.png)

I can't support it anymore. Use official API instead. Readme has been updated with instructions. It is just as free but without rate limits

**Comment by iaston** [comment]
> I haven't been able to access chat.openai.com since last week. ![Screenshot from 2023-02-04 12-21-54](https://user-images.githubusercontent.com/36258159/216771726-eb999162-bd86-423e-b1a8-9ea54652f6b9.png)
> 
> I can't support it anymore. Use official API instead. Readme has been updated with instructions. It is just as free but without rate limits

You can use a proxy to bypass the Access deny.

**Comment by getxd-dev** [comment]
I had this issue before, turning off my anti-virus for my browser fixed it (Kaspersky).
