### ISSUE TITLE
Customizable user in ask()

### ISSUE THREAD

**Issue by The-Ballen** [acheong08/ChatGPT#554]
How do I change the user? as said by #540

I'm trying `chatbot.ask(prompt, user='someone')`
which didn't work
`ask() got an unexpected keyword argument 'user'`

I just wanted to change the user for each new prompt, is this somehow possible?

**Comment by acheong08** [comment]
Hasn't been released yet

**Comment by The-Ballen** [comment]
> Hasn't been released yet

Oh, I'm sorry, I thought it already was

btw it works now, thanks
