### ISSUE TITLE
Help me with this error


### ISSUE THREAD

**Issue by Amalbro07** [acheong08/ChatGPT#561]
from revChatGPT.revChatGPT import AsyncChatbot as ChatGPT3Bot

I'm getting error like in the image ![Screenshot_2023-02-05-19-35-58-39_dce875ef40efa4e902b2719365b6f678.jpg](https://user-images.githubusercontent.com/124343610/216824219-32a0b84d-c108-41c0-80a5-e3e216faf379.jpg)

**Comment by acheong08** [comment]
`pip3 install revChatGPT`

**Comment by Amalbro07** [comment]
No such file or directory

**Comment by acheong08** [comment]
Mobile might not work. Got some dependencies that requires UNIX like system or Windows
