### ISSUE TITLE
> Most basic example (I don't know async):

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#562]
> Most basic example (I don't know async):
> 
> ```python
> from revChatGPT.Official import AsyncChatbot
> import asyncio
> 
> async def main():
>     bot = AsyncChatbot(api_key="sk-...")
>     return await bot.ask("Hello World")
> 
> if __name__ == "__main__":
>     print(asyncio.run(main()))
> ```
your origin code has error:loof is running,after i ask chatgpt,it gives me these code,but it seems that no respond,please help me
![image](https://user-images.githubusercontent.com/86822589/216825259-3301454d-ed02-4445-9359-588e6a64edd1.png)

_Originally posted by @zjrwtx in https://github.com/acheong08/ChatGPT/issues/558#issuecomment-1417966843_

**Comment by 1beb** [comment]
```
from revChatGPT.Official import Chatbot

bot = Chatbot(apikey)
r = bot.ask("How are you today?")
r
````
