### ISSUE TITLE
[Help]how to run revChatGPT official mode in Windows?

### ISSUE THREAD

**Issue by iaston** [acheong08/ChatGPT#563]
I don't know whether the official mode of revChatGPT can only run under linux? It seems that the python program should be cross-platform, but it seems that after installing pip install revChatGPT, you cannot run OfficialChatGPT -- api on the command line of Windows_ key API_ KEY --stream

Thanks for help.

**Comment by acheong08** [comment]
Windows doesn't automatically add PyPi packages to PATH

**Comment by acheong08** [comment]
As of `[tag 1.1.5](https://github.com/acheong08/ChatGPT/releases/tag/1.1.5)`, `python3 -m revChatGPT` also uses official

**Comment by iaston** [comment]
> As of [tag 1.1.5](https://github.com/acheong08/ChatGPT/releases/tag/1.1.5), `python3 -m revChatGPT` also uses official

Thanks for help.

and more, how to use proxy in command?
revchatgpt --api_key api_key --stream --proxy http://127.0.0.1:8080
(show error info)

**Comment by acheong08** [comment]
Proxy doesn't work yet
