### ISSUE TITLE
Cool project to add

### ISSUE THREAD

**Issue by ofikodar** [acheong08/ChatGPT#566]
Hey, I made this app using your repo (thanks!), 

ChatCV - Resume Builder with OpenAI ChatGPT
git: https://github.com/ofikodar/chatgpt-resume-builder
demo: https://huggingface.co/spaces/ofikodar/chatgpt-resume-builder

**Comment by acheong08** [comment]
Added. Interesting that there are many resume builders being made. This one definitely has the better interface though.

**Comment by ofikodar** [comment]
Thanks
