### ISSUE TITLE
Why there is a maximum prompt length limit in offical chatgpt implimentation

### ISSUE THREAD

**Issue by ericzhou571** [acheong08/ChatGPT#569]
Dear team,

As I was using ChatGPT, I noticed that there is a limitation on prompt length. I'm curious about why this limitation exists, and if there's a possibility of removing it.

Here are a few points to consider:

- If we send a too long input sentence, the history will be truncated (https://github.com/acheong08/ChatGPT/blob/be9307d72d1d0baf86d757950edf0bd3648a5d4d/src/revChatGPT/Official.py#L308-L319).
- According to some YouTubers' examples, ChatGPT is capable of "reading" several-page financial reports (with over 10,000 words) and summarizing each paragraph.

Thank you for your time and consideration. I look forward to hearing back from you.

Best regards,
Erich

**Comment by acheong08** [comment]
> According to some YouTubers' examples, ChatGPT is capable of "reading" several-page financial reports (with over 10,000 words) and summarizing each paragraph.

Not true

**Comment by acheong08** [comment]
What I believe they are doing is passing each paragraph through sequentially

**Comment by acheong08** [comment]
There is 4000 token limit on the base model.

iirc they used to have 8000 token limit on the website but that has since changed to 4000 as well

**Comment by acheong08** [comment]
> I'm curious about why this limitation exists

It is a token limit of the model. Anything over and it would overflow their allocated memory

**Comment by ericzhou571** [comment]
> What I believe they are doing is passing each paragraph through sequentially

Thanks a lot for quick relying!
