### ISSUE TITLE
Reference to 'Official' not found in '__init__.py'

### ISSUE THREAD

**Issue by 17Reset** [acheong08/ChatGPT#570]
when I installed revChatGPT via pip, I can't introduce this sentence in python file correctly, what is the problem, I am a newbie, thanks a lot
![image](https://user-images.githubusercontent.com/122418720/216877947-b5d1d49f-8426-44ea-840f-a7bdf0e97286.png)

**Comment by acheong08** [comment]
Your IDE isn't picking it up. Open an issue with them. Out of scope
