### ISSUE TITLE
tiktoken ?

### ISSUE THREAD

**Issue by hafidzaini** [acheong08/ChatGPT#573]
when install it, i get error 

 Could not find a version that satisfies the requirement tiktoken (from revChatGPT) (from versions: )
No matching distribution found for tiktoken (from revChatGPT)

**Comment by Hashimlokasher** [comment]
I rerun this command and it worked
'pip3 install revChatGPT'

**Comment by hafidzaini** [comment]
i rerun as you suggest, now revChatGPT installed, but still no tiktoken so revChatGPT still cant run

![Screenshot 2023-02-06 at 3 38 29 PM](https://user-images.githubusercontent.com/17491023/216924168-c29d89e5-4c17-479f-92a0-5ec9035a58e8.png)


> I rerun this command and it worked 'pip3 install revChatGPT'

**Comment by Manamama** [comment]
Just run: 
`pip install tiktoken`
or whatever you may be missing.

**Comment by hafidzaini** [comment]
problem solve after upgrade python3.7 to 3.8

**Comment by helloworldcoding** [comment]
@hafidzaini  thanks
