### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by QiuZiXian** [acheong08/ChatGPT#574]
**Description**
env: win11+python3.9+ChatGPT1.1.5;
1. I try to load history by 'chatbot.prompt.chat_history', but it return empty list.
2. I try to set the conversation_id,  to implement multiple rounds of dialogue. but fail

**Steps to Reproduce**
fix Officical.py
after  chatbot = Chatbot(api_key=args.api_key)
before while True
new a conversion_id, like conversion_id="test-123"
then
modify 473 line  response = chatbot.ask(prompt, temperature=args.temperature)
to response = chatbot.ask(prompt,conversation_id=conversation_id, temperature=args.temperature)
final 
run main.py (set api-key)

1. after many conversations， I send !load_c （or first !save_c then !load_c），but return empty list
2. after many conversations，I try  chatbot.prompt.chat_history，but return empty list

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/discussions/521#discussioncomment-4878935

**Comment by acheong08** [comment]
It takes 4 commands right now:
1. `!save_c example`
2. `!save_f example`
3. `!load_f example`
4. `!load_c example`

**Comment by acheong08** [comment]
Open a pull request if you can write something to simplify this
