### ISSUE TITLE
chrome not reachable，help

### ISSUE THREAD

**Issue by andysdc** [acheong08/ChatGPT#576]
'unknown error: cannot connect to chrome at 127.0.0.1:52302 from chrome not reachable'

chrome版本：版本 109.0.5414.119（正式版本） (x86_64)
chromedriver -> /usr/local/Caskroom/chromedriver/109.0.5414.74/chromedriver

**Comment by acheong08** [comment]
Are you in a virtual environment such as conda?

**Comment by acheong08** [comment]
Also, please note that the Official API is available. The unofficial API is no longer actively supported by myself due to IP blocks

**Comment by andysdc** [comment]
> Are you in a virtual environment such as conda?

yes

**Comment by andysdc** [comment]
> Also, please note that the Official API is available. The unofficial API is no longer actively supported by myself due to IP blocks

Tried. Unfortunately， the chatgpt version is too low.

**Comment by acheong08** [comment]
> > Are you in a virtual environment such as conda?
> 
> yes

Conda blocks Python from accessing Chrome in my experience

**Comment by acheong08** [comment]
> > Also, please note that the Official API is available. The unofficial API is no longer actively supported by myself due to IP blocks
> 
> Tried. Unfortunately， the chatgpt version is too low.

What do you mean? If there is a bug with the official version, I will try to fix it.

**Comment by andysdc** [comment]
> > > Also, please note that the Official API is available. The unofficial API is no longer actively supported by myself due to IP blocks
> > 
> > 
> > Tried. Unfortunately， the chatgpt version is too low.
> 
> What do you mean? If there is a bug with the official version, I will try to fix it.

No bug, but the the official version is "text-chat-davinci-002-20221122",  not the latest version

**Comment by chenlikun** [comment]
> > > Are you in a virtual environment such as conda?
> > 
> > 
> > yes
> 
> Conda blocks Python from accessing Chrome in my experience

Hello,  I don't use conda,  but appeared same error.

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at [127.0.0.1:37674](http://127.0.0.1:37674/)

**Comment by acheong08** [comment]
You might have to define the chromedriver path manually in the config

**Comment by hafidzaini** [comment]
any sample with this?
sorry noob question 😂🙏
i was using browserless but cost money 😰
want to try browser version but having this same error

**Comment by hafidzaini** [comment]
on unofficial.py contain :
   self.session = tls_client.Session(
            client_identifier="chrome_108",
        )

is the error happen because we use latest chrome 110 ?

toor@chatgpt:~$ google-chrome --version
Google Chrome 110.0.5481.77

🤔

**Comment by acheong08** [comment]
Install chrome driver

**Comment by hafidzaini** [comment]
oh ok, i thought it was already installed by requirement.txt

**Comment by acheong08** [comment]
Python cannot install drivers automatically

**Comment by hafidzaini** [comment]
i see.
latest Selenium suggest using webdriver-manager to auto install the driver.
[](https://pypi.org/project/webdriver-manager/)
i will try install it manually.

**Comment by hafidzaini** [comment]
spec
OS : debian 11
python : Python 3.9.2
selenium : Version: 4.8.0
undetected-chromedriver : Version: 3.4.5
google chrome : Google Chrome 110.0.5481.77
chrome driver : ChromeDriver 104.0.5112.20

config json
{
  "email": "xxx@xxx",
  "password": "xxxx",
  "driver_exec_path": "/home/xuser/chromedriver"
}

still no luck
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:47045
from chrome not reachable

**Comment by hafidzaini** [comment]
apt install xvfb -y (or what ever your OS is)
export DISPLAY=:1
Xvfb $DISPLAY -screen $DISPLAY 1280x1024x16 &

no problem with chrome connection 
but stuck on browser spawned.

toor@chatgpt:~$ python3 test.py
Spawning browser...
Browser spawned.

😰
