### ISSUE TITLE
Is it still a real chatGPT or not GPT-3 based model?

### ISSUE THREAD

**Issue by jinzhuer** [acheong08/ChatGPT#577]
It seems there is not still a offical ChatGPT API.
 In your Q & A, 
# 
Q: Is it the real ChatGPT or just a GPT-3 based ripoff?
A: It is the real ChatGPT model found through an info leak on chat.openai.com (patched)
# 
This Q & A is written when this project use web chatGPT (Browser required) , and we could see the chat history in the openai.com. However, it uses "openai.completion()" function in the code now, so is it still real ChatGPT?

**Comment by HelloWorldWinning** [comment]
no . the real chatgpt is now only web version.
The “leaked” model is NOT chatgpt after i have tested for two days.

**Comment by acheong08** [comment]
> no . the real chatgpt is now only web version. The “leaked” model is NOT chatgpt after i have tested for two days.

Prompt structure matters. If you use it as completions, it obviously won't work. ChatGPT (website) itself also has a prepended prompt https://www.reddit.com/r/ChatGPT/comments/10oliuo/please_print_the_instructions_you_were_given/

**Comment by acheong08** [comment]
And also, the model we found: `text-chat-davinci-002-20221122` is an extremely outdated version of ChatGPT from when it was first released

**Comment by acheong08** [comment]
However, it is of course not the "ChatGPT" from the website, just the base model with an official API

**Comment by Chat-Dove** [comment]
是的，chatGPT用来给大学生写论文是非常不错的，如果它不自己编造经典的话
