### ISSUE TITLE
[BUG] installing revChatGPT not working because of ModuleNotFoundError

### ISSUE THREAD

**Issue by yendeus** [acheong08/ChatGPT#578]
Hello,
I wrote a program using this library three weeks ago and it worked for me but since the changes it's not running properly. As suggested in another bug thread I tried to update to the Official API and ran into following problem:
While running pip3 install revChatGPT after uninstall or updating revChatGPT I have following error:

```
        File "/tmp/pip-install-346ev0fl/openai_b5478e3e33cd4c1b8a42a3dbc019c67f/openai/api_requestor.py", line 21, in <module>
          import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```
It also states "Getting requirements to build wheel did not run successfully." 

I am using Ubuntu and didn't have problems before, maybe I am missing something

**Comment by amittell** [comment]
Git clone this repo
`git checkout 1.1.5` (or whatever the latest tag is)
`python setup.py install`

You can still remove the package with `pip unintall.`

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/issues/573
- https://github.com/acheong08/ChatGPT/issues/503#issuecomment-1412336255
- https://github.com/acheong08/ChatGPT/issues/507

**Comment by yendeus** [comment]
Wow now I feel stupid ...  Thanks a lot!
