### ISSUE TITLE
[BUG] Incomplete documentation?

### ISSUE THREAD

**Issue by Manamama** [acheong08/ChatGPT#580]
**Description**
Out of curiosity, I have also run revChatGPT on a local computer. 
End-user "newbie" comments: 

* Improve [the instructions/configuration/setup guide](https://github.com/acheong08/ChatGPT/wiki/Setup) from: 

> Copy the session token value in __Secure-next-auth.session-token
> Paste it into config.json in the current working directory

->

> * Copy the session token value in __Secure-next-auth.session-token
> * In the current working directory run: 
> `echo "{ 'session_token': '<YOUR_TOKEN>' }" >> config.json`
or like (nano, gedit) for greater clarity.

* Even after doing all this and having e.g. the 
```
echo "export OPENAI_API_KEY='<API_KEY>'" >> ~/.zshc && source ~/.zshrc
 && echo $OPENAI_API_KE
```
preset, still:
`python3 -m revChatGPT`
throws up: 
```
    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press enter twice to submit your question.

usage: __main__.py [-h] --api_key API_KEY [--stream] [--temperature TEMPERATURE]
__main__.py: error: the following arguments are required: --api_key

```

For now I have hacked it with: 
`python3 -m revChatGPT --api_key <API_KEY>`
and it runs fine, but surely I misunderstand one of the preceding steps. 
The other "newbie" users may as well.

**Comment by acheong08** [comment]
The wiki is outdated. Read the README

**Comment by acheong08** [comment]
> python3 -m revChatGPT --api_key <API_KEY>

Yes, that is how you run it

**Comment by Manamama** [comment]
Thanks for [reacting to it now](https://github.com/acheong08/ChatGPT/wiki/): my "naive end-user" QC has thus worked ;). Let us close it then.
