### ISSUE TITLE
Found this ChatGPT api on RapidApi

### ISSUE THREAD

**Issue by thevisualizer** [acheong08/ChatGPT#581]
I used this ChatGPT Api on rapidapi. This one is quite useful if you don't want to work with any code.
https://rapidapi.com/markascensio28/api/chatgpt-conversation-api/

**Comment by Hyperz** [comment]
So you uploaded this (or a similar) library to RapidAPI in an attempt to fleece money out of people, and thought it was a good idea to advertise it here? The project was added 6 hours ago, and this issue was opened 5 hours ago... I hope you get reported and banned.

**Comment by acheong08** [comment]
It's fine to use this library commercially. Advertising isn't nice though unless you're open source.
