### ISSUE TITLE
"[BUG]stash: <class 'stashutils.wheels.WheelError'>: top_level.txt entry 'GPTserver' not found in toplevel directory!" When trying to install the package on pythonista iPad

### ISSUE THREAD

**Issue by bigplayer-ai** [acheong08/ChatGPT#582]
**Description**
I am trying to install: https://github.com/lencx/ChatGPT
When I try to install your [pure python project (chatgpt)](https://github.com/lencx/ChatGPT) on pythonista on my iPad I receive this error:
stash: <class 'stashutils.wheels.WheelError'>: top_level.txt entry 'GPTserver' not found in toplevel directory!

**Steps to Reproduce**
1. Go to Pythonista iPad
2. Install [stash](https://github.com/ywangd/stash)
3. launch stash
4. enter the command:
pip install revChatGPT
5. receive the error:
stash: <class 'stashutils.wheels.WheelError'>: top_level.txt entry 'GPTserver' not found in toplevel directory!
**Expected behavior**
To install chatgpt API on my iPad
**Output**

stash: <class 'stashutils.wheels.WheelError'>: top_level.txt entry 'GPTserver' not found in toplevel directory!
**Environment**
Pythonista Application on iPad

 - OS: iPadOS 16.3
 - Python version: python 3
 - ChatGPT Version: Not succeeding to install.

**Comment by acheong08** [comment]
iPad not supported
