### ISSUE TITLE
Account bans

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#583]
> My account was banned after frequently using the official API. Getting message 
> 
```
openai.error.RateLimitError: Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact support@openai.com.
```
> Is there a hard limit on how many requests we can send to the model before the account gets banned?

_Originally posted by @reveching in https://github.com/acheong08/ChatGPT/issues/533#issuecomment-1420154001_

**Comment by fukemy** [comment]
it's seem dangerous when using this lib

**Comment by acheong08** [comment]
> it's seem dangerous when using this lib

It's not the library but what you do with the library. If you break their TOS, you will get suspended

**Comment by waylaidwanderer** [comment]
Don't use it for NSFW or racist/hateful/violent stuff if you want to avoid bans. You can do it anyway - bans are infrequent (based on your luck) - but know the risks.

**Comment by acheong08** [comment]
@xyxxmb has also been banned. This could be a severe issue

**Comment by acheong08** [comment]
@xyxxmb did you try to do anything NSFW or against TOS?

**Comment by waylaidwanderer** [comment]
2 banned accounts out of who knows how many thousands of users without knowing what they did with the API seems like a non-issue to me

**Comment by acheong08** [comment]
> 2 banned accounts out of who knows how many thousands of users, without knowing what they did with the API, seems like a non-issue to me

3 more contacted me via email

**Comment by waylaidwanderer** [comment]
I edited my comment 😉

**Comment by BY1998** [comment]
Has this bug been solved?My project still reports this error.

**Comment by bigplayer-ai** [comment]
Can you add what were they doing with the API and which API they were using?

**Comment by acheong08** [comment]
No idea

**Comment by BY1998** [comment]
> Can you add what were they doing with the API and which API they were using?

I used chatbot.ask API,Python file is Official

**Comment by reveching** [comment]
chatbot.ask and the prompts involve tricking the model to generate the original prompts that were used to train ChatGPT and that might have some TOS issues. Also don't call the api too frequently i think there was a rate limit. Actually, that's not a problem anymore since the model is dead anyway?

**Comment by xyxxmb** [comment]
> @xyxxmb did you try to do anything NSFW or against TOS?

No, I only tried the order: python3 -m revChatGPT.Official --api_key API_KEY --stream
