### ISSUE TITLE
can't get openAI api keys

### ISSUE THREAD

**Issue by gnohgnailoug** [acheong08/ChatGPT#584]
when i try to get new api keys, the page shows that 'Not available' though i use a VPN. Does this mean my IP has been blocked?
![image](https://user-images.githubusercontent.com/69443774/217173726-367231be-1f6b-4f22-b397-e522b4a05d83.png)

**Comment by acheong08** [comment]
What's your IP location? Got to connect to US endpoint preferably

**Comment by gnohgnailoug** [comment]
> What's your IP location? Got to connect to US endpoint preferably

I used US endpint indeed, but the promblem still exists

**Comment by gnohgnailoug** [comment]
this page shows 'You are being rate limited.'
![image](https://user-images.githubusercontent.com/69443774/217176032-75ed9b6a-4144-4b8c-9f7e-5490e723f2ed.png)

**Comment by acheong08** [comment]
Your VPN is blocked. Might need to use a private VPN (dedicated IP)

**Comment by gnohgnailoug** [comment]
> Your VPN is blocked. Might need to use a private VPN (dedicated IP)

Thanks to your reply! That's really helpful : ) . Could you recommend a private VPN? I know nothing about it
