### ISSUE TITLE
If I pay for ChatGPT Plus, can this API call ChatGPT Plus with the paid key?

### ISSUE THREAD

**Issue by jrnzefxx475** [acheong08/ChatGPT#586]
May I ask if the official version of the api uses the account key of the paid version（ChatGPTPlus） of chatGPT, can it call the resources of the paid version?
The current openAI official free version is too unstable, I want to try to pay for this service to get a better experience (chatGPTplus). Not sure if this idea is feasible?
I don't often ask questions on github, hope my question doesn't offend.

**Comment by acheong08** [comment]
ChatGPT Plus is not supported here as I don't have it myself for testing. Based on the tests of other people, it uses a different model (I don't know the name)

**Comment by acheong08** [comment]
If you want a more reliable experience, you should check out the [base model API](https://github.com/acheong08/ChatGPT/blob/main/README.md#base-model-api-browserless). It has pretty much 100% uptime and a rate limit of 50 requests per minute.

**Comment by jrnzefxx475** [comment]
> 如果您想要更可靠的体验，您应该查看[基本模型 API](https://github.com/acheong08/ChatGPT/blob/main/README.md#base-model-api-browserless)。它有几乎 100% 的正常运行时间和每分钟 50 个请求的速率限制。

Thank you for your answer
