### ISSUE TITLE
[BUG] When Python is less than version 3.9, Official.py cannot be run.

### ISSUE THREAD

**Issue by Zrincet** [acheong08/ChatGPT#587]
In Official.py, Line 70
https://github.com/acheong08/ChatGPT/blob/e2f30d10fed4f60ba4246fa23fa3e9bcf48df41d/src/revChatGPT/Official.py#L70

`removesuffix` is a 3.9+ method in str. In previous versions, str doesn't have a removesuffix attribute. When Python version < 3.9, there is an error:

`AttributeError: 'str' object has no attribute 'removesuffix'`

**Comment by acheong08** [comment]
Upgrade your Python version. The reason for using `removesuffix` is explained here:
- https://github.com/acheong08/ChatGPT/pull/575

**Comment by Zrincet** [comment]
@acheong08 In https://stackoverflow.com/a/66683635/10985361, there are two ways to solve this problem.

Use pathlib or Create a method:
```py
def remove_suffix(input_string, suffix):
    if suffix and input_string.endswith(suffix):
        return input_string[:-len(suffix)]
    return input_string
```

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.1.7
