### ISSUE TITLE
In Official version，How to use REST API

### ISSUE THREAD

**Issue by CNWann** [acheong08/ChatGPT#588]
In Official version，I want to use REST API,
But I can't find configuration documents,
I tried to use revApiGPT  to run server and configured config.json, but it didn't work。

Traceback (most recent call last):
  File "/usr/local/bin/revApiGPT", line 5, in <module>
    from revChatGPT.GPTserver import main
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/GPTserver.py", line 11, in <module>
    chatbot = Chatbot(config={}, conversation_id=None, parent_id=None, no_refresh=True)
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 93, in __init__
    raise Exception("Invalid config!")
Exception: Invalid config!

**Comment by acheong08** [comment]
The GPTserver is for the unsupported version. Haven't updated it yet

**Comment by acheong08** [comment]
You don't really need an API server as the official version is just a wrapper around OpenAI's public API

**Comment by CNWann** [comment]
Thks, for some reason, I can't use OpenAI's public API directly, So I want to use the wrapper REST API
