### ISSUE TITLE
[BUG]That model does not exist 

### ISSUE THREAD

**Issue by itqzy** [acheong08/ChatGPT#590]
![image](https://user-images.githubusercontent.com/45928094/217206581-66573b87-1204-4881-8201-a277156f170a.png)
This is my file
![image](https://user-images.githubusercontent.com/45928094/217206800-7570fefc-558a-459c-84f2-ef292b4c83c3.png)
Looking forward to reply Thank you

**Comment by acheong08** [comment]
What's your `revChatGPT` version?

`pip3 show revChatGPT`

**Comment by acheong08** [comment]
Still works for me

**Comment by itqzy** [comment]
This is my version
![image](https://user-images.githubusercontent.com/45928094/217210087-e4f5d7bc-74fc-4263-894f-de5bc1f7b320.png)

**Comment by acheong08** [comment]
It's outdated significantly.

Do `pip3 install --upgrade revChatGPT`

**Comment by itqzy** [comment]
Is there a problem with the source I updated
![image](https://user-images.githubusercontent.com/45928094/217215113-eefb5d5a-41ca-47b8-9461-8c5f57db17a2.png)

**Comment by acheong08** [comment]
`pip3 uninstall revChatGPT` 
`pip3 install revChatGPT`

**Comment by ITerydh** [comment]
I also have this problem. It seems that `tiktoken` do not be installed.

**Comment by thinkforanameissohard** [comment]
> 

I ran into this bug too. How does `tiktoken` get installed?

**Comment by thinkforanameissohard** [comment]
> I also have this problem. It seems that `tiktoken` do not be installed.

I ran into this bug too. How does `tiktoken` get installed?

**Comment by chuanhhoang** [comment]
Any update?

**Comment by PositiveVibe** [comment]
I just updated to the latest and still got this. I would suspect its because of the model version described on line 13 here: https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/Official.py

When I ran this command to set an environment variable to the default davinci 003 model, I was able to get it to work.
`export GPT_ENGINE=text-davinci-003`

**Comment by PositiveVibe** [comment]
> > I also have this problem. It seems that `tiktoken` do not be installed.
> 
> I ran into this bug too. How does `tiktoken` get installed?

`pip3 install tiktoken`

or 

`pip install tiktoken`

depending on your version of pip.

**Comment by acheong08** [comment]
The model has been pulled

**Comment by acheong08** [comment]
We are working towards finding a new solution

**Comment by acheong08** [comment]
It's back
