### ISSUE TITLE
"Connection broken: ConnectionResetError(104, 'Connection reset by peer')"“

### ISSUE THREAD

**Issue by xjd-ziyu** [acheong08/ChatGPT#593]
Excuse me, has anyone encountered this problem? Is it because I use api key to visit too often?or because the official server resources are unstable?
If anyone knows the reason for this, I will be grateful.

**Comment by acheong08** [comment]
Looks like a network issue on your end

**Comment by acheong08** [comment]
Are OpenAI's websites blocked in your country?

**Comment by HackerDogo** [comment]
prob a network issue
