### ISSUE TITLE
[BUG] ModuleNotFoundError in GPTserver.py

### ISSUE THREAD

**Issue by Dorian25** [acheong08/ChatGPT#598]
**Description**
When I run the flask app in `GPTserver.py`, i have this error : 
```
Feb 7 09:47:43 PM      from revChatGPT.ChatGPT import Chatbot
Feb 7 09:47:43 PM  ModuleNotFoundError: No module named 'revChatGPT.ChatGPT'
```
I run your source code not using your module `revChatGPT`

**Steps to Reproduce**
1. Go to into the folder `src/revChatGPT`
2. run `python3 GPTServer.py`

**Expected behavior**
No need to put `revChatGPT` in  `from revChatGPT.ChatGPT import Chatbot`
You can replace by `from Official import Chatbot`, i mean `from Unofficial import Chatbot` because the Chatbot doesn't have `config` argument/attribute in his `init`

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: Windows
 - Python version: 3.9.1
 - ChatGPT Version: last release (source code)

**Comment by tjboudreaux** [comment]
I am encountering this issue as well.

**Comment by acheong08** [comment]
Solved
