### ISSUE TITLE
[BUG] Flask not in requirements.txt

### ISSUE THREAD

**Issue by Dorian25** [acheong08/ChatGPT#599]
**Description**
the `Flask` module is not present in the requirements.txt

**Steps to Reproduce**
1. See the requirements.txt

**Expected behavior**
Add `Flask` in `requirements.txt`

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`

**Environment**
Please update your packages before reporting the issue:
`pip3 install --upgrade revChatGPT`

 - OS: Windows
 - Python version: 3.9.1
 - ChatGPT Version: last release (source code)

**Comment by acheong08** [comment]
You're not meant to use requirements.txt. It's part of `setup.py`
