### ISSUE TITLE
[BUG] InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by takiholadi** [acheong08/ChatGPT#600]
Again this error

**Comment by Absence000** [comment]
I think openAI is trying to shut this down again, I'm switching over to GPT-3 temporarily

**Comment by ydamni** [comment]
Same here, happened just now

**Comment by ediziks** [comment]
Same here as well. Possible change of the model name by OpenAI?

**Comment by amittell** [comment]
Yup dead again :(

**Comment by soleimanian** [comment]
same here

**Comment by Absence000** [comment]
this isn't good, I just tried using @canfam's code to brute force test thousands of models and none of them worked

**Comment by pcrouthers** [comment]
I've tested all dates (if that's what it was) from 2020 all through to 2024 and no valid models on the text-devinci-002 so not sure what to make of that :(

**Comment by Absence000** [comment]
same with davinci-001

**Comment by xsa-dev** [comment]
official channel closed?

**Comment by chuanhhoang** [comment]
> try:
> 
> ```
> export GPT_ENGINE=text-davinci-003
> ```
> 
> and
> 
> ```
> pip3 install tiktoken
> ```

Obviously it should work. But then you have to pay for it. The cost would probably be high, obviously substantially higher than chatgpt plus if you use it daily.

**Comment by SEQOU** [comment]
I've been running with the theory that maybe these could be a possibility for the one running on the website.  I've not attempted a brute-force method yet but if anyone wants to try them feel free. 

Note: Assumed 'date' is for the most recent update from the website displayed at the bottom. 

"text-chat-openai-gpt-20230130"
"openai-text-chat-gpt-20230130"
"gpt-text-chat-openai-20230130"

**Comment by xsa-dev** [comment]
Not work for me((

> I've been running with the theory that maybe these could be a **possibility** for the one running on the website. I've not attempted a brute-force method yet but if anyone wants to try them feel free.
> 
> **_Note: 'date' is for the most recent update from the website displayed at the bottom._**
> 
> * "text-chat-openai-gpt-20230130"
> * "openai-text-chat-gpt-20230130"
> * "gpt-text-chat-openai-20230130"
> * "text-openai-chatgpt-20230130"
> * "openai-chatgpt-text-20230130"
> * "chatgpt-openai-text-20230130"
> * "openai-gpt-text-chat-20230130"
> * "gpt-openai-text-chat-20230130"
> * "chat-openai-gpt-text-20230130"
> * "text-chat-openai-gpt-model-20230130"
> * "openai-text-chat-gpt-version-20230130"
> * "chatgpt-openai-text-model-20230130"
> * "bing-text-chat-microsoft"
> * "microsoft-bing-text-chat"
> * "text-microsoft-bing-chat"
> * "text-chat-microsoft-bing"

**Comment by martysl** [comment]
azure 
![image](https://user-images.githubusercontent.com/78570936/217391860-c45530b7-4c5d-4eb2-8ad9-801a15d41914.png)

**Comment by acheong08** [comment]
Yes. Currently running extensive brute force

**Comment by jordandadams** [comment]
> Yes. Currently running extensive brute force

Thank you for all you do!

**Comment by acheong08** [comment]
```python
import openai
import concurrent.futures
import os
from revChatGPT.Official import Chatbot

defaultModel = "chat-davinci-002-XXXXXXXX"
successfulModels = []

def test_model(model):
    try:
        bot = Chatbot(api_key="...", engine=model)
        response = bot.ask("say this is a test")
        if response:
            successfulModels.append(model)
    except openai.InvalidRequestError:
        print("Model [" + model + "] failed to load. (Invalid Request Error)")

with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
    for year in range(2022, 2024):
        for month in range(1, 13):
            for day in range(1, 32):
                formatted_year = "{:04d}".format(year)
                formatted_month = "{:02d}".format(month)
                formatted_day = "{:02d}".format(day)
                model = defaultModel.replace("XXXXXXXX", formatted_year + formatted_month + formatted_day)
                executor.submit(test_model, model)

print("Successful Models: " + str(successfulModels))
```

Can tweak this a bit to brute force things other than date

**Comment by acheong08** [comment]
Currently no date available. I'm assuming they changed the naming scheme

**Comment by enterprise-apis** [comment]
> azure ![image](https://user-images.githubusercontent.com/78570936/217391860-c45530b7-4c5d-4eb2-8ad9-801a15d41914.png)

Where on Azure is this?

**Comment by acheong08** [comment]
> Where on Azure is this?

For people that bought the OpenAI service

**Comment by acheong08** [comment]
Not having any luck brute forcing. I'll overhaul the browser version first

**Comment by mccoydj1** [comment]
> > Where on Azure is this?
> 
> For people that bought the OpenAI service

What does the screenshot mean exactly? Is that the prefix?

**Comment by acheong08** [comment]
Seems to be the model name used internally

**Comment by acheong08** [comment]
We don't have access to it

**Comment by ShengdingHu** [comment]
Any ideas？Does anyone have ChatGPT Plus account？

**Comment by izhx** [comment]
> Any ideas？Does anyone have ChatGPT Plus account？

@acheong08 : "[I'm overhauling the browser based version and working towards a proxy service to remove the need for a browser.](https://twitter.com/GodlyIgnorance/status/1623125287318990848)" 

@ShengdingHu

**Comment by wzqstudio** [comment]
make some change in Official.py
#ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"
ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"

**Comment by ComEyt** [comment]
> ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"

work for me

**Comment by Johnny-Zhang92** [comment]
> ```python
> import openai
> import concurrent.futures
> import os
> from revChatGPT.Official import Chatbot
> 
> defaultModel = "chat-davinci-002-XXXXXXXX"
> successfulModels = []
> 
> def test_model(model):
>     try:
>         bot = Chatbot(api_key="...", engine=model)
>         response = bot.ask("say this is a test")
>         if response:
>             successfulModels.append(model)
>     except openai.InvalidRequestError:
>         print("Model [" + model + "] failed to load. (Invalid Request Error)")
> 
> with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
>     for year in range(2022, 2024):
>         for month in range(1, 13):
>             for day in range(1, 32):
>                 formatted_year = "{:04d}".format(year)
>                 formatted_month = "{:02d}".format(month)
>                 formatted_day = "{:02d}".format(day)
>                 model = defaultModel.replace("XXXXXXXX", formatted_year + formatted_month + formatted_day)
>                 executor.submit(test_model, model)
> 
> print("Successful Models: " + str(successfulModels))
> ```
> 
> Can tweak this a bit to brute force things other than date

Successful Models: []         🤣

**Comment by pengzhile** [comment]
> make a change in Official.py
> #ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"
> ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"

and here

> #ENCODER = tiktoken.get_encoding("gpt2")
> ENCODER = tiktoken.get_encoding("p50k_base")

Otherwise, there is a problem with the calculation of the token length, which will cause problems with the context.

**Comment by coolmian** [comment]
> try:
> 
> ```
> export GPT_ENGINE=text-davinci-003
> ```
> 
> and
> 
> ```
> pip3 install tiktoken
> ```

if we use text-davinci-003
this code is wrong.

```
            if response["choices"][0]["text"] == "<|im_end|>":
                break
```

Openai does not return by the whole word, but is divided into different parts
```
<|im
_
end
|
>
```

**Comment by shuqinlee** [comment]
It is easy for Openai to not put ChatGPT model onto API, or add some admission mechanism to it, so potentially difficult to use it again? 
But thanks @acheong08  anyways, we have experienced it for some time.

**Comment by QiuZiXian** [comment]
> > ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"
> 
> work for me

work for me too

**Comment by txtspam** [comment]
> 

can you elaborate it more and what is the solution thank you

**Comment by BISON7777** [comment]
> 尝试：
> 
> ```
> export GPT_ENGINE=text-davinci-003
> ```
> 
> 和
> 
> ```
> pip3 install tiktoken
> ```

It works for me

**Comment by ediziks** [comment]
Just be careful when using `text-davinci-003` since it's not a free model as chatGPT. You might face with an unexpected billing if there's a payment method defined. Specially without a hard limit

**Comment by Liu-Angelo** [comment]
> 
I tried all the models and they didn't work

**Comment by txtspam** [comment]
maybe maybe those who has chatgpt plus and bruteforce its model and provide to everyone its api. just maybe what you think guys? hmmm

**Comment by wzqstudio** [comment]
> > ```python
> > import openai
> > import concurrent.futures
> > import os
> > from revChatGPT.Official import Chatbot
> > 
> > defaultModel = "chat-davinci-002-XXXXXXXX"
> > successfulModels = []
> > 
> > def test_model(model):
> >     try:
> >         bot = Chatbot(api_key="...", engine=model)
> >         response = bot.ask("say this is a test")
> >         if response:
> >             successfulModels.append(model)
> >     except openai.InvalidRequestError:
> >         print("Model [" + model + "] failed to load. (Invalid Request Error)")
> > 
> > with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
> >     for year in range(2022, 2024):
> >         for month in range(1, 13):
> >             for day in range(1, 32):
> >                 formatted_year = "{:04d}".format(year)
> >                 formatted_month = "{:02d}".format(month)
> >                 formatted_day = "{:02d}".format(day)
> >                 model = defaultModel.replace("XXXXXXXX", formatted_year + formatted_month + formatted_day)
> >                 executor.submit(test_model, model)
> > 
> > print("Successful Models: " + str(successfulModels))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can tweak this a bit to brute force things other than date
> 
> Successful Models: [] 🤣

Successful Models: []

**Comment by coolmian** [comment]
@txtspam My temporary solution is
```
            if (response["choices"][0]["text"] == "<|im_end|>"
                    or response["choices"][0]["text"].strip() == "<|im"):
                break
```

**Comment by Liu-Angelo** [comment]
> maybe maybe those who has chatgpt plus and bruteforce its model and provide to everyone its api. just maybe what you think guys? hmmm

There is a chatgpt plus model available, or a paid trial

**Comment by txtspam** [comment]
> > maybe maybe those who has chatgpt plus and bruteforce its model and provide to everyone its api. just maybe what you think guys? hmmm
> 
> There is a chatgpt plus model available, or a paid trial

yeah but chatgpt plust is different from the trial of openai. it is unlimited if you get base mode from just like the leak that has been shutdown lately... maybe if those person who has a chatgpt plus and someone bruteforce its model and he gives its api access but just maybe we dont know if it is worked like that lol..

**Comment by txtspam** [comment]
heres the temporalily working Official.py solution but it costs you:

from
ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"
to
ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"

from
ENCODER = tiktoken.get_encoding("gpt2")
to
ENCODER = tiktoken.get_encoding("p50k_base")

from
if response["choices"][0]["text"] == "<|im_end|>":
                break

to
if (response["choices"][0]["text"] == "<|im_end|>"
                    or response["choices"][0]["text"].strip() == "<|im"):
                break

hopes it helps for a while

thanks and credits to
[pengzhile](https://github.com/pengzhile)
[coolmian](https://github.com/coolmian)

**Comment by cuongitl** [comment]
this is worked

**Comment by cuongitl** [comment]
This is worked:

`from revChatGPT.Official import Chatbot

client = Chatbot('openai-api', engine='text-davinci-003')

resp = client.ask("What is chatGPT version?")

print(resp)
`
But, costs credit with engine='text-davinci-003'
Be careful.

**Comment by acheong08** [comment]
Model works again

**Comment by acheong08** [comment]
Maintenance from OpenAI

**Comment by txtspam** [comment]
> Maintenance from OpenAI

thank you for the effort much love <3

**Comment by innocentius** [comment]
Naisu.

**Comment by MarcosFP97** [comment]
Hi everyone, 

I saw that the model works again, but I am experiencing the same error over and over again:

```
from revChatGPT.Official import Chatbot

chatbot = Chatbot(api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxx)

response = chatbot.ask("Say hi", temperature=0)

response = response['choices'][0]['text']+'\n'

print(response)
```
InvalidRequestError: That model does not exist
