### ISSUE TITLE
Always loop to Browser spawned

### ISSUE THREAD

**Issue by CNWann** [acheong08/ChatGPT#604]
In v1.2.1,chrome 110.0.5481.78, spawning browser an infinite loop after successful login

Logging in...
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Found Session Token!
Login successful.
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!

**Comment by leolrg** [comment]
same

**Comment by acheong08** [comment]
Might be a bad session token. Try using email/password authentication

**Comment by acheong08** [comment]
Could also be that the cf_clearance is invalid for an unknown reason

**Comment by zengxiang1** [comment]
@acheong08 i check it in line 282 return 403

**Comment by noahBin23** [comment]
same issue

**Comment by coolmian** [comment]
me too

**Comment by jianhuihi** [comment]
same

**Comment by jianhuihi** [comment]
`        url = BASE_URL + "api/auth/session"
        print(url)
        print(self.session)
        response = self.session.get(url, timeout_seconds=180)
        print(response)`
        
        return 403

**Comment by acheong08** [comment]
ChatGPT is extremely unstable. They have scaled down their resources.

**Comment by acheong08** [comment]
Also proxies. Proxies are not properly supported

**Comment by Yuqi154** [comment]
same

**Comment by JerryWn12** [comment]
They returned a cloudflare authorization page, maybe need some another cookie?

**Comment by lss233** [comment]
I think this is because the IP you are using is banned by Cloudflare, it happens frequently for whom using a public VPN service.
