### ISSUE TITLE
[BUG] can't get conversation_id or parent_id

### ISSUE THREAD

**Issue by Lynnjl** [acheong08/ChatGPT#605]
can't get conversion_id or parent_id in Official.py script

**Comment by txtspam** [comment]
official.py model already shutdown by openai kindly update your model to davinci 3

**Comment by Lynnjl** [comment]
> 

I have updated the model. But now I can't using multi-conversion.

**Comment by txtspam** [comment]
elaborate your error.

**Comment by acheong08** [comment]
Official.py is working again. Model was only temporarily down
