### ISSUE TITLE
[BUG]openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

### ISSUE THREAD

**Issue by Lynnjl** [acheong08/ChatGPT#608]
When I run the command: python3 -m revChatGPT.Official --api_key API_KEY --stream
the following error : penai.error.ServiceUnavailableError: The server is overloaded or not ready yet

**Comment by txtspam** [comment]
i got it also:

openai.error.RateLimitError: The server is currently overloaded with other requests. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.

maybe they UP the model but doing a ratelimit. ? maybe openai dev is watching us here

**Comment by leolrg** [comment]
Same

**Comment by cateyelow** [comment]
same help me

**Comment by Lynnjl** [comment]
> same help me

I revert to davinci-3 using export GPT_ENGINE="text-davinci-003". and the problem is fixed.

**Comment by txtspam** [comment]
> same help me

heres the temporalily working Official.py solution but it costs you:

from
`ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"`
to
`ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"`

from
`ENCODER = tiktoken.get_encoding("gpt2")`
to
`ENCODER = tiktoken.get_encoding("p50k_base")`

from
`if response["choices"][0]["text"] == "<|im_end|>":
                break
`
to
`if (response["choices"][0]["text"].strip() == "<|im_end|>"
                    or response["choices"][0]["text"].strip() == "<|im"):
                break
`
find this in code:
`Add request/response to chat history for next prompt`
look for
`<|im_end|>`
then remove it and it would look like
`"\n"`

hopes it helps for a while

thanks and credits to
[pengzhile](https://github.com/pengzhile)
[coolmian](https://github.com/coolmian)

**Comment by cateyelow** [comment]
> 

text-davinci-003 is paid model. i have no money

**Comment by acheong08** [comment]
I don't either. Wait a while for the servers to recover from overload

**Comment by xjd-ziyu** [comment]
> I don't either. Wait a while for the servers to recover from overload

It seems that the current official model is unstable and often affected by the official openai. I look forward to your unofficial browserless version. Thank you.

**Comment by siyuyuan** [comment]
> I don't either. Wait a while for the servers to recover from overload

i have the same problem

`openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.`

**Comment by txtspam** [comment]
> > same help me
> 
> heres the temporarily working Official.py solution but it costs you:
> 
> from `ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"` to `ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"`
> 
> from `ENCODER = tiktoken.get_encoding("gpt2")` to `ENCODER = tiktoken.get_encoding("p50k_base")`
> 
> from `if response["choices"][0]["text"] == "<|im_end|>": break ` to `if (response["choices"][0]["text"].strip() == "<|im_end|>" or response["choices"][0]["text"].strip() == "<|im"): break ` find this in code: `Add request/response to chat history for next prompt` look for `<|im_end|>` then remove it and it would look like `"\n"`
> 
> hopes it helps for a while
> 
> thanks and credits to [pengzhile](https://github.com/pengzhile) [coolmian](https://github.com/coolmian)



> > I don't either. Wait a while for the servers to recover from overload
> 
> i have the same problem
> 
> `openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.`

Use this temporarily...

**Comment by siyuyuan** [comment]
> > > same help me
> > 
> > 
> > heres the temporarily working Official.py solution but it costs you:
> > from `ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"` to `ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"`
> > from `ENCODER = tiktoken.get_encoding("gpt2")` to `ENCODER = tiktoken.get_encoding("p50k_base")`
> > from `if response["choices"][0]["text"] == "<|im_end|>": break ` to `if (response["choices"][0]["text"].strip() == "<|im_end|>" or response["choices"][0]["text"].strip() == "<|im"): break ` find this in code: `Add request/response to chat history for next prompt` look for `<|im_end|>` then remove it and it would look like `"\n"`
> > hopes it helps for a while
> > thanks and credits to [pengzhile](https://github.com/pengzhile) [coolmian](https://github.com/coolmian)
> 
> > > I don't either. Wait a while for the servers to recover from overload
> > 
> > 
> > i have the same problem
> > `openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.`
> 
> Use this temporarily...

but it is costly :(

**Comment by hafidzaini** [comment]
so, no solution yet for this problem without paying? 😂

**Comment by ericzhou571** [comment]
Hi,

thanks for your solution. But why you change tokenizer to "p50k_base"? text-davinci-003 is supposed to be a gpt3.5 model, so does text-chat-davinci-002. Since text-chat-davinci-002, I think we should still use "gpt2" tokenizer right?
Maybe you have special reason to do so? It would be very nice if you could give more explain to this change.

Best
Erich

**Comment by seanhuangjf** [comment]
the same problem: openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

**Comment by hafidzaini** [comment]
![](https://i.imgur.com/ClgMBJ8.png)
is "text-davinci-002-render" could be real model name? anyone tried?

**Comment by ericzhou571** [comment]
> ![](https://camo.githubusercontent.com/466d2b1deb9b97ece48d21029aeb855693c07513db360cb8af570922e74a569c/68747470733a2f2f692e696d6775722e636f6d2f436c674d424a382e706e67)
1. It seems to be convince! It is not a public openai gpt3.5 model in `openai.Engine.list()`. 
![截屏2023-02-08 22 48 49](https://user-images.githubusercontent.com/57415741/217563927-72008cca-4d56-4217-a119-5b8336975ec9.png)
2. **However it did not work when i replace the engine with "text-davinci-002-render". "text-chat-davinci-002-render" also did not work.** 
3. Maybe "text-davinci-002-render" is the exact model chatgpt use now days, but they need an extra auth token to be able to access it. Could you tell us, where you find this post data?
![截屏2023-02-08 22 42 38](https://user-images.githubusercontent.com/57415741/217563969-a533824f-443d-47de-87eb-6831090e4940.png)

**Comment by leolrg** [comment]
>is "text-davinci-002-render" could be real model name? anyone tried?
doesn't work

**Comment by sunshuai12** [comment]
> > 同样帮助我
> 
> 这是临时工作的 Official.py 解决方案，但它会花费你：
> 
> 从 `ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"` 到 `ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"`
> 
> 从 `ENCODER = tiktoken.get_encoding("gpt2")` 到 `ENCODER = tiktoken.get_encoding("p50k_base")`
> 
> 从代码 `if response["choices"][0]["text"] == "<|im_end|>": break ` 中 `if (response["choices"][0]["text"].strip() == "<|im_end|>" or response["choices"][0]["text"].strip() == "<|im"): break ` 找到它： `Add request/response to chat history for next prompt` 查找 `<|im_end|>` 然后删除它，它看起来像 `"\n"`
> 
> 希望它能帮助一段时间
> 
> 感谢并感谢 [蓬](https://github.com/pengzhile) [之乐酷面](https://github.com/coolmian)



> > same help me
> 
> heres the temporarily working Official.py solution but it costs you:
> 
> from `ENGINE = os.environ.get("GPT_ENGINE") or "text-chat-davinci-002-20221122"` to `ENGINE = os.environ.get("GPT_ENGINE") or "text-davinci-003"`
> 
> from `ENCODER = tiktoken.get_encoding("gpt2")` to `ENCODER = tiktoken.get_encoding("p50k_base")`
> 
> from `if response["choices"][0]["text"] == "<|im_end|>": break ` to `if (response["choices"][0]["text"].strip() == "<|im_end|>" or response["choices"][0]["text"].strip() == "<|im"): break ` find this in code: `Add request/response to chat history for next prompt` look for `<|im_end|>` then remove it and it would look like `"\n"`
> 
> hopes it helps for a while
> 
> thanks and credits to [pengzhile](https://github.com/pengzhile) [coolmian](https://github.com/coolmian)

这个也无法使用了

**Comment by lonerge** [comment]
> 

thanks it works

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.0

**Comment by acheong08** [comment]
works now!

**Comment by myfingerhurt** [comment]
I think the `text-davinci-003` is dumper than `text-chat-davinci-002-20221122` and has more misleading information.

By the way `text-chat-davinci-002-sh-alpha-aoruigiofdj83` is not working any more.
```
InvalidRequestError(message='That model does not exist', param=None, code=None, http_status=404, request_id=None)
```
