### ISSUE TITLE
[BUG] got response.status_code=403

### ISSUE THREAD

**Issue by 1160300419** [acheong08/ChatGPT#609]
**Description**
i got the "Login successful" message, but when i run into this code `self.__map_conversations()` , i got the response.status_code=403.
And if  the code `self.__map_conversations()` was annotated, i got the same error.
i will be very  appreciated if you could give me some advice about it .

**Steps to Reproduce**
1. run Developer code in python
![微信截图_20230208134011](https://user-images.githubusercontent.com/36816245/217444631-126e6210-c44b-4ca1-aece-c034f5fb920f.png)

3. my config 
![微信截图_20230208134125](https://user-images.githubusercontent.com/36816245/217444561-f64136ca-caf1-430b-bb14-baeeef5a941b.png)

4. see the error:
![微信截图_20230208134036](https://user-images.githubusercontent.com/36816245/217444948-920ada58-d76d-4646-9100-eeb3c58c53b0.png)

![微信截图_20230208134050](https://user-images.githubusercontent.com/36816245/217445004-be8dea1d-a465-4860-a522-40b48774b944.png)

**Comment by goldSunshine** [comment]
same problem, It may be that the interface strengthens the verification, resulting in 403
