### ISSUE TITLE
They didn't block anything

### ISSUE THREAD

**Issue by rawandahmad698** [acheong08/ChatGPT#61]
Plus I'd like to assure you, they can't, Code from my repo has been updated with the new headers.
https://github.com/rawandahmad698/PyChatGPT

**Comment by rawandahmad698** [comment]
There's also reports of changes in css selectors/html changes, but since we use regex, we're good.

**Comment by acheong08** [comment]
Confirmed. Fixed

**Comment by acheong08** [comment]
I was panicking because, yes you can block remote access (I've done this with my own websites before)

**Comment by rawandahmad698** [comment]
Leave that to me, haha. btw need ur twitter #

**Comment by acheong08** [comment]
Lol true. I got no Twitter though. You can email me directly at `acheong@student.dalat.org`

**Comment by rawandahmad698** [comment]
works for me, email is `rawa@rawa.dev`
