### ISSUE TITLE
[info] A restricted hidden model or some kind of issue?

### ISSUE THREAD

**Issue by D3FAU4T** [acheong08/ChatGPT#616]
**Is your feature request related to a problem? Please describe.**

It's not directly related to a problem, just found out a different response from OpenAI today which could be informative but I don't know if this is something valid or not.

When you actually search for newer models, it usually gives that "This model doesn't exist" if you cannot find a valid model naming scheme. But with this one it says "Model not found" instead of "doesn't exist".

Hidden restricted model or something else?

**Additional context**
![image](https://user-images.githubusercontent.com/89858397/217671120-871accac-d7d7-4d4f-8b94-b0c1dd1cb663.png)
![image](https://user-images.githubusercontent.com/89858397/217671256-ae960416-c677-44b0-b0ff-942603b3e8af.png)

**Comment by acheong08** [comment]
Yes. Use https://github.com/acheong08/ChatGPT/blob/main/README.md#v1-browser-automation

**Comment by leolrg** [comment]
interesting

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.0
