### ISSUE TITLE
[BUG]after successful login, still loop on 'Spawning browser', and with valided 'session' config is alway go to login page

### ISSUE THREAD

**Issue by iaston** [acheong08/ChatGPT#618]
**Description**
![image](https://user-images.githubusercontent.com/11807657/217798832-e0e11b32-db6c-413f-8724-033a376bb03d.png)

so, I try to use session_token:
from revChatGPT.Unofficial import Chatbot
str_session= '5NyvISVdw5vE1eijMWouLg_GKmaW4wmV436....................'
my_Chatbot = Chatbot(dict(session_token=str_session, proxy='http://127.0.0.1:8080'), conversation_id=None,
                         parent_id=None)
Then, Chrome alway be redirected to Login page...., and can't login obviously without username and password.

BTW, while going to the waiting page, maybe auto refresh will be better than close and reopen browser:
![image](https://user-images.githubusercontent.com/11807657/217802282-a88170d7-6813-4aa9-baff-ba3d6482dd40.png)

**Comment by CrispOvO** [comment]
I had the same issue since yesterday afternoon. 
![1676079214578](https://user-images.githubusercontent.com/57664771/218231666-51158ef9-eb7f-4c6d-86a4-8f9fb63e8353.png)

**Comment by acheong08** [comment]
The reason here is that ChatGPT is at capacity and is blocking normal users

**Comment by CrispOvO** [comment]
> The reason here is that ChatGPT is at capacity and is blocking normal users

got it, thank you very much :)

**Comment by CrispOvO** [comment]
> The reason here is that ChatGPT is at capacity and is blocking normal users

got it, thank you very much :)

**Comment by iaston** [comment]
> The reason here is that ChatGPT is at capacity and is blocking normal users

Maybe not the reason for already logined...

**Comment by binocla** [comment]
Kinda weird
Having the same one with ChatGPT Plus bought (I guess it bypasses `ChatGPT is at capacity` which was mentioned above)
Checked chromium'n'chrome versions etc. but no effort

Python 3.11.0
Windows 10 22H2
Chrome version: 110.0.5481.78
![image](https://user-images.githubusercontent.com/32897870/218286056-60e5a016-73f4-4e3c-9a49-9ce237e3a10f.png)
