### ISSUE TITLE
The request is blocked.

### ISSUE THREAD

**Issue by bupticybee** [acheong08/ChatGPT#62]
When using the api, I encounter this error: 

Error refreshing session
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>07NuOYwAAAADUXOmTDFUARKHTefoB5PcoU0lOMzBFREdFMDIxMABlNjZiOGIwMy0wNzkzLTQ0MDktOTc3My0yZTYxMmU3MWExZTM=</span></div></div></body></html>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/bytedance/PycharmProjects/ChineseAiDungeonChatGPT/venv/lib/python3.6/site-packages/revChatGPT/revChatGPT.py", line 61, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

Now it seems that the use of api is detected and baned by openai. Can someone please confirm this? Or is there any way around it?

**Comment by acheong08** [comment]
Update
`pip3 install revChatGPT --upgrade`

**Comment by bupticybee** [comment]
I see. It did resolve the problem, thank you very much.
