### ISSUE TITLE
[BUG] pip3 install revChatGPT[unofficial] zsh: no matches found: revChatGPT[unofficial]

### ISSUE THREAD

**Issue by smartboy37597** [acheong08/ChatGPT#624]
**Description**
use `pip3 install revChatGPT[unofficial]`
return `zsh: no matches found: revChatGPT[unofficial]`

how should i solve this problem

**Comment by acheong08** [comment]
Put in quotes: `pip3 install "revChatGPT[unofficial]"`

**Comment by smartboy37597** [comment]
> 
thx :)

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/1.2.2 - Just run `pip3 install revChatGPT` now since other version dead

**Comment by smartboy37597** [comment]
> 

Is this the v2 version used? Is the v1 version still available?

**Comment by acheong08** [comment]
V2 is dead. V1 still available

**Comment by smartboy37597** [comment]
> 1.2.2

Is the 1.2.2 version you just released v1 or v2?

**Comment by acheong08** [comment]
It contains both but only v1 works

**Comment by acheong08** [comment]
The release version has nothing to do with bypass version

**Comment by smartboy37597** [comment]
> The release version has nothing to do with bypass version

Thank you very much for your answer, it helped me a lot!

I have another question that I have correctly installed `revChatGPT[unofficial]`, but report this error at runtime, is there a problem with my python environment?
![image](https://user-images.githubusercontent.com/47653926/218002746-2dddc0de-9bd7-4b83-8fee-5a620576c979.png)

**Comment by acheong08** [comment]
`python3 -m pip install revChatGPT`

**Comment by smartboy37597** [comment]
> Make sure you aren't in a virtual environment

I think I've installed the environment correctly (possibly) :(
![image](https://user-images.githubusercontent.com/47653926/218004093-dfd17fb8-925d-48eb-a5b9-abb1d3b111ce.png)
![image](https://user-images.githubusercontent.com/47653926/218004105-68a94d4b-9e3b-4062-bb63-c9e1603f39ca.png)

**Comment by smartboy37597** [comment]
`python3 -m revChatGPT.Official --api_key API_KEY --stream`
This official command can be executed correctly in my place, but because v2 is dead, it cannot have a dialogue, but only the official command reports an error as soon as it is executed.

**Comment by smartboy37597** [comment]
I uninstalled and reinstalled to run v1 now, but I have the following problem
![image](https://user-images.githubusercontent.com/47653926/218006176-1eb7adf4-e458-493d-8d45-b8a60a4c4bcf.png)

**Comment by acheong08** [comment]
Proxy issue or network issue

**Comment by smartboy37597** [comment]
> Proxy issue or network issue

I moved the project to an Amazon Linux server to solve the network problem while installing Chrome, but now I have a new problem
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/47653926/218047658-fa543495-4711-472e-82cf-4afdb7e177fa.png">

**Comment by acheong08** [comment]
- https://github.com/acheong08/ChatGPT/issues/353

Use XVFB
