### ISSUE TITLE
model does not exist

### ISSUE THREAD

**Issue by zhangshuai0396** [acheong08/ChatGPT#625]
https://github.com/acheong08/ChatGPT/blob/f298db5f0a9ee4d773abcc4e4e9a3cede2814ec9/src/revChatGPT/Official.py#L13

**That model does not exist**

**Comment by seanhuangjf** [comment]
the same error:  openai.error.InvalidRequestError: That model does not exist

**Comment by acheong08** [comment]
Yes. Model doesn't exist anymore

**Comment by zhangshuai0396** [comment]
> 同样报错：openai.error.InvalidRequestError: That model does not exist

可能官方把模型名改了，我试了试这个仍还是不对
<img width="775" alt="image" src="https://user-images.githubusercontent.com/32203328/218024224-a6856b2e-8ead-4617-80d5-b20c43d5ac3d.png">

**Comment by tuapuikia** [comment]
You can try 
```text-davinci-003```

**Comment by seanhuangjf** [comment]
> You can try `text-davinci-003`
have tried, but ... wrong

**Comment by saulide** [comment]
text-davinci-003 costs money, but it works quite good

**Comment by Ijazweb** [comment]
I know the person who obtained a new model that bypasses rate limits and does not count tokens, but he is not revealing the method.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.0
