### ISSUE TITLE
Access api from browser

### ISSUE THREAD

**Issue by tomasliachovskis** [acheong08/ChatGPT#632]
How I can access API from browser something like 127.0.0.1/chat ?

**Comment by acheong08** [comment]
I actually made a full solution for this but haven't had the time to document it.

Relevant projects:
- https://github.com/acheong08/ChatGPT-Proxy - Hosts a cloudflare bypass server
- https://github.com/acheong08/OpenAIAuth - Browserless login
- https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/Proxied.py - MVP browserless proxy client (WIP)

**Comment by acheong08** [comment]
The proxied client lacks error handling for now

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.0
