### ISSUE TITLE
[BUG] How to use the unoffical chatbot to have access to the Chatgpt plus

### ISSUE THREAD

**Issue by xfleezy** [acheong08/ChatGPT#633]
Hello, I have subscribed to the Chatgpt plus. Does someone have an idea about how to modify unoffical.py to log into the Chatgpt plus  when the capacity for the standard Chatgpt is full?

**Comment by xiaoyongzhu** [comment]
plus one on this, it always return 400 for me.


```
{"detail":"An error ocurred. Try refreshing your browser."}
Traceback (most recent call last):
  File "/Users/james/openai_python.py", line 8, in <module>
    response = chatbot.ask("who are you", conversation_id='7daf443f-abb2-47e1-b908-14288314226c', parent_id=None) # You can specify custom conversation and parent ids. Otherwise it uses the saved conversation (yes. conversations are automatically saved)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/monolith/lib/python3.9/site-packages/revChatGPT/Unofficial.py", line 160, in ask
    raise HTTPError(
requests.exceptions.HTTPError: Wrong response code: 400! Refreshing session...
```

**Comment by xfleezy** [comment]
I also get the same error now.

**Comment by thechen130** [comment]
是的，現在需要chatgpt plus登錄的辦法

**Comment by acheong08** [comment]
I don't have a plus account so it's difficult to test. I can add support if you share me the model name used by Plus

**Comment by thechen130** [comment]
> 我没有加号帐户，因此很难测试。如果您与我分享 Plus 使用的型号名称，我可以添加支持

我可以給你分享賬戶，希望您能增加此項功能

**Comment by xfleezy** [comment]
> I don't have a plus account so it's difficult to test. I can add support if you share me the model name used by Plus

Do you have the account now? If not, I can share my account. Thanks for your contribution!

**Comment by acheong08** [comment]
No need anymore! Official model found once again thanks to @waylaidwanderer

**Comment by acheong08** [comment]
It's much faster than plus and no rate limits

**Comment by thechen130** [comment]
> 不需要了！多亏了@waylaidwanderer，官方模型再次被发现

小白該如何使用，比如接入釘釘機器人

**Comment by aliencaocao** [comment]
So how to use this with my own plus account?

**Comment by acheong08** [comment]
New model dead. I need someone to share me the plus model so I can implement it

**Comment by acheong08** [comment]
@xfleezy Mind helping out?

**Comment by jarviszeng-zjc** [comment]
I can help you. How can I contact you?

**Comment by jarviszeng-zjc** [comment]
> New model dead. I need someone to share me the plus model so I can implement it

I can help you. How can I contact you?

**Comment by acheong08** [comment]
@jarviszeng-zjc acheong@student.dalat.org

I may be slow to respond. Currently extremely busy

**Comment by flo3535** [comment]
Change "text-davinci-002-render" to "text-davinci-002-render-paid"

**Comment by acheong08** [comment]
> Change "text-davinci-002-render" to "text-davinci-002-render-paid"

ah so that was the model name. I will add option in config

**Comment by xfleezy** [comment]
> @xfleezy Mind helping out?

How to contact you? Do you mind sharing your email?

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.0.3 and new readme

**Comment by Jamminroot** [comment]
"text-davinci-002-render-sha" for "turbo"

**Comment by Jamminroot** [comment]
Interestingly enough, that works for free accounts, too; Although I noticed that it still is ratelimited - can't tell numbers, but feels like it is limited to a 3-4 requests per minute; Maybe a cooldown (sometimes getting 429 after third request on plus account)

**Comment by waylaidwanderer** [comment]
@Jamminroot yeah they're rolling out the turbo model for free accounts

**Comment by MichalBortkiewicz** [comment]
So can we use ChatGPT plus with this repo? What modifications are to be made to make it work?

**Comment by MichalBortkiewicz** [comment]
Alright, I found out the additional config flag `paid`:

```
chatbot = Chatbot({
    "email": "<email>",
    "password": "<password>",
    "paid": True
}, conversation_id=None, parent_id=None) 
```

**Comment by aliencaocao** [comment]
@waylaidwanderer what is turbo mode?

**Comment by waylaidwanderer** [comment]
@aliencaocao Turbo **model.**

![image](https://user-images.githubusercontent.com/2882110/218293744-f5222790-e30b-4d37-bb95-8fc7011b3ca4.png)

**Comment by aliencaocao** [comment]
Oh, does it affect accuracy/quality though
