### ISSUE TITLE
[BUG]repeat login even if login successful

### ISSUE THREAD

**Issue by thurderbird521** [acheong08/ChatGPT#637]
**Description**
can not work

 - OS: [Windows10]
 - Python version: 3.9

- network location
- HONG KONG

run cmd: C:\python.exe D:/chatGPT/ChatGPT-main/src/revChatGPT/Unofficial.py
![image](https://user-images.githubusercontent.com/30044455/218249057-7d04189e-9a87-4fb1-879d-f1aca0962e7f.png)

is there anybody meeting same situation?

**Comment by thechen130** [comment]
请问整个过程该如何操作，我已经有了一台在美国的Ubuntu服务器和chatgpt账号。
我该怎么入手，本人小白，有大佬愿意提示一下吗

**Comment by goldSunshine** [comment]
same as the problem you have，I guess the reason is that request 403 causes retry

**Comment by lss233** [comment]
Possible duplicated of https://github.com/acheong08/ChatGPT/issues/604  ?

I've also posted a solution here: https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
