### ISSUE TITLE
Option to change Base prompt in proxy version. Also what is the default Base prompt?

### ISSUE THREAD

**Issue by vaibhavard** [acheong08/ChatGPT#638]
It is also possible to use  / add ask_stream in proxy version?

**Comment by acheong08** [comment]
The proxy version is pure ChatGPT, not the base model

**Comment by acheong08** [comment]
there is no base prompt

**Comment by vaibhavard** [comment]
What about ask_stream option? Can you add that?

**Comment by acheong08** [comment]
Not possible due to OpenAI's restrictions. Depends on https://github.com/FlorianREGAZ/Python-Tls-Client

**Comment by vaibhavard** [comment]
Sorry for asking again , but how does this one has ask_stream:
https://github.com/mmabrouk/chatgpt-wrapper
Also , can i save the login in chatgpt after closing script , like in the above one?

**Comment by acheong08** [comment]
Yeah keeps browser open 100% of the time which is what I'm trying to avoid.

**Comment by acheong08** [comment]
> Also , can i save the login in chatgpt after closing script , like in the above one?

Save it to `$HOME/.config/revChatGPT/config.json`
```json
{"email": "<your username>", "password": "<your password>"}
```

**Comment by vaibhavard** [comment]
So saving to config json means that when I run .py script, it won't login again
Thanks
