### ISSUE TITLE
[BUG] KeyError: 'accessToken'

### ISSUE THREAD

**Issue by ITerydh** [acheong08/ChatGPT#639]
**Description**
When i use the Proxied Version, it shows this error.

![image](https://user-images.githubusercontent.com/46839689/218256164-fa7ee2c3-cc55-403f-85fb-4c6d9f9049d1.png)

PS:
I used email and password in config.json.

**Environment**
`pip3 install --upgrade revChatGPT`

**Comment by binocla** [comment]
I had the same exception since my country is forbidden by OpenAI Authentication. I've tried to use VPN and it worked like a charm. Try it out and probably it solves your trouble

**Comment by coolmian** [comment]
change your config.json to set the proxy
like this 
```
{"email": "xxx", "password": "xxx", "proxy": "socks5://127.0.0.1:10808"}
```

**Comment by ld909** [comment]
same error

**Comment by xsy822** [comment]
> 更改您的 config.json 以像这样设置代理
> 
> ```
> {"email": "xxx", "password": "xxx", "proxy": "socks5://127.0.0.1:10808"}
> ```

tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": socks connect tcp 127.0.0.1:8000->explorer.api.openai.com:443: dial tcp 127.0.0.1:8000: connectex: No connection could be made because the target machine actively refused it.

**Comment by coolmian** [comment]
@xsy822 Make sure you are using the correct proxy server port and are using socks or HTTP

**Comment by kamendula** [comment]
@coolmian  thanks for your answering. I had the same error and I want to find a way to solve it.
I followed the command to run the repo:

> `pip3 install --upgrade revChatGPT`

```

> from revChatGPT.V2 import Chatbot
> 
> async def main():
>     chatbot = Chatbot(email="...", password="...")
>     response = await chatbot.ask("Hello")
>     print(response["choices"][0]["text"])
> 
> if __name__ == "__main__":
>     import asyncio
>     asyncio.run(main())

```
You mentioned we should config the `config.json` file. so where should I config it?

**Comment by acheong08** [comment]
No more config.json for now

**Comment by acheong08** [comment]
Need VPN rather than proxy until further notice

**Comment by kamendula** [comment]
thanks. but why can I get the apikeys with the webbrowser, but have the error 'KeyError: 'accessToken' in the code?
