### ISSUE TITLE
Incorrect API key provided

### ISSUE THREAD

**Issue by 0324wy** [acheong08/ChatGPT#64]
{"detail":{"message":"Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}

**Comment by acheong08** [comment]
Update `pip3 install revChatGPT --upgrade`

Ensure you are using the correct email and password. If you could, please help write some error handlers for this and make a pull request.

**Comment by 0324wy** [comment]
> 

Has anyone else encountered this problem?

**Comment by acheong08** [comment]
@0324wy https://github.com/acheong08/ChatGPT/issues/55

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/issues/72
