### ISSUE TITLE
Don't know how to move on: That model does not exist

### ISSUE THREAD

**Issue by 51364x** [acheong08/ChatGPT#642]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/104958540/218259051-8d13b995-351a-4db5-a109-0fbdb57c73e5.png">

python version 3.9.13
got version: 2.0.1

**Comment by faissaloo** [comment]
I'm seeing the same thing

**Comment by acheong08** [comment]
The model no longer exists because OpenAI found us
