### ISSUE TITLE
Google Authentication Login Option

### ISSUE THREAD

**Issue by cmdnl** [acheong08/ChatGPT#644]
I can't seem to use this api because I need a normal username + password in order to use it. However, I have an account that can only login via Google Authentication login. OpenAI doesn't seem to have the option to send me a normal password.

I have ChatGPT plus so I'd love to use my account and not make some random new one.

Does anyone have a solution for this? Or can this feature be added please?

**Comment by Liu-Angelo** [comment]
> 我似乎无法使用这个 api，因为我需要一个普通的用户名 + 密码才能使用它。但是，我有一个帐户只能通过谷歌身份验证登录。OpenAI 似乎没有向我发送普通密码的选项。
> 
> 我有 ChatGPT plus，所以我喜欢使用我的帐户，而不是随机创建一个新帐户。
> 
> 有人对此有解决方案吗？或者可以添加此功能吗？

Does ChatGPT Plus provide API or burst model after successful subscription？

**Comment by Liu-Angelo** [comment]
> I can't seem to use this api because I need a normal username + password in order to use it. However, I have an account that can only login via Google Authentication login. OpenAI doesn't seem to have the option to send me a normal password.
> 
> I have ChatGPT plus so I'd love to use my account and not make some random new one.
> 
> Does anyone have a solution for this? Or can this feature be added please?

Does ChatGPT Plus provide API or provide model after successful subscription

**Comment by jnxyp** [comment]
> > I can't seem to use this api because I need a normal username + password in order to use it. However, I have an account that can only login via Google Authentication login. OpenAI doesn't seem to have the option to send me a normal password.
> > I have ChatGPT plus so I'd love to use my account and not make some random new one.
> > Does anyone have a solution for this? Or can this feature be added please?
> 
> Does ChatGPT Plus provide API or provide model after successful subscription

Not yet, it says the API is comming soon :(

**Comment by cmdnl** [comment]
@acheong08 I see you closed this as completed. Does that mean you'll build in a way to use Google Authentication?

**Comment by acheong08** [comment]
Already available via session tokens. Will release soon

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/pull/739
