### ISSUE TITLE
[BUG]Error while finding module specification for 'revChatGPT.V2'

### ISSUE THREAD

**Issue by siyuyuan** [acheong08/ChatGPT#650]
i have conduct

`pip3 install --upgrade revChatGPT`

but

`/home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: __path__ attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2')
`

**Comment by liuyan731** [comment]
> i have conduct
> 
> `pip3 install --upgrade revChatGPT`
> 
> but
> 
> `/home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: __path__ attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2') `

same "No module named revChatGPT.V2"

**Comment by acheong08** [comment]
`pip3 show revChatGPT`. Might be a cache issue

**Comment by liuyan731** [comment]
> 



> `pip3 show revChatGPT`. Might be a cache issue

thanks

use this @siyuyuan :   pip3 install revChatGPT==2.1.0 -i https://pypi.mirrors.ustc.edu.cn/simple

**Comment by siyuyuan** [comment]
> pip3 show revChatGPT

`pip3 show revChatGPT`

```
Name: revChatGPT
Version: 2.1.0
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/ysy/anaconda3/envs/ysy_env/lib/python3.8/site-packages
Requires: asyncio, httpx, OpenAIAuth, tiktoken
Required-by: 
```

**Comment by siyuyuan** [comment]
> > 
> 
> > `pip3 show revChatGPT`. Might be a cache issue
> 
> thanks
> 
> use this @siyuyuan : pip3 install revChatGPT==2.1.0 -i https://pypi.mirrors.ustc.edu.cn/simple

Not work:(
`
/home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: __path__ attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2')
`

**Comment by acheong08** [comment]
> /home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: __path__ attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2')

What did you run?

**Comment by siyuyuan** [comment]
> > /home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: **path** attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2')
> 
> What did you run?

`python3 -m revChatGPT.V2 -h`

**Comment by acheong08** [comment]
Do `python3 -m pip install revChatGPT==2.1.0`

**Comment by siyuyuan** [comment]
> python3 -m pip install revChatGPT==2.1.0

not work:(

**Comment by acheong08** [comment]
what error?

**Comment by siyuyuan** [comment]
> what error?

when i conduct `python3 -m pip install revChatGPT==2.1.0`, i do not get error. 

but when i continue conducting `python3 -m revChatGPT.V2 -h`

the error is 

/home/ysy/anaconda3/envs/ysy_env/bin/python3: Error while finding module specification for 'revChatGPT.V2' (ModuleNotFoundError: __path__ attribute not found on 'revChatGPT' while trying to find 'revChatGPT.V2')

**Comment by acheong08** [comment]
anaconda3 breaks things sometimes. Use without it

**Comment by siyuyuan** [comment]
> 

ok~thanks
