### ISSUE TITLE
[BUG]revChatGPT.V2这个版本会报错KeyError: 'accessToken'

### ISSUE THREAD

**Issue by long202258** [acheong08/ChatGPT#652]
revChatGPT.V2这个版本
Traceback (most recent call last):
  File "e:\admin\Desktop\openai\chatgpt.py", line 10, in <module>
    asyncio.run(main())
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "e:\admin\Desktop\openai\chatgpt.py", line 4, in main
    chatbot = Chatbot(email="", password="")
  File "D:\Python\lib\site-packages\revChatGPT\V2.py", line 120, in __init__
    self.login(email, password)
  File "D:\Python\lib\site-packages\revChatGPT\V2.py", line 173, in login
    self.api_key = auth.get_access_token()
  File "D:\Python\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 348, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'
会出现报错，请帮忙解决

**Comment by acheong08** [comment]
需要VPN在中国

**Comment by long202258** [comment]
已经用了VPN了

**Comment by acheong08** [comment]
是"Clash"吗？

**Comment by long202258** [comment]
大神能加个微信吗

**Comment by long202258** [comment]
v2rayn
![image](https://user-images.githubusercontent.com/97136192/218299877-cc82abb3-5521-4385-8773-df2ad07b795a.png)

**Comment by acheong08** [comment]
有可能是 OpenAI 阻止这个IP

**Comment by acheong08** [comment]
我等会儿写个 Auth server

**Comment by long202258** [comment]
ok ，大神等你更新

**Comment by long202258** [comment]
大神加个微信平常带我玩玩呀，来南京我请你吃饭

**Comment by acheong08** [comment]
微信就不加了，我也需要点隐私。

**Comment by zhaoxiaomeng** [comment]
@long202258 你的问题里把你的邮箱和id都暴露了，建议隐藏一下吧

**Comment by long202258** [comment]
> @long202258 你的问题里把你的邮箱和id都暴露了，建议隐藏一下吧

谢谢大哥

**Comment by long202258** [comment]
> 微信就不加了，我也需要点隐私。
> 
> _而且我在重庆，有点远_

重庆也没事我给你寄点南京的特产，偶尔也会去出差

**Comment by long202258** [comment]
> 

大哥我们也加个微信吧

**Comment by hfyydd** [comment]
我也是这样

**Comment by Martinzz** [comment]
__part_eight方法请求404，拿不到access_token

**Comment by yutrd** [comment]
也是这个问题

**Comment by yutrd** [comment]
> 也是这个问题

网页上直接访问是有token的

**Comment by JacksonTxl** [comment]
大佬解决了给个回信，待会在来看看

**Comment by acheong08** [comment]
正在写。等一一等

**Comment by frankShih** [comment]
> revChatGPT.V2这个版本 Traceback (most recent call last): File "e:\admin\Desktop\openai\chatgpt.py", line 10, in asyncio.run(main()) File "D:\Python\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "D:\Python\lib\asyncio\base_events.py", line 649, in run_until_complete return future.result() File "e:\admin\Desktop\openai\chatgpt.py", line 4, in main chatbot = Chatbot(email="", password="") File "D:\Python\lib\site-packages\revChatGPT\V2.py", line 120, in **init** self.login(email, password) File "D:\Python\lib\site-packages\revChatGPT\V2.py", line 173, in login self.api_key = auth.get_access_token() File "D:\Python\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 348, in get_access_token self.access_token = response.json()["accessToken"] KeyError: 'accessToken' 会出现报错，请帮忙解决

目前有辦法註冊嗎? 我嘗試了不少 email，結果還是只能通過 Google & M$ 登入 ...

**Comment by 1308024507pkh** [comment]
请问如何在代码中设置vpn呢？

**Comment by acheong08** [comment]
Proxy option added:
![image](https://user-images.githubusercontent.com/36258159/218320070-be91873e-afc9-4f2c-8178-8da7956e90bd.png)

**Comment by acheong08** [comment]
I will deploy auth proxy

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.1.6

`--insecure-auth` uses a proxy that I host to get access token.

**Comment by JacksonTxl** [comment]
Traceback (most recent call last):
  File "/Users/xx/Desktop/woshua/python/openai/main.py", line 10, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/xx/Desktop/woshua/python/openai/main.py", line 5, in main
    response = await chatbot.ask("Hello")
TypeError: object async_generator can't be used in 'await' expression

**Comment by JacksonTxl** [comment]
产生一个新的问题

**Comment by acheong08** [comment]
It's a stream. 

```py
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="...", password="...")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

**Comment by acheong08** [comment]
You can also do:
```py
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="...", password="...")
	full_text = ""
    async for line in chatbot.ask("Hello"):
        full_text += line["choices"][0]["text"].replace("<|im_end|>", "")
        sys.stdout.flush()
    print(full_text)

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

**Comment by JacksonTxl** [comment]
忘记回复大佬了，已经跑起来了，感谢~~

**Comment by yutrd** [comment]
感谢佬！

**Comment by shenziqian** [comment]
佬，我这还是这个问题
File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 209, in login
    auth.get_access_token()
  File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 353, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'
试图print json结果是个空子典

**Comment by Pengchengistaken** [comment]
> 佬，我这还是这个问题 File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 135, in **init** self.login(email, password, proxy, insecure, session_token) File "C:\Python310\lib\site-packages\revChatGPT\V2.py", line 209, in login auth.get_access_token() File "C:\Python310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 353, in get_access_token self.access_token = response.json()["accessToken"] KeyError: 'accessToken' 试图print json结果是个空子典

应该是代理不成功。
