### ISSUE TITLE
[BUG] ChatGPT response seems to be incomplete

### ISSUE THREAD

**Issue by FerdinandoPH** [acheong08/ChatGPT#654]
**Description**
When I ask something to chatGPT with the ask command, the answer gets cut out at some point (I can tell because the last word is incomplete). Is there a token limit for the answer or something?

**Steps to Reproduce**
1. Ask something that takes a few lines to answer with chatbot.ask

**Expected behavior**
The full answer

**Output**
(it's in spanish, last word seems to be "trabajaba", but it finished in "trab", and didn't finish the rest of the answer

Mariano, un campesino del antiguo Egipto, trabajaba arduamente en sus campos durante el caluroso verano. Un día, mientras regaba sus cultivos, un gato misterioso se acercó a él y comenzó a seguirlo a donde quiera que fuera. Mariano lo encontró un poco extraño, pero decidió no preocuparse por ello y continuar con su trabajo. Sin embargo, el gato parecía tener un propósito más grande en mente. Mientras Mariano trab

**Environment**
   Windows 10, python 3.11.2, revChatGPT 2.1.0

**Comment by Liu-Angelo** [comment]
> **描述** 当我使用 ask 命令向 chatGPT 提问时，答案有时会被截断（我能看出来是因为最后一个词不完整）。答案是否有令牌限制？
> 
> **重现步骤**
> 
> 1. 使用 chatbot.ask 问一些需要几行才能回答的问题
> 
> **预期行为** 完整答案
> 
> **输出** （它是西班牙语，最后一个词似乎是“trabajaba”，但它以“trab”结束，并且没有完成其余的答案
> 
> Mariano, un campesino del antiguo Egipto, trabajaba arduamente en sus campos durante el caluroso verano。Un día, mientras regaba sus cultivos, un gato misterioso se acercó a él y comenzó a seguirlo a donde quiera que fuera。Mariano lo encontró un poco extraño，pero decidió no preocuparse por ello continuar con su trabajo。Sin embargo, el gato parecía tener un proposósito más grande en mente。米恩特拉马里亚诺 trab
> 
> **环境** Windows 10，python 3.11.2，revChatGPT 2.1.0

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/19570026/218302451-95d97f2d-6e79-4373-82c0-61bc7eb663ac.png">

输出不全

**Comment by acheong08** [comment]
Fixed on server

**Comment by acheong08** [comment]
Not fixed apparently.

**Comment by acheong08** [comment]
I'll keep trying

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.1.1
