### ISSUE TITLE
登录建议

### ISSUE THREAD

**Issue by boogiie** [acheong08/ChatGPT#655]
建议以API-Key的方式交互，以账户登录太困难了。

**Comment by lss233** [comment]
API Key 方式登录用不了网页版 ChatGPT

**Comment by acheong08** [comment]
中国被OpenAI阻止使用。我在写另一个Auth0 server

**Comment by rllll** [comment]
v2版本没办法开代理吗，可以支持传入自定义代理端口吗

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT-Proxy-V2

**Comment by thechen130** [comment]
> 建议以API-Key的方式交互，以账户登录太困难了。

API-Key去找找，有很多的，但是用邮箱账号的不多。而且，用API-Key的根本不是chatgpt，只有用有邮箱密码的才能实现真实的Chatgpt。

**Comment by acheong08** [comment]
> > 建议以API-Key的方式交互，以账户登录太困难了。
> 
> API-Key去找找，有很多的，但是用邮箱账号的不多。而且，用API-Key的根本不是chatgpt，只有用有邮箱密码的才能实现真实的Chatgpt。

Thank you for explaining.

Translation: Look for API-Key, there are many, but not many use email accounts. Moreover, the API-Key is not chatgpt at all, and the real Chatgpt can only be realized by using the email password.
