### ISSUE TITLE
[BUG] 使用 celery 在子进程中运行 ChatGPT，tls-client 无响应。

### ISSUE THREAD

**Issue by dusty-cjh** [acheong08/ChatGPT#658]
### Env
macOS m1
django4.1, celery5.2
使用 tls-client.dylib，`revChatGPT.V2` 运行正常。

学校QQ群机器人，思路是当用户艾特机器人时，主动创建一个子进程（这里用的是 celery）来拉起新的 chatGPT 对话。

### 可能存在死锁 `venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py:77`
`revChatGPT.V2` 运行正常，但当使用子进程运行登陆脚本时，代码卡在 `venv/lib/python3.9/site-packages/tls_client/sessions.py:337`，这里是直接导入动态库，然后用 tls-client 去请求。

### 需求
现在就是命令行运行正常，但在子进程里就会卡住。
关于下一步的解决方案，我是没有思路了，希望各位大佬能不吝赐教，或者其他部分有我没考虑到的，希望可以帮忙指认出来～
感谢🙏

**Comment by acheong08** [comment]
Report here: https://github.com/FlorianREGAZ/Python-Tls-Client

**Comment by dusty-cjh** [comment]
感谢大佬的回答，已经找到问题了，是因为 tls-client 本身会开启多线程，但 fork 函数只会 copy 主线程，然后就会导致互斥量死锁。

解决方案：
先 fork 再导入 tls-client，同时 mac os 还需要开启环境变量：OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

bug 和本项目无关，这里我就 close 了
