### ISSUE TITLE
[BUG]KeyError: 'accessToken'

### ISSUE THREAD

**Issue by 17Reset** [acheong08/ChatGPT#659]
self.access_token = response.json()["accessToken"]
                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'accessToken'

**Comment by zenorochaV1** [comment]
me too

**Comment by acheong08** [comment]
Check latest version

**Comment by acheong08** [comment]
https://github.com/acheong08/OpenAIAuth/releases/tag/0.1.1

**Comment by 17Reset** [comment]
I updated the version, but there is a new error: print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="") ~~~~^^^^^^^^^^^ TypeError: string indices must be integers, not 'str'

**Comment by F33RNI** [comment]
> ```
> self.access_token = response.json()["accessToken"]
>                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
> ```
> 
> KeyError: 'accessToken'

https://github.com/acheong08/ChatGPT/pull/680

**Comment by acheong08** [comment]
Print the full line please

**Comment by 17Reset** [comment]
Okay, I printed the whole line and this problem "Error... Logging in again", what is the cause of this problem?
