### ISSUE TITLE
it doesnt work after run “python3 -m revChatGPT” here is my cmd screenshot，please tell me the problem 

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#66]
<img width="744" alt="913f115de6051a624a5290d80f2d905" src="https://user-images.githubusercontent.com/86822589/205851476-00f1557e-6711-4a7a-9661-803dbce30055.png">

**Comment by acheong08** [comment]
I don't have Windows. Need people to test this. Check out this issue: https://github.com/acheong08/ChatGPT/issues/53 and see if it's related

**Comment by zjrwtx** [comment]
well i saw the problem .but its not related .and config.json was filled out as your readme. so i just cant figure out where is the problem

![image](https://user-images.githubusercontent.com/86822589/205852904-38c4bbec-3c31-4bf5-8101-8e7810449c32.png)

**Comment by zepef** [comment]
Hello  ,it works fine on my Windows 11 machine. Could you provide more détails please?
![image](https://user-images.githubusercontent.com/698357/205853434-cc0e2e7f-5037-4753-bf2f-90ce802245fb.png)

**Comment by acheong08** [comment]
Invalid config. You don't need authorization. I should make that more clear

**Comment by acheong08** [comment]
Only need email and password

**Comment by zjrwtx** [comment]
> Only need email and password
well i done it but it still not works
![image](https://user-images.githubusercontent.com/86822589/205859955-1039a467-abef-4017-8f79-87744f2cdf9d.png)
![image](https://user-images.githubusercontent.com/86822589/205860194-f14b5485-3478-47e3-80a5-833206def8c2.png)

**Comment by acheong08** [comment]
You didn't save the config file

**Comment by acheong08** [comment]
`control+s`

**Comment by zjrwtx** [comment]
> `control+s`

acutallly i have already saved kt

**Comment by acheong08** [comment]
I have no idea why there is no output at all. Need help from more Windows users

**Comment by zjrwtx** [comment]
> I have no idea why there is no output at all. Need help from more Windows users

all right. i am waiting for the help

**Comment by silvermooooon** [comment]
> > I have no idea why there is no output at all. Need help from more Windows users
> 
> all right. i am waiting for the help

Try changing `python3 - m revChatGPT`  to `python - m revChatGPT`

I have the same problem as you

Because I set python3 to python when installing python

I hope it can help you:)

**Comment by zjrwtx** [comment]
> `python3 - m revChatGPT` --> `python3 -m revChatGPT` # Lose the space.
> 
> On Windows, you can try: `py -m revChatGPT`

well ，i solve it ！Thank you very much
