### ISSUE TITLE
[BUG] ChatGPT Plus account did not receive reply.

### ISSUE THREAD

**Issue by xuafeng** [acheong08/ChatGPT#660]
**Environment**
 - OS: Linux
 - Python version: Python 3.9.10
 - ChatGPT Version: 2.1.1

![Capture](https://user-images.githubusercontent.com/6166193/218309544-15ec55cf-cf9c-4120-8d6f-37ef4cc25d6f.PNG)

**Comment by acheong08** [comment]
Plus accounts aren't supported yet

**Comment by verazuo** [comment]
same issue. Any suggestion about how to modify current version to support Plus accounts? like change model's name?

**Comment by acheong08** [comment]
I'll need to modify code and cause 10 seconds of downtime

**Comment by acheong08** [comment]
will support in next release in a few minutes

**Comment by verazuo** [comment]
many thx!

**Comment by xuafeng** [comment]
Thanks.

**Comment by acheong08** [comment]
Sorry got distracted with other bugs

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.1.2
