### ISSUE TITLE
[BUG] NameError: name 'response' is not defined

### ISSUE THREAD

**Issue by verazuo** [acheong08/ChatGPT#661]
**Description**
Hi, I tried to use the developer example code shown in Readme.md
And I notice `response` has never been assigned value before called.

```
from revChatGPT.V2 import Chatbot
import os
import sys 

async def main():
    chatbot = Chatbot(email="xxxxx", password="xxxxx")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()
    print(response["choices"][0]["text"])

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

**Output**
```
    print(response["choices"][0]["text"])
NameError: name 'response' is not defined
```

**Comment by 17Reset** [comment]
me too, I just commented it out

**Comment by verazuo** [comment]
oh yes, comment it out works for me.

**Comment by 17Reset** [comment]
但是我还是显示报出我提交的那个错误，像这个“print(response["choices"][0]["text"])
NameError: name 'response' is not defined”，请问您解决了吗？

**Comment by 17Reset** [comment]
But I still show the error I submitted, like this "print(response["choices"][0]["text"]) NameError: name 'response' is not defined", did you solve it?

**Comment by verazuo** [comment]
I use code snippet like 
```
from revChatGPT.V2 import Chatbot
import os
import sys 

async def main():
    chatbot = Chatbot(email="xxxxx", password="xxxxx")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

No errors anymore.

**Comment by 17Reset** [comment]
I'm sad that I still get this error "'accessToken' "

**Comment by Liu-Angelo** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/19570026/218315954-5574fcd0-1d02-4699-ad92-4ac44937d2af.png">
How to get paid 。。。。。。

**Comment by Liu-Angelo** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/19570026/218316002-cf59e559-10e8-4c91-b6ff-aa2e101811d7.png">
How to get Paid 。。。。。。
