### ISSUE TITLE
[BUG] The program entered an infinite loop

### ISSUE THREAD

**Issue by ridiculers** [acheong08/ChatGPT#662]
**Description**
The program entered an infinite loop at the following position in Unofficial.py:
![微信图片_20230212203827](https://user-images.githubusercontent.com/48056715/218311572-432b1543-ad8b-45c7-8cc0-5c94c9639111.png)

**Steps to Reproduce**
1. just run the developer example code under V1 browser automation.
![微信图片_20230212204044](https://user-images.githubusercontent.com/48056715/218311682-7bb992be-c5f3-4e22-848a-d6ff24f3a6b2.png)

**Expected behavior**
Login successful.

**Environment**

 - OS: [Windows]
 - Python version: python 3.9.16
 - ChatGPT Version: 2.1.1

**Comment by mattsegura** [comment]
why close? currently looking into this issue as I have it

**Comment by acheong08** [comment]
Unofficial no longer supported

**Comment by mattsegura** [comment]
ah okay, so what's supported now?

**Comment by acheong08** [comment]
Check readme

**Comment by mattsegura** [comment]
> Check readme

lol I was just about to make a pull request on regarding the readme
