### ISSUE TITLE
[BUG] When I open ChatGPT Plus, the program no longer returns chat messages normally

### ISSUE THREAD

**Issue by kisona11** [acheong08/ChatGPT#663]
When I open ChatGPT Plus, the program no longer returns chat messages normally. What is the solution

**Comment by wuyanxin** [comment]
see this commit https://github.com/acheong08/ChatGPT/commit/a779db846d2fa05bc6449e7e7210a4069f837314
maybe can help

**Comment by verazuo** [comment]
same here. Tried both plus account and normal account with revChatGPT 2.1.2 and 2.1.1.
Either of them can work

**Comment by acheong08** [comment]
It broke for a few moments. Should work now. DDOS attack

**Comment by acheong08** [comment]
DDOS IPs banned
