### ISSUE TITLE
Why don't use official API anymore?

### ISSUE THREAD

**Issue by cooolinx** [acheong08/ChatGPT#664]
Sorry, this is not a bug report, just want a discussion.
I notice that, we no longer use the official API (`openai` module) after https://github.com/acheong08/ChatGPT/commit/eba3016f0f031c9b6c84a34926042639746e8441 
I wonder why? What's your concern? Is there any risk we need to know when using the API?

**Comment by acheong08** [comment]
> I notice that, we no longer use the official API (openai module) after https://github.com/acheong08/ChatGPT/commit/eba3016f0f031c9b6c84a34926042639746e8441

Our free access got revoked

**Comment by acheong08** [comment]
> I wonder why? What's your concern? I

I wrote a cloudflare bypass

**Comment by acheong08** [comment]
> Is there any risk we need to know when using the API?

Read source code: https://github.com/acheong08/ChatGPT-V2
