### ISSUE TITLE
[BUG] paid=True

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#665]
The account is a paid account for ChatGPT Plus, and the subscription to the Plus version has been paid, but the result value is empty

async def main(prompt):
    chatbot = Chatbot(email="*********", password="**********", paid=True)
    message = []
    conver_id = ""
    async for line in chatbot.ask('写一个二分查找代码'):
        result = line["choices"][0]["text"].replace("<|im_end|>", "")
        message.append(result)
        conver_id = line["id"]
        print("-----------", result)
        print(result, end="")
        sys.stdout.flush()
    res = "".join(message)
    print('--------:', res)

**Comment by verazuo** [comment]
same here. 
BTW, the chatgpt plus can only be used in revChatGPT.Unofficial right? 
revChatGPT.V2 cannot use it?

**Comment by acheong08** [comment]
fixed

**Comment by acheong08** [comment]
server side issue
