### ISSUE TITLE
[BUG]Conversation is not recording response from CHATGPT

### ISSUE THREAD

**Issue by freddiewanah** [acheong08/ChatGPT#667]
**Description**
It seems that the conversation retrieved by `conversations.get("conversation_id")` only contains my question prompt. It didn't include the response from CHATGPT.

**Screenshot**
<img width="826" alt="Screenshot 2023-02-12 at 14 46 40" src="https://user-images.githubusercontent.com/11172573/218318013-d007f6bc-f1cd-42f7-b6c1-d891b6b0a516.png">

**Comment by acheong08** [comment]
thanks for the report

**Comment by freddiewanah** [comment]
Hi thanks for the quick response, I have two concerns 1. the conversation history is only added for commandline but not added in the ChatBot.ask(). 2. the conversation_id should be dynamic?

**Comment by acheong08** [comment]
> Hi thanks for the quick response, I have two concerns 1. the conversation history is only added for commandline but not added in the ChatBot.ask(). 2. the conversation_id should be dynamic?

Fixed concern #1. As for #2, conversation_id can be dynamic if you set it programmatically. Command line is just demo

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.1.8
