### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#672]
![image](https://user-images.githubusercontent.com/86822589/218319771-b3030caa-7d5c-49e6-a866-6db838215cef.png)

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/218325133-661a7600-bf6f-418f-9899-a355560e609d.png)

Working for me. Try again

**Comment by acheong08** [comment]
Remember to update

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/218354290-f8ecd29f-8ac9-4712-a374-8c24623fe714.png)
![image](https://user-images.githubusercontent.com/86822589/218354328-89ffb74a-e890-4439-a57f-173bec1faebd.png)
another new account,lastest version,same error
