### ISSUE TITLE
My account is Plus, and when I execute the following command, the following error is displayed.

### ISSUE THREAD

**Issue by thechen130** [acheong08/ChatGPT#673]
python3 -m revChatGPT.V2 -e ********@qq.com -p *******
![image](https://user-images.githubusercontent.com/74664452/218320409-8d1b9a49-4f78-4419-961a-05c588ae7121.png)

**Comment by basetrade** [comment]
i found Error... Logging in again, guess connection failed

**Comment by acheong08** [comment]
Try new version

**Comment by acheong08** [comment]
and make sure you're using normal email/password and not google

**Comment by KyleZhang0536** [comment]
Does plus account have a better offical api perforance?
