### ISSUE TITLE
help me！！！

### ISSUE THREAD

**Issue by thechen130** [acheong08/ChatGPT#677]
python3 -m revChatGPT.V2 -e ********@qq.com -p ******** --paid
![image](https://user-images.githubusercontent.com/74664452/218327801-37b41100-af0a-4909-bff9-59e1bb2d9833.png)

When I run "python3 example.py", the error message is as follows:
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="*******@qq.com", password="*******")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
![image](https://user-images.githubusercontent.com/74664452/218327974-447caf85-14de-4df5-b664-48b68396325c.png)

**Comment by acheong08** [comment]
Try printing the full line and showing what the issue is

**Comment by Pengchengistaken** [comment]
先自己调试，把line打印出来，看看line是什么内容，确定是作者的bug，再来打bug标签。
