### ISSUE TITLE
PROXY_URL 

### ISSUE THREAD

**Issue by iceychanowo** [acheong08/ChatGPT#678]
You're doing a great job!
Sorry to ask this question, but I was wondering what exactly PROXY_URL (https://chat.duti.tech) was doing in the V2 version. It seems to be doing something more than simply forwarding the official api with a headless browser in the previous version. I've observed in V2 that ask requests are simply appending /completions to the PROXY_URL, how is this bypass the official anti-bot tactics?

**Comment by kyrylogy** [comment]
seems sketchy to me as well, especially after handing over not just the api key but account email and password

**Comment by acheong08** [comment]
You're not handing over email/password. Look at the source code. Login is client side

**Comment by acheong08** [comment]
The server is open source https://github.com/acheong08/ChatGPT-V2

**Comment by acheong08** [comment]
>  headless browser in the previous version

No browser on server

**Comment by acheong08** [comment]
Authentication is done locally with this code: https://github.com/acheong08/OpenAIAuth

**Comment by iceychanowo** [comment]
> The server is open source https://github.com/acheong08/ChatGPT-V2

I see it Thanks for the answer
