### ISSUE TITLE
No module named "revChatGPT.V2"

### ISSUE THREAD

**Issue by misakiigmd** [acheong08/ChatGPT#679]
**Description**
After installing the latest version of revChatGPT ( 2.1.10 ), whenever I try to import revChatGPT.V2, I get the error "ModuleNotFoundError: No module named 'revChatGPT.V2'".

**Code (copy pasted from the example)**
```
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="...", password="...")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

**Error**
```
>>> from revChatGPT.V2 import Chatbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'revChatGPT.V2'
```

**Comment by ArjunSahlot** [comment]
This isn't the library's fault, there is a problem with installation.
Here are some possible fixes:
Try running `pip install --upgrade revChatGPT`
This should update the version, there should be **no errors**.
You should see a message "Successfully installed revChatGPT-2.1.10"

Check your virtual environments
Make sure the version you want is installed in the virtual environment you are working in.
Run `pip freeze` or `pip list` to check the versions and packages.

**Comment by misakiigmd** [comment]
Ill try again tomorrow, but I already checked and I did have revChatGPT-2.1.10

**Comment by Pengchengistaken** [comment]
环境问题，建议取消bug标签。

**Comment by Jacobew** [comment]
> This isn't the library's fault, there is a problem with installation. Here are some possible fixes: Try running `pip install --upgrade revChatGPT` This should update the version, there should be **no errors**. You should see a message "Successfully installed revChatGPT-2.1.10"
> 
> Check your virtual environments Make sure the version you want is installed in the virtual environment you are working in. Run `pip freeze` or `pip list` to check the versions and packages.

@ArjunSahlot  I uninstall revChatGPT and run `pip install --upgrade revChatGPT`, but `pip list` shows that I installed revChatGPT of version 2.0.3. 
`python -m revChatGPT.V2 -h` returns error: `No module named revChatGPT.V2`, and `python -m revChatGPT -h` returns error: `No module named openai`.
How can I fix it? Thanks for your response

**Comment by acheong08** [comment]
Latest version is https://github.com/acheong08/ChatGPT/releases/tag/2.2.6

**Comment by acheong08** [comment]
If you're using third party pypi, you need to do `pip3 install revChatGPT==2.2.6`

**Comment by ArjunSahlot** [comment]
You could also try `pip install --upgrade revChatGPT`.
