### ISSUE TITLE
TODO: Log rate limit errors

### ISSUE THREAD

**Issue by memves** [acheong08/ChatGPT#682]
```
 root@jinnvpn:/home/GPTPython# python3 -m revChatGPT.V2 -e *********** -p ************

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.


You:
Hi

ChatGPT:


Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/GPTPython/tutorial-env/lib/python3.10/site-packages/revChatGPT/V2.py", line 325, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/GPTPython/tutorial-env/lib/python3.10/site-packages/revChatGPT/V2.py", line 315, in main
    result = line["choices"][0]["text"].replace("<|im_end|>", "")
TypeError: string indices must be integers
```
Have no idea. Is it a bug or what?
Please help

**Comment by player2I0** [comment]
same

**Comment by yiwangethan** [comment]
Sometimes my script gets stuck and returns this error. However, I just rerun the script and find that the same code does not return this error.

**Comment by acheong08** [comment]
Print full line to show error

**Comment by acheong08** [comment]
Could be rate limits

**Comment by yiwangethan** [comment]
The probability of this error occurring is about 1/30. ChatGPT returns 30 responses and encounters this error once.

**Comment by acheong08** [comment]
Makes perfect sense

**Comment by acheong08** [comment]
Rate limit is 30 requests per minute

**Comment by fengshansi** [comment]
I always have this error.

**Comment by acheong08** [comment]
Are you sharing your account with anyone? Rate limits are account based

**Comment by fengshansi** [comment]
> 

Yes.

**Comment by acheong08** [comment]
Your classmate might be overusing.

**Comment by zzttyy413841467** [comment]
same question


TypeError                                 Traceback (most recent call last)
Cell In[10], line 2
      1 async for line in chatbot.ask('Write a sorting algorithm for arrays in C++ language'):
----> 2     print(line["choices"])
      3     #result = line["choices"][0]["text"].replace("<|im_end|>", "")
      4     #print(result, end="")

TypeError: string indices must be integers
