### ISSUE TITLE
[Feature] (conversation_id & parent_id) How can I get the conversation_id? 

### ISSUE THREAD

**Issue by silent-wolf-arm** [acheong08/ChatGPT#683]
**Is your feature request related to a problem? Please describe.**
I debugged the example you show in the README, but I realize the line object gets and id with just tree points like this "..."

**Describe the solution you'd like**
able to get the conversation_id and parent_id to continue the conversation

**Benefits or Justification**
Resume conversations

**Comment by acheong0** [comment]
It's handled by the code: https://github.com/acheong08/ChatGPT/wiki/V2

**Comment by silent-wolf-arm** [comment]
> It's handled by the code: https://github.com/acheong08/ChatGPT/wiki/V2

I saw you receive conversation_id as a parameter, but it seems you are saving this conversations in an ephemeral structure (Dictionary in memory). and do I put whatever conversation_id I want there? because the question is, how can I know what is the conversation_id of my current conversation to store in a database or something like that and resume later. Sorry if I didn't see this in the code but it seems isn't in that way....

**Comment by acheong08** [comment]
>  do I put whatever conversation_id I want there

Yes it creates the structure automatically when receiving new ID.

>  how can I know what is the conversation_id of my current conversation to store in a database or something like that and resume later. 

You have to write your own code to handle that
