### ISSUE TITLE
[BUG]Hello, I upgraded chatgpt to the plus version, and the program has the following error. This error also occurs when I try not to use the plus version, how should I deal with this problem. I do not share accounts with anyone. This is my first time using your program.

### ISSUE THREAD

**Issue by lean-wang** [acheong08/ChatGPT#685]
Traceback (most recent call last):
  File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 14, in <module>
    asyncio.run(main())
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 8, in main
    print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
TypeError: string indices must be integers

**Comment by acheong08** [comment]
Did you do `--paid`?

**Comment by acheong08** [comment]
If you're using paid account, you must define `paid=True`

**Comment by lean-wang** [comment]
I defined paid=True, it still doesn't work, I print the line, the line says Error... Logging in again

**Comment by acheong08** [comment]
I'm adding more error codes

**Comment by acheong08** [comment]
wait a moment

**Comment by lean-wang** [comment]
ok,thank you

**Comment by lean-wang** [comment]
i defined insecure=True，The program shows KeyError: 'accessToken'

**Comment by zzttyy413841467** [comment]
you can try to  add a proxy，and i is the same before.

**Comment by lean-wang** [comment]
I use vpn, a node in the United States

**Comment by thechen130** [comment]
> 如果您使用的是付费帐户，则必须定义`paid=True`

--paid 是用的官方的API-key吗？还是只是用于plus账号的登录？

**Comment by acheong08** [comment]
Plus account

**Comment by lean-wang** [comment]
I upgraded to 2.1.11. The running program now displays Exception: OpenAI error!

**Comment by Silhouettes-of-U** [comment]
> Traceback (most recent call last): File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 14, in asyncio.run(main()) File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/Users/wzq/opt/anaconda3/envs/chatgpt/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/Users/wzq/Desktop/word_medi/event_extraction/models/ie/uie.py", line 8, in main print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="") TypeError: string indices must be integers

I got the same error... and my location is China, when I run `python3 -m revChatGPT.Proxied` it will return "AttributeError: 'OpenAIAuth' object has no attribute 'get_access_token'"

**Comment by thechen130** [comment]
> Plus account



> If you're using paid account, you must define `paid=True`

请问在哪个文件中定义`paid=True`

**Comment by lean-wang** [comment]
The program is back to normal. Thank you for your work
