### ISSUE TITLE
[付费请求帮助]python小白付费求帮助

### ISSUE THREAD

**Issue by long202258** [acheong08/ChatGPT#686]
python小白付费求帮助能让程序跑起来

**Comment by cat-my-earn** [comment]
很简单的，自己学学就好了，之前的帖子里面有很多例子

**Comment by thechen130** [comment]
> python小白付费求帮助能让程序跑起来

+1，我也是小白，不知道如何跑起来，有大佬愿意指导一下吗

**Comment by cat-my-earn** [comment]
> > python小白付费求帮助能让程序跑起来
> 
> +1，我也是小白，不知道如何跑起来，有大佬愿意指导一下吗

具体操作流程应该没问题吧（直接用、py调用），如果是网络问题（比如一直跳浏览器循环），建议试一下手机热点，我手机热点就能正常用。

我也是小白，但是大佬其实把具体流程写得比较清楚了，很多细节没写，但是去看一下源代码里面Chatbot这个类的实现，以及初始化具体在做什么，弄懂这些基本上流程上的东西就清楚了。

主要问题还是网络问题，这个只能等大佬慢慢修复，目前我自己的情况是用vpn不行，开全局都不行，不用vpn显示访问拒绝，只有手机开热点关vpn的时候才能正常登上。

**Comment by shinjiyu** [comment]
确实,有啥问题不如直接在这里问.

**Comment by apple2099** [comment]
我都是Error... Logging in again，你们是这样吗？

**Comment by cat-my-earn** [comment]
> 我都是Error... Logging in again，你们是这样吗？

没有遇到这个情况，得说的具体一些

**Comment by apple2099** [comment]
用readme给出的示例代码运行
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="myemail@qq.com", password="mypassword")
    async for line in chatbot.ask("Hello"):
        print(line)
        # print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush=True)
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

没有报错，但得出的结果就是Error... Logging in again
