### ISSUE TITLE
[BUG]How to use it in China, whether or not to use vpn can not be used

### ISSUE THREAD

**Issue by cat-my-earn** [acheong08/ChatGPT#687]
The only successful one is to use cell phone traffic without proxy, using the session_token method to log in, and the email password will enter the loop of constantly opening and closing the browser no matter what the situation is.

The trouble is that you can't always turn on the mobile hotspot, once you switch to another network you will enter the state where you can't access without hanging a proxy, and hanging a proxy will enter the infinite loop of opening and closing the browser. I have seen in other posts that the proxy is turned on and off until the first time the browser is closed, but the result is that it enters the inaccessible interface again.

目前唯一成功的就是用手机流量同时不挂代理，使用的是session_token的方法登录，邮箱密码无论什么情况下都会进入不停打开关闭浏览器的循环。

麻烦的地方在于总不能时时开着手机热点，一旦切换到其他网络就会进入不挂代理就无法访问，挂了代理就进入无限循环打开关闭浏览器的状态。之前在其他帖子看到在打开代理，直到第一次关闭浏览器之后关闭代理，但是这样的结果就是又进入无法访问的界面。

**Comment by acheong08** [comment]
Check V2

**Comment by cat-my-earn** [comment]
I'll try it.

**Comment by long202258** [comment]
> --insecure-auth

付费求解决

**Comment by cat-my-earn** [comment]
> Check V2
> 
> In China you must use proxy or `--insecure-auth`

how to ues V2 ? 
QAQ

**Comment by acheong08** [comment]
`pip3 install --upgrade revChatGPT`

Check new readme

**Comment by cat-my-earn** [comment]
> 

thanks ,I'll try

**Comment by nieziqi123** [comment]
目前使用--insecure-auth可以登录成功 但https://chat.duti.tech还是需要通过proxy才能访问 不知是否有什么解决办法？  @acheong08

**Comment by cat-my-earn** [comment]
> `pip3 install --upgrade revChatGPT`
> 
> Check new readme

I used it on python, and after the update, I couldn't even log in through the session-token, I don't know what happened, the browser jumped to the login interface after launching, and then it didn't move, even if I logged in again myself didn't continue to go down

我在python上使用，在更新之后甚至无法通过session-token来登陆了，不知道发生了什么，浏览器启动后跳转到登陆界面，然后不动了，即使我自己后面又登陆了也没有继续向下进行（因为我用的是微软账号而不是直接的邮箱密码，所以习惯用session-token登录）

**Comment by acheong08** [comment]
> I used it on python, and after the update, I couldn't even log in through the session-token, I don't know what happened, the browser jumped to the login interface after launching, and then it didn't move, even if I logged in again myself didn't continue to go down

Session token don't work anymore

**Comment by acheong08** [comment]
> 目前使用--insecure-auth可以登录成功 但[https://chat.duti.tech还是需要通过proxy才能访问](https://chat.duti.xn--techproxy-yn8rq55a464fsexa25gckqyha63bu41eoue/) 不知是否有什么解决办法？ @acheong08

我没办法。Use VPN

**Comment by cat-my-earn** [comment]
> > I used it on python, and after the update, I couldn't even log in through the session-token, I don't know what happened, the browser jumped to the login interface after launching, and then it didn't move, even if I logged in again myself didn't continue to go down
> 
> Session token don't work anymore
What is the reason for the cancellation of it, can you ask?

**Comment by cat-my-earn** [comment]
> > I used it on python, and after the update, I couldn't even log in through the session-token, I don't know what happened, the browser jumped to the login interface after launching, and then it didn't move, even if I logged in again myself didn't continue to go down
> 
> Session token don't work anymore

What is the reason for the cancellation of it

**Comment by acheong08** [comment]
It should work on next release

**Comment by acheong08** [comment]
It just takes time to get everything fixed since i'm rewriting from scratch
