### ISSUE TITLE
[BUG] Suffering DDOS again?

### ISSUE THREAD

**Issue by yiwangethan** [acheong08/ChatGPT#688]
Just a few minutes ago, all my processes simultaneously reported "Exception. Unknown error". I don't think I exceeded the speed limit and can confirm that my e-mail password is fine, is it possible that the server went offline or got attacked again?

**Comment by acheong08** [comment]
rate limiting

**Comment by acheong08** [comment]
This error is from OpenAI, not me

**Comment by yiwangethan** [comment]
Sorry, but I have no idea how to solve this error. I have changed several accounts, but they all keep reporting "Exception. Unknown error".

**Comment by acheong08** [comment]
Are you using Microsoft or Google account? Not supported

**Comment by acheong08** [comment]
Not supported

**Comment by yiwangethan** [comment]
I just wait about 30 mins, and right now I can log in with the accounts mentioned above now. P.S.: I still don't know what happened, but thanks for your reply.

**Comment by dawhdb** [comment]
你好，这个速率限制是对单账号还是对ip，我第一次启动全是Unknown error

**Comment by acheong08** [comment]
> Hello, is this rate limit for a single account or for an ip? All the results are Unknown error when I start it for the first time

Rate limit is based on IP address now

**Comment by acheong08** [comment]
If you need higher rate limits, you need a private server

**Comment by dawhdb** [comment]
> 

If chatbot passes in the account password as well as the proxy, can it not use the same ip address?

**Comment by dawhdb** [comment]
> If you need higher rate limits, you need a private server

If chatbot passes in the account password as well as the proxy, can it not use the same ip address?

**Comment by acheong08** [comment]
Yes. By OpenAI. 50 RPS
