### ISSUE TITLE
Error... Logging in again[BUG]

### ISSUE THREAD

**Issue by 17Reset** [acheong08/ChatGPT#692]
Error... Logging in again
当我执行如下代码时，出现这样的错误：
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="@gmail.com", password="xxx")
    async for line in chatbot.ask("Hello"):
        # print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        print(line)
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

**Comment by ZZY-26-26-25** [comment]
Same as me

**Comment by acheong08** [comment]
OpenAI returning error for some reason

**Comment by ZoidbergPi** [comment]
加一个for循环包裹try..catch来实现重复登录直到登录上为止
