### ISSUE TITLE
Hello, is V2 able to remember previous conversations?

### ISSUE THREAD

**Issue by AChangAZha** [acheong08/ChatGPT#695]
Every time you ask it a question, you need to send it the following sentence and all its previous replies.
```
BASE_PROMPT = (
    os.environ.get("BASE_PROMPT")
    or """You are ChatGPT, a large language model by OpenAI. Respond conversationally\n\n\n"""
)
```
It seems that this is not the real "ChatGPT"? Is it just completing sentences sent to it?
Is it not the same as the Unofficial version? I remember that Unofficial version only required `conversation_id` and `parent_id` as parameters to resume the conversation.

**Comment by JerryWn12** [comment]
https://github.com/acheong08/ChatGPT/wiki/V2

**Comment by JerryWn12** [comment]
The official ChatGPT have a prompt too

**Comment by AChangAZha** [comment]
> The official ChatGPT have a prompt too

Thank you for your reply. If the program terminates without saving the past conversation messages, it means there is no way to restore the conversation, right? I prefer Unofficial version, just need to pass two id's to resume the conversation.

**Comment by acheong08** [comment]
You must do so via code.

On another note: Unofficial is now available as browserless via https://github.com/acheong08/ChatGPT#v1-standard-chatgpt

**Comment by AChangAZha** [comment]
> You must do so via code.
> 
> On another note: Unofficial is now available as browserless via https://github.com/acheong08/ChatGPT#v1-standard-chatgpt

Thank you very much for your reply. I will try it.
