### ISSUE TITLE
提示：RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by guangh01** [acheong08/ChatGPT#697]
![1676282245561](https://user-images.githubusercontent.com/87555064/218427038-f4a70498-06b8-4f23-9e15-abbb77881b0e.png)
问题中没找到答案，麻烦帮助我，非常感谢！

**Comment by DiGolDi** [comment]
Same error

**Comment by shenziqian** [comment]
我也是，命令行是正常的
