### ISSUE TITLE
请问这是GPT-3.5还是GPT-3呢

### ISSUE THREAD

**Issue by yuzyf** [acheong08/ChatGPT#698]

**Comment by yuzyf** [comment]
感觉和网页的不太一样呢

**Comment by thechen130** [comment]
同问

**Comment by acheong08** [comment]
GPT3.5

**Comment by acheong08** [comment]
Same model as `chat.openai.com`

**Comment by yuzyf** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/77232395/218464538-17041ff3-791d-4d74-9e30-2d492a0d5919.png">
可是这个显示的是2020年的模型呢、资料库也是2020年、3.5不是截止到2021年吗

**Comment by acheong08** [comment]
It says 2021 when you ask it in English
