### ISSUE TITLE
[BUG]Exception: Unknown error

### ISSUE THREAD

**Issue by ZZY-26-26-25** [acheong08/ChatGPT#699]
**Description**

**Steps to Reproduce**
(ros_data_process) apple@Mills-MacBookPro14 ChatGPT-2.1.1 % python3 -m revChatGPT.V2 -e "" -p ""

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Logging in...
Logged in

Type '!help' to show a full list of commands
Press enter twice to submit your question.

You:

You:
you

ChatGPT:
error: Unknown error
Traceback (most recent call last):
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 361, in <module>
    asyncio.run(main())
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 350, in main
    async for line in chatbot.ask(prompt=prompt):
  File "/Users/apple/miniforge3/envs/ros_data_process/lib/python3.9/site-packages/revChatGPT/V2.py", line 169, in ask
    raise Exception("Unknown error")
Exception: Unknown error

**Output**
In the correct directory, run the following command:
`python3 -m revChatGPT --debug`
No module named revChatGPT.__main__; 'revChatGPT' is a package and cannot be directly executed

**Environment**
 - OS: MacOS, m1 chip
 - Python version: python  3.9.15
 - ChatGPT Version: 2.1.14

**Comment by wttnb911** [comment]
I have the same problem. Have you solved it

**Comment by Amirnoroozi** [comment]
I have the same problem

**Comment by fkgiljoni** [comment]
Same problem

**Comment by fkgiljoni** [comment]
Oh, I have an OpenAI Plus subscription, and the solution to my problem was to include paid=True during the chatbot initialization. The module doesn't work without it

**Comment by acheong08** [comment]
Plus accounts must either have `paid=True` in code or `--paid` in command line

**Comment by ZZY-26-26-25** [comment]
but I'm not the plus account. ~~

**Comment by acheong08** [comment]
Are you using a Google or Microsoft account? Those aren't supported either and require session tokens

**Comment by ZZY-26-26-25** [comment]
> Plus accounts must either have `paid=True` in code or `--paid` in command line

I'm not the plus accounts and it doesn't work if I make changes with the "paid" QAQ

**Comment by acheong08** [comment]
Google and Microsoft don't work either

**Comment by ZZY-26-26-25** [comment]
I'm using outlook accounts. Like XXXX@outlook.com

**Comment by ZZY-26-26-25** [comment]
> 

I'm using outlook accounts, seems not Google or Microsoft

**Comment by fkgiljoni** [comment]
> > 
> 
> I'm using outlook accounts, seems not Google or Microsoft

Outlook is Microsoft's email service

**Comment by ZZY-26-26-25** [comment]
> 
Thanks. So I had better use other account.

**Comment by ArjunSahlot** [comment]
> Are you using a Google or Microsoft account? Those aren't supported either and require session tokens
@acheong08 

Does an email like "asdf@gmail.com" and password like "password" not work? I don't use the "Continue with Google" button yet I can still sign in, but, I am also getting an error.

**Comment by acheong08** [comment]
Server was DDOSed. It's back up but without --insecure-auth option

**Comment by ArjunSahlot** [comment]
Is that the cause of the Unknown error? Because it is still happening to me.

**Comment by acheong08** [comment]
Could be a different error then

**Comment by acheong08** [comment]
We don't support Microsoft and Google accounts

**Comment by ArjunSahlot** [comment]
Could you give me an example of what type of account is supported?

**Comment by acheong08** [comment]
Standard OpenAI accounts via email & password. You can also try session tokens https://chat.openai.com/api/auth/session

**Comment by acheong08** [comment]
I will add accessToken support later

**Comment by ArjunSahlot** [comment]
> Standard OpenAI accounts via email & password. You can also try session tokens [chat.openai.com/api/auth/session](https://chat.openai.com/api/auth/session)

So does that disqualify all emails that end in @gmail.com?

**Comment by acheong08** [comment]
No. Only Google login

**Comment by JacksonTxl** [comment]
windows访问就会有这个http unknown error 错误，是因为账号导致的？

**Comment by ArjunSahlot** [comment]
> No. Only Google login

I use the normal email login, but I still get this error. Could there be another possible cause?

**Comment by ArjunSahlot** [comment]
I just created a new account (with normal email), and it still doesn't work :(

**Comment by ttytu2** [comment]
sample error
use qq email login

**Comment by acheong08** [comment]
Server shut down due to OpenAI

**Comment by ypatz** [comment]
> Server shut down due to OpenAI

I can use chatgpt through browser but failed when using api with email passwd and session_token

**Comment by Gauss-G** [comment]
> > Server shut down due to OpenAI
> 
> I can use chatgpt through browser but failed when using api with email passwd and session_token

same case

**Comment by ArjunSahlot** [comment]
> Server shut down due to OpenAI

Can we self host?

**Comment by huangyangyu** [comment]
Similar issue. Weird! The **accessToken** is different between browser's one and API's one. Before replace it, I got error code 404 and after I replaced it, the error code turned to 502.

**Comment by huangyangyu** [comment]
> Similar issue. Weird! The **accessToken** is different between browser's one and API's one. Before replace it to browser's one in V2.py, I got error code 404 and after I replaced it, the error code turned to 502.

Same issue with or without VPN.

**Comment by Gauss-G** [comment]
it seems return a 502 error with openAI api
error: 502

**Comment by XZY23333** [comment]
Exact same error here, plz fix it, thanks!

**Comment by acheong08** [comment]
V2 broken. Use V1
