### ISSUE TITLE
Unreliable conversation_id

### ISSUE THREAD

**Issue by angelfor3v3r** [acheong08/ChatGPT#7]
I was wondering if you've had luck using "conversation_id" to continue a conversation. It seems like when I first start a conversation (without passing "conversation_id") and then reusing it for future replies, I always get a response like so:
```
bot  | {"detail":"Too many requests, please slow down"}
bot  | Error: Response is not a text/event-stream
```

Am I using it wrong? I'm basically just caching off the "conversation_id" after I get my first response and passing it to the `ChatBot` constructor.

**Comment by acheong08** [comment]
> {"detail":"Too many requests, please slow down"}

This is a sign of rate limiting. There was a limit of 48 requests per minute I think. It might have been reduced.

**Comment by acheong08** [comment]
Replicated. If you try to put a conversation_id manually, it fails. It might be that it compares the parent_id to the conversation_id on the server side. Try setting the correct parent_id as well as conversation_id

**Comment by angelfor3v3r** [comment]
Yeah, I'm not rate limited anymore but it seems like it forgets it's previous replies for me (i.e, I ask it to write code and to modify it's last response and it doesn't understand).

I'm caching off "conversation_id" and "parent_id", then reusing both values on the next invocation of "get_chat_response".

**Comment by acheong08** [comment]
Does it work if you run it from the command line?

```
 $ python3 -m revChatGPT     

    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT
    
Type '!exit' to exit
Press enter twice to submit your question.

You: Hello



Chatbot: Hello! I'm Assistant, a large language model trained by OpenAI. I'm here to help you with any questions you may have. What can I help you with today?


0
You: What is an egg



Chatbot: An egg is a reproductive body produced by female birds, reptiles, insects, and other animals. It consists of a protective outer layer called the shell, a nutrient-rich white or yellowish substance called the albumen, and a central yolk that contains the egg's genetic material. Some eggs are also fertilized by a male, in which case the egg contains a developing embryo. Eggs are a common ingredient in many types of food, and they are also a good source of protein and other nutrients.


0
You: continue



Chatbot: Sure! Is there anything specific you would like me to continue talking about regarding eggs? For example, I can talk more about the different types of eggs, how they are used in cooking, or their nutritional value. Let me know if there's anything specific you're interested in.


0
You: 
```

**Comment by angelfor3v3r** [comment]
Yes, It does. I must be doing something *very* wrong in my code. I'm basically doing something like so:
```
chatbot = Chatbot(self.chatbot_cfg, conversation_id=convo_id)

if parent_id:
    chatbot.parent_id = saved_parent_id

resp = chatbot.get_chat_response("prompt")
```

Both my "convo_id" and "parent_id" are the same ones from the original reply, but the replies I get seem to forget I've been talking to it.

**Comment by acheong08** [comment]
```py
        self.parent_id = response["message"]["id"]
        self.conversation_id = response["conversation_id"]
        message = response["message"]["content"]["parts"][0]
        return {'message':message, 'conversation_id':self.conversation_id, 'parent_id':self.parent_id}
```
The `get_chat_response` function returns the `conversation_id` and `parent_id`. Make sure you're taking it from there.

**Comment by angelfor3v3r** [comment]
I was. I'm trying a different approach now where I just cache off the entire "Chatbot" class instead. So far it seems to work better and I don't get rate limited, I need to test more though.

**Comment by Pab450** [comment]
> I was. I'm trying a different approach now where I just cache off the entire "Chatbot" class instead. So far it seems to work better and I don't get rate limited, I need to test more though. Thanks for all the help so far!

Hey can you show me an example? I get the same problem and I don't quite understand how you managed to solve it?

**Comment by angelfor3v3r** [comment]
My solution is pretty awful. Im just saing off the entire ChatBot class instance for each “user” in a dict. I then manually refresh tokens and such.

**Comment by acheong08** [comment]
@angelfor3v3r 
```py
from revChatGPT.revChatGPT import Chatbot
import json
# Get config
config = open("config.json", "r").read()
config = json.loads(config)
# Create a chatbot object
chatbot = Chatbot(config)

chatbot.refresh_session()

# Get a response
response = chatbot.get_chat_response("What is an egg?", output="text")

conversation = response['conversation_id']
parent_id = response['parent_id']
message = response['message']
print(message)

del chatbot

chatbot = Chatbot(config)
chatbot.conversation_id = conversation
chatbot.parent_id = parent_id
response = chatbot.get_chat_response("continue", output="text")
message = response['message']
print(message)
```

```
 $ python3 GPT.py
Logging in...
An egg is a fertilized or unfertilized reproductive cell produced by birds, reptiles, and some amphibians. In birds and reptiles, the egg contains a developing embryo, which is fed by a yolk. The egg is surrounded by a hard shell that protects the embryo and helps to regulate its temperature. In some species, the egg is also covered in a protective outer layer called the chorion. Eggs are a source of nutrition for many animals and are also used as a food by humans.
Eggs are an important food for many animals, including birds and reptiles, which use them to provide nourishment to their young. For humans, eggs are a rich source of protein, vitamins, and minerals, and are often used in cooking. They can be prepared in a variety of ways, including boiling, frying, and scrambling. Eggs are also used in many processed foods, such as baked goods and pasta. Some people also use eggs as a source of food for their pets, such as birds and reptiles.
```
