### ISSUE TITLE
[BUG]revChatGPT.V1报错 - V1 Under maintenance 

### ISSUE THREAD

**Issue by long201058** [acheong08/ChatGPT#702]
![image](https://user-images.githubusercontent.com/67696824/218452339-60dabb72-615b-45cb-9c19-afeda4dd14c0.png)
python 3.10.5  W10 详细看图

**Comment by Linusp** [comment]
看起来是认证出错了，你没贴初始化部分，不确定是啥问题

```python
chatbot = Chatbot(config={
  "email": "<your email>",
  "password": "your password"
})
```

国内的话，或许要加个 `proxy` 到 config 里

**Comment by Silhouettes-of-U** [comment]
> 看起来是认证出错了，你没贴初始化部分，不确定是啥问题
> 
> ```python
> chatbot = Chatbot(config={
>   "email": "<your email>",
>   "password": "your password"
> })
> ```
> 
> 国内的话，或许要加个 `proxy` 到 config 里

想问一下这个`proxy`里面应该加什么字段？是找一个外网的ip吗

**Comment by acheong0** [comment]
V1 was taken down. Under rewrite in Go

**Comment by Linusp** [comment]
> > 看起来是认证出错了，你没贴初始化部分，不确定是啥问题
> > ```python
> > chatbot = Chatbot(config={
> >   "email": "<your email>",
> >   "password": "your password"
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 国内的话，或许要加个 `proxy` 到 config 里
> 
> 想问一下这个`proxy`里面应该加什么字段？是找一个外网的ip吗

这样

```
chatbot = Chatbot(config={
  "email": "<your email>",
  "password": "your password",
  "proxy": "http://localhost:8888",
})
```

增加的 `"proxy": "http://localhost:8888",` 这个就是用来设置代理，也就是我们说的 VPN 之类的东西，这个你自己查下资料了解下自己解决吧。

另外，上一条作者回复了，V1 需要的一个中转服务（作者维护，不用你管）目前下线重写中，也就是说现在 V1 暂时用不了，等作者消息吧。

**Comment by acheong08** [comment]
Pinned and will fix later

**Comment by acheong08** [comment]
No longer under maintenance

**Comment by acheong08** [comment]
fixed

**Comment by acheong08** [comment]
It's under V1

**Comment by CGandGameEngineLearner** [comment]
> It's under V1
must use V1?

**Comment by CGandGameEngineLearner** [comment]
> It's under V1

V2 can't work too

**Comment by acheong08** [comment]
V2 broken
