### ISSUE TITLE
[BUG] `523 Origin is unreachable` Exception

### ISSUE THREAD

**Issue by magnusrodseth** [acheong08/ChatGPT#704]
**Description**

I'm trying to follow the example described in the `README.md`. My end goal is to read a file and use this to communicate with ChatGPT, but this is not relevant to the bug discovered.

This is my current code:

```python
import sys
from revChatGPT.V2 import Chatbot
import os

# Whatever prompt can go here.
prompt = """
What are the pros and cons of working at Facebook?
"""


async def generate(argv) -> bool:
    # argv should only process 1 argument
    if len(argv) != 1:
        print("> Invalid input. Please use the following format:")
        print(f'$ python3 generate.py filename')
        return False

    filename: str = argv[0]
    email: str = os.environ.get("EMAIL")
    password: str = os.environ.get("PASSWORD")

    chatbot = Chatbot(email=email, password=password)
    query = chatbot.ask(prompt)

    async for line in query:
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

    return True


async def main():
    await generate(sys.argv[1:])


if __name__ == '__main__':
    import asyncio
    # Syntax: python3 generate.py filename
    succeeded = asyncio.run(main())

    print(
        "> Successfully generated response from ChatGPT!"
        if succeeded
        else "> An error occurred when trying to communicate with ChatGPT!"
    )
```

I get the following error stack trace when running the script:

```sh
error: Unknown error
Traceback (most recent call last):
  File path_to_project/generate.py", line 39, in <module>
    succeeded = asyncio.run(main())
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "path_to_project/generate.py", line 33, in main
    await generate(sys.argv[1:])
  File "path_to_project/generate.py", line 24, in generate
    async for line in query:
  File "/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "~/Library/Caches/pypoetry/virtualenvs/applier-czcvEFrK-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1583, in stream
    yield response
  File "~/Library/Caches/pypoetry/virtualenvs/applier-czcvEFrK-py3.11/lib/python3.11/site-packages/revChatGPT/V2.py", line 170, in ask
    raise Exception("Unknown error")
Exception: Unknown error
```

Note how the error is simply an `Unknown error`.

I started debugging by printing in the library's `.ask()` method. I can see that I get a `523 Origin is unreachable`. This is Cloudflare -specific, but I cannot see any part about how to resolve this error in the `README` or Wiki.

If this is a common problem, this should be addressed in the documentation.

The `README` has a part about [using Cloudflare bypass server](https://github.com/acheong08/ChatGPT#v2-fast-chatgpt-api), but it's not fleshed out and I don't understand if I need to run it myself.

**Steps to Reproduce**
1. Start new project
2. Activate virtual environment
3. Add sample code from `README`

```python
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="...", password="...")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="")
        sys.stdout.flush()
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```

4. Authenticate using email and password
5. Add prompt
6. Observe that you get the Cloudflare error

**Expected behavior**

I should be able to communicate with ChatGPT.

**Comment by youhj1992** [comment]
+1

**Comment by hou-rong** [comment]
+1

**Comment by acheong08** [comment]
Don't comment +1. Upvote using 👍 if you are experiencing this. It is working fine for me personally so it could be an account issue. I will write some automated tests tomorrow

**Comment by magnusrodseth** [comment]
@acheong08 As I have not looked into how communication between the Python library and ChatGPT works, I'm asking you: Do you know if the `523` code stems from capacity in the ChatGPT service?

If so, I would gladly submit a PR that handles this exception and gives the user a better error message.

**Comment by acheong08** [comment]
> Do you know if the 523 code stems from capacity in the ChatGPT service?

It does not. It stems from the server code which detects OpenAI errors. I will update the server code to forward the OpenAI status code

**Comment by acheong08** [comment]
The error from OpenAI is `{"detail": "An error ocurred. Try refreshing your browser."}`

**Comment by acheong08** [comment]
It is very generic on their side as well

**Comment by acheong08** [comment]
I am assuming it is a case of invalid accessToken

**Comment by magnusrodseth** [comment]
@acheong08 It may actually be related to authentication. I seem to recall it working (and not sending a `523`) when my environment variables were loaded correctly.

**Comment by acheong08** [comment]
I agree. It also returns this error if you have a plus account but trying to use free model or free account trying to use paid model

**Comment by magnusrodseth** [comment]
@acheong08 Quickfix open now 👍🏼

**Comment by youhj1992** [comment]
> Don't comment +1. Upvote using 👍 if you are experiencing this. It is working fine for me personally so it could be an account issue. I will write some automated tests tomorrow

sure, now it is fixd,thanks
