### ISSUE TITLE
[BUG] RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by ITerydh** [acheong08/ChatGPT#706]
**Description**
RuntimeError: Event loop is closed

![v2](https://user-images.githubusercontent.com/46839689/218465557-e8a22b62-a2f1-4dc8-9f65-4e185c3015db.png)

This will happen whether the VPN is used or not

**Environment**
`pip3 install --upgrade revChatGPT`

**Comment by acheong08** [comment]
V2 broken. Use V1
