### ISSUE TITLE
502 bad gateway when use --insecure-auth

### ISSUE THREAD

**Issue by xjd-ziyu** [acheong08/ChatGPT#707]
Login failed

**Comment by xjd-ziyu** [comment]
![543f802b62fb1937699e0cdfad147871](https://user-images.githubusercontent.com/65710139/218470476-ac4770c1-e419-470b-9ad0-52e7ab850dfc.png)

**Comment by xjd-ziyu** [comment]
To add, when I do not use --insecure-auth, I log in successfully

**Comment by acheong08** [comment]
Auth got killed due to ddos

**Comment by acheong08** [comment]
but yes, try to avoid insecure auth
