### ISSUE TITLE
Does anyone have this problem

### ISSUE THREAD

**Issue by wangjiangyue0226** [acheong08/ChatGPT#71]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/49555200/205864744-03a09cac-64dc-44ce-9429-4e730a8fc223.png">

**Comment by acheong08** [comment]
What is your `revChatGPT` version and Python version?
`python3 -V`
`pip3 show revChatGPT`

**Comment by wangjiangyue0226** [comment]
您好，您发给我的邮件我已收到，会尽快给您回复。祝您身体健康，天天开心。

**Comment by wangjiangyue0226** [comment]
Python 3.10.8
revChatGPT 0.0.14

**Comment by acheong08** [comment]
You are using an extremely outdated version of `revChatGPT`. Please update `pip3 install revChatGPT --upgrade`

**Comment by wangjiangyue0226** [comment]
Solved, thank you
