### ISSUE TITLE
[Bug]: How To install in Termux

### ISSUE THREAD

**Issue by Kuchiriel** [acheong08/ChatGPT#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

You have to do `pkg install libxslt` and `pkg install rust` in order to run `pip3 install --upgrade revChatGPT` successfully. 

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

.

### What is your operating system ?

Android

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
Invalid. Not a bug. Open in discussions
