### ISSUE TITLE
[Bug]: Fail to run the starter

### ISSUE THREAD

**Issue by zhimin-z** [acheong08/ChatGPT#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

 I install this tool on my Anaconda PC but failed to run the starter code.

### Steps to reproduce the problem

1. install revChatGPT with `pip3 install --upgrade revChatGPT`
2. create a new python file named `example.py`
3. copy the starter code and add my token: 
```
from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(session_toke=os.getenv('OPENAI_API_KEY'))
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush = True)
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
```
4. run the code

### What should have happened?

I do not know, this is the very first time I run the code.

### Commit where the problem happens

NA

### What is your operating system ?

Windows 10

### Command Line Arguments

```Shell
python example.py
```

### Console logs

```Shell
Here is my error running the starter:

   async for line in chatbot.ask("Hello"):
    ^
SyntaxError: 'async for' outside async function
```
```


### Additional information

_No response_

**Comment by acheong08** [comment]
Are you using Python 2? This should not happen.

**Comment by zhimin-z** [comment]
> Are you using Python 2? This should not happen.

I am using Python 3.9.13
