### ISSUE TITLE
('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')

### ISSUE THREAD

**Issue by mazzzystar** [acheong08/ChatGPT#72]
```bash
Logging in...

You:
Hi

Chatbot:
Something went wrong!
list index out of range
```

```bash
pip3 install revChatGPT --upgrade
Requirement already satisfied: revChatGPT in /opt/homebrew/lib/python3.9/site-packages (0.0.26.1)
```

**Comment by acheong08** [comment]
Do `python3 -m revChatGPT --text`. If that works, it means there is an error with streaming

**Comment by mazzzystar** [comment]
```bash
Logging in...

You:
Hi

Chatbot:
/Users/Library/Python/3.9/lib/python/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
Something went wrong!
('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')
```

It needs API Key, I thought it could be done with only `email` & `password`

**Comment by acheong08** [comment]
It shouldn't. This could mean wrong email/password

**Comment by mazzzystar** [comment]
I've confirmed of using this email+password to re-login OpenAI right now.

**Comment by acheong08** [comment]
What version? `pip3 show revChatGPT`?

**Comment by mazzzystar** [comment]
```bash
>>> pip3 show revChatGPT
Name: revChatGPT
Version: 0.0.26.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /opt/homebrew/lib/python3.9/site-packages
Requires: bs4, lxml, requests, tls-client
Required-by:
```

**Comment by acheong08** [comment]
While running it, try `!config` and see if the tokens show up

**Comment by mazzzystar** [comment]
```bash
You:
!config

{
    "email": "xxx",
    "password": "xxx,
    "Authorization": "",
    "session_token": null
}
```

**Comment by acheong08** [comment]
It's not logging in properly. Could be due to captcha. I am unsure.

**Comment by acheong08** [comment]
Try `!refresh` and see if any errors show

**Comment by mazzzystar** [comment]
```bash
Logging in...

You:
!refresh

Error refreshing session
{}
Session refreshed.
```

I've also tried of removing all OpenAI's cookie from Chrome, still not working.

**Comment by acheong08** [comment]
> Error refreshing session

Hmm. Can you clone the repository and try adding some debug code? For example, print out the full responses of session refresh

**Comment by acheong08** [comment]
I can't replicate

**Comment by mazzzystar** [comment]
OK, I've try and put on more information.

**Comment by yumusb** [comment]
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>xxxxxx</span></div></div></body></html>


Maybe block by waf, or other bot manager ?

**Comment by mazzzystar** [comment]
BTW, It's confusing that your [config.json.example](https://github.com/acheong08/ChatGPT/blob/main/config.json.example) shows 
```bash
{
    "Authorization": "<API_KEY>",
    "session_token": "<SESSION_TOKEN>"
}
```

But the [Setup](https://github.com/acheong08/ChatGPT/wiki/Setup) was using 
```bash
{
    "email": "<YOUR_EMAIL>",
    "password": "<YOUR_PASSWORD>"
}
```

**Comment by acheong08** [comment]
@yumusb Update please. `pip3 install revChatGPT` --upgrade

**Comment by acheong08** [comment]
> BTW, It's confusing that your [config.json.example](https://github.com/acheong08/ChatGPT/blob/main/config.json.example?rgh-link-date=2022-12-06T09%3A28%3A48Z) shows
> 
> ```shell
> {
>     "Authorization": "<API_KEY>",
>     "session_token": "<SESSION_TOKEN>"
> }
> ```
> 
> But the [Setup](https://github.com/acheong08/ChatGPT/wiki/Setup) was using
> 
> ```shell
> {
>     "email": "<YOUR_EMAIL>",
>     "password": "<YOUR_PASSWORD>"
> }
> ```

I forgot to update the example

**Comment by acheong08** [comment]
btw I found the error. Fixing now

**Comment by acheong08** [comment]
Fixed. Please test

**Comment by zjrwtx** [comment]
well ，it seems that ！config doesnt work in my CLI

![image](https://user-images.githubusercontent.com/86822589/205887993-23c1dfa2-5347-4b53-ad9f-b24ab5535e51.png)

**Comment by acheong08** [comment]
@zjrwtx It seems you haven't updated. `pip3 install --upgrade revChatGPT`

!config doesn't require API

**Comment by alberduris** [comment]
It works for me on the CLI but I get the same error when using the Python script

```
from revChatGPT.revChatGPT import Chatbot

config = {
    "email": "xxx",
    "password": "xxx"#,
    #"session_token": "<SESSION_TOKEN>", # Deprecated. Use only if you encounter captcha with email/password
    #"proxy": "<HTTP/HTTPS_PROXY>"
}

chatbot = Chatbot(config, conversation_id=None)

prompt = "Javascript library for cropping images programatically"

chatbot.get_chat_response(prompt, output="text")
```

Output:
```
/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
Traceback (most recent call last):
  File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 74, in get_chat_text
    response = response.text.splitlines()[-4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alber/Desktop/ChatGPTApp/test.py", line 14, in <module>
    chatbot.get_chat_response(prompt, output="text")
  File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 109, in get_chat_response
    return self.get_chat_text(data)
  File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 87, in get_chat_text
    raise ValueError("Response is not in the correct format", error_desp)
ValueError: ('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')
```

I am using the latest release of revChatGPT

`pip3 show revChatGPT`

```
Name: revChatGPT
Version: 0.0.27
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages
Requires: bs4, lxml, requests, tls-client
Required-by: 
```

**Comment by acheong08** [comment]
It's not logging in. 
This is the normal output:
```
 $ python3 -m revChatGPT

    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...

You:
```

If it isn't I'm guessing there's something wrong with your config. Do !config and show the censored output

**Comment by mazzzystar** [comment]
Thanks for the quick reply.

```bash
python3 -m revChatGPT --text

    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT

Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Error refreshing session:
'OpenAIAuth' object has no attribute 'session_token'

You:
Hi

Chatbot:
/Users/Library/Python/3.9/lib/python/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(
Something went wrong!
('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')

You:
```

**Comment by acheong08** [comment]
> Thanks for the quick reply.
> 
> ```shell
> python3 -m revChatGPT --text
> 
>     ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
>     Repo: github.com/acheong08/ChatGPT
> 
> Type '!help' to show commands
> Press enter twice to submit your question.
> 
> Logging in...
> Error refreshing session:
> 'OpenAIAuth' object has no attribute 'session_token'
> 
> You:
> Hi
> 
> Chatbot:
> /Users/Library/Python/3.9/lib/python/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
>   warnings.warn(
> Something went wrong!
> ('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')
> 
> You:
> ```

Token issue. Looking into it

**Comment by acheong08** [comment]
> It works for me on the CLI but I get the same error when using the Python script
> 
> ```
> from revChatGPT.revChatGPT import Chatbot
> 
> config = {
>     "email": "xxx",
>     "password": "xxx"#,
>     #"session_token": "<SESSION_TOKEN>", # Deprecated. Use only if you encounter captcha with email/password
>     #"proxy": "<HTTP/HTTPS_PROXY>"
> }
> 
> chatbot = Chatbot(config, conversation_id=None)
> 
> prompt = "Javascript library for cropping images programatically"
> 
> chatbot.get_chat_response(prompt, output="text")
> ```
> 
> Output:
> 
> ```
> /home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/bs4/__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 74, in get_chat_text
>     response = response.text.splitlines()[-4]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/alber/Desktop/ChatGPTApp/test.py", line 14, in <module>
>     chatbot.get_chat_response(prompt, output="text")
>   File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 109, in get_chat_response
>     return self.get_chat_text(data)
>   File "/home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 87, in get_chat_text
>     raise ValueError("Response is not in the correct format", error_desp)
> ValueError: ('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')
> ```
> 
> I am using the latest release of revChatGPT
> 
> `pip3 show revChatGPT`
> 
> ```
> Name: revChatGPT
> Version: 0.0.27
> Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
> Home-page: https://github.com/acheong08/ChatGPT
> Author: Antonio Cheong
> Author-email: acheong@student.dalat.org
> License: GNU General Public License v2.0
> Location: /home/alber/Desktop/ChatGPTApp/chatgpt_venv/lib/python3.10/site-packages
> Requires: bs4, lxml, requests, tls-client
> Required-by: 
> ```

Documentation error. Fixing docs

**Comment by acheong08** [comment]
```py
from revChatGPT.revChatGPT import Chatbot

config = {
    "email": "xxx",
    "password": "xxx"
}

chatbot = Chatbot(config, conversation_id=None)

chatbot.refresh_session()

prompt = "Javascript library for cropping images programatically"

print(chatbot.get_chat_response(prompt, output="text")['message'])
```

**Comment by acheong08** [comment]
@mazzzystar 
Please show censored output of `!config`.

**Comment by mazzzystar** [comment]
```bash
Logging in...
Error refreshing session:
'OpenAIAuth' object has no attribute 'session_token'

You:
!config

{
    "email": "xxx",
    "password": "xxx",
    "Authorization": null
}

```

**Comment by acheong08** [comment]
Probably incorrect email/password. That is the only reason session_token would not exist

**Comment by mazzzystar** [comment]
However, just now I logged out OpenAI, and use  the email/password below to login, it succeed.
```bash
!config

{
    "email": "xxx",
    "password": "xxx",
    "Authorization": null
}
```

**Comment by acheong08** [comment]
Replicated with wrong email and password
```py
 $ python3 -m revChatGPT --text

    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show commands
Press enter twice to submit your question.

Logging in...
Error refreshing session: 
'OpenAIAuth' object has no attribute 'session_token'

You:
```

Adding better error output

**Comment by mazzzystar** [comment]
Can you figure out this issue when I run `python3 -m revChatGPT --text`?
```bash
'OpenAIAuth' object has no attribute 'session_token'
```

**Comment by acheong08** [comment]
> Can you figure out this issue when I run `python3 -m revChatGPT --text`?
> 
> ```shell
> 'OpenAIAuth' object has no attribute 'session_token'
> ```

With `--text` and without does the exact same thing.

**Comment by yumusb** [comment]
If there are a lot of people having that problem. Then you should not simply assume that it is an account password error. You should type specific log messages in the code to resolve the problem.

**Comment by mazzzystar** [comment]
@yumusb @acheong08 
I will try to print some logs

**Comment by acheong08** [comment]
@yumusb 
I get that error if I enter the wrong password. I am currently looking through the error handlers to spot where it is going wrong

**Comment by yumusb** [comment]
> <style type='text/css'>body { font-family:Arial; margin-left:40px; }img { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title>
> ## The request is blocked.
> xxxxxx
> Maybe block by waf, or other bot manager ?

This is my response,  not found some error about "wrong password". I think it 's waf return.

**Comment by acheong08** [comment]
> This happens when user agent isn't set or if you're in China.

I have to use a VPN to use ChatGPT

**Comment by yumusb** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/43062104/205906286-5e5d0481-e1c3-4ca9-a40c-cfe7ae48a7ca.png">
You can write a code to judge return html does have "Wrong email or password</span>" to judge the wrong password.

**Comment by acheong08** [comment]
Since it's updated, I think you're correct that it's a waf or geographical blocking

**Comment by yumusb** [comment]
> > This happens when user agent isn't set or if you're in China.
> 
> I have to use a VPN to use ChatGPT

Me too. And the proxy works in Chrome.

**Comment by yumusb** [comment]
My proxy IP address is Korea. And I can use chatgpt normally with my browser.

**Comment by acheong08** [comment]
> <img alt="image" width="1673" src="https://user-images.githubusercontent.com/43062104/205906286-5e5d0481-e1c3-4ca9-a40c-cfe7ae48a7ca.png">
> 
> You can write a code to judge return html does have "Wrong email or password" to judge the wrong password.

Do you mind writing this? I can't figure it out and my brain is burnt out.

**Comment by yumusb** [comment]
I am trying to write the code, but found that I can use it properly. But I haven't changed config.json ...

**Comment by acheong08** [comment]
Nevermind. I got it

**Comment by acheong08** [comment]
@yumusb Latest release can detect invalid credentials but in the process of testing:
![image](https://user-images.githubusercontent.com/36258159/205915102-97d95026-c801-40f4-8d25-276da1c1a4f7.png)

Can you help me test (Don't attempt too many times)
