### ISSUE TITLE
INVALID ISSUES CLOSED. PLEASE FILE THEM PROPERLY

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#720]
Check for duplicates and file them as proper issues with proper formats. Feature requests too

**Comment by acheong08** [comment]
Please try to do your own debugging before opening an issue

**Comment by klbnkg** [comment]
err code: 403
cf_clearance: null
token: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..pDMxLMivBYXB17Ro.9D4en7rDjvTrWuK3nBEyPKpB5Cr1lYmfTVyc9dLiSQRkwVwcqgC2kxoZ5KWk9tw-xRXCTwNftQDbPPpSyvNaTzzW44Fr0e0W31_x7U4tYTtq_wwhakLiCJG_iWmErEiX7ILE3uD47LwwIKEudAwFgJnVY1e5LvkLVr1xJ7fdVJpGG8SucljbMeZA70Q0HI3tx0oIeT3wUb8LR6RTWs8XoLXdDByQVbaogCcODBexSO8Cu2L_IYfzDiUphW2wiRvSl7ac1Eda-k8MhOGDH0Ti4brUxFqegoSCvIN_vst3KT49sjL7Exi6zS7I8Al_YAoHVFAKblSnigdEXso1nezwDIUzi9_rWpXNaLZpCVy3tNROOn7jwaFKHh09f6fwAoTs3xKlGQwho80HlHjGV_MnVOG7BzWwZSu9qXdkEUpQiaIupKHOI7DVAW4iJHXxOs8hjgH8_fr61c7gPqd_Vvh2U_ZgGwejG9zWAay2kgA06neiBEm8-4t3KhLWP4alsbUe0VsNZpDfUQbiQzE_SjXmkyfvfLNaL8quTpiMTzdVHz8lgv7i88oupV4tYi7250qxk9R1YjWWcQuR8ey-PjWjikmIVZM3axRwuV8LVOHYvE_zm2ezUfg8lXz_9kvdyowmHuXmSP5V9NJJwsULENQMJS0PBwkElkuNZK4usbSwiphnPjPdwRlh60SOFWALq4jGNF4FFFA3iKhRMwCOIL1w13roOiCye6n5FEhE5RaNQifpL9eiRXkaMygwp_w6UkhQ64PLsLGWVF7GByb1rP2cLfWzi-FkegixnWaWY2E9NyxIerc8RaFjU3ZBTzgwmgBrkKFAHGpE3TiE_lZb189LYuLck-U63Cup6af8ZZdKThtcxupQCwmX2SS33MhJRNPbnKbECg49IwnL-xa03zKQOMaaLnecqEaLz02hpNHu43sr5qaf9_G4JDl7Uw_zk_61P3RByI0V8VThV33rZWnB7_cqgpcU7Nvg7TqHH-PUttOA9zjwt4xGk5qG3ZKZx9DLbuBFmHUZIIqafi2QfC-1hB3E46a-DI_5T4ZKyT0JbS3iBszydf_cR3AhUAQEFcN7jkMXktZtK9UkT_q7JRkZcaM_aGc5DmAFztC143NqePXC2n9GzY7pVk3f4D10Bv3GnY-5vm56leP7yfDb5Esml5j4vv4G5vS8sBhr_Z_MZ7P7xY5pP2GiyheadhuZFM5-eUSNMQvsW6ShpXkH5Vm0cJolPfbdMFsUTLFYUoxjEblMvNGRnL3QTwVLWCKtLkijSBlNO3zs4hB6CruR9LuKFwnlxU0ykM3US_33twogTCL1CSu4OeXlKmjBFvZwTto-owZkesueXEL2BRMVQgXPS8wIOBENItZhm5vwNTjQd97pgaeNLfeGI1KldRTFHp6zSIJPiXa_ovC2rhSdWO6dv9PIjymmk5kPG230AXwnFjpxrHlCL6_fBpfdGmhX6OoqUTlMt5jloPrGbHB7D04CkSm9vaM09Gd7y9ntFPYdIlEoEYxuRS9oCtLglvmcjXSekInBrJ_WW4dp0YIgqDo5wliZBIvMjNKJ_1uNwOs0upuYjXRYagdei--HZR-aU7z6B4pxsP2TuPaAomKxyQI6xSdvU_B-QQdhZ3B918kJ_FI3dy4VHszuIl1DO5uF76ZgriR3ub4wJqZ6jMieajbWDbTMasrUf8u9XUbNd2YcuEej1Oatfe_wyYO1UGtON_Ae7Hzr39jvtgxSq4UdTMsWueA8xU98VOfKH68eB1HG-W42UZ03Af4cP7K8_E9BTI9xB2_HIZL5cgwVWguNxtkAiIheZcjo5r0ofF8gdOnWZyr2TSpsQNNOQmK6Tf33SYhzH7e1qmB5soLasHgf8CgA1dPVymvPRk2NtkmPNudT0o1p3i-P7r4uBbid2HFKbo_zlZR6liFVFyfuWQCUI7U9RZHdnasJO0EaazRDtsZOn25iOKWwBNWz6xc_aAe-djvxFIg5o6xFcD2ICPFFiItgVP9ZKbaSMPt5VmAXzcfDk-y29kHBULGdlS69J18uIa2vwbPKhHZGGSk9saVVP2FoCCZWBGTYyxWuvVy-S6VfqMaK90d_jFcJnzyOYzj1o2dzehNloLTFTtp1XupOk1mWgA-kPTWUwCZPon8vnfHMsCtNHz7g49F5ct0H0rN4ebxLFu6-UMZdNAS9w7mZdvHskrUXLHRWALh4CAIxRVXjDl25Wz4sm2qqdoZnAZmYM2hiVZHkkq5gSan7akP60iK_sM8L5s9-NNY6hjQoUfDrADGGurw2iBIbiyoDyfIZG51LFsD3kZC12YsRrGw6POpy4SMzq7N7QMOOIJETGxVWXQ.J3g7qTqK295YtTdBxhSboQ
userAgent: null
请检查以上参数是否正确，是否过期。并且获取以上参数的浏览器要和本程序在同一IP地址
Please check whether the above parameters are correct or expired. And the browser that obtains the above parameters must be at the same IP address as this program

**Comment by klbnkg** [comment]
求助

**Comment by klbnkg** [comment]
> The authentication token wasn't copied correctly

![image](https://user-images.githubusercontent.com/120541656/219023154-489761cd-d085-400f-a2ff-58fab92862e2.png)
Is the configuration file written like this？thanks

**Comment by acheong08** [comment]
You are using wrong session token

**Comment by acheong08** [comment]
Session token comes from cookies in `chat.openai.com`

**Comment by acheong08** [comment]
read readme

**Comment by klbnkg** [comment]
> Session token comes from cookies in `chat.openai.com`

i know it.  My session_ Token is from chat.openai.com

**Comment by yybjy** [comment]
![image](https://user-images.githubusercontent.com/91821567/219037979-6920f203-f2cd-46fa-8227-14d2fd62387e.png)
why it always show this,i use the latest selenium but it always show this.

**Comment by acheong08** [comment]
That is from Unofficial (No longer supported)
