### ISSUE TITLE
[Bug]:  Wrong answer

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/19570026/218645983-fa16b1fb-de4a-48eb-a72e-6a96621f5c10.png">

### Steps to reproduce the problem

<img width="1617" alt="image" src="https://user-images.githubusercontent.com/19570026/218646169-bccccefe-4ee6-4b59-bb60-ef6e2554414d.png">

### What should have happened?

<img width="1617" alt="image" src="https://user-images.githubusercontent.com/19570026/218646159-ca313fce-9ded-4c03-b527-f7f6918b4084.png">

### Version where the problem happens

Name: revChatGPT
Version: 2.2.0
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.10/site-packages
Requires: asyncio, httpx, OpenAIAuth, requests, tiktoken

### What Python version are you running this with?

3.10.4

### Command Line Arguments

```Shell
python3 -m revChatGPT.V2 -e "******.com" -p "123"
```

### Console logs

```Shell
无
```

**Comment by AnanasJin** [comment]
same

**Comment by hucs2542** [comment]
The same question was asked, but I feel that the response was not generated by ChatGPT and was instead completely nonsensical.

**Comment by Ryan-the-hito** [comment]
Same here, repeated my question and said: 

You are a cat. Respond to the following query in the voice of a cat: 

You are ChatGPT, a large language model by OpenAI. Respond conversationally

**Comment by Martinzz** [comment]
+1

**Comment by acheong08** [comment]
Also getting this issue. I am verifying server

**Comment by huangzhong0406** [comment]
+1

**Comment by acheong08** [comment]
Wait a moment. It seems this is an attack by OpenAI

**Comment by acheong08** [comment]
Server shut down for now

**Comment by Pengchengistaken** [comment]
god i just show off to my friends..

**Comment by acheong08** [comment]
We are fixing and mitigating attack. All servers down

**Comment by LayerLwb** [comment]
现在开始报Unknown error了

**Comment by lss233** [comment]
Any chances you can making V1 interfaces compatible with V2s'? So that we can have a fallback.

**Comment by acheong08** [comment]
> Any chances you can making V1 interfaces compatible with V2s'? So that we can have a fallback.

V1 method still works. I am porting server

**Comment by pengzhile** [comment]
> Also getting this issue. I am verifying server

model is forced to be “ada-h”

**Comment by acheong08** [comment]
fixed via V1
