### ISSUE TITLE
SERVER SHUT DOWN

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#724]
Under attack by OpenAI

**Comment by dawhdb** [comment]
> 受到 OpenAI 的攻击

Hello, how did you build this server? Can I build one for my own use

**Comment by lean-wang** [comment]
大佬出个付费版，为这个付费也是可以的

**Comment by mikegreen7892003** [comment]
so quick ....

**Comment by RangerCD** [comment]
What happened to [ChatGPT-Proxy-V2](https://github.com/acheong08/ChatGPT-Proxy-V2) ?

**Comment by acheong08** [comment]
Takedown request

**Comment by acheong08** [comment]
Don't worry I've found another method. Working on it

**Comment by zwmcoder** [comment]
WIll get overflowed for the request if deploy on you own server.  just a suggest, maintain the golang proxy will be enough.

**Comment by tianlichunhong** [comment]
> Don't worry I've found another method. Working on it

Thank you! look forwar to you new solution.

**Comment by ZoidbergPi** [comment]
> Don't worry I've found another method. Working on it

Thank you!

**Comment by xcloudx12345** [comment]
is that the reason for this error?
![image](https://user-images.githubusercontent.com/40192522/218659784-5f025b44-782f-476f-b80a-9524d887ca5c.png)

**Comment by sqy941013** [comment]
> is that the reason for this error? ![image](https://user-images.githubusercontent.com/40192522/218659784-5f025b44-782f-476f-b80a-9524d887ca5c.png)

yes, when the server is ip this error will be gone.

**Comment by sqy941013** [comment]
> is that the reason for this error? ![image](https://user-images.githubusercontent.com/40192522/218659784-5f025b44-782f-476f-b80a-9524d887ca5c.png)

yes, when the server is up this error will be gone.

**Comment by kof4467** [comment]
If the service is deployed in the United States, does it mean that ChatGPT-Proxy-V2 is not needed?

**Comment by lss233** [comment]
> If the service is deployed in the United States, does it mean that ChatGPT-Proxy-V2 is not needed?

It is stil required to bypass Cloudflare, or you could just use `Unoffical` api

**Comment by iwmbm** [comment]
The browser version is also dead 🙂🙂🙂🙂🙂

**Comment by tianwen2019** [comment]
New bee ！

**Comment by shenziqian** [comment]
貌似openai开放官方api了

**Comment by shenziqian** [comment]
我还没试过 代码：import openai
openai.api_key = ""
response = openai.Completion.create(
  model="text-chat-davinci-002-20221122",
  prompt="Hello",
  temperature=0,
  max_tokens=50,
  stream=True,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0
)

**Comment by iwmbm** [comment]
> > If the service is deployed in the United States, does it mean that ChatGPT-Proxy-V2 is not needed?
> 
> It is still required to bypass Cloudflare, or you could just use `Unoffical` api, and bypass it in your own server using a latest Chrome.

Unoffical api dead too!!!!!!!!!!!

**Comment by iwmbm** [comment]
> 貌似openai开放官方api了

官方api模型比浏览器版的差一点

**Comment by yaoching0** [comment]
> 我还没试过 代码：import openai openai.api_key = "" response = openai.Completion.create( model="text-chat-davinci-002-20221122", prompt="Hello", temperature=0, max_tokens=50, stream=True, top_p=1, frequency_penalty=0, presence_penalty=0 )

这个模型早三四天前就不能用了...

**Comment by shenziqian** [comment]
官方api是真实Chatgpt吗

**Comment by shenziqian** [comment]
> > 我还没试过 代码：import openai openai.api_key = "" response = openai.Completion.create( model="text-chat-davinci-002-20221122", prompt="Hello", temperature=0, max_tokens=50, stream=True, top_p=1, frequency_penalty=0, presence_penalty=0 )
> 
> 这个模型早三四天前就不能用了...

草，万恶的openai

**Comment by iwmbm** [comment]
> 官方api是真实Chatgpt吗

 应该是比较旧的模型，模型肯定比网页版的小

**Comment by dawhdb** [comment]
> > > 我还没试过 代码：import openai openai.api_key = "" response = openai.Completion.create( model="text-chat-davinci-002-20221122", prompt="Hello", temperature=0, max_tokens=50, stream=True, top_p=1, frequency_penalty=0, presence_penalty=0 )
> > 
> > 
> > 这个模型早三四天前就不能用了...
> 
> 草，万恶的openai

还可以用吧，需要账号有余额

**Comment by iwmbm** [comment]
cloudflare 的反爬虫有点厉害 👍👍👍👍👍

**Comment by yaoching0** [comment]
> > > > 我还没试过 代码：import openai openai.api_key = "" response = openai.Completion.create( model="text-chat-davinci-002-20221122", prompt="Hello", temperature=0, max_tokens=50, stream=True, top_p=1, frequency_penalty=0, presence_penalty=0 )
> > > 
> > > 
> > > 这个模型早三四天前就不能用了...
> > 
> > 
> > 草，万恶的openai
> 
> 还可以用吧，需要账号有余额

能用的是text-chat-davinci-003 很贵，效果也不如chatgpt，另外text-chat-davinci-002作者在1.1.1的时候就是用的这个，现在拿掉了

**Comment by shenziqian** [comment]
现在还有哪个api活着吗，没有的话我要开始准备自己写了

**Comment by wth1107** [comment]
> 现在还有哪个api活着吗，没有的话我要开始准备自己写了

快出手吧！！

**Comment by dawhdb** [comment]
> 己写了

等你

**Comment by shenziqian** [comment]
可能会写的有点暴力

**Comment by samcarmen** [comment]
> 貌似openai开放官方api了

请问是在哪里？

**Comment by dawhdb** [comment]
> > 貌似openai开放官方api了
> 
> 请问是在哪里？

https://platform.openai.com/playground

**Comment by shenziqian** [comment]
> > 貌似openai开放官方api了
> 
> 请问是在哪里？

不可用了

**Comment by shenziqian** [comment]
有没有什么办法绕过OpenAI's services are not available in your country.

**Comment by dawhdb** [comment]
> 有

用国外的服务器运行，我尝试过在请求的时候加入代理，不知道为什么没有效果

**Comment by iwmbm** [comment]
> 有没有什么办法绕过OpenAI's services are not available in your country.

我草还以为你是大神，这个这么简单，FQ啊  🙄🙄🙄🙄🙄🙄🙄🙄🙄

**Comment by iwmbm** [comment]
cloud flare的 浏览器检查才难搞

**Comment by shenziqian** [comment]
草

**Comment by shenziqian** [comment]
不知道为什么，虽然很合理但总觉得这个方法怪怪的

**Comment by dawhdb** [comment]
> cloud flare的浏览器检查才难搞

我记得之前undetected_chromedriver可以过掉cloud flare，但是现在不知道还可不可以用了

**Comment by shenziqian** [comment]
不过我知道fq要不然我还问

**Comment by iwmbm** [comment]
> > cloud flare的浏览器检查才难搞
> 
> 我记得之前undetected_chromedriver可以过掉cloud flare，但是现在不知道还可不可以用了

我都试过了 现在检查很严格

**Comment by shenziqian** [comment]
主要是我之前看到ChatGPT is at capacity right now可以绕过，所以想知道能不能绕OpenAI's services are not available in your country.

**Comment by iwmbm** [comment]
> 主要是我之前看到ChatGPT is at capacity right now可以绕过，所以想知道能不能绕OpenAI's services are not available in your country.

这个应该很好绕过把 你外国服务器 多换几个地区 试试

**Comment by shenziqian** [comment]
就在这种时候我的vpn不好使了，草

**Comment by iwmbm** [comment]
很多基于浏览器的项目都挂了

**Comment by shenziqian** [comment]
> 很多基于浏览器的项目都挂了

你信不信我的不基于浏览器（但是实现方式非常sb）

**Comment by dawhdb** [comment]
> 

怎么实现的？爬取接口，但是接口有cloud flare这个啊

**Comment by sqy941013** [comment]
cloud flare的认证难过

**Comment by ypatz** [comment]
```
PROXY_URL = os.environ.get("PROXY_URL") or "https://chat.duti.tech"
       
 async with httpx.AsyncClient(proxies=self.proxy if self.proxy else None).stream(
            method="POST",
            url=PROXY_URL + "/completions",
            data=json.dumps(body),
            headers={"Authorization": f"Bearer {self.api_key}"},
            timeout=1080,
        ) as response:
```

请教下各位，这个代理(self.proxy)的意义是什么
如果不设置PROXY_URL，是不是所有流量都会这样走：proxy=>chat.duti.tech=>openai
这样流量集中很容易就会被cloudflare给屏蔽了啊
不能自己搭建代理服务器吗？

**Comment by coolmian** [comment]
> What happened to [ChatGPT-Proxy-V2](https://github.com/acheong08/ChatGPT-Proxy-V2) ?

Not long ago, if ChatGPT-Proxy-V2 was used, the response model was forced to be changed to "ada-h“
So the answer is wrong. ChatGPT-Proxy-V2 is closed

**Comment by shenziqian** [comment]
作者没发config.json目前别想

**Comment by coolmian** [comment]
@ypatz ChatGPT-Proxy-V2 is currently unavailable, even if you deploy it yourself

**Comment by iwmbm** [comment]
> > 很多基于浏览器的项目都挂了
> 
> 你信不信我的不基于浏览器（但是实现方式非常sb）

你太年轻了 他要先执行JavaScript验证过才能继续访问，不用浏览器没法执行JavaScript

**Comment by cc4dogman** [comment]
> 

每分钟1个token的限制直接搞崩溃了,调用2次请求就被限流了

**Comment by jack-guo-dash** [comment]
> Don't worry I've found another method. Working on it

looking forward!

**Comment by shenziqian** [comment]
> > > 很多基于浏览器的项目都挂了
> > 
> > 
> > 你信不信我的不基于浏览器（但是实现方式非常sb）
> 
> 你太年轻了 他要先执行JavaScript验证过才能继续访问，不用浏览器没法执行JavaScript

怎么说呢，基于Chatgpt客户端（返璞归真）

**Comment by acheong08** [comment]
> The browser version is also dead slightly_smiling_faceslightly_smiling_faceslightly_smiling_faceslightly_smiling_faceslightly_smiling_face

It is still alive but not maintained

**Comment by acheong08** [comment]
Just updated V1

**Comment by acheong08** [comment]
Hello world. It works

**Comment by tianwen2019** [comment]
@acheong08 V2 did not work

**Comment by acheong08** [comment]
V1 works. V2 doesn't
