### ISSUE TITLE
The server source code page is missing.

### ISSUE THREAD

**Issue by Aliecetine9** [acheong08/ChatGPT#729]
Will it be available in the future?

**Comment by coolmian** [comment]
ChatGPT-Proxy-V2 is based on an unpublished endpoint, but this method is currently invalid. Please wait for the new method.

**Comment by Liu-Angelo** [comment]
/usr/bin/python3: No module named revChatGPT.V2

**Comment by gunjianpanxdd** [comment]
https://chat.duti.tech   404 page not found

**Comment by acheong08** [comment]
please wait. I am working on it

**Comment by acheong08** [comment]
Almost done

**Comment by hziheng** [comment]
> https://chat.duti.tech 404 page not found

me too, i print response.status_code, is 404

**Comment by acheong08** [comment]
Use V1 code. Check readme

**Comment by MarcosFP97** [comment]
After logging in, when I try to ask I always get 502 Bad Gateway

**Comment by acheong08** [comment]
V2 code is dead

**Comment by MarcosFP97** [comment]
I am using V1

**Comment by acheong08** [comment]
`pip3 show revChatGPT`

**Comment by acheong08** [comment]
always update. I only recently released

**Comment by MarcosFP97** [comment]
Sorry, my bad, I have just updated. Thanks for everything you do for us @acheong08

**Comment by hucs2542** [comment]
@acheong08 My account is "plus". What parameters do I need to pass in V1?

**Comment by acheong08** [comment]
`paid=True` in code or `"paid": true` in config

**Comment by acheong08** [comment]
> Any prediction on when V2 will work again?

Next week official API will be released for V2 according to sources

**Comment by ArjunSahlot** [comment]
Thanks for this project @acheong08. I was wondering once V2 is ready, will it be consistently available like the browser version is?

**Comment by acheong08** [comment]
V2 was the alpha testing for OpenAI's public API sort of. Once it is available, you will be able to use it just like any other model from their official completions endpoint

**Comment by ArjunSahlot** [comment]
Great! Good luck!

**Comment by Aliecetine9** [comment]
@acheong08 How to use session_token to login in V1?

**Comment by acheong08** [comment]
Read readme

**Comment by acheong08** [comment]
And the server source code is at https://github.com/acheong08/ChatGPT-Proxy-V1
