### ISSUE TITLE
Non deterministic results

### ISSUE THREAD

**Issue by MarcosFP97** [acheong08/ChatGPT#731]
Hi everyone,

I was using V2 of this repository until yesterday, to test the accuracy of ChatGPT for queries for which I have the correct answer. However I have some doubts:

- How can I confirm that the model used is ChatGPT and not another one?
- I was obtaining non-deterministic results. My guess is that this is related to the non-cleaning of the conversation. After calling chatbot ask in a loop, how can I clean the conversation each time?

I know the server is know under maintenance, but I would appreciate any help.

**Comment by acheong08** [comment]
It was endpoint issue. Right now I switched to using conversations. You will see conversations you have with this library show up on chat.openai.com

**Comment by acheong08** [comment]
Use new V1 for it to be perfectly like real ChatGPT
