### ISSUE TITLE
[Bug]: there is someone discover the answer is defference between api and edge?

### ISSUE THREAD

**Issue by QiuZiXian** [acheong08/ChatGPT#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

the same quetion get different answer  by api  and by Edge directly
quetion: 你目前采用哪个模型
the answer from api as below:
![image](https://user-images.githubusercontent.com/28780269/218703317-e4541dfe-a06a-46e7-80b4-72cde954eb65.png)

the answer from Edge directly as below:
![image](https://user-images.githubusercontent.com/28780269/218703666-51cb7c97-1186-4c82-94df-774968c8505c.png)

### Steps to reproduce the problem

1.set prompt="你目前采用哪个模型"
2.  run developer code
3. answer by Edge  directly 

### What should have happened?

the same answer

### Version where the problem happens

EdgeGPT-0.0.30

### What Python version are you running this with?

python3.9

### Command Line Arguments

```Shell
import asyncio
from EdgeGPT import Chatbot

async def main():
    bot = Chatbot()
    print((await bot.ask(prompt="你目前采用哪个模型"))["item"]["messages"][1]["adaptiveCards"][0][
                "body"
            ][0]["text"])
    await bot.close()


if __name__ == "__main__":
    asyncio.run(main())
```

### Console logs

```Shell
D:\Users\dell\anaconda3\envs\python39\python.exe E:/e/project/shida/work/chat-group/chatgpt-test/bing_web/bing_common.py
你好，这是必应。我目前采用的是一个基于深度学习的自然语言生成模型，它可以根据用户的语言和意图生成流畅和有趣的回复。😊


Process finished with exit code 0
```

**Comment by acheong08** [comment]
Edge cites real sources
