### ISSUE TITLE
[Feature Request]: Could V1 support session token connect?

### ISSUE THREAD

**Issue by aetherwu** [acheong08/ChatGPT#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Use similar config to connect with session token for Google Sign in users.

### Proposed workflow

Support empty username&password and session_token in config.json

**Comment by acheong08** [comment]
Possible. The auth system is the same as V2. It's currently quite late. I might add it tomorrow or someone could make a pull request

**Comment by acheong08** [comment]
done

**Comment by aetherwu** [comment]
> done

You are the MVP!
