### ISSUE TITLE
[Bug]: KeyError: 'accessToken'

### ISSUE THREAD

**Issue by wulliwui** [acheong08/ChatGPT#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I encountered the error "KeyError: 'accessToken'" after using revChatGPT.V1 to create a chatbot. Upon investigating the issue, I discovered that the access_token was not obtained after executing auth.begin().

### Steps to reproduce the problem

chatbot = Chatbot(config={
      "email": "...",
      "password": "..."
    })
My network environment doesn't require a proxy to access ChatGPT, and I can connect to ChatGPT without any issues.

### What should have happened?

normal login

### Version where the problem happens

v2.2.2

### What Python version are you running this with?

py3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
File "/root/PycharmProjects/fastApiProject/venv/lib/python3.9/site-packages/revChatGPT/V1.py", line 64, in __init__
    self.__login()
  File "/root/PycharmProjects/fastApiProject/venv/lib/python3.9/site-packages/revChatGPT/V1.py", line 87, in __login
    access_token = auth.get_access_token()
  File "/root/PycharmProjects/fastApiProject/venv/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 352, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'
```

**Comment by acheong08** [comment]
Google or Microsoft account requires session token

**Comment by wulliwui** [comment]
> Google or Microsoft account requires session token

How can I solve this problem? I have looked at the code, and it seems that the access_token is returned from the server.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.2.4

Check new readme

**Comment by wulliwui** [comment]
> https://github.com/acheong08/ChatGPT/releases/tag/2.2.4
> 
> Check new readme

I filled in the session_token and access_token in the config, and successfully logged in and created a chatbot object. However, when I called ask, I received an error from the server that says: '{'detail': {'message': 'Unauthorized - Access token is missing'}}'

**Comment by go-xmyang** [comment]
> 

same problem

**Comment by thurderbird521** [comment]
the same to me ,is anyone solve it ?

**Comment by Nanfacius** [comment]
> > https://github.com/acheong08/ChatGPT/releases/tag/2.2.4
> > Check new readme
> 
> I filled in the session_token and access_token in the config, and successfully logged in and created a chatbot object. However, when I called ask, I received an error from the server that says: '{'detail': {'message': 'Unauthorized - Access token is missing'}}'

The same problem to me.

**Comment by wulliwui** [comment]
> > https://github.com/acheong08/ChatGPT/releases/tag/2.2.4
> > Check new readme
> 
> I filled in the session_token and access_token in the config, and successfully logged in and created a chatbot object. However, when I called ask, I received an error from the server that says: '{'detail': {'message': 'Unauthorized - Access token is missing'}}'

I have solved this problem. When creating the chatbot object, I only need to fill in the access_token in the config, and there is no need to fill in email, password, or session_token.

**Comment by ypatz** [comment]
> 

I am not use Google or Microsoft account, I just use outlook email when register openai account.

**Comment by thurderbird521** [comment]
how to get access_token?

**Comment by acheong08** [comment]
https://chat.openai.com/api/auth/session

**Comment by wttnb911** [comment]
I used Proton mail account, but I still got the same problem

**Comment by acheong08** [comment]
Use `access_token` in config if authentication fails

**Comment by R3habDroid** [comment]
Chatbot: 
Field missing
{'detail': {'message': 'Unauthorized - Invalid access token'}}

**Comment by FAIpang** [comment]
> > > https://github.com/acheong08/ChatGPT/releases/tag/2.2.4
> > > Check new readme
> > 
> > 
> > I filled in the session_token and access_token in the config, and successfully logged in and created a chatbot object. However, when I called ask, I received an error from the server that says: '{'detail': {'message': 'Unauthorized - Access token is missing'}}'
> 
> I have solved this problem. When creating the chatbot object, I only need to fill in the access_token in the config, and there is no need to fill in email, password, or session_token.

This access_token will expired. Is there any way to avoid this?

**Comment by acheong08** [comment]
> This access_token will expired. Is there any way to avoid this?

It expires in two weeks. If you have email/password, you can call the login function
