### ISSUE TITLE
why is there no respond after i enter my words

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#75]
![image](https://user-images.githubusercontent.com/86822589/205882340-5fbe0dcb-88a8-423a-9999-0ed26a992ab8.png)

**Comment by acheong08** [comment]
Press enter twice to submit your question

**Comment by acheong08** [comment]
Look at the line printed out right after !help

**Comment by acheong08** [comment]
Captcha detected. I don't support captcha yet

**Comment by acheong08** [comment]
Check out https://github.com/rawandahmad698/PyChatGPT for captcha support
