### ISSUE TITLE
[Bug]: empty response

### ISSUE THREAD

**Issue by xcloudx12345** [acheong08/ChatGPT#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

data["message"] allway return empty string
![image](https://user-images.githubusercontent.com/40192522/218950302-40940330-b2be-4cdb-98ef-5779f9e1939f.png)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

return a string

### Version where the problem happens

2.2.6

### What Python version are you running this with?

3.10

### What is your operating system ?

Other/Cloud

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
{'message': '', 'conversation_id': '2419e05c-35a6-473a-a2ce-2effbef5a177', 'parent_id': 'fea9d193-8f79-42e1-a20f-9c726071f0b9'}
```

### Additional information

the code i'm using:
```
config = get_config()
chatbot = Chatbot(config={
  "email": os.environ['email'],
  "password": os.environ['password']
})
async def handle_response(message) -> str:
    prev_text = ""
    for data in chatbot.ask(message):
        response = data["message"][len(prev_text) :]
        print(data)
        return response
```

**Comment by acheong08** [comment]
The first response is always blank. You must return it after the for loop completes
