### ISSUE TITLE
[Bug]: revChatGPT.V1.Error

### ISSUE THREAD

**Issue by R3habDroid** [acheong08/ChatGPT#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

error on win10,pycharm

### Steps to reproduce the problem

I'm using the basic example code:
from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "email": "mail",
  "password": "pwd"
})

print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()

### What should have happened?

chatbot:xxx

### Version where the problem happens

Version: 2.2.0

### What Python version are you running this with?

Python 3.10.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Chatbot: 
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

Traceback (most recent call last):
  File "C:\Users\Davis\Desktop\gptgptgpt\main.py", line 12, in <module>
    for data in chatbot.ask(
  File "C:\Users\Davis\Desktop\gptgptgpt\venv\lib\site-packages\revChatGPT\V1.py", line 142, in ask
    self.__check_response(response)
  File "C:\Users\Davis\Desktop\gptgptgpt\venv\lib\site-packages\revChatGPT\V1.py", line 192, in __check_response
    raise error
revChatGPT.V1.Error
```

**Comment by acheong08** [comment]
Update your version
