### ISSUE TITLE
[Feature Request]: Work with the latest model on paid accounts

### ISSUE THREAD

**Issue by chelishchev** [acheong08/ChatGPT#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Right now V1 create chats on paid account with Legacy model (The previous ChatGPT Plus model). It'll be good have options to switch between models or use the last one Default (Optimized for speed, currently available to Plus users).

### Proposed workflow

1. Have a paid account on openAI
2. Run python script with paid: True
3. See on the website https://chat.openai.com/chat, that created chat used "legacy" model.

**Comment by acheong08** [comment]
`text-davinci-002-render-sha` is available for free iirc

**Comment by chelishchev** [comment]
> `text-davinci-002-render-sha` is available for free iirc

O, I see https://github.com/acheong08/ChatGPT/pull/759 
Yes. It'll be good

I think it's good default behavior, but I prefer to have options in config to set model manually

**Comment by acheong08** [comment]
Make a pull request if you wish

**Comment by acheong08** [comment]
But to use latest model, just don't set paid to true
