### ISSUE TITLE
[Bug]: When using V1, SSLError: HTTPSConnectionPool(host='chatgpt-proxy.fly.dev', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by fzp0424** [acheong08/ChatGPT#757]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

I upgrade the newest release version and simply run example code:
```from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "email": "mine",
  "password": "mine",
  "access_token": "mine",
  "proxy": "mine"
})

print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
```
it produced this bug `SSLError: HTTPSConnectionPool(host='chatgpt-proxy.fly.dev', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))`

### Steps to reproduce the problem

V1

### What should have happened?

.

### Version where the problem happens

.

### What Python version are you running this with?

_3.9_

### What is your operating system ?

_win_

### Command Line Arguments

```Shell
NONE
```

### Console logs

```Shell
SSLError: HTTPSConnectionPool(host='chatgpt-proxy.fly.dev', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

**Comment by fzp0424** [comment]
produce the same when I only fill `access_token` or `access_token` with `proxy`

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.2.7

**Comment by acheong08** [comment]
I was trying to use serverless but it seems it's not great

**Comment by fzp0424** [comment]
> I was trying to use serverless but it seems it's not great

thx, it actually works on the server

**Comment by acheong08** [comment]
Yeah serverless sucks for some reason

**Comment by ForgetThatNight** [comment]
Don't close this issues until it has been solved, please!

**Comment by acheong08** [comment]
I've swapped servers. Update your version

**Comment by ForgetThatNight** [comment]
> 

This problem has been solved by https://blog.csdn.net/qq_42902997/article/details/128305580

**Comment by Arcadia822** [comment]
> This problem happens when i use repo version ==2.3.0. And here is my config format, can you help me? ![image](https://user-images.githubusercontent.com/69443774/219831719-e33b0353-aff1-4059-ad20-40e220f2e1e7.png)
> 
> ![image](https://user-images.githubusercontent.com/69443774/219831431-eaa3efd5-0dea-447a-9015-58d0ae329887.png)

I'm encountering this problem with version 2.3.0 on python 3.8.  but it works smoothly on python 3.10. Same code and network. I checked urllib3 and requests they are also same version.

config is access_token, proxy, paid.

**Comment by acheong08** [comment]
I develop on Python 3.10 so there might be issues with lower versions

**Comment by noirmist** [comment]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found')))

https://github.com/acheong08/ChatGPT-Proxy-V4/issues/22#issue-1644385660

I think I have save Issue.

I run the proxy server and and update json file with "proxy": "localhost:8080" 
Do I miss something?
