### ISSUE TITLE
[Bug]: Remote end closed connection without response

### ISSUE THREAD

**Issue by wulliwui** [acheong08/ChatGPT#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I used the sample code, which was working fine an hour ago, but just now when I ran the sample code, I got this error message "http.client.RemoteDisconnected: Remote end closed connection without response".

### Steps to reproduce the problem

chatbot = Chatbot(config={
        "access_token": "my access_token",
        "conversation_id": "my conversation_id",
        "parent_id": "my parent_id"
    })

### What should have happened?

normal

### Version where the problem happens

2.2.6

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
File "/usr/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by CodeSPA** [comment]
both proxy server addresses are not avaliable

**Comment by acheong08** [comment]
I'll update to use original proxy address

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.2.7
