### ISSUE TITLE
[Feature Request]:  Session context function

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

from revChatGPT.V1 import Chatbot

Using the first session ID as the next parent session ID is context-free

### Proposed workflow

       from revChatGPT.V1 import Chatbot

        chatbot = Chatbot(config={
            "email": "{}".format(random_info['email']),
            "password": "{}".format(random_info['password']),
            "conversation_id": "{}".format(conver_id),
            "parent_id": "{}".format(parent_id)
        })
        prev_text = ""
        response = chatbot.ask(prompt, conversation_id=chatbot.config.get("conversation"),
                               parent_id=chatbot.config.get("parent_id"))
        for data in response:
            message = data["message"][len(prev_text):]
            prev_text = data["message"]
        logging.info(f'parent_id ----------:  {chatbot.parent_id}')
        logging.info(f'conversation_id ----------: {chatbot.conversation_id}')
       
       1. chatbot.parent_id is used as the parent session ID of the next round to request again without context
       2. Is it my usage of the session ID or the form of the account password that is problematic in multiple sessions itself

Seek a solution

### Additional information

Using the first session ID as the next parent session ID is context-free

**Comment by acheong08** [comment]
`conversation_id` is the one that tracks context
