### ISSUE TITLE
[Bug]: python3 -m revChatGPT.V1 

### ISSUE THREAD

**Issue by monkeyshichi** [acheong08/ChatGPT#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

couln not parse your authentication.please try signing in again 

### Steps to reproduce the problem

python3 -m revChatGPT.V1 

### What should have happened?

don't know

### Version where the problem happens

2.2.7

### What Python version are you running this with?

python3.8

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
[Bug]: python3 -m revChatGPT.V1
```

### Console logs

```Shell
couln not parse your authentication.please try signing in again
```

**Comment by acheong08** [comment]
I don't know what this is either. Please give more details

**Comment by monkeyshichi** [comment]
![image](https://user-images.githubusercontent.com/16351198/218999193-0ee75c92-16e5-4f70-ae50-00dde1e6ab49.png)
![image](https://user-images.githubusercontent.com/16351198/218999273-48d94454-aaab-4f9d-80c9-12b63654e5f7.png)

**Comment by monkeyshichi** [comment]
I clearly provided an access_token, yet they said I did not provide an access_token.

**Comment by monkeyshichi** [comment]
config.json in /root/.config/revChatGPT dir

**Comment by acheong08** [comment]
If you provide access token, don't provide email and password

**Comment by monkeyshichi** [comment]
I DELETE EMAIL AND PASSWORD .
STILL WRONG
![image](https://user-images.githubusercontent.com/16351198/219000703-9dacf8d4-b9ca-4741-a868-def08ab83765.png)

**Comment by monkeyshichi** [comment]
i get the #### Access token through 
https://chat.openai.com/api/auth/session

**Comment by acheong08** [comment]
That error means that your accesstoken is invalid. Did you perhaps not copy paste the full thing?

**Comment by monkeyshichi** [comment]
yes,you are right ,thank you!
