### ISSUE TITLE
[Bug]: Failing to authenticate

### ISSUE THREAD

**Issue by wttnb911** [acheong08/ChatGPT#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

chatbot = Chatbot(config={
    "email": "***@proton.me",
    "password": "****"
})

### Steps to reproduce the problem

run the code:

from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
    "email": "***@proton.me",
    "password": "****"
})

for data in chatbot.ask(
        "how are you?",
        conversation_id=chatbot.config.get("conversation"),
        parent_id=chatbot.config.get("parent_id"),
):
    print(data["message"], end="", flush=True)
print()

### What should have happened?

normal login

### Version where the problem happens

2.2.7

### What Python version are you running this with?

3.9.6

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "**/test.py", line 3, in <module>
    chatbot = Chatbot(config={
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 69, in __init__
    self.__login()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/V1.py", line 105, in __login
    auth.get_access_token()
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 352, in get_access_token
    self.access_token = response.json()["accessToken"]
KeyError: 'accessToken'
```

**Comment by zy783282949** [comment]
same problem,anyone know how to handle it?

**Comment by wttnb911** [comment]
1, I used Proton mail to register and login chatGPT, not Gmail/Outlook
2, I used local proxy and I can connect chatGPT without any issues
3, I used password to login in, can I get the access token using this way?

**Comment by xiezhuokui** [comment]
same problem

**Comment by wttnb911** [comment]
> 这个问题已经解决了。参考本期#743。

different problem: 
#743 is using token to login
#I am using PASSWORD to login.
can i get access token in this way?

**Comment by acheong08** [comment]
No matter what type of account you use, you can still use the accessToken. It is universal

**Comment by acheong08** [comment]
Sometimes email/passwords just don't work for an unknown reason

**Comment by acheong08** [comment]
> 3, I used password to login in, can I get the access token using this way?

yes

**Comment by thurderbird521** [comment]
very thanks , i have run V1 ok with access_token. But there is no GPTserver.py in version 2.2.4 , so if i want to provide as a server service ,how can i do ?

**Comment by Mrxiahelong** [comment]
I find if i use vpn,  this problem is solved

**Comment by acheong08** [comment]
Yes. OpenAIAuth is blocked in China

**Comment by acheong08** [comment]
> very thanks , i have run V1 ok with access_token. But there is no GPTserver.py in version 2.2.4 , so if i want to provide as a server service ,how can i do ?

You'll have to write your own. GPTserver was deprecated

**Comment by acheong08** [comment]
Stale
