### ISSUE TITLE
[BUG] NOT WORKING !! SAME RESPONSE 

### ISSUE THREAD

**Issue by kashyapkumbhani** [acheong08/ChatGPT#77]
![image](https://user-images.githubusercontent.com/22000370/205908111-07f58641-63ce-4652-8fb8-55c686dcc3da.png)

**Comment by acheong08** [comment]
API error downgrade to 0.0.27
`pip3 install pyChatGPT==0.0.27`
Fixing

**Comment by acheong08** [comment]
Fixed. `pip3 install pyChatGPT==0.0.28`

**Comment by kashyapkumbhani** [comment]
![image](https://user-images.githubusercontent.com/22000370/206372829-ebf22ffa-72ac-430c-94e0-d5efe8934617.png)

**Comment by kashyapkumbhani** [comment]
pip3 install pyChatGPT==0.0.2 
working

**Comment by acheong08** [comment]
The latest version is at `0.0.32.1`

**Comment by acheong08** [comment]
> pip3 install pyChatGPT==0.0.2 working

That is way too outdated. No longer works due to API changes.

`pip3 install --upgrade revChatGPT`

**Comment by acheong08** [comment]
I am so sorry. It's revChatGPT, not pyChatGPT.
