### ISSUE TITLE
[Bug]: Field missing

### ISSUE THREAD

**Issue by boxiyang** [acheong08/ChatGPT#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

python -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
hello

Chatbot:
Field missing
{'detail': {'message': 'Incorrect API key provided: <{"user"*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************Q"}>. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

### Steps to reproduce the problem

same as what happen

### What should have happened?

return answer

### Version where the problem happens

revChatGPT 2.2.7

### What Python version are you running this with?

3.9.13

### Command Line Arguments

```Shell
python -m revChatGPT.V1
```

### Console logs

```Shell
same as what happened
```

**Comment by LotusMoves** [comment]
i might be wrong but have you checked your API key? it says "Incorrect API key"

**Comment by acheong08** [comment]
Incorrect API key. Not my problem

**Comment by boxiyang** [comment]
> 

config.json use access_token which is acquired from  https://chat.openai.com/api/auth/session ，no API KEY inside

**Comment by LotusMoves** [comment]
> Incorrect API key. Not my problem

thats what I'm talking about be assertive lol ill try to keep up on issues and answer best I can

**Comment by boxiyang** [comment]
> > Incorrect API key. Not my problem
> 
> thats what I'm talking about be assertive lol ill try to keep up on issues and answer best I can

but I do not use API KEY explicitly， with the only configuration item "access_token", which is acquired from https://chat.openai.com/api/auth/session.

**Comment by boxiyang** [comment]
I chose session_token and done
