### ISSUE TITLE
[Bug]: https://chat.duti.tech/auth 404

### ISSUE THREAD

**Issue by jiangying000** [acheong08/ChatGPT#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

when I use `chatbot = Chatbot(email=e[0], password=e[1], insecure=True)`
I got an error: 
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

After look into code, I found:
`curl https://chat.duti.tech/auth -XPOST --data '{"email":"ss@mail.com","password":"1324"}'`
is returning 404
```html
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

### Steps to reproduce the problem

run `chatbot = Chatbot(email=e[0], password=e[1], insecure=True)`

### What should have happened?

login ok

### Version where the problem happens

Name: revChatGPT
Version: 2.2.7
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/ubuntu/.local/lib/python3.8/site-packages
Requires: asyncio, requests, httpx, tiktoken, OpenAIAuth
Required-by: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "py.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "py.py", line 19, in main
    raise e
  File "py.py", line 10, in main
    chatbot = Chatbot(email=e[0], password=e[1], insecure=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/revChatGPT/V2.py", line 135, in __init__
    self.login(email, password, proxy, insecure, session_token)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/revChatGPT/V2.py", line 233, in login
    self.api_key = auth_request.json()["accessToken"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by acheong08** [comment]
It got shut down due to excessive memory usage. It is now hosted on a secondary server: https://sathoro.duti.tech/auth

**Comment by jiangying000** [comment]
seems https://sathoro.duti.tech/auth is also down

**Comment by acheong08** [comment]
It keeps getting overloaded due to it being written in Python. I will need to do a full rewrite in Go. In the meantime, you can try hosting it yourself with the following code:
```python
from typing import Union

from fastapi import FastAPI
from pydantic import BaseModel
from OpenAIAuth.OpenAIAuth import OpenAIAuth

app = FastAPI()


class AuthenticationDetails(BaseModel):
    email: Union[str, None] = None
    password: Union[str, None] = None


@app.post("/auth")
async def auth(auth_details: AuthenticationDetails):
    """
    Authenticate yourself
    """
    # Get email and password from request JSON
    email = auth_details.email
    password = auth_details.password
    try:
        openai = OpenAIAuth(email, password)
        openai.begin()
    except Exception as exc:
        return {"error": str(exc)}
    token = openai.access_token
    return {"accessToken": token}
```

**Comment by jiangying000** [comment]
got it, thank you
