### ISSUE TITLE
[Bug]: Even if the same conversation_id is used, the context cannot be traced.

### ISSUE THREAD

**Issue by wulliwui** [acheong08/ChatGPT#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

chatbot = Chatbot(config={
      "access_token":access_token,
      "conversation_id": openid
})
for data in chatbot.ask(ask,conversation_id=chatbot.config.get("conversation")):
    message_list.append(data["message"])
print(message_list[-1])

"openid" is fixed and is my user ID. I wrote my code like this, but every time it runs, a new conversation is initiated. I don't know if this is a bug or a problem with my usage. How can I write it so that it performs context tracking?

### Steps to reproduce the problem

Execute the code above.

### What should have happened?

Successfully tracked the context.

### Version where the problem happens

2.2.6

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

**Comment by wulliwui** [comment]
我本来想的是传入自己的用户id作为回话id,但是我发现这样不对,应该记录ask后返回的会话id,后续对话作为ask的参数传入才会起作用,我实现了我想要的功能

**Comment by kevinrench** [comment]
> 我本来想的是传入自己的用户id作为回话id,但是我发现这样不对,应该记录ask后返回的会话id,后续对话作为ask的参数传入才会起作用,我实现了我想要的功能

请问，ask后返回的会话ID，应该如何取得？我查阅了CSDN、以及这个项目的WIKI，并没有找到相应的描述，能否请您指点一下，或者分享一段代码？

非常感谢！

https://github.com/acheong08/ChatGPT/wiki/V1#get_conversations
