### ISSUE TITLE
My account has been blocked - From the repo owner

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#78]
![image](https://user-images.githubusercontent.com/36258159/205915887-ac68c304-cc91-4383-a1e5-74cc80765457.png)

I can't conduct further testing until it is reinstated. If anyone can help, please do.

**Comment by Ukenn2112** [comment]
A cell phone number can create more than one account, you can try to re-register with a different email address

**Comment by acheong08** [comment]
> A cell phone number can create more than one account, you can try to re-register with a different email address

Tried that. It says it reached the maximum number.

**Comment by acheong08** [comment]
Bought an e-sim
