### ISSUE TITLE
[Bug]: V1 seems lost conversation context

### ISSUE THREAD

**Issue by luzy99** [acheong08/ChatGPT#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I run V1 from up-to-day code with only `access_token` in config file.
The bot seems to start a new conversation after every round of `ask` during a single run. Thus it lost conversation context.
![image](https://user-images.githubusercontent.com/43703357/219299486-93f429c1-024e-4cb0-b590-8efe668d78fb.png)
After that, several conversations appear on `chat.openai.com`
![image](https://user-images.githubusercontent.com/43703357/219300866-f7863c47-b553-4522-bf82-c7bcc9cb372c.png)

Is there someway I can keep it in the same conversation during one run?

### Steps to reproduce the problem

1. set `access_token` in config file
2. run `python .\src\revChatGPT\V1.py`
3. ask several questions

### What should have happened?

The bot starts a new conversation after every round of `ask`

### Version where the problem happens

> git log  
commit 7ee16b028a493f6ba5a2ccb668e15d54ee8393ff (HEAD -> main, origin/main, origin/HEAD)
Merge: 8e6e08b c4b129d
Author: Antonio Cheong <acheong@student.dalat.org>
Date:   Thu Feb 16 13:33:42 2023 +0800

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
python .\src\revChatGPT\V1.py
```

### Console logs

```Shell
You:
please recommend a sci-fi movie for me

Chatbot:
Sure, I'd be happy to recommend a sci-fi movie for you! 

One recent sci-fi movie that I would highly recommend is "Tenet" directed by Christopher Nolan. It's an action-packed thriller that explores the concept of time inversion, where objects and people can move backwards in time. The movie follows a protagonist known only as "The Protagonist" as he attempts to prevent a global catastrophe. The film features stunning visual effects, a complex plot, and an all-star cast including John David Washington, Robert Pattinson, and Elizabeth Debicki. 

If you've already seen "Tenet," another great sci-fi movie to check out is "Arrival" directed by Denis Villeneuve. It's a thoughtful and cerebral film that explores the idea of communication with extraterrestrial life. The movie follows a linguistics professor, played by Amy Adams, as she works to communicate with mysterious alien ships that have landed on Earth. The film features stunning cinematography, a powerful emotional core, and a thought-provoking story.

You:
i prefer a Chinese one

Chatbot:
I'm sorry, I'm not sure what you are referring to. Could you please provide more context or clarify your request so I can better understand how to assist you?
```

**Comment by wulliwui** [comment]
You need to fill in the conversation_id when you call ask, so that it will stay in the same session consistently.

**Comment by luzy99** [comment]
How could i get the first conversation_id? Simply generate a UUID?

**Comment by wulliwui** [comment]
> How could i get the first conversation_id? Simply generate a UUID?

I obtained the ID from the response after the first call to ask, saved it, and passed the conversation_id as a parameter when calling ask again.

**Comment by acheong08** [comment]
Yup there is a bug

**Comment by acheong08** [comment]
Fixing

**Comment by acheong08** [comment]
It was messed up by a pull request. I will do better reviews in the future. Might need some help with automated GitHub CI/CD tests

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.2.8

**Comment by fredmo** [comment]
Hello, I try to use the UUID, but I don't see how ?
this is a new thread at each request : 

``
import os
import sys


from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "email": os.environ['CHATGPT_LOGIN'],
  "password": os.environ['CHATGPT_PW'],
  "conversation_id": "XXXXXX-6659-42ab-a8f8-ecc6417e9020",
  "parent_id": "XXXXXX-6659-42ab-a8f8-ecc6417e9020"
})

print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    sys.argv[1],
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()
``



when you say, you should use UUID in the ask ?  could you share the example ? 
I guess, it would be?
for data in chatbot.ask(
    sys.argv[1],
    "conversation_id": "XXXXXX-6659-42ab-a8f8-ecc6417e9020",
):
but still ko.

Thank you
