### ISSUE TITLE
The console is locked and needs to be unlocked by entering the Pin

### ISSUE THREAD

**Issue by zhangxianwei2015** [acheong08/ChatGPT#787]
Hi,

I saw an error response like below, is it caused by the proxy server?

**_the console is locked and needs to be unlocked by entering the pin_**

some key words "Werkzeug Debug Console Pin Bypass"

thanks

**Comment by acheong08** [comment]
server was down for 30 seconds. it should be fixed with the latest version

**Comment by zihaolucky** [comment]
> server was down for 30 seconds. it should be fixed with the latest version

Hi, does V1 support Plus version? It seems a bit slow now

**Comment by acheong08** [comment]
> Hi, does V1 support Plus version

Set `paid` to `true` in config

**Comment by acheong08** [comment]
I need to scale my servers

**Comment by zihaolucky** [comment]
> > Hi, does V1 support Plus version
> 
> Set `paid` to `true` in config

Yes, it works. BTW, when I set paid=True, it's legacy version.
