### ISSUE TITLE
Server overload: 503 bad gateway

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#788]
Working on scaling my servers

**Comment by acheong08** [comment]
I have added load balancing and 3 servers. Working on migration

**Comment by rachithaiyappa** [comment]
Thanks!

Could this probably be the reason I'm seeing `502 Bad Gateway` in the past hour or so?

**Comment by acheong08** [comment]
Yup

**Comment by acheong08** [comment]
The server was overloaded

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.3.0

Uses new load balanced servers
