### ISSUE TITLE
Use `__Secure-next-auth.session-token` cookie for accessToken generation

### ISSUE THREAD

**Issue by Cubicpath** [acheong08/ChatGPT#8]
By using the `__Secure-next-auth.session-token` cookie, you are able to generate access tokens just like a browser would. This would allow users to set a config value once and forget (until the session expires, which the API says ~1 month).

Since the `__Secure-next-auth.session-token` value changes after every session call, you would need to store it in a `requests.Session`, as well as dump the new cookie value into the config for preservation.

Approximate Example:
```python
import json
from pathlib import Path
from requests import Session

config_path = Path('config.json')
config = json.loads(config_path.read_text())

session = Session()
session.headers |= {'Accept': 'application/json'}
session.cookies.set('__Secure-next-auth.session-token', config['Authorization'], domain='chat.openai.com')

def refresh_auth():
    response = session.get('https://chat.openai.com/api/auth/session')
    session.headers |= {'Authorization': f'Bearer {response.json()['accessToken']}'}
    config |= {'Authorization': session.cookies.get('__Secure-next-auth.session-token', domain='chat.openai.com')}
    config_path.write_text(json.dumps(config))
```

I have a [working solution](https://github.com/Cubicpath/ChatGPT-GUI/blob/master/src/chatgpt_gui/network/client.py) in my own project, though its not very clean and uses `PySide6.QNetwork` as opposed to `requests`.

**Comment by acheong08** [comment]
I'll check this out

**Comment by acheong08** [comment]
It seems the `__Secure-next-auth.session-token`  doesn't actually change after each session call. It has a pretty long expiry date (around 3 weeks) but it is reset with the same value every refresh (until an unknown time). I will implement this as a method of authentication

**Comment by acheong08** [comment]
> session.cookies.set('__Secure-next-auth.session-token', config['Authorization'], domain='chat.openai.com')

I don't think the session token and bearer key is the same

**Comment by Cubicpath** [comment]
Are you sure it's not changing? I am getting a distinct `set-cookie` value for `__Secure-next-auth.session-token` after every call to `https://chat.openai.com/api/auth/session`. The prefix stays the same (I assume that is user identification), but not the rest of the token.

Also yes I wrote that example up quick, in this case `config['Authorization']` was the Session token, not the Bearer token.

`__Secure-next-auth.session-token` could be represented by `config['SessionToken']` instead?

**Comment by acheong08** [comment]
> Are you sure it's not changing

It seems I was mistaken. I didn't compare the whole thing

> __Secure-next-auth.session-token could be represented by config['SessionToken'] instead?

Working on it

**Comment by acheong08** [comment]
Implemented. Writing docs

**Comment by acheong08** [comment]
Done. Thank you for your help
