### ISSUE TITLE
[Feature Request]: 我想利用java实现，但卡在api请求上

### ISSUE THREAD

**Issue by iori0758** [acheong08/ChatGPT#806]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

我正写一个java版的，但目前测试接口的时候卡在一直返回403，我的网络是ok的，能直接用官网提问，
测试是用postman
`curl --location --request POST 'https://chat.openai.com/backend-api/conversation' \
--header 'X-Openai-Assistant-App-Id: ""' \
--header 'accept: text/event-stream' \
--header 'Connection: close' \
--header 'Authorization: Bearer ${使用https://chat.openai.com/api/auth/session 请求返回的accessToken}' \
--header 'content-type: application/stream+json' \
--header 'cookie: __Secure-next-auth.session-token=${使用https://chat.openai.com/api/auth/session 请求返回的cookie里的__Secure-next-auth.session-token}' \
--header 'Accept-Language: en-US,en;q=0.9' \
--header 'referer: https://chat.openai.com/chat' \
--data-raw '{
    "action": "next",
    "messages": [
        {
            "id": "3cec29b9-fc06-4537-b320-f132f7f7f366",--试用python -c 'import uuid; print(uuid.uuid4())'生产，按道理第一次是使用uuid
            "role": "user",
            "content": {
                "content_type": "text",
                "parts": [
                    "今天天气如何"
                ]
            }
        }
    ],
    "parent_message_id": "287b7e78-ee7c-4859-a8ba-b29a63c75b32", --试用python -c 'import uuid; print(uuid.uuid4())'生产，按道理第一次是使用uuid
    "model": "text-davinci-002-render"
}'`

但不知道为什么请求一直返回403
Requested URL: chat.openai.com/backend-api/conversation
					</li>
					<li>Error reference number: 1020

希望作者可以指点指点
Sorry for my bad english,所以用中文提问，感谢

### Proposed workflow

1. 用postman请求https://chat.openai.com/backend-api/conversation
2. Press ....
3. ...

**Comment by acheong08** [comment]
Use chatgpt.duti.tech/api instead of [chat.openai.com/backend-api/conversation](https://chat.openai.com/backend-api/conversation)
