### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'OpenAIAuth'

### ISSUE THREAD

**Issue by feranwq** [acheong08/ChatGPT#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

from revChatGPT.V1 import Chatbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/revChatGPT/V1.py", line 11, in <module>
    from OpenAIAuth import Authenticator, Error as AuthError
ModuleNotFoundError: No module named 'OpenAIAuth'

### Steps to reproduce the problem

docker run -it --rm python bash
pip install --upgrade revChatGPT
python
from revChatGPT.V1 import Chatbot

### What should have happened?

no error

### Version where the problem happens

Name: revChatGPT
Version: 2.3.1
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.10/site-packages
Requires: OpenAIAuth, requests
Required-by: 

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
none
```

**Comment by lyleshaw** [comment]
Same thing happens on macos

**Comment by acheong08** [comment]
Run: `pip3 install OpenAIAuth && pip3 show OpenAIAuth`

**Comment by lyleshaw** [comment]
> Run: `pip3 install OpenAIAuth==0.3.0 && pip3 show OpenAIAuth`

I tried `pip3 install revchatgpt==2.3.0` to install version 2.3.0 and everything works fine.
It seems that there may be some problems with the dependencies of the 2.3.1 version.

@acheong08 

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/25427168/219869773-af360840-36cd-4c1a-8d60-c6587cc4b196.png">

**Comment by acheong08** [comment]
Try https://github.com/acheong08/ChatGPT/releases/tag/2.3.2

**Comment by feranwq** [comment]
> Try https://github.com/acheong08/ChatGPT/releases/tag/2.3.2

2.3.2 is ok

**Comment by acheong08** [comment]
fixed then

**Comment by summitsingh** [comment]
Still receiving errors while running `pipenv run proxy`

```
ChatGPT-Proxy % pipenv run proxy
Traceback (most recent call last):
  File "/Users/Documents/chatgpt/ChatGPT-Proxy/proxy.py", line 13, in <module>
    from OpenAIAuth.Cloudflare import Cloudflare
ModuleNotFoundError: No module named 'OpenAIAuth.Cloudflare'; 'OpenAIAuth' is not a package

```

**Comment by acheong08** [comment]
Downgrade your OpenAIAuth version
