### ISSUE TITLE
{'detail': {'message': 'Unauthorized - Access token is missing'}}

### ISSUE THREAD

**Issue by qimo2020** [acheong08/ChatGPT#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![image](https://user-images.githubusercontent.com/60610664/219909331-32359d32-08c6-48b2-8f2d-1d8053584d19.png)

### Proposed workflow

![image](https://user-images.githubusercontent.com/60610664/219909335-de54c0dc-8697-433f-accd-a4c8de1b26ad.png)

**Comment by acheong08** [comment]
More details please. What version?

**Comment by xiaoSUM** [comment]
The latest version I downloaded, 2.3.3V1, also has this problem.I use Microsoft Mail.

**Comment by salahxgamer** [comment]
I just had the same issue and took me a while to fix it, so apparently if you just remove the email and password and leave the tokens it should work, try it out

**Comment by xiaoSUM** [comment]
您好，您的邮件我已收到，我会尽快回复您的。祝好！刘倩

**Comment by salahxgamer** [comment]
lol you should probably deactivate auto reply for github messages

**Comment by xiaoSUM** [comment]
> 



> lol you should probably deactivate auto reply for github messages

lol, thank you, I will follow your way to try, also, my English is very poor, this sentence is translated by translation software, hope you don't mind.

**Comment by salahxgamer** [comment]
No problems, your messages are crystal clear, update me

**Comment by xiaoSUM** [comment]
> No problems, your messages are crystal clear, update me
chatGPT can be used according to your suggestion just now, thank you very much.

**Comment by acheong08** [comment]
Use access_token only. No email/password
