### ISSUE TITLE
[Feature Request]: https://chatgpt.duti.tech/, how is this system implemented? 

### ISSUE THREAD

**Issue by zongyunboo** [acheong08/ChatGPT#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Can we deploy and implement it ourselves ?

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by pengzhile** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues and checked the recent builds/commits
> 
> ### What would your feature do ?
> Can we deploy and implement it ourselves ?
> 
> ### Proposed workflow
> 1. Go to ....
> 2. Press ....
> 3. ...
> 
> ### Additional information
> _No response_

You can find the answer you're looking for in this repo: https://github.com/pengzhile/pandora

**Comment by acheong08** [comment]
Use discussions for questions

**Comment by masonc15** [comment]
This **is** a question.  I would also like to know what this external site is.  Is the purpose so you hide the actual model name being used?

**Comment by acheong08** [comment]
It's a simple proxy system to hide how we're bypassing Cloudflare. The purpose is to prevent the method from being shut down.

Note: V2 was shut down mere hours after the source code was disclosed

**Comment by pengzhile** [comment]
> This **is** a question. I would also like to know what this external site is. Is the purpose so you hide the actual model name being used?

You can read the source code in yet another command-line ChatGPT repository I provided earlier, which should have the secrets you're looking for.

**Comment by acheong08** [comment]
Oh yes, it seems you found it.

**Comment by acheong08** [comment]
I'll release this and remove the need for the proxy by the end of this week. This is a larger repository with OpenAI's eyes on it

**Comment by ryomahan** [comment]
@acheong08 @pengzhile love you guys so mush, I find the answer whole day, I really should have come here earlier.

**Comment by ade90036** [comment]
It doesn't take a genius to figure what the "proxy" is actually doing. (bypassing is an understatement)

Question 2) Is it safe to use and you are using this responsibly? Meaning are you scraping `access_tokens` and contents of the APIs (request / response)?

**Comment by acheong08** [comment]
>  Is it safe to use and you are using this responsibly? Meaning are you scraping access_tokens and contents of the APIs (request / response)?

I am not logging any data. I get around 600GB of data per day and it would be a nightmare to log any of that. I can't afford it.

Also, I recently got some funding from the community so there is no financial need for me to do so either.

**Comment by acheong08** [comment]
> I'll release this and remove the need for the proxy by the end of this week. This is a larger repository with OpenAI's eyes on it

Although I did want to open it up, I was informed not to by the general community via a Twitter poll as well as advice from other people with way more skill/knowledge than I do. @pengzhile has the endpoint and you can get it from their repo. However, I cannot put it directly in this repository due to the number of eyes on it.

**Comment by acheong08** [comment]
> It doesn't take a genius to figure what the "proxy" is actually doing. (bypassing is an understatement)

I think you mean overstatement. Yeah, it's just a basic proxy. The secret is in the endpoint we found.

**Comment by ade90036** [comment]
OK, thanks for your candor and honesty. 

Obviously if data is power, then 600GB of data daily is a lot of power.  

`I think you mean overstatement`

YES, well it really depended on how the proxy was implemented, if NONE was implemented it would have been understatement but you said that you are proxying content, therefore it is an overstatement. :smile_cat:

**Comment by yaleh** [comment]
> > This **is** a question. I would also like to know what this external site is. Is the purpose so you hide the actual model name being used?
> 
> You can read the source code in yet another command-line ChatGPT repository I provided earlier, which should have the secrets you're looking for.

So OpenAI will block it soon?

**Comment by MaximKiselev** [comment]
@pengzhile hi,  is it a  pandora script?

**Comment by acheong08** [comment]
It was same.

> @pengzhile hi, is it a pandora script?

**Comment by acheong08** [comment]
> > > This **is** a question. I would also like to know what this external site is. Is the purpose so you hide the actual model name being used?
> > 
> > 
> > You can read the source code in yet another command-line ChatGPT repository I provided earlier, which should have the secrets you're looking for.
> 
> So OpenAI will block it soon?

It got blocked.

**Comment by MaximKiselev** [comment]
@acheong08 and how you resolved this problem? im mean that buti hosts also on cf. does serv do something or only reversed proxy on origin serv? thanks.

**Comment by acheong08** [comment]
The previous proxy server is now open source: https://github.com/acheong08/ChatGPT-Proxy-V1

Now I wrote another bypass closed source for now. Completely different method

**Comment by MaximKiselev** [comment]
@acheong08 Can you even hint by what principle does it work? did you change headers or something else? thanks

**Comment by acheong08** [comment]
> @acheong08 Can you even hint by what principle does it work? did you change headers or something else? thanks

something similar yes.
