### ISSUE TITLE
[Bug]: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package

### ISSUE THREAD

**Issue by PeiAlan** [acheong08/ChatGPT#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

python3 server.py 

Traceback (most recent call last):
  File "/application/openai/server.py", line 5, in <module>
    from revChatGPT.V2 import Chatbot
  File "/usr/local/python3/lib/python3.10/site-packages/revChatGPT/V2.py", line 12, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth
ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package

### Steps to reproduce the problem

pip3 install revchatgpt==2.3.2
pip3 install OpenAIAuth==0.3.1 && pip3 show OpenAIAuth
python3 -m revChatGPT.V2

python3 -m revChatGPT.V2 -h
python3 server.py 

### What should have happened?

no error

### Version where the problem happens

Name: revChatGPT
Version: 2.3.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/python3/lib/python3.10/site-packages
Requires: OpenAIAuth, requests
Required-by: 

### What Python version are you running this with?

Python 3.10.4

### Command Line Arguments

```Shell
Linux
```

### Console logs

```Shell
no
```

### Additional information

none

**Comment by rothnic** [comment]
I was just trying to get this running as well and ran into this same issue. I wasn't sure from the readme whether the v2 is functional or not given the under maintenance message.

**Comment by zabzd999** [comment]
Getting the same error  in python 3.10.4

**Comment by PeiAlan** [comment]
I was just trying to import individually  and trying to run code "import OpenAIAuth " , no error. 
I feel that he v2 is not functional

**Comment by acheong08** [comment]
V2 is broken

**Comment by acheong08** [comment]
Use V1

**Comment by HiEddie666** [comment]
Can V1 use chatgpt plus version?

**Comment by acheong08** [comment]
yes. set paid to true in config
