### ISSUE TITLE
[Bug]: Server chatboot.V1  get_msg_history() return wrong chinese string encoding

### ISSUE THREAD

**Issue by jyg9** [acheong08/ChatGPT#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I cant decode chinese characters when calling "chatbot.get_msg_history()"
It is encoded in UTF-8, but is not a valid Chinese character.

### Steps to reproduce the problem

.

### What should have happened?

.

### Version where the problem happens

.

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
Invalid issue. Fill out your Python version

**Comment by acheong08** [comment]
All details must be filled

**Comment by rakuyoMo** [comment]
> Invalid issue. Fill out your Python version

This issue occurs with version 3.11 of python and version 2.2.7 of revChatGPT.

**Comment by acheong08** [comment]
is it only for `get_msg_history` or does `ask` also break?

**Comment by rakuyoMo** [comment]
> is it only for `get_msg_history` or does `ask` also break?

only `get_msg_history`

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.3.4
