### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'revChatGPT.ChatGPT'

### ISSUE THREAD

**Issue by GrahamboJangles** [acheong08/ChatGPT#823]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

python3 main.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    from revChatGPT.ChatGPT import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.ChatGPT'

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

it should have ran

### Version where the problem happens

Version: 2.3.3

### What Python version are you running this with?

Python 3.8.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no console logs
```

**Comment by acheong08** [comment]
`from revChatGPT.V1 import Chatbot`
