### ISSUE TITLE
[Feature Request]: Can inside China use it with an VPN?

### ISSUE THREAD

**Issue by jinfagang** [acheong08/ChatGPT#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

1. Does it work with vpn?
2. Does it have limited quota?

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
Yes it works in China with a VPN. That is what I'm doing

**Comment by jinfagang** [comment]
oh, what I want ask, is that is it work without VPN?

**Comment by acheong08** [comment]
OpenAIAuth doesn't work without VPN.

**Comment by acheong08** [comment]
But works if you use access_token

**Comment by jinfagang** [comment]
@acheong08 If access_token got then it doesn't need VPN anylonger to request a response?

How long does an access_token can survive?

**Comment by acheong08** [comment]
yes and 2 weeks
