### ISSUE TITLE
[Feature Request]: New chat for each request

### ISSUE THREAD

**Issue by yinzhangyue** [acheong08/ChatGPT#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Currently each request shares the same chat context, which may interfere with each other. So for each new request, can the request be made based on the chat window name?

### Proposed workflow

1. Locate the chat window name, or create a new chat window
2. Request

**Comment by acheong08** [comment]
you can make a new chat by calling reset
