### ISSUE TITLE
[Feature Request]: Add temperature as an input

### ISSUE THREAD

**Issue by mccoydj1** [acheong08/ChatGPT#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Would it be possible to add temperature as an input? I can't find it in this latest version

### Proposed workflow

1. Enter temperature as an input
2. Temperature adjusts output of ChatGPT

**Comment by acheong08** [comment]
ChatGPT doesn't have temperature option

**Comment by mccoydj1** [comment]
Bummer! Thanks for checking
