### ISSUE TITLE
[Feature Request]:  The output of V1 version 2.2.6 is incorrect

### ISSUE THREAD

**Issue by Liu-Angelo** [acheong08/ChatGPT#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

the first：
 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/19570026/220038336-b4442a72-dc3d-4c07-ba88-837a925dbe78.png">

### Proposed workflow

The first：
This result is the output of the new model

<img width="621" alt="image" src="https://user-images.githubusercontent.com/19570026/220038374-aa89a35b-2f84-4bd1-a9bc-9ad41fa4bdfd.png">

The second time ：
This result is the output of the old model
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/19570026/220071994-66d8f57f-b0c9-49a3-bf7a-eb3209b61d16.png">

With the same V 2.2.6 version of the code, the output deviation is relatively large

**Comment by acheong08** [comment]
This is OpenAI's issue, not mine

**Comment by Liu-Angelo** [comment]
> 这是 OpenAI 的问题，不是我的

Every time the task is initialized, it is fine, but if you have a session in a bot after the initialization, this will happen

**Comment by Liu-Angelo** [comment]
> This is OpenAI's issue, not mine

Every time you initialize a bot, you have a problem. If you initialize a bot in a session, you have a problem
