### ISSUE TITLE
Field missing

### ISSUE THREAD

**Issue by yehx1** [acheong08/ChatGPT#834]
Field missing
{'detail': {'message': 'Could not parse your authentication token. Please try signing in again.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_jwt'}}
I got this error even try signing again.

**Comment by wswslzp** [comment]
Same to me. Just used "access_token" to sign in but got this error.

```python
chatbot = Chatbot(config={
  "access_token": "<access_token>"
  # "email": "<your email>",
  # "password": "<your password>"
})
```

**Comment by Anianonymous** [comment]
> Field missing {'detail': {'message': 'Could not parse your authentication token. Please try signing in again.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_jwt'}} I got this error even try signing again.

It seems that you are encountering an authentication error while trying to access a service that requires authentication using a JSON Web Token (JWT).

**Comment by salahxgamer** [comment]
if you could share more details like the config you used (alter sensitive data) and try getting new tokens by logging out and back in

**Comment by acheong08** [comment]
Didn't copy the full jwt

**Comment by yehx1** [comment]
I used config file, namely ~/.config/revChatGPT/config.json, then got this error.
But if I set config with  Chatbot(config={"access_token": "<access_token>"}), the problem was gone. Now I can use it with this method.
