### ISSUE TITLE
Exception: Field missing. Details: {'detail': {'message': 'Incorrect API key provided:

### ISSUE THREAD

**Issue by Mrw33554432** [acheong08/ChatGPT#835]
Error when using token access
Exception: Field missing. Details: {'detail': {'message': 'Incorrect API key provided:
seem like API key is missing somewhere

**Comment by wswslzp** [comment]
Same to me. Just used "access_token" to sign in but got this error.

```python
chatbot = Chatbot(config={
  "access_token": "<access_token>"
  # "email": "<your email>",
  # "password": "<your password>"
})
```

**Comment by salahxgamer** [comment]
shouldn't you add the session token too ?

**Comment by acheong08** [comment]
No need for session token if have access token. Here it seems that the access token is invalid (either not copied correctly or expired)

**Comment by acheong08** [comment]
Centralized tracking https://github.com/acheong08/ChatGPT/issues/846

**Comment by acheong08** [comment]
Centralized tracking https://github.com/acheong08/ChatGPT/issues/846
