### ISSUE TITLE
Details: {'detail': {'message': 'Unauthorized - Access token is missing'}}

### ISSUE THREAD

**Issue by SnapdragonLee** [acheong08/ChatGPT#838]
Seems like OpenAIAuth is not working. access token is missing....

File "*****\chatgpt-weBot\revChat\revChatGPT.py", line 190, in ask
    raise Exception("Field missing. Details: " + str(line))
Exception: Field missing. Details: {'detail': {'message': 'Unauthorized - Access token is missing'}}

**Comment by QylinFly** [comment]
V1 不可以用啦！

**Comment by acheong08** [comment]
Centralized tracking https://github.com/acheong08/ChatGPT/issues/846
