### ISSUE TITLE
[Bug]: Exception: Field missing. Details: {'detail': {'message': 'Unauthorized - Invalid access token'}}

### ISSUE THREAD

**Issue by wswslzp** [acheong08/ChatGPT#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After `pip3 install revChatGPT`, I followed the instructions in README.md, created a config.json file in CWD,
```json
{
  "access_token": "<my_own_openai_api_key>"
}
```
and ran `python3 -m revChatGPT.V1` in bash. Then got the exception as the title. **The OpenAI API Key can work normally in other Apps like VSCode ChatGPT extension.** 

The report shows 
```
➜  chatbot git:(master) ✗ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
Hi 

Chatbot: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 437, in <module>
    main(configure())
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 418, in main
    for data in chatbot.ask(
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 191, in ask
    raise Exception("Field missing. Details: " + str(line))
Exception: Field missing. Details: {'detail': {'message': 'Unauthorized - Invalid access token'}}
```

The OS is Windows Subsystem Linux. Ubuntu 20.04.5 LTS

### Steps to reproduce the problem

See the comments above.

### What should have happened?

Should act as what README said. 

### Version where the problem happens

Latest version. 

### What Python version are you running this with?

Python 3.8.10 (default, Nov 14 2022, 12:59:47)

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No arguments
```

### Console logs

```Shell
➜  chatbot git:(master) ✗ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
Hi 

Chatbot: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 437, in <module>
    main(configure())
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 418, in main
    for data in chatbot.ask(
  File "/home/zliao/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 191, in ask
    raise Exception("Field missing. Details: " + str(line))
Exception: Field missing. Details: {'detail': {'message': 'Unauthorized - Invalid access token'}}
```

**Comment by wswslzp** [comment]
A more detailed version of this issue reported right here. It should be helpful to debug. 

Note that same syndrome happens when running the Python API example.

**Comment by evilinsipid** [comment]
Do you include the angle brackets in the config? The correct way should be like 
{
  "access_token": "my_own_openai_api_key"
}

**Comment by c0pper** [comment]
> Do you include the angle brackets in the config? The correct way should be like
> 
> ```
> {
>   "access_token": "my_own_openai_api_key"
> }
> ```

The same happens when using the developer API example (used to work until this a couple hours before this message). Should the access token be added to the chatbot object config parameter?

**Comment by acheong08** [comment]
Centralized tracking https://github.com/acheong08/ChatGPT/issues/846
