### ISSUE TITLE
快速注册访问ChatGPT方法

### ISSUE THREAD

**Issue by hardwellwell** [acheong08/ChatGPT#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

快速科学上网教程：[科学上网](https://github.com/hardwellwell/FreePAC)

注册ChatGPT完整教程 ：[注册ChatGPT教程](https://github.com/hardwellwell/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

### Proposed workflow

快速科学上网教程：[科学上网](https://github.com/hardwellwell/FreePAC)

注册ChatGPT完整教程 ：[注册ChatGPT教程](https://github.com/hardwellwell/FreePAC/wiki/ChatGPT%E6%B3%A8%E5%86%8C%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%8C%E6%95%B4%E6%8C%87%E5%8D%97%EF%BC%89)

**Comment by bywjge** [comment]
I think you should add the advertising label

**Comment by slippersheepig** [comment]
@acheong08 it seems that someone want to be [block](https://github.com/contact/report-content)

**Comment by acheong08** [comment]
Advertising not allowed. I will ban user
