### ISSUE TITLE
[Bug]: Exception: Field missing. Details: {'detail': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID a4108d28d747aef4547ba914913566bc in your message.)', 'type': 'server_error', 'param': None, 'code': None}}

### ISSUE THREAD

**Issue by yuandongbo-1** [acheong08/ChatGPT#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

from revChatGPT.V2 import Chatbot

async def main():
    chatbot = Chatbot(email="***",password="***")
    async for line in chatbot.ask("Hello"):
        print(line["choices"][0]["text"].replace("<|im_end|>", ""), end="", flush = True)
    print()

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())

### Steps to reproduce the problem

just run

### What should have happened?

shuold be normal

### Version where the problem happens

2.3.4

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Exception: Field missing. Details: {'detail': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID a4108d28d747aef4547ba914913566bc in your message.)', 'type': 'server_error', 'param': None, 'code': None}}
```

**Comment by gnohgnailoug** [comment]
same problem

**Comment by Jecket22** [comment]
ChatGPT seems to struggle right now, even for Paid users. This issue is not specific to this repository

**Comment by gnohgnailoug** [comment]
> ChatGPT seems to struggle right now, even for Paid users. This issue is not specific to this repository

Thanks to your reply! Hope this problem won't affect our using this repo

**Comment by doevent** [comment]
Server OpenAI is down

https://status.openai.com/

**Comment by RangerCD** [comment]
Now it's back online!
> Monitoring - Service is now beginning to recover, we are continuing to monitor.
Feb 21, 2023 - 02:04 PST
