### ISSUE TITLE
does not work after a day (bug?)

### ISSUE THREAD

**Issue by SneznyKocur** [acheong08/ChatGPT#85]
**Describe the bug**
Tried to refresh the chatbot

**To Reproduce**
1. Use this code:
```
from revChatGPT.revChatGPT import Chatbot
chatbot = Chatbot(config, conversation_id=None)
chatbot.refresh_session()
chatbot.reset_chat() # Forgets conversation
```
3. See error

**Environment (please complete the following information):**
 - MacOS
 - Python version: 3.8.10
 - Version: 0.0.23.5

**Additional context**
I am using python 3.8 to be compatible with other libraries in this project

**Comment by acheong08** [comment]
@SneznyKocur Always update the version before opening an issue. 
`pip3 install pyChatGPT==0.0.28`
