### ISSUE TITLE
[Bug]: cant use,help! command line error

### ISSUE THREAD

**Issue by alphaokxyz** [acheong08/ChatGPT#860]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

installed but cant use 

### Steps to reproduce the problem

dont know

### What should have happened?

dont know

### Version where the problem happens

Version: 2.3.5

### What Python version are you running this with?

3.8.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
user@vps:/$ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
hi

Chatbot:
{"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 444, in <module>
    main(configure())
  File "/home/user/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 425, in main
    for data in chatbot.ask(
  File "/home/user/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 172, in ask
    self.__check_response(response)
  File "/home/user/.local/lib/python3.8/site-packages/revChatGPT/V1.py", line 226, in __check_response
    raise error
__main__.Error
```

### Additional information

help!

**Comment by AJHIAUNncnfbg** [comment]
Try updating the dependencies to the latest version. I also encountered a similar problem, and this is how I solved it

**Comment by luy98** [comment]
Try updating the dependencies to the latest version. I also encountered a similar problem, and this is how I solved it.

**Comment by alphaokxyz** [comment]
> 

升级了两个依赖 然并卵 你什么系统啊 会不会是我Ubuntu的问题

**Comment by alphaokxyz** [comment]
@luy98 升级了两个依赖 然并卵 你什么系统啊 会不会是我Ubuntu的问题

**Comment by xoox** [comment]
Try
```
pip install --upgrade --upgrade-strategy eager revChatGPT
```

@luy98's method works. Though the reason unknown.

**Comment by alphaokxyz** [comment]
@xoox 666 work fine good job
