### ISSUE TITLE
[Bug]: Error reported when using V1

### ISSUE THREAD

**Issue by chenjinzhi1990** [acheong08/ChatGPT#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Error reported when using V1   tag:2.3.5

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/25029027/220833411-4e2a025e-03b5-4403-b5fb-04ddf3ca80f1.png)

### What should have happened?

![image](https://user-images.githubusercontent.com/25029027/220833420-b1201107-3880-401d-b628-654320eafec8.png)

### Version where the problem happens

![image](https://user-images.githubusercontent.com/25029027/220833430-8b44b364-3561-4245-a06e-5e5e6d0760f9.png)

### Command Line Arguments

```Shell
Error reported when using V1
```

### Console logs

```Shell
Error reported when using V1
```

**Comment by xoox** [comment]
https://github.com/acheong08/ChatGPT/issues/860#issuecomment-1441281024 might solve the problem.

**Comment by chenjinzhi1990** [comment]
Using v2.3.0 back worked
