### ISSUE TITLE
[Bug]: Streaming doesn't appear to work

### ISSUE THREAD

**Issue by JulianRoyet** [acheong08/ChatGPT#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

If I understand the code and provided examples correctly, the ask function should yield partial messages word by word as they are generated. However, calling the function freezes for a few seconds, then yields everything at once.

### Steps to reproduce the problem

for r in bot.ask("hello world"):
   print(r["message"])

or just

python -m revChatGPT.V1
you: Hello world

### What should have happened?

>"Hi"
>"Hi!"
>"Hi! What"
...
>"Hi! What can I do"
...
>"Hi! what can I do for you?"

instead it's just
...
...
...
"Hi! What can I do for you?"

### Version where the problem happens

2.3.6

### What Python version are you running this with?

3.8.12

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
python -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press enter twice to submit your question.

Logging in...

You:
hello world

Chatbot: 
Hello there! How can I assist you today?

You:
what languages do you speak

Chatbot: 
As an artificial intelligence language model, I am capable of understanding and generating text in several languages including but not limited to English, Spanish, French, German, Italian, Chinese, Japanese, Korean, Arabic, and Portuguese. However, my proficiency in each language may vary, and I am constantly learning and improving my language abilities.
```

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT/releases/tag/2.3.8

**Comment by JulianRoyet** [comment]
well that was quick, thank you
