### ISSUE TITLE
[Feature Request]: Better docstrings

### ISSUE THREAD

**Issue by acheong08** [acheong08/ChatGPT#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Improve current docstrings and documentation

### Proposed workflow

Rewrite everything, possibly with the help of GPT

### Additional information

Most of the documentation of this repo was written by a kind contributor last year. Since then, tons of updates has been made. Need to actually write some docs and not assume every user is omniscient. More examples will be welcome

**Comment by acheong08** [comment]
Request to the community: Post some code snippets of how to use this library in this thread. I will later migrate those examples to a dedicated wiki page. Thanks.

**Comment by NymdaFromSalad** [comment]
Here is a simplified version of what i used for my project (Wanted to support multi-account, so it was simpler to move your lib to a webserver
```Python
#A simple flask server to use ChatGPT

from flask import Flask, request
import base64
import asyncio
from revChatGPT.V1 import Chatbot

app = Flask(__name__)

@app.route("/")
async def service():
    try:
        prompt = str(base64.urlsafe_b64decode(request.args.get('gpt')), 'utf-16')
        for data in chatbot.ask(prompt):
            response = data["message"]
        return response
    except Exception as e: #Not sure if it can generate any other errors here, so to hell with it
        return 'Too many requests', 429

chatbot = Chatbot(config={
  "email": "<login>",
  "password": "<wordOfThePass>"
})

print("logged in")

#    And using the server:
#    query = input()
#
#    data = base64.urlsafe_b64encode(bytes(query, 'utf-16'))
#    data = str(data)[2:-1]
#    response = requests.get(f'http://{Address}/test/?gpt={data}')#
```
Not sure, if it is what you want, but it is what i have
