### ISSUE TITLE
[Feature Request]: V1: Non-streaming request support

### ISSUE THREAD

**Issue by zouyxdut** [acheong08/ChatGPT#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The non-streaming request is very profitable as it consumes much less network traffic than the streaming one. I tried to change the ask function to non-streaming, but it just accumulates multiple responses and returns them together.
Is there a way to support the REAL non-streaming request?

**Comment by acheong08** [comment]
not possible. the API ignores stream parameters on OpenAI's side
