### ISSUE TITLE
[Bug]: - revChatGPT.V1 - ERROR - ask - Field missing NoneType: None

### ISSUE THREAD

**Issue by Panzer-Jack** [acheong08/ChatGPT#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

```
用户：hi
2023-02-25 20:08:52,757 - revChatGPT.V1 - ERROR - ask - Field missing
NoneType: None
Traceback (most recent call last):
  File "E:\TecProject\QQ_Rob\chatGPT.py", line 31, in <module>
    chatGPT_ask(askText, prev_text)
  File "E:\TecProject\QQ_Rob\chatGPT.py", line 17, in chatGPT_ask
    for data in chatbot.ask(
  File "C:\Users\danny\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\V1.py", line 277, in ask
    raise Error(source="ask", message="Field missing", code=1)
revChatGPT.V1.Error
```

### Steps to reproduce the problem

This problem appears in both Linux and Win10 computer.
One hour ago it did work..everything was ok, but when i went back and restarted the programme  it show me this...
I tried to restart the programme on other computer (Window10) but it also show me this.

### What should have happened?

Does it mean OpenAI blocked my account ?

### Version where the problem happens

revChatGPT-2.3.10
revChatGPT.V1

### What Python version are you running this with?

Python 3.8.10

### What is your operating system ?

Windows, Linux

### Command Line Arguments

```Shell
2023-02-25 20:08:52,757 - revChatGPT.V1 - ERROR - ask - Field missing
NoneType: None
```

### Console logs

```Shell
2023-02-25 20:18:04,439 - revChatGPT.V1 - ERROR - ask - Field missing
NoneType: None
Traceback (most recent call last):
  File "E:\TecProject\QQ_Rob\chatGPT.py", line 31, in <module>
    chatGPT_ask(askText, prev_text)
  File "E:\TecProject\QQ_Rob\chatGPT.py", line 17, in chatGPT_ask
    for data in chatbot.ask(
  File "C:\Users\danny\AppData\Local\Programs\Python\Python38\lib\site-packages\revChatGPT\V1.py", line 277, in ask
    raise Error(source="ask", message="Field missing", code=1)
revChatGPT.V1.Error
```

**Comment by GP1390** [comment]
I met the same problem，but it's because of expired access_token. Just refresh the access_token and it gets solved.

**Comment by noseon** [comment]
and only you do the treatment when you return the response None.then with that you can put a second account to continue using.

**Comment by acheong08** [comment]
Access token can now be cached and renewed when expired

**Comment by vvaezian** [comment]
@acheong08 I'm getting a slightly different error. It's not related to the expired token, as my token is working fine.
```py
from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={"access_token": '***'})

prompt = "how many beaches does portugal have?"
response = ""

for data in chatbot.ask(prompt):
    response = data["message"]

print(response)
```

```
2023-02-27 13:15:13,305 - revChatGPT.V1 - ERROR - ask - Field missing
NoneType: None
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[51], line 8
      5 prompt = "how many beaches does portugal have?"
      6 response = ""
----> 8 for data in chatbot.ask(
      9   prompt
     10 ):
     11     response = data["message"]
     13 print(response)

File ~\AppData\Roaming\Python\Python38\site-packages\revChatGPT\V1.py:399, in Chatbot.ask(self, prompt, conversation_id, parent_id, timeout)
    392         log.error("Invalid access token")
    393         raise Error(
    394             source="ask",
    395             message=line.get("detail", {}).get("message"),
    396             code=3,
    397         )
--> 399     raise Error(source="ask", message="Field missing", code=1)
    400 message = line["message"]["content"]["parts"][0]
    401 if message == prompt:

Error: 
```

**Comment by Panzer-Jack** [comment]
> 

You can change the "CHATGPT_BASE_URL" to the official one. It's in revChatGPT.V1

**Comment by Panzer-Jack** [comment]
> @acheong08 I'm getting a slightly different error. It's not related to the expired token, as my token is working fine.
> 
> ```python
> from revChatGPT.V1 import Chatbot
> 
> chatbot = Chatbot(config={"access_token": '***'})
> 
> prompt = "how many beaches does portugal have?"
> response = ""
> 
> for data in chatbot.ask(prompt):
>     response = data["message"]
> 
> print(response)
> ```
> 
> ```
> 2023-02-27 13:15:13,305 - revChatGPT.V1 - ERROR - ask - Field missing
> NoneType: None
> ---------------------------------------------------------------------------
> Error                                     Traceback (most recent call last)
> Cell In[51], line 8
>       5 prompt = "how many beaches does portugal have?"
>       6 response = ""
> ----> 8 for data in chatbot.ask(
>       9   prompt
>      10 ):
>      11     response = data["message"]
>      13 print(response)
> 
> File ~\AppData\Roaming\Python\Python38\site-packages\revChatGPT\V1.py:399, in Chatbot.ask(self, prompt, conversation_id, parent_id, timeout)
>     392         log.error("Invalid access token")
>     393         raise Error(
>     394             source="ask",
>     395             message=line.get("detail", {}).get("message"),
>     396             code=3,
>     397         )
> --> 399     raise Error(source="ask", message="Field missing", code=1)
>     400 message = line["message"]["content"]["parts"][0]
>     401 if message == prompt:
> 
> Error: 
> ```

You can change the "CHATGPT_BASE_URL" to the official one. It's in revChatGPT.V1
