### ISSUE TITLE
[Feature Request]:  Terminal colors for the conversation

### ISSUE THREAD

**Issue by cypggs** [acheong08/ChatGPT#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

Can the terminal color of the robot and you be increased to better visually present the conversation?

**Comment by pengzhile** [comment]
like this?

![](https://github.com/pengzhile/pandora/raw/master/doc/images/s05.png)

**Comment by acheong08** [comment]
Yes

**Comment by acheong08** [comment]
I'll add it by tonight

**Comment by cypggs** [comment]
> I'll add it by tonight

High efficiency，tks^_^

**Comment by cypggs** [comment]
`while True:
    #    prompt = get_input("\nYou:\n")
        prompt = get_input("\033[1;32;40mYou:\033[0m\n")
...
        print("\033[1;34;40mChatbot:\033[0m")
      #  prev_text = "\033[1;33;40m" + prev_text + "\033[0m"
`

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/3694954/221521917-0763710f-e321-40d6-91dd-0daff48274d8.png">

I just implemented this without coloring the entire text

**Comment by pengzhile** [comment]
> `while True: # prompt = get_input("\nYou:\n") prompt = get_input("\033[1;32;40mYou:\033[0m\n") ... print("\033[1;34;40mChatbot:\033[0m") # prev_text = "\033[1;33;40m" + prev_text + "\033[0m" `
> 
> <img alt="image" width="1378" src="https://user-images.githubusercontent.com/3694954/221521917-0763710f-e321-40d6-91dd-0daff48274d8.png">
> 
> I just implemented this without coloring the entire text

Maybe you also need to consider compatibility under the `windows`.

**Comment by acheong08** [comment]
Not sure about windows though
