### ISSUE TITLE
Chrome Mac - Where to find accessToken?

### ISSUE THREAD

**Issue by acaexplorers** [acheong08/ChatGPT#9]
Definitely a n00b question, but I've been unable to find any information elsewhere.

**Comment by acheong08** [comment]
Right click and inspect
![image](https://user-images.githubusercontent.com/36258159/205495766-39e9af0d-89b1-4c8d-9197-40b4bdc4b84c.png)

Or `fn+f12`

**Comment by acaexplorers** [comment]
Yep, I saw your updated instructions with visuals!  Really helpful, and also thanks for the reply!

Now it is saying "TypeError: 'ValueError' object is not subscriptable" I will try to start a new thread.
