### ISSUE TITLE
[Feature Request]: Check if access token is valid

### ISSUE THREAD

**Issue by linhandev** [acheong08/ChatGPT#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Check for invalid access token and request a new one automatically.

### Proposed workflow

Check if the access token is valid when setting it and maybe request a new one if user provided other means of auth. 

Catch access token invalid error returns during ask and maybe relogin and retry the ask.

**Comment by mdabir1203** [comment]
I would like to take in the issue

**Comment by acheong08** [comment]
I'll do this

**Comment by acheong08** [comment]
Done
