### ISSUE TITLE
[Bug]: Access Denied Error

### ISSUE THREAD

**Issue by getxd-dev** [acheong08/ChatGPT#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I now receive Access Denied error whenever I ask something.

This is the [error output](https://pastebin.com/8DEU6t4h) that it produces.

### Steps to reproduce the problem

By using the library itself.

### What should have happened?

The AI responds normally.

### Version where the problem happens

2.3.14

### What Python version are you running this with?

Python 3.9.16

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
https://pastebin.com/8DEU6t4h
```

**Comment by yiwangethan** [comment]
I guess I meet the same issue now.
Here's the returning error: **revChatGPT.V1.Error: ('OpenAI', 403, '<!DOCTYPE html>\n<html lang="en-US">\n**

**Comment by CarsonKompon** [comment]
Can confirm I'm also getting this. I'm having a feeling the plug was just pulled on OpenAI's end...

**Comment by wlc002** [comment]
openai's reason ? me too

**Comment by CarsonKompon** [comment]
> openai's reason ? me too

Probably self-explanatory. This repo is a *reverse engineered* ChatGPT API, not official.
The wording in the README is a bit misleading since it says "Reverse Engineered ChatGPT API by OpenAI" :P

**Comment by ruanqizhen** [comment]
我也遇到这个问题了。我开始测试前几条请求可以，但是试了几条之后就不行了。

**Comment by tracy15932** [comment]
I met the same problem seem like it's banned by openAI?

**Comment by zenorochaV1** [comment]
me too

**Comment by F33RNI** [comment]
same

**Comment by hnuzhoulin** [comment]
same problem

**Comment by YutongWang1216** [comment]
same here

**Comment by achaosss** [comment]
same here

**Comment by freebr** [comment]
same problem, hoping for solution

**Comment by nptry** [comment]
same

**Comment by assassingyk** [comment]
Changing the CHATGPT_BASE_URL to the official one seems can work

**Comment by AA8j** [comment]
same here

**Comment by wlc002** [comment]
> Changing the CHATGPT_BASE_URL to the official one seems can work

what is the official url?

**Comment by assassingyk** [comment]
> > Changing the CHATGPT_BASE_URL to the official one seems can work
> 
> what is the official url?

https://github.com/acheong08/ChatGPT/commit/88b7dea883c34b532c413563c615d27984148dd0

**Comment by an9xyz** [comment]
> Changing the CHATGPT_BASE_URL to the official one seems can work

Nice, work for me

**Comment by getxd-dev** [comment]
> > URL to the official one seems can work
> 
> what is the official url?

Works for me. Thanks!

**Comment by acheong08** [comment]
Fixed.
