### ISSUE TITLE
[Bug]: revChatGPT.V1.Error. It seems OpenAI blocks access to the chat history.

### ISSUE THREAD

**Issue by xfleezy** [acheong08/ChatGPT#923]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Here is the error message I get after I call the function chatbot.ask("xxxx"):

<!DOCTYPE html>
<html lang="en-US">
   <head>
      <title>Access denied</title>
      <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
      <meta name="robots" content="noindex, nofollow" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
      <script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:5}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>

      <script>
      (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
      </script>
      <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
   </head>
   <body>
   <div class="cf-main-wrapper" role="main">
      <div class="cf-header cf-section">
         <div class="cf-error-title">
            <h1>Access denied</h1>
            <span class="cf-code-label">Error code <span>1020</span></span>
         </div>
         <div class="cf-error-description">
            <p>You do not have access to chat.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>
      </div>
   </div>

   <div class="cf-details-wrapper">
      <div class="cf-section" role="region">
         <div class="cf-expandable" id="cf-details-wrapper-expandable">
            <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
               <p class="cf-dropdown-title">Error details</p>
               <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
               class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
            </label>

            <input id="error-details-checkbox" class="hidden" type="checkbox">

            <div class="cf-expandable-error-info hidden">
               <p class="cf-error-copy-description">Provide the site owner this information.</p>
               <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
<div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chat.duti.tech/api/conversation.</p>

<p>Error code: 1020</p>
<p>Ray ID: 79fcf43de84e2037</p>
<p>Country: US</p>
<p>Data center: ind01</p>
<p>IP: 128.210.106.81</p>
<p>Timestamp: 2023-02-27 00:55:17 UTC</p>
</div>
                  <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
               </button>
            </div>
         </div>
      </div>

      <div class="clearfix cf-footer cf-section" role="contentinfo">
      <div class="cf-column">
           <div class="feedback-hidden py-8 text-center" id="error-feedback">
    <div id="error-feedback-survey" class="footer-line-wrapper">
        Was this page helpful?
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
    </div>
    <div class="feedback-success feedback-hidden" id="error-feedback-success">
        Thank you for your feedback!
    </div>
</div>

      </div>
         <div class="cf-column cf-footer-line-wrapper text-center">
            <p>
               Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
            </p>
         </div>
      </div>
   </div>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"79fcf43de84e2037","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
</body>
</html>

Traceback (most recent call last):
  File "/try.py", line 12, in <module>
    for e, d in enumerate(data):
  File "/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 141, in ask
    self.__check_response(response)
  File "/opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py", line 193, in __check_response
    raise error
revChatGPT.V1.Error

### Steps to reproduce the problem

from revChatGPT.V1 import Chatbot

chatbot = Chatbot(config={
  "email": "lxxxxxx,
  "password": "xxxxxxxx", "paid" :True})

data = chatbot.ask("hello", conversation_id=chatbot.config.get("conversation"),parent_id=chatbot.config.get("parent_id"),)

for e, d in enumerate(data):
    print(d)

### What should have happened?

Chatbot should return messages.

### Version where the problem happens

python3 -m pip show revChatGPT

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
No
```

**Comment by JIACHENG135** [comment]
Same issue here. 
```bash
>>> from revChatGPT.V1 import Chatbot
>>> b = Chatbot(config={
...             "access_token": 
...             "mytoken"
...             })
>>> b.get_conversations(offset=0, limit=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxxx/Documents/chat/venv/lib/python3.9/site-packages/revChatGPT/V1.py", line 223, in get_conversations
    self.__check_response(response)
  File "/Users/xxxxx/Documents/chat/venv/lib/python3.9/site-packages/revChatGPT/V1.py", line 213, in __check_response
    raise error
revChatGPT.V1.Error
```
<img width="738" alt="截屏2023-02-26 下午5 08 16" src="https://user-images.githubusercontent.com/31320373/221449869-60135e24-e613-4d18-9e2c-677831544dde.png">

**Comment by bjtu2011** [comment]
It seems the proxy has been down

**Comment by SnapdragonLee** [comment]
same problem

**Comment by ShafiqSadat** [comment]
same

**Comment by achaosss** [comment]
same

**Comment by Ary0075** [comment]
same

**Comment by sunbo1999** [comment]
same

**Comment by fanzfeng** [comment]
same

**Comment by leonardocsc** [comment]
same here

**Comment by redocecin** [comment]
same problem

**Comment by Rroscha** [comment]
same

**Comment by ck0729666** [comment]
me too

**Comment by hrizal** [comment]
yeah me too ...

**Comment by kenrinx** [comment]
same

**Comment by shiqwang** [comment]
hahaha, I think we should have another way to solve it. I already got one.

**Comment by xfleezy** [comment]
> hahaha, I think we should have another way to solve it. I already got one.

Lol, bro, do you mind sharing it?

**Comment by acheong08** [comment]
Fixed
