### ISSUE TITLE
[Feature Request]: invalid path 'wiki/Code-examples:.md' in windows

### ISSUE THREAD

**Issue by qiangzi1024** [acheong08/ChatGPT#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When I git clone the code base under the windows operating system, it prompts an error.

`invalid path 'wiki/Code-examples:.md' `

![Snipaste_2023-02-27_10-36-32](https://user-images.githubusercontent.com/24761926/221460304-256ead6e-41a5-4372-b79c-6fd8487e4e02.jpg)

### Proposed workflow

-

**Comment by acheong08** [comment]
Fixed
