### ISSUE TITLE
[Feature Request]: Pay by Alipay or Wechat pay

### ISSUE THREAD

**Issue by zhangxianwei2015** [acheong08/ChatGPT#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I want to buy your a coffee, but I don't have the card for it.

### Proposed workflow

1. Go to ....buymeacoffee
2. Press ....by
3. ... no card....

**Comment by bokesyo** [comment]
you can buy a virtual credit card on Taobao, then you can pay

**Comment by acheong08** [comment]
BMC closed. I reached the target and can keep the public proxy running well until Official API released. I'll be improving rate limits

**Comment by acheong08** [comment]
Thanks
