### ISSUE TITLE
A timeout occured

### ISSUE THREAD

**Issue by MrShadowDev** [acheong08/ChatGPT#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Tryed to acess Chat GPT & i can't because it throwed the ``A Timeout Occured``
![image](https://i.imgur.com/LR5XNjm.png)

### Steps to reproduce the problem

1. Go to chat.openai.com
2. Clicked enter to load site.
3. It keeps loading and it crash

### What should have happened?

It should've been opened Chat GPT to start using it.

### Version where the problem happens

Web Browser

### What Python version are you running this with?

Web Browser

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
Web Browser
```

### Console logs

```Shell
Web Browser
```

### Additional information

![image](https://i.imgur.com/LR5XNjm.png)

**Comment by Rroscha** [comment]
Me too!

**Comment by MrShadowDev** [comment]
> Me too!

I just switched on my pc. Went to Chat GPT, and throwing erros. Idk whats the consequence.

**Comment by acheong08** [comment]
https://status.openai.com/

**Comment by acheong08** [comment]
OpenAI is down

**Comment by devkoriel** [comment]
Now it's available for paying users.

**Comment by acheong08** [comment]
I think it's fixed
