### ISSUE TITLE
[Bug]: Get 1020 ERROR FROM CF using the Chatbot API class but works through command Line

### ISSUE THREAD

**Issue by aiseei** [acheong08/ChatGPT#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hi 

I am able to login and use via command line initiated with "python -m revChatGPT.V1"  but when I use the api calls ==> from revChatGPT.V1 import Chatbot  I get 1020 access denied error from Cloudflare. 

Running on revChatGPT==2.3.14

Much appreciate your help !!

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

The API call should have logged in 

### Version where the problem happens

revChatGPT==2.3.14

### What Python version are you running this with?

3.9.16

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
NA
```

### Console logs

```Shell
ERROR:
><div class="cf-error-details cf-error-1020">\n  <h1>Access denied</h1>\n  <p>You do not have access to chat.openai.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>\n  <ul class="cferror_details">\n    <li>Ray ID: 7a04ea84bb07r34e5</li>\n    <li>Timestamp: 2023-02-28 00:06:45 UTC</li>\n    <li>Your IP address: xx.xx.xx.xxx </li>\n    <li class="XXX_no_wrap_overflow_hidden">Requested URL: chat.openai.com/api/conversation </li>\n    <li>Error reference number: 1020</li>\n    <li>Server ID: FL_492F117</li>\n    <li>User-Agent: python-urllib3/1.26.9</li>\n  </ul>\n</div>\n</div>\n    </div>
```

**Comment by acheong08** [comment]
Can't find your Ray ID in my logs

**Comment by aiseei** [comment]
Sorry. Not sure whether it was use to use as I dont use your proxy. 7a04ea84bb07a974

**Comment by acheong08** [comment]
> Sorry. Not sure whether it was used as I dont use your proxy. 

What are you using then?

**Comment by aiseei** [comment]
the api via ===>  revChatGPT.V1 import Chatbot . I get this error using the api but not when I use the CLI.

**Comment by acheong08** [comment]
I just set an allow rule for your user agent. If it doesn't work, you might be using the wrong URL. As an alternative, you can set CHATGPT_BASE_URL=chatgpt-proxy2.fly.dev

**Comment by aiseei** [comment]
thanks. 
CHATGPT_BASE_URL is set to ===> https://chat.openai.com/
 We can change the user agent - what should be preferred agent ?

Unfortunately, Still get the same error using the above base url. 
Much appreciate you responsiveness!

**Comment by acheong08** [comment]
> CHATGPT_BASE_URL is set to ===> [chat.openai.com](https://chat.openai.com/)

That will cause errors

**Comment by aiseei** [comment]
ok. so just so that I am clear.
 What should be default then ? So are then by design all requests proxied by you?

thanks!

**Comment by aiseei** [comment]
hi used the proxy that u provided but got this error

ERROR HTTPSConnectionPool(host='chatgpt-proxy2.fly.devapi', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f35785f40>: Failed to establish a new connection: [Errno -2] Name or service not known')) (MaxRetryError("HTTPSConnectionPool(host='chatgpt-proxy2.fly.devapi', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2f35785f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))")

**Comment by aiseei** [comment]
It worked with the proxy url. Closing this issue
