### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by steegecs** [acheong08/ChatGPT#95]
It appears that I am not able to log in. Might there be some issue with bot blocking again?

**Comment by steegecs** [comment]
<img width="132" alt="Screen Shot 2022-12-06 at 11 27 50 AM" src="https://user-images.githubusercontent.com/56660047/205980786-dba4424e-cc54-44f7-b3b3-5eae9630d643.png">

<img width="271" alt="Screen Shot 2022-12-06 at 11 28 13 AM" src="https://user-images.githubusercontent.com/56660047/205980854-5d815f8a-831a-4031-aa01-b6ae91de5052.png">

The error refreshing the session is happening here. 
<img width="353" alt="Screen Shot 2022-12-06 at 11 30 01 AM" src="https://user-images.githubusercontent.com/56660047/205981160-a06c1079-0342-460c-b78d-19056f88a049.png">

**Comment by acheong08** [comment]
Open again following the proper Bugs template.

Too much information missing
