### ISSUE TITLE
[Bug]: Long responses are cut

### ISSUE THREAD

**Issue by marc-dsalab** [acheong08/ChatGPT#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Whenever i provide a prompt that leads to a large reply, the response (if asked via the API) is cut. The very same prompt works fine via the web interface.

I already played around with the timeout parameter and also tried the streamed approach.

It seems though that it is not always cut at the same position. 

Any idea what it could be or how i could get the full response?

### Steps to reproduce the problem

Just try a prompt that generates a rather large response.

### What should have happened?

I would expect to receive the full response

### Version where the problem happens

2.3.16

### What Python version are you running this with?

Python 3.9.6

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
not applicable
```

### Console logs

```Shell
none
```

**Comment by acheong08** [comment]
Limitation by OpenAI

**Comment by acheong08** [comment]
ask it to `continue`

**Comment by marc-dsalab** [comment]
I doubt so, if i do it in the web interface, the response is complete...

**Comment by marc-dsalab** [comment]
You were right, it works. Sorry, didn't realize it immediately!
