### ISSUE TITLE
[Bug]: "error code: 1020" , which means "Access denied".

### ISSUE THREAD

**Issue by zhangxianwei2015** [acheong08/ChatGPT#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hi,

The error is thrown by below lines:

response = self.session.post(
    url=BASE_URL + "api/conversation",
    data=json.dumps(data),
    timeout=timeout,
    stream=True,
)

The response txt is "error code: 1020" , which means "Access denied".

### Steps to reproduce the problem

call function: chatbot.ask 

### What should have happened?

No error should happen, I check several user/password, the issue persistent 

### Version where the problem happens

Name: revChatGPT
Version: 2.3.18
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: prompt-toolkit, asyncio, requests, OpenAIAuth, httpx
Required-by:

### What Python version are you running this with?

Python 3.8.10

### Command Line Arguments

```Shell
NO
```

### Console logs

```Shell
error code: 1020
```

### Additional information

NO

**Comment by Ary0075** [comment]
I have the same problem
```
<div class="cf-main-wrapper" role="main">
  <div class="cf-header cf-section">
     <div class="cf-error-title">
        <h1>Access denied</h1>
        <span class="cf-code-label">Error code <span>1020</span></span>
     </div>
     <div class="cf-error-description">
        <p>You do not have access to chatgpt.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
     </div>
  </div>
</div>
```
This problem has appeared before in issue #923

**Comment by wangcailin** [comment]
I have the same problem, but it's OK to change an IP address

**Comment by acheong08** [comment]
Send your ray ID. I'll whitelist. You may have been blocked as a consequence of abuse by others in the same IP range

**Comment by Ary0075** [comment]
@acheong08 7a0e9d9add063662, thanks a lot!

**Comment by acheong08** [comment]
> @acheong08 7a0e9d9add063662, thanks a lot!

`No firewall events found matching your filters`. Doesn't seem to be a block on my side.

**Comment by Ary0075** [comment]
ok, I'll check if there is any other solution

**Comment by acheong08** [comment]
> ok, I'll check if there is any other solution

Could you try again? I've removed a few firewall rules.

**Comment by Ary0075** [comment]
> Could you try again? I've removed a few firewall rules.

it's normal now

**Comment by zhangxianwei2015** [comment]
works now

**Comment by hucs2542** [comment]
I have also made the same mistake. Is this a limitation of OpenAI or the revChatGPT project?

**Comment by LimeVista** [comment]
Same issue. Ray ID: 7a0f1c3f7da9879f

**Comment by hucs2542** [comment]
Ray ID: 7a0e54309a79050e

**Comment by acheong08** [comment]
I can't find your IDs in the logs. Email me your IP address at acheong@student.dalat.org and I'll see if it's an issue on my servers. Otherwise, the bypass could have been blocked.

**Comment by acheong08** [comment]
Edit: Bypass working for me. Might have been accidentally detected but not logged. Unsure

**Comment by acheong08** [comment]
Issue report:

`AS45102 ALIBABA-CN-NET Alibaba US Technology Co., Ltd.` was blocked due to abuse by multiple of their IP. I have blocked the IPs directly and whitelisted the ASN. Check again and it should work. If it doesn't, contact me again.

**Comment by yxc1227** [comment]
I got the same problem.
My ray ID is 7a3f594f3f76af6a

**Comment by MollyShuu** [comment]
I got the same problem.
My ray ID is 7a3fbab4beb80f0c.

**Comment by murongweibo** [comment]
I got the same problem.
Ray ID: 7a3fafa7f8a1e354

**Comment by acheong08** [comment]
Upgrade to latest version fixes it

**Comment by MollyShuu** [comment]
> Upgrade to latest version fixes it

I have upgrade to the latest version. However, these is still an error with"error code: 1020"

**Comment by acheong08** [comment]
I'll check

**Comment by acheong08** [comment]
Not found in firewall logs

**Comment by acheong08** [comment]
Please use V3. Proxy server is consistently overloaded by DDOS

**Comment by johnshuxian** [comment]
I have the same question as well.
Ray ID: 7a4177dddba352ef

**Comment by acheong08** [comment]
It should resolve it

**Comment by yogeshvar** [comment]
I have the same issue.

Ray ID: 7a4b2e428b3f3e6a

**Comment by yogeshvar** [comment]
@acheong08 I have upgraded to the new version.
<img width="250" alt="Screenshot 2023-03-08 at 11 30 37 pm" src="https://user-images.githubusercontent.com/17572818/223719713-9316b734-f4e2-4d07-873b-6c51b355262a.png">

**Comment by acheong08** [comment]
Can you send another Ray ID. It seems that one was from a previous version

**Comment by acheong08** [comment]
It shows that you're trying to access `chatgpt.duti.tech` which has been deprecated in favor of `chat.duti.tech`

**Comment by acheong08** [comment]
and the reason for the block seems to be due to missing cookies

**Comment by yogeshvar** [comment]
It works now, I have not refreshed my env (my bad :P) thanks for your timely reply.
