### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bnuzhanyu** [acheong08/ChatGPT#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Would you support openai.api_key for Chatbot initialization? e.g. generated by https://platform.openai.com/account/api-keys.

### Proposed workflow

Chatbot(config={'api_key':'sk-xxxx'})

**Comment by acheong08** [comment]
Not possible unfortunately
