### ISSUE TITLE
[Feature Request]: Provide a colour scheme for white background terminals.

### ISSUE THREAD

**Issue by dreirund** [acheong08/ChatGPT#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The feature would allow to easily read the output on black-on-white terminals.

### Proposed workflow

1. Start `revchatgpt` with a command line option `--theme light` or similar, or set a persistent configuration option from within `revchatgpt` by e.g. typing `!config set theme=light`.
2. Read the replies in a dark-coloured font, thus making it easily readable on white background terminals.

### Additional information

Currently, it is hardly readable on white background terminals, see screenshot:

---

![revchatgpt_background](https://user-images.githubusercontent.com/1590519/222103605-d69d215d-3043-4ca5-91aa-832fc76222bf.png)

---

**Comment by acheong08** [comment]
What colors do you suggest for white backgrounds?

**Comment by acheong08** [comment]
Just no colors for now with light mode

**Comment by acheong08** [comment]
Got to set `NO_COLOR` to something in environment variables
