### ISSUE TITLE
[Feature Request]: Allow sending prompts by pressing a key combination like `<ctrl>`+`<return>`.

### ISSUE THREAD

**Issue by dreirund** [acheong08/ChatGPT#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

It would allow to more quickly send prompts.

### Proposed workflow

1. Start `revchatgpt`.
2. Enter your prompt.
3. Press the key combination `<ctrl>`+`<return>` to send the prompt.

### Additional information

Currently, it is required to press `<esc>`, then press `<return>`. This has two disadvantages:

* `<esc>` usually is far away from the "homing" position of any finger, needing a far reach.
* `<esc>` is on some terminals, especially remote terminals, specially handled, and requiring `<esc>` is not compatible in every situation.

**Comment by acheong08** [comment]
`Alt+Enter` also works
