### ISSUE TITLE
[Feature Request]: OpenAI Official Chat API

### ISSUE THREAD

**Issue by binocla** [acheong08/ChatGPT#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Recently, OpenAI has released official ChatGPT API: https://openai.com/blog/introducing-chatgpt-and-whisper-apis,
Docs: https://platform.openai.com/docs/guides/chat.

Nevertheless, API wrapper is already included in the official OpenAI Python lib (https://platform.openai.com/docs/libraries). I suppose, there could be a variety of opportunities to implement the functionality right here. For instance, some kind of switching from V1 way to Official API (paid per 1k tokens) to avoid Rate Limits and increase resilience or just include business-logic under the hood of the official lib (aka migrate) just to make Out-of-the-Box solution (kinda all in one).

Anyway, I'm sure that there are plenty other ideas of in which way this implementation can be dedicated for profitableness

### Proposed workflow

1. Go to `config.json` or apply desired changes straight in the constructor
2. Add extra properties for proper configuration (i.e. `token: XXXXX`, `official: True` etc.)
3. Support additional properties like it was a several months ago with leaked `002` model such as `temperature`, `role`, [moderation](https://platform.openai.com/docs/guides/moderation/quickstart) with corresponding methods for `Chatbot` instance

**Comment by acheong08** [comment]
Almost done

**Comment by slavakurilyak** [comment]
Please update the README to account for v4

**Comment by acheong08** [comment]
Supported

**Comment by hongyi-zhao** [comment]
> Please update the README to account for v4

What's v4? I can only see v3 from listed in README.

**Comment by acheong08** [comment]
Typo
