### ISSUE TITLE
[Feature Request]: New ChatGPT API supports.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Today, I received the following notification from OpenAI:

> Starting today, you can build apps and products with our new ChatGPT and Whisper APIs. You can read more about the APIs and early partners’ use cases [here](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/VWx36g6cFJw4W9gqFVs2KBbr5W95j2m74XD8x7N3hBC6k3lSc3V1-WJV7CgZYvW1Ll2DF4C6GcjW3-XYYL6zfc7WW1Hl1P41WY3GJW1FKXXR6hT1tSW8WRWgl5mG7QlW7QbW4N4WMFBVW2kytmS3Vx0F9W7jXl9T1CKhphW1RNzms6SysCQW5JDQ2w1TRyLfW7hhBN76CZHNQW6mtC5q7V1djHW1mpGGf7bwkYmN5HhK7kn07s1V6kfZz4s9mnGW6YX-364601csW2v5lP2943nDmW5w5l1y6xt6Y3W2bcPjn45gyjyN44pVvCL48gmW4WcxfK9dsP-HVFl0mB1dMPltW3T23JG32qh-0W3MfhGq5YdlqH329L1). 
> 
>  
> 
> ChatGPT API 
> 
> The new Chat API calls gpt-3.5-turbo, the same model used in the ChatGPT product. It’s also our best model for many non-chat use cases; we’ve seen early testers migrate from text-davinci-003 to gpt-3.5-turbo with only a small amount of adjustment needed to their prompts. Learn more about the Chat API in [our documentation](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/VWx36g6cFJw4W9gqFVs2KBbr5W95j2m74XD8x7N3hBC613lSbNV1-WJV7CgJSVW1--PRq4B5cmtW6bp73P3BDS0MW6mZ3Qy7MP7-6W3CsRcd8HgfHwW3PNbBN1KjLqqVdPyP_71Sc77W6LlvJh8vSsjHVvMn4J1lRxPlW2YRX-r3bBLKgW4xzJmJ8SH0YqW65vhgq3W2YmlN1gr6hDTqqpbW4YpBfr6CPHrhN909mr0G07Q0VTxrx694q1j9W8nChLL2JZ1lrW2Gh0rd8D-pJTW36DwG242F_XlW9ljHWg9j0Pz_VLnc88459JMVW4TGX0K12W8zkW77bWbs9ky75S3mvN1).
> 
> Pricing
> It’s priced at $0.002 per 1K tokens, which is 10x cheaper than the existing GPT-3.5 models.
> 
> Model updates
> We are constantly improving our Chat models, and want to make these improvements available to developers as well. Developers who use the gpt-3.5-turbo model will always get our recommended stable model, while still having the flexibility to opt for a specific model version.
> 
>  
> 
> For example, today we’re releasing “gpt-3.5-turbo-0301”, which will be supported through at least June 1st, and we’ll update gpt-3.5-turbo to a new stable release in April. The [models page](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/VWx36g6cFJw4W9gqFVs2KBbr5W95j2m74XD8x7N3hBC613lSbNV1-WJV7CgH0FW2s65JH38YSnmW4QgTRx2-w2CDW641jxz6lGYg8W5Y6L0L6xDC5JW8NgKvj5bRCPZW3603bs6kggk4W6Pb6-K97Hm8gW1mXPbJ2SGzBHW4dB_y04xYZDcN5TbXT-FtpFwW6ttDFT4pjrt4W1vKSdB3vScRmN3652Q9fFW7pW1Z2-2k27qFldW6LNn-V6MJWxzW4tsMLL2DSGsQW7rzhww4Mj9MhW5J-2z91gkg8xW19Jf5m11zpX2W10YtBn89_xnVW79nyJb8Bsf8HN6QR2_qj-CQP35h_1) will provide switchover updates.
> 		
> 
> Whisper API
> 
> We’ve been thrilled to see the community response to Whisper, the speech-to-text model we open-sourced in September 2022. Starting today, the large-v2 model is available through our API as whisper-1 – making it the fastest, cheapest, and most convenient way to use the model. Learn more about the Whisper API in [the documentation](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/VWx36g6cFJw4W9gqFVs2KBbr5W95j2m74XD8x7N3hBC6k3lSc3V1-WJV7CgQvmW274qNz7lqlhzW7btVv181l5GyW113DcQ7nbsPBW1mhjCJ7GcCV2W3Cs8k-8lkYz8W668jbJ3JjGG9W37LWnH4XfmDGW20T0md7q3YzJW6yqqBC9lB4xCW8cbhxV4Vy3GyW7007tq90zCQlW6S5qsH7GQZ58W2P0-qr7Sj3y-W8WmCvk3x1zJ2W2HNG6C7Xs-3dVRGvxC7GT6HmW8hlHXT4QrXxRW97q6SF4VSF0wN8zjRwJH3Z19W4mSDCT71Ll1xN6fZfgNPj1xyMgfyW_wLPdyW1WXDC998mH7SW2xRm7f3kNwHH3knW1).
> 
>  
> 
> Pricing
> The API is priced at $0.006 / minute, rounded up to the nearest second.
> 		
> 
> Changes in our policies and how we use your data
> 
> Over the past six months, we’ve been collecting feedback from our API customers to understand how we can better serve them. We’ve made a number of concrete changes, such as:
> 
>     Data submitted through the API is no longer used for model training or other service improvements, unless you explicitly opt in
>     Implementing a default 30-day data retention policy for API users, with options for shorter retention windows depending on user needs
>     Removing our pre-launch review – unlocked by improving our automated monitoring
>     Simplifying our Terms of Service and Usage Policies, including terms around data ownership: users own the input and output of the models
> 
> [Check out](https://cz6y004.na1.hubspotlinks.com/Ctc/RI+113/cZ6Y004/VWx36g6cFJw4W9gqFVs2KBbr5W95j2m74XD8x7N3hBC6k3lSc3V1-WJV7CgHYGW5ZQzNM8MstFsN8dLH5bbxhQYW2W_NFb6QCYHTW2CqwLW8dYzvmN4v4L09q86n6W7LsNVK46m8JxW3Sz9-J2VSl1XN6BDwFSQWHQ9W1WLXqg5WP46fN44GYfWr3jFYW93SyBT8ktn1jW64sn0H8HC57tW10S8t53qrZHLW4M8KB66GDgG5W90F3gb1q8l0hF4tKP3vHK6_W5gL73M5ltdMyW6ZdKGX3FZZFgW6wy9jc35YBBrW2bBHx45Yw4j_W6GVF7N3NZDQrW7TD7Zd6QK0NJW781Pyh4f0R2CW7XVWF823MCq83lQM1) what our early partners like Snap, Shopify, and Instacart have built with the new APIs – and start building next-generation apps powered by ChatGPT & Whisper today.
> 
>  
> —The OpenAI team

So, I issued this FR.

Best, 
Zhao

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by JIACHENG135** [comment]
It looks like that as of now e.g. 2023-03-01, the gpt-3.5-turbo model doesn't support conversation, which is the most fascinating and powerful feature of chatgpt. And most of the classical chatgpt prompts are not working well on the gpt-3.5-turbo (so called the latest one). I'm upset about this release.

**Comment by slavakurilyak** [comment]
You can now use POST `https://api.openai.com/v1/chat/completions` to [create a chat completion](https://platform.openai.com/docs/api-reference/chat/create)

**Comment by acheong08** [comment]
Duplicate of
- #974

**Comment by acheong08** [comment]
> It looks like that as of now e.g. 2023-03-01, the gpt-3.5-turbo model doesn't support conversation, which is the most fascinating and powerful feature of chatgpt. And most of the classical chatgpt prompts are not working well on the gpt-3.5-turbo (so called the latest one). I'm upset about this release.

It does.

**Comment by olegsvs** [comment]
@acheong08
what about tokens?
```
Error: 400 Bad Request {
  "error": {
    "message": "This model's maximum context length is 4096 tokens. However, your messages resulted in 4144 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```

**Comment by acheong08** [comment]
Need to fix

**Comment by JIACHENG135** [comment]
> > It looks like that as of now e.g. 2023-03-01, the gpt-3.5-turbo model doesn't support conversation, which is the most fascinating and powerful feature of chatgpt. And most of the classical chatgpt prompts are not working well on the gpt-3.5-turbo (so called the latest one). I'm upset about this release.
> 
> It does.

It does, but not explicitly does. You need tricks to support that.

**Comment by acheong08** [comment]
https://platform.openai.com/docs/guides/chat/introduction

**Comment by hongyi-zhao** [comment]
> It does, but not explicitly does. You need tricks to support that.

I want to know whether it is possible to achieve this goal from the perspective of this project?

**Comment by acheong08** [comment]
> > [#975 (comment)](https://github.com/acheong08/ChatGPT/issues/975#issuecomment-1451270606)
> > It does, but not explicitly does. You need tricks to support that.
> 
> I want to know whether it is possible to achieve this goal from the perspective of this project?

I already did it

**Comment by hongyi-zhao** [comment]
> I already did it

It seems that you mean [this one](https://github.com/acheong08/ChatGPT#v3-official-chat-api):

![image](https://user-images.githubusercontent.com/11155854/222330666-d996a6be-1217-42a9-928c-27c53ff07e28.png)

BTW, to use this API interface, must I regenerate a separate <api_key>? If so, where is the web URL to do so?

**Comment by acheong08** [comment]
> BTW, to use this API interface, must I regenerate a separate <api_key>? If so, where is the web URL to do so?

https://platform.openai.com/account/api-keys

**Comment by hongyi-zhao** [comment]
> Yes, did you mean something else?

Not really. Just wanted to make sure we understand each other correctly. Because this new technology is easy to misunderstand each other on some communication details and lead to a waste of time.

**Comment by hongyi-zhao** [comment]
> https://platform.openai.com/account/api-keys

I tried to use my API key, however, this method does not support the use of arrow keys to move the cursor, as shown below:

![image](https://user-images.githubusercontent.com/11155854/222332763-e85f480b-f2cb-4215-83b6-aefdac358e35.png)

**Comment by hongyi-zhao** [comment]
Another question on `gpt-3.5-turbo model`, see my inquiry and ChatGPT's answer:

```
(datasci) werner@X10DAi:~$ python3 -m revChatGPT.V3 --api_key <api_key > 

    ChatGPT - Official ChatGPT API
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press enter twice to submit your question.


User:
Do you use the gpt-3.5-turbo model?

ChatGPT: 
As an AI language model, I don't have access to specific information about the models used to train me or any other AI language model. However, I was trained using a variant of the GPT architecture, which is a very popular and effective approach for natural language processing tasks.

User:

(datasci) werner@X10DAi:~$ python3 -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.
Logging in...

You:
Do you use the gpt-3.5-turbo model?

Chatbot: 
As an AI language model, I am not capable of using any specific model, including the "gpt-3.5-turbo" model that you mentioned. However, I am trained on a large dataset that includes a wide range of language models, including but not limited to GPT-3, which enables me to understand and generate human-like responses to a wide range of questions and topics.

You:
```
Why would it give such an explanation?

**Comment by acheong0** [comment]
dunno

**Comment by acheong08** [comment]
> I tried with my API key, the results show that this method has a much faster speed. Does it mean more expensive use costs?

$0.002 per 1k tokens. Reference: https://platform.openai.com/pricing. It's cheaper than GPT-3

> However, this method does not support the use of arrow keys to move the cursor, as shown below:

I'll fix that
