### ISSUE TITLE
Add to awesome list

### ISSUE THREAD

**Issue by dotmet** [acheong08/ChatGPT#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A lightweight web UI for ChatGPT which can be deployed to Hugging face (no VPN required) or Google colab (need a VPN) to bypass the area restriction of the chatgpt server.

### Proposed workflow

- [ChatGPT_WebUI](https://github.com/dotmet/chatgpt_webui) - A lightweight web UI of ChatGPT

**Comment by acheong08** [comment]
added
