### ISSUE TITLE
[Feature Request]: Tab doesn't work for completion.

### ISSUE THREAD

**Issue by hongyi-zhao** [acheong08/ChatGPT#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

See below:

![image](https://user-images.githubusercontent.com/11155854/222347679-e012eb3c-d9e4-483a-af05-c5b54da6bf2d.png)

In this case, I found that hitting Tab doesn't do the completion of the candidate words, while right arrow key does. 

Regards,
Zhao 

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by acheong08** [comment]
yes. I'm not gonna add tab completion since I use tabs when writing

**Comment by hongyi-zhao** [comment]
Use it for what? It seems that your habit is very unusual.

**Comment by PaTTeeL** [comment]
> In this case, I found that hitting Tab doesn't do the completion of the candidate words, while right arrow key does.

Finally found how to use the auto-complete function in conversations.



> yes. I'm not gonna add tab completion since I use tabs when writing

It would be appreciated if we had a setting to enable the tab key for auto-complete since it is undefined in conversations.
