### ISSUE TITLE
[Feature request]: Track multiple conversations

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/ChatGPT#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I deployed the v3 api to the server, I found that the chat history was displayed in different users, which means that different users are actually using the same conversation. Is this a bug？

### Steps to reproduce the problem

When I deployed the v3 api to the server, I found that the chat history was displayed in different users, which means that different users are actually using the same conversation. Is this a bug？

### What should have happened?

maybe the source api problem

### Version where the problem happens

Name: revChatGPT
Version: 3.0.5
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: d:\python\lib\site-packages
Requires: asyncio, httpx, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:

### What Python version are you running this with?

Python 3.10.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no
```

**Comment by zjrwtx** [comment]
solve it

**Comment by Dreamscape315** [comment]
How did you solve it?

**Comment by acheong08** [comment]
You need to create multiple instances. Tracking multiple conversations hasn't been supported yet.

**Comment by Pengchengistaken** [comment]
looking forward for this feature.

**Comment by ZZM-user** [comment]
If you mean that each user should have their own unique reply, I recommend it;
1. You need to use a map-like storage cutoff to store the user's ID and 'conversation_id' and 'parent_id', and then pass them on to revChatGPT when it visits again;
2. If the user visits for the first time, you should give him new conversation_id and parent_id, as in the author's source code.
So they wouldn't have the same reply.

**Comment by acheong08** [comment]
Added some preliminary support. Not for CLI though

**Comment by acheong08** [comment]
Note: Use `reset(convo_id)` to make new conversation

**Comment by acheong08** [comment]
Now automatic
