### ISSUE TITLE
[Bug]: requests.exceptions.SSLError

### ISSUE THREAD

**Issue by jianhai0527** [acheong08/ChatGPT#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

requests.exceptions.SSLError

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

requests.exceptions.SSLError

### Version where the problem happens

3.0.5

### What Python version are you running this with?

3.10.9

### Command Line Arguments

```Shell
from revChatGPT.V1 import Chatbot
chatbot = Chatbot(config={
            "email": email,
            "password": password,
            "proxy": "socks5://127.0.0.1:13659"
        })
```

### Console logs

```Shell
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(CertificateError("hostname 'explorer.api.openai.com' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'")))
```

**Comment by acheong08** [comment]
OpenAI got blocked in China completely. Use VPN or proxy

Duplicate of #987

**Comment by hongyi-zhao** [comment]
@acheong08 
> OpenAI got blocked in China completely. Use VPN or proxy

The OP has already used the proxy in him/her config, as stated below:

> ### Command Line Arguments
> 
> ```shell
> from revChatGPT.V1 import Chatbot
> chatbot = Chatbot(config={
>             "email": email,
>             "password": password,
>             "proxy": "socks5://127.0.0.1:13659"
>         })
> ```

I also tried with the similar testing, and no error occurs:
 
> ### Console logs
> 
> ```shell
> requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(CertificateError("hostname 'explorer.api.openai.com' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'")))
> ```

Please compare with my following testing results:

```python
In [1]: from revChatGPT.V1 import Chatbot

In [2]: chatbot = Chatbot(config={
   ...: 
   ...:             "access_token": "<access_token>",
   ...:             "proxy": "socks5h://127.0.0.1:18890"
   ...:         })

In [3]: print("Chatbot: ")
   ...: prev_text = ""
   ...: for data in chatbot.ask(
   ...:     "Hello world",
   ...: ):
   ...:     message = data["message"][len(prev_text) :]
   ...:     print(message, end="", flush=True)
   ...:     prev_text = data["message"]
   ...: print()
Chatbot: 
Hello! How can I assist you today?

```
